Repository woodpecker-ci/woodpecker, pull requests merged in 2021-06, with the labels that each got.

#227 Switch in docs to new docker hub image repo
  Dockerfile
  Dockerfile.agent
  charts/woodpecker-agent/values.yaml
  charts/woodpecker-server/values.yaml
  docker-compose.yml
  docs/docs/administration/bitbucket.md
  docs/docs/administration/bitbucket_server.md
  docs/docs/administration/database.md
  docs/docs/administration/github.md
  docs/docs/administration/gitlab.md
  docs/docs/administration/lets-encrypt.md
  docs/docs/administration/ssl.md
  docs/docs/environment-variables.md
  docs/docs/pipeline.md
  docs/docs/server-setup.md
Labels: documentation

#228 Enforce code format
  .drone.sh
  .drone.yml
  .editorconfig
  .gitignore
  .vscode/launch.json
  Makefile
  README.md
  build/.gitignore
  cli/drone/build/build_approve.go
  cli/drone/build/build_decline.go
  cli/drone/build/build_info.go
  cli/drone/build/build_kill.go
  cli/drone/build/build_last.go
  cli/drone/build/build_list.go
  cli/drone/build/build_ps.go
  cli/drone/build/build_queue.go
  cli/drone/build/build_start.go
  cli/drone/build/build_stop.go
  cli/drone/log/log_purge.go
  cli/drone/repo/repo_add.go
  cli/drone/repo/repo_chown.go
  cli/drone/repo/repo_info.go
  cli/drone/repo/repo_list.go
  cli/drone/repo/repo_repair.go
  cli/drone/repo/repo_sync.go
  cli/drone/user/user_add.go
  cmd/drone-agent/health.go
  cmd/drone-server/setup.go
  cncd/pipeline/pipec/exec.go
  cncd/queue/fifo_test.go
  cncd/queue/queue.go
  docker-compose.example.yml
  go.mod
  go.sum
  model/queue.go
  remote/bitbucketserver/bitbucketserver.go
  remote/bitbucketserver/convert.go
  remote/bitbucketserver/convert_test.go
  remote/bitbucketserver/internal/client.go
  router/middleware/store.go
  server/build.go
  server/hook.go
  server/metrics/prometheus.go
  server/rpc.go
  store/datastore/builds.go
  store/datastore/config.go
  store/datastore/logs.go
  store/datastore/procs.go
  store/datastore/registry.go
  store/datastore/repos.go
  store/datastore/secret.go
  store/datastore/sender.go
  store/datastore/store.go
  store/datastore/task.go
  store/datastore/users.go
Labels: refactor, tests

#231 ci: fix build
  .drone.yml
  Makefile
Labels: skip-changelog

#230 Enable go vet for ci
  .cli.sh
  .drone.yml
  Makefile
  cncd/pipeline/pipeline/rpc/client_grpc_health.go
  remote/gogs/helper_test.go
Labels: refactor, tests

#175 Using configured server URL instead of obtained from request
  server/badge.go
  server/build.go
  server/hook.go
  server/rpc.go
Labels: enhancement

#174 Add support for path-prefix condition
  cncd/pipeline/pipeline/frontend/metadata.go
  cncd/pipeline/pipeline/frontend/yaml/constraint.go
  cncd/pipeline/pipeline/frontend/yaml/constraint_test.go
  docs/docs/pipeline.md
  go.mod
  go.sum
  model/build.go
  remote/github/convert.go
  remote/github/fixtures/hooks.go
  remote/github/parse_test.go
  remote/github/types.go
  server/procBuilder.go
  store/datastore/ddl/mysql/ddl_gen.go
  store/datastore/ddl/mysql/files/025_add_builds_changed_files_column.sql
  store/datastore/ddl/postgres/ddl_gen.go
  store/datastore/ddl/postgres/files/025_add_builds_changed_files_column.sql
  store/datastore/ddl/sqlite/ddl_gen.go
  store/datastore/ddl/sqlite/files/025_add_builds_changed_files_column.sql
Labels: feature, github

#237 fix: Build server with correct option
  Makefile
Labels: bug

#236 update / remove drone dependencies
  cmd/drone-agent/agent.go
  cmd/drone-agent/signal.go
  go.mod
  go.sum
  server/rpc.go
Labels: refactor
