Repository woodpecker-ci/woodpecker, pull requests merged in 2021-12, with the labels that each got.

#556 Add notice of supported YAML versions in docs
  docs/docs/20-usage/10-intro.md
Labels: documentation

#554 Add linter revive
  .golangci.yml
  cli/internal/util.go
  cli/lint/lint.go
  cmd/server/server.go
  cmd/server/setup.go
  pipeline/backend/docker/convert.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/schema/schema.go
  pipeline/schema/schema_test.go
  server/api/badge.go
  server/api/build.go
  server/api/file.go
  server/api/hook.go
  server/api/login.go
  server/api/repo.go
  server/api/stream.go
  server/api/user.go
  server/api/users.go
  server/grpc/rpc.go
  server/model/cc_test.go
  server/model/repo.go
  server/queue/fifo_test.go
  server/remote/bitbucket/bitbucket.go
  server/remote/bitbucket/bitbucket_test.go
  server/remote/bitbucket/convert.go
  server/remote/bitbucket/convert_test.go
  server/remote/bitbucket/internal/client.go
  server/remote/bitbucket/internal/types.go
  server/remote/bitbucketserver/bitbucketserver.go
  server/remote/bitbucketserver/internal/client.go
  server/remote/bitbucketserver/internal/types.go
  server/remote/coding/coding.go
  server/remote/coding/hook.go
  server/remote/coding/hook_test.go
  server/remote/coding/internal/project.go
  server/remote/coding/internal/webhook.go
  server/remote/gitlab/convert.go
  server/remote/gitlab/gitlab.go
  server/remote/gitlab/gitlab_test.go
  server/router/middleware/session/repo.go
  server/router/middleware/token/token.go
  server/shared/buildStatus_test.go
  server/shared/configFetcher.go
  server/shared/procBuilder.go
  server/shared/procBuilder_test.go
  server/shared/userSyncer.go
  server/store/datastore/init_cgo.go
  server/store/datastore/permission.go
  server/web/web.go
  shared/httputil/httputil.go
  shared/oauth2/oauth2.go
  shared/yml/yml.go
  web/web.go
Labels: refactor

#499 Add more golangci-lint linters & sort them
  .golangci.yml
Labels: tests

#560 Update README
  README.md
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/woodpecker.png
  docs/docusaurus.config.js
Labels: documentation

#564 Remove github.com/kr/pretty in favor of assert.EqualValues()
  go.mod
  pipeline/frontend/yaml/compiler/params_test.go
  pipeline/frontend/yaml/compiler/script_posix_test.go
  pipeline/frontend/yaml/container_test.go
  pipeline/frontend/yaml/network_test.go
  pipeline/frontend/yaml/secret_test.go
  pipeline/frontend/yaml/volume_test.go
  vendor/github.com/kr/pretty/.gitignore
  vendor/github.com/kr/pretty/License
  vendor/github.com/kr/pretty/Readme
  vendor/github.com/kr/pretty/diff.go
  vendor/github.com/kr/pretty/formatter.go
  vendor/github.com/kr/pretty/go.mod
  vendor/github.com/kr/pretty/go.sum
  vendor/github.com/kr/pretty/pretty.go
  vendor/github.com/kr/pretty/zero.go
  vendor/github.com/kr/text/License
  vendor/github.com/kr/text/Readme
  vendor/github.com/kr/text/doc.go
  vendor/github.com/kr/text/go.mod
  vendor/github.com/kr/text/indent.go
  vendor/github.com/kr/text/wrap.go
  vendor/github.com/rogpeppe/go-internal/LICENSE
  vendor/github.com/rogpeppe/go-internal/fmtsort/mapelem.go
  vendor/github.com/rogpeppe/go-internal/fmtsort/mapelem_1.11.go
  vendor/github.com/rogpeppe/go-internal/fmtsort/sort.go
  vendor/golang.org/x/net/html/atom/atom.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/const.go
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/entity.go
  vendor/golang.org/x/net/html/escape.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/html/token.go
  vendor/modules.txt
Labels: refactor

#565 fix `make test`
  Makefile
Labels: bug, skip-changelog

#464 Move plugin config to root.pipeline.[step].settings
  docs/docs/20-usage/20-pipeline-syntax.md
  pipeline/frontend/yaml/compiler/cacher.go
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/container.go
  pipeline/frontend/yaml/container_test.go
  pipeline/frontend/yaml/linter/linter.go
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/schema/.woodpecker/test-plugin.yml
  pipeline/schema/.woodpecker/test-step.yml
  pipeline/schema/schema.json
Labels: enhancement, breaking, wip

#569 Update Documentation (fix diffs and add settings)
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/20-usage/22-conditional-execution.md
  docs/docs/20-usage/50-environment.md
  docs/docs/20-usage/51-plugins/10-plugins.md
  docs/docs/20-usage/51-plugins/20-sample-plugin.md
  docs/docs/20-usage/71-project-settings.md
  docs/docs/20-usage/project-settings.png
  docs/docs/20-usage/repo-list.png
  docs/docs/30-administration/20-vcs/github_oauth.png
  docs/docs/91-migrations.md
Labels: documentation

#384 Remove ghodss/yaml
  go.mod
  go.sum
  pipeline/frontend/yaml/compiler/params.go
  shared/yml/yml.go
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/modules.txt
Labels: refactor

#570 Write own yaml2json func
  Makefile
  pipeline/frontend/yaml/compiler/params.go
  pipeline/frontend/yaml/compiler/params_test.go
  shared/yml/yml.go
  shared/yml/yml_test.go
Labels: bug, refactor, skip-changelog

#562 hotfix ci pipeline
  .woodpecker/test.yml
  Makefile
Labels: bug, skip-changelog

#573 Update proxy docs
  docs/docs/30-administration/70-proxy.md
Labels: documentation

#576 improve favicons
  server/web/web.go
  web/index.html
  web/public/favicons/favicon-dark-default.png
  web/public/favicons/favicon-dark-default.svg
  web/public/favicons/favicon-dark-error.png
  web/public/favicons/favicon-dark-error.svg
  web/public/favicons/favicon-dark-pending.png
  web/public/favicons/favicon-dark-pending.svg
  web/public/favicons/favicon-dark-success.png
  web/public/favicons/favicon-dark-success.svg
  web/public/favicons/favicon-light-default.png
  web/public/favicons/favicon-light-default.svg
  web/public/favicons/favicon-light-error.png
  web/public/favicons/favicon-light-error.svg
  web/public/favicons/favicon-light-pending.png
  web/public/favicons/favicon-light-pending.svg
  web/public/favicons/favicon-light-success.png
  web/public/favicons/favicon-light-success.svg
  web/src/App.vue
  web/src/compositions/useFavicon.ts
  web/src/main.ts
  web/src/views/repo/RepoBuild.vue
Labels: ui, enhancement

#529 fix back links
  web/src/compositions/useRouteBackOrDefault.ts
  web/src/views/repo/RepoBuild.vue
  web/src/views/repo/RepoSettings.vue
Labels: bug, ui, skip-changelog

#574 Improve secrets tab
  web/src/components/form/CheckboxesField.vue
  web/src/components/form/TextField.vue
  web/src/components/repo/settings/SecretsTab.vue
Labels: ui, enhancement

#575 Improve commit icons
  web/src/components/repo/build/BuildItem.vue
  web/src/views/repo/RepoBuild.vue
Labels: ui, enhancement

#579 another fix for settings field in pipeline config
  .woodpecker/main.yml
  pipeline/frontend/yaml/compiler/params.go
  pipeline/frontend/yaml/compiler/params_test.go
  pipeline/frontend/yaml/container_test.go
  pipeline/schema/schema.json
Labels: bug, server, skip-changelog

#583 remove gopkg.in/yaml.v2
  go.mod
  pipeline/frontend/yaml/types/network.go
  pipeline/frontend/yaml/types/network_test.go
  pipeline/frontend/yaml/types/ulimit.go
  pipeline/frontend/yaml/types/ulimit_test.go
  vendor/modules.txt
Labels: bug, skip-changelog

#582 Dont panic, report error back
  server/api/build.go
  server/api/hook.go
  server/grpc/rpc.go
  server/model/proc.go
Labels: bug, refactor

#585 Make cancel pipeline work again
  cmd/agent/agent.go
  cmd/server/server.go
  server/api/build.go
Labels: bug, server

#587 Replace deprecated eslint airbnb typescript config
  web/.eslintrc.js
  web/package.json
  web/yarn.lock
Labels: skip-changelog, dependencies

#588 fix live logging
  web/src/compositions/useBuildProc.ts
Labels: bug, skip-changelog

#584 Add log-level option to cli
  cli/common/flags.go
  cli/common/zerologger.go
  cmd/cli/main.go
Labels: enhancement, cli

#592 fix pr secret event names
  server/api/build.go
  server/model/build.go
  server/model/const.go
  server/model/secret.go
  server/remote/github/github.go
  server/shared/procBuilder.go
  server/store/datastore/migration/003_fix_pr_secret_event_name.go
  server/store/datastore/migration/migration.go
  web/src/lib/api/types/webhook.ts
Labels: bug, skip-changelog

#595 Nits Collected over last month
  Makefile
  cmd/agent/agent.go
  cmd/server/setup.go
  server/plugins/secrets/builtin.go
  server/queue/fifo.go
  server/queue/fifo_test.go
  server/store/datastore/migration/003_fix_pr_secret_event_name.go
Labels: refactor, skip-changelog

#593 let remove be a remove
  server/api/repo.go
  server/model/log.go
  server/store/datastore/build.go
  server/store/datastore/proc.go
  server/store/datastore/repo.go
  server/store/datastore/repo_test.go
  web/src/components/atomic/Icon.vue
  web/src/components/repo/settings/ActionsTab.vue
  web/src/lib/api/index.ts
Labels: ui, enhancement

#601 Remove workaround for gitlab webhook parsing
  server/remote/gitlab/gitlab.go
Labels: refactor, skip-changelog

#603 hide gin routes logging on none-debug starts
  cmd/server/server.go
Labels: server, enhancement

#606 Clarify Docs on Docker for new users in intro
  docs/docs/10-intro.md
Labels: documentation

#568 Add multi-pipeline support to exec & lint
  cli/common/pipeline.go
  cli/exec/exec.go
  cli/lint/lint.go
Labels: feature, cli

#586 add flag to set oauth redirect host in dev mode
  cmd/server/flags.go
  cmd/server/server.go
  server/config.go
  server/remote/gitea/gitea.go
  server/remote/github/github.go
  server/remote/gitlab/gitlab.go
Labels: enhancement

#604 Get secrets in settings
  docs/docs/20-usage/40-secrets.md
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/compiler/params.go
  pipeline/frontend/yaml/compiler/params_test.go
Labels: feature

#608 Docker Images use golang image for ca-certificates
  Dockerfile
  Dockerfile.agent
  Dockerfile.agent.alpine
  Dockerfile.alpine
Labels: bug

#594 Let Accept Gated Pipeline use same func as non Gate Pipeline to create final pipeline
  server/api/build.go
  server/api/hook.go
  server/model/secret.go
Labels: bug, refactor, skip-changelog

#611 update docs
  docs/docusaurus.config.js
  docs/package.json
  docs/plugins/woodpecker-plugins/package.json
  docs/plugins/woodpecker-plugins/yarn.lock
  docs/yarn.lock
Labels: documentation, skip-changelog

#612 Improve hook errors
  server/api/hook.go
Labels: enhancement, skip-changelog

#613 Fix event type deployment for ui
  web/src/lib/api/types/webhook.ts
Labels: bug, ui, skip-changelog

#615 Calculate build number on creation
  server/api/repo.go
  server/model/repo.go
  server/store/datastore/build.go
  server/store/datastore/build_test.go
  server/store/datastore/migration/004_repos_drop_repo_counter.go
  server/store/datastore/migration/migration.go
Labels: server, enhancement

#619 fix new pipeline not published to UI if protected repo mode enabled
  server/api/hook.go
Labels: bug, server

#620 Use gitlab generic webhooks instead of drone-ci-service
  server/remote/gitlab/gitlab.go
  server/remote/gitlab/testdata/projects.go
  server/remote/gitlab/testdata/testdata.go
  server/shared/configFetcher.go
  shared/token/token.go
Labels: enhancement

#625 Add flag for not fetching permissions (FlatPermissions) (#491)
  cmd/server/flags.go
  cmd/server/server.go
  server/api/user.go
  server/config.go
  server/shared/userSyncer.go
Labels: server, skip-changelog

#623 Add "woodpeckerci/plugin-docker-buildx" to privileged plugins
  cli/exec/flags.go
  cmd/server/flags.go
  shared/constant/privileged_plugins.go
Labels: enhancement

#627 Fix gRPC incomapatability in helm chart
  charts/woodpecker-agent/templates/deployment.yaml
Labels: bug

#624 pipeline env migrate CI_TAG & CI_PULL_REQUEST to new CI_COMMIT_TAG & CI_COMMIT_PULL_REQUEST
  docs/docs/91-migrations.md
  pipeline/frontend/metadata.go
  pipeline/frontend/yaml/container.go
Labels: server, refactor, skip-changelog

#629 fix sqlite migration on column drop of abnormal schemas
  server/store/datastore/migration/common.go
  server/store/datastore/migration/common_test.go
Labels: bug, server, imporant

#632 Use Woodpecker theme colors on Safari Tab Bar / Header Bar
  web/index.html
  web/src/compositions/useDarkMode.ts
Labels: ui

#622 Add multiarch support agent
  .woodpecker/main.yml
  Makefile
  docker/Dockerfile.agent
  docker/Dockerfile.agent.alpine
  docker/Dockerfile.agent.alpine.multiarch
  docker/Dockerfile.agent.multiarch
Labels: agent, feature, build

#610 add development docs
  .gitignore
  .vscode/extensions.json
  .woodpecker/main.yml
  docs/docs/92-development.md
  docs/docs/92-development/vscode-debug.png
  docs/docs/92-development/vscode-run-test.png
  docs/docs/92-development/woodpecker-architecture.png
Labels: documentation

#636 Improve dev docs
  .gitignore
  .vscode/settings.json
  docs/docs/92-development.md
  docs/docs/92-development/01-getting-started.md
  docs/docs/92-development/03-ui.md
  docs/docs/92-development/04-docs.md
  docs/docs/92-development/05-architecture.md
  docs/docs/92-development/06-guides.md
  docs/docs/92-development/_category_.yml
  docs/docs/92-development/ui-proxy.svg
  web/vite.config.ts
Labels: documentation, skip-changelog

#634 Multiarch build cli docker images
  .woodpecker/main.yml
  docker/Dockerfile.cli
  docker/Dockerfile.cli.alpine
  docker/Dockerfile.cli.alpine.multiarch
  docker/Dockerfile.cli.multiarch
Labels: feature, build, cli

#561 Improve status updates
  server/api/build.go
  server/api/hook.go
  server/grpc/rpc.go
  server/model/proc.go
  server/remote/bitbucket/bitbucket.go
  server/remote/bitbucket/bitbucket_test.go
  server/remote/bitbucket/convert.go
  server/remote/bitbucket/convert_test.go
  server/remote/bitbucketserver/bitbucketserver.go
  server/remote/bitbucketserver/convert.go
  server/remote/coding/coding.go
  server/remote/common/status.go
  server/remote/gitea/gitea.go
  server/remote/gitea/gitea_test.go
  server/remote/gitea/parse.go
  server/remote/github/github.go
  server/remote/gitlab/gitlab.go
  server/remote/gitlab/status.go
  server/remote/gogs/gogs.go
  server/remote/gogs/gogs_test.go
  server/remote/mocks/remote.go
  server/remote/remote.go
Labels: bug, enhancement

#642 Add `repo` to `when` block
  docs/docs/20-usage/22-conditional-execution.md
  pipeline/schema/.woodpecker/test-when.yml
  pipeline/schema/schema.json
Labels: documentation

#638 Add field for image list in Secrets Repo Settings (Web UI)
  server/model/secret.go
  server/model/secret_test.go
  web/src/components/repo/settings/SecretsTab.vue
Labels: ui, feature

#639 Add bit more contributing info & history of owners
  CONTRIBUTING.md
Labels: documentation

#646 Mention Matrix Space & Rooms in Readme & Docs
  CONTRIBUTING.md
  README.md
  docs/docs/30-administration/20-vcs/50-bitbucket.md
  docs/docusaurus.config.js
Labels: documentation

#647 proc.Tree() func do not depend on sorted procs list
  server/model/proc.go
  server/model/proc_test.go
Labels: bug
