Repository woodpecker-ci/woodpecker, pull requests merged in 2021-10, with the labels that each got.

#392 Remove unused files
  pipeline/backend/backend.go
  pipeline/multipart/analysis/doc.go
  pipeline/multipart/coverage/doc.go
  pipeline/multipart/doc.go
  pipeline/multipart/selenium/doc.go
  pipeline/multipart/terminal/doc.go
Labels: refactor

#391 Replace drone with woodpecker
  cli/exec/exec.go
  cmd/server/flags.go
  pipeline/frontend/yaml/compiler/option_test.go
  pipeline/frontend/yaml/constraint_test.go
  server/api/file.go
  server/grpc/rpc.go
  server/remote/bitbucket/bitbucket.go
  server/remote/bitbucket/convert.go
  server/remote/bitbucketserver/bitbucketserver.go
  server/remote/bitbucketserver/convert.go
  server/remote/coding/coding.go
  server/remote/coding/coding_test.go
  server/remote/coding/fixtures/handler.go
  server/remote/coding/fixtures/hooks.go
  server/remote/coding/hook_test.go
  server/remote/gitea/gitea.go
  server/remote/gitea/gitea_test.go
  server/remote/gitea/helper.go
  server/remote/gitea/helper_test.go
  server/remote/github/convert.go
  server/remote/github/github.go
  server/remote/gogs/gogs.go
  server/remote/gogs/gogs_test.go
  server/remote/gogs/helper.go
  server/remote/gogs/helper_test.go
  server/router/middleware/version.go
  server/shared/configFetcher_test.go
  server/shared/procBuilder.go
  server/store/datastore/builds_test.go
  server/store/datastore/config_test.go
  server/store/datastore/perms_test.go
  server/store/datastore/repos_test.go
  server/store/datastore/users_test.go
  server/swagger/files/swagger.yml
Labels: refactor

#390 Rename drone-go to woodpecker-go
  cli/deploy/deploy.go
  cli/internal/util.go
  cli/registry/registry_add.go
  cli/registry/registry_set.go
  cli/repo/repo_update.go
  cli/secret/secret_add.go
  cli/secret/secret_set.go
  cli/user/user_add.go
  woodpecker-go/LICENSE
  woodpecker-go/README.md
  woodpecker-go/woodpecker/client.go
  woodpecker-go/woodpecker/client_test.go
  woodpecker-go/woodpecker/const.go
  woodpecker-go/woodpecker/interface.go
  woodpecker-go/woodpecker/types.go
Labels: refactor

#380 Move cli exec flags to own file
  cli/build/build_logs.go
  cli/exec/exec.go
  cli/exec/flags.go
  cmd/cli/main.go
  pipeline/backend/backend.go
Labels: refactor, skip-changelog

#396 Add security policy
  SECURITY.md
Labels: documentation, governance

#397 github.com/golang-jwt/jwt v3.2.2 -> v4.1.0
  go.mod
  go.sum
  shared/token/token.go
  vendor/github.com/golang-jwt/jwt/MIGRATION_GUIDE.md
  vendor/github.com/golang-jwt/jwt/claims.go
  vendor/github.com/golang-jwt/jwt/v4/.gitignore
  vendor/github.com/golang-jwt/jwt/v4/LICENSE
  vendor/github.com/golang-jwt/jwt/v4/MIGRATION_GUIDE.md
  vendor/github.com/golang-jwt/jwt/v4/README.md
  vendor/github.com/golang-jwt/jwt/v4/VERSION_HISTORY.md
  vendor/github.com/golang-jwt/jwt/v4/claims.go
  vendor/github.com/golang-jwt/jwt/v4/doc.go
  vendor/github.com/golang-jwt/jwt/v4/ecdsa.go
  vendor/github.com/golang-jwt/jwt/v4/ecdsa_utils.go
  vendor/github.com/golang-jwt/jwt/v4/ed25519.go
  vendor/github.com/golang-jwt/jwt/v4/ed25519_utils.go
  vendor/github.com/golang-jwt/jwt/v4/errors.go
  vendor/github.com/golang-jwt/jwt/v4/go.mod
  vendor/github.com/golang-jwt/jwt/v4/go.sum
  vendor/github.com/golang-jwt/jwt/v4/hmac.go
  vendor/github.com/golang-jwt/jwt/v4/map_claims.go
  vendor/github.com/golang-jwt/jwt/v4/none.go
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v4/rsa.go
  vendor/github.com/golang-jwt/jwt/v4/rsa_pss.go
  vendor/github.com/golang-jwt/jwt/v4/rsa_utils.go
  vendor/github.com/golang-jwt/jwt/v4/signing_method.go
  vendor/github.com/golang-jwt/jwt/v4/staticcheck.conf
  vendor/github.com/golang-jwt/jwt/v4/token.go
  vendor/github.com/golang-jwt/jwt/v4/types.go
  vendor/modules.txt
Labels: server, skip-changelog, dependencies

#398 Publish alpine container
  .dockerignore
  .woodpecker/main.yml
  BUILDING
  Dockerfile
  Dockerfile.agent
  docker/Dockerfile.agent
  docker/Dockerfile.agent.alpine
  docker/Dockerfile.server
  docker/Dockerfile.server.alpine
  docs/docs/80-downloads.md
Labels: build

#400 Improve release
  .gitignore
  .woodpecker/main.yml
  Makefile
Labels: build

#402 Correct bin path
  docker/Dockerfile.agent
  docker/Dockerfile.agent.alpine
  docker/Dockerfile.server
  docker/Dockerfile.server.alpine
Labels: bug, build

#406 Add image migration docs
  docs/docs/91-migrations.md
Labels: documentation

#404 Release cli images
  .woodpecker/main.yml
  docker/Dockerfile.cli
  docker/Dockerfile.cli.alpine
  docs/docs/80-downloads.md
Labels: build

#407 Fix cli build
  Makefile
Labels: bug, skip-changelog

#496 Fix bug where db file is posible moved outside of docker volume
  cmd/server/setup.go
Labels: bug, skip-changelog

#497 Changelog for v0.14.3
  CHANGELOG.md
Labels: documentation, skip-changelog

#495 Embedding libcompose types for yaml parsing
  go.mod
  go.sum
  pipeline/frontend/yaml/compiler/cacher.go
  pipeline/frontend/yaml/config.go
  pipeline/frontend/yaml/config_test.go
  pipeline/frontend/yaml/constraint.go
  pipeline/frontend/yaml/container.go
  pipeline/frontend/yaml/container_test.go
  pipeline/frontend/yaml/types/command.go
  pipeline/frontend/yaml/types/command_test.go
  pipeline/frontend/yaml/types/network.go
  pipeline/frontend/yaml/types/network_test.go
  pipeline/frontend/yaml/types/types_yaml.go
  pipeline/frontend/yaml/types/types_yaml_test.go
  pipeline/frontend/yaml/types/ulimit.go
  pipeline/frontend/yaml/types/ulimit_test.go
  pipeline/frontend/yaml/types/volume.go
  pipeline/frontend/yaml/types/volume_test.go
  vendor/github.com/docker/libcompose/LICENSE
  vendor/github.com/docker/libcompose/yaml/build.go
  vendor/github.com/docker/libcompose/yaml/external.go
  vendor/modules.txt
Labels: refactor
