Repository woodpecker-ci/woodpecker, pull requests merged in 2021-09, with the labels that each got.

#295 Flag for specific grpc server addr
  cmd/drone-server/flags.go
  cmd/drone-server/server.go
Labels: enhancement

#291 Fix docs/makefile after #284 got merged
  BUILDING
  Makefile
Labels: documentation

#301 [CI] Fix docs deploy & links
  .woodpecker/docs.yml
  README.md
  charts/README.md
  cmd/drone-server/flags.go
Labels: skip-changelog, build

#298 Issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/issue_template.md
  .github/pull_request_template.md
Labels: documentation

#296 Community Guide
  CONTRIBUTING.md
  README.md
Labels: documentation

#307 Improve administration docs
  docs/README.md
  docs/docs/30-administration/00-setup.md
  docs/docs/30-administration/10-server-config.md
  docs/docs/30-administration/11-agent-config.md
  docs/docs/30-administration/20-vcs/20-github.md
  docs/docs/30-administration/20-vcs/30-gitea.md
  docs/docs/30-administration/20-vcs/40-gitlab.md
  docs/docs/30-administration/20-vcs/50-bitbucket.md
  docs/docs/30-administration/20-vcs/60-bitbucket_server.md
  docs/docs/30-administration/20-vcs/gitea_oauth.gif
  docs/docs/30-administration/30-database.md
  docs/docs/30-administration/50-lets-encrypt.md
  docs/docs/30-administration/60-ssl.md
  docs/docs/80-downloads.md
  docs/docusaurus.config.js
Labels: documentation

#310 Add Support section to README
  .github/FUNDING.yml
  README.md
Labels: documentation

#299 Change pipeline config path resolution
  cmd/drone-server/flags.go
  docs/docs/20-usage/10-intro.md
  docs/docs/20-usage/71-project-settings.md
  docs/docs/91-migrations.md
  model/repo.go
  server/build.go
  server/configFetcher.go
  server/configFetcher_test.go
  server/repo.go
  store/datastore/ddl/mysql/ddl_gen.go
  store/datastore/ddl/mysql/files/026_drop_repo_fallback_column.sql
  store/datastore/ddl/postgres/ddl_gen.go
  store/datastore/ddl/postgres/files/026_drop_repo_fallback_column.sql
  store/datastore/ddl/sqlite/ddl_gen.go
  store/datastore/ddl/sqlite/files/026_drop_repo_fallback_column.sql
  store/datastore/repos.go
  store/datastore/sql/mysql/files/repos.sql
  store/datastore/sql/mysql/sql_gen.go
  store/datastore/sql/postgres/files/repos.sql
  store/datastore/sql/postgres/sql_gen.go
  store/datastore/sql/sqlite/files/repos.sql
  store/datastore/sql/sqlite/sql_gen.go
  web/src/screens/repo/screens/settings/index.js
Labels: enhancement, breaking

#313 docs: improve plugin docs
  docs/docs/20-usage/51-plugins/10-plugins.md
Labels: documentation

#281 Remove push, tag and deployment webhook filters
  drone-go/drone/types.go
  model/repo.go
  server/hook.go
  server/repo.go
  server/swagger/files/swagger.yml
  store/datastore/ddl/mysql/ddl_gen.go
  store/datastore/ddl/mysql/files/027_drop_allow_push_tags_deployments_columns.sql
  store/datastore/ddl/postgres/ddl_gen.go
  store/datastore/ddl/postgres/files/027_drop_allow_push_tags_deployments_columns.sql
  store/datastore/ddl/sqlite/ddl_gen.go
  store/datastore/ddl/sqlite/files/027_drop_allow_push_tags_deployments_columns.sql
  store/datastore/repos.go
  store/datastore/sql/mysql/files/repos.sql
  store/datastore/sql/mysql/sql_gen.go
  store/datastore/sql/postgres/files/repos.sql
  store/datastore/sql/postgres/sql_gen.go
  store/datastore/sql/sqlite/files/repos.sql
  store/datastore/sql/sqlite/sql_gen.go
  web/src/screens/repo/screens/settings/index.js
Labels: enhancement, breaking

#323 docs: fix typo plattform -> platform
  docs/docs/20-usage/20-pipeline-syntax.md
Labels: documentation

#326 Fix sanitziePath
  server/hook.go
  server/procBuilder.go
  server/procBuilder_test.go
Labels: bug, skip-changelog

#311 fix: cli matrix filter
  cli/drone/exec/exec.go
Labels: bug

#327 Support recursive glob for path conditions
  .woodpecker/docs.yml
  cncd/pipeline/pipeline/frontend/yaml/constraint.go
  cncd/pipeline/pipeline/frontend/yaml/constraint_test.go
  docs/docs/20-usage/20-pipeline-syntax.md
  go.mod
  go.sum
  vendor/github.com/bmatcuk/doublestar/v4/.gitignore
  vendor/github.com/bmatcuk/doublestar/v4/.travis.yml
  vendor/github.com/bmatcuk/doublestar/v4/LICENSE
  vendor/github.com/bmatcuk/doublestar/v4/README.md
  vendor/github.com/bmatcuk/doublestar/v4/UPGRADING.md
  vendor/github.com/bmatcuk/doublestar/v4/doublestar.go
  vendor/github.com/bmatcuk/doublestar/v4/glob.go
  vendor/github.com/bmatcuk/doublestar/v4/globwalk.go
  vendor/github.com/bmatcuk/doublestar/v4/go.mod
  vendor/github.com/bmatcuk/doublestar/v4/match.go
  vendor/github.com/bmatcuk/doublestar/v4/utils.go
  vendor/github.com/bmatcuk/doublestar/v4/validate.go
  vendor/modules.txt
Labels: enhancement

#332 migrate jwt token lib
  go.mod
  go.sum
  shared/token/token.go
  vendor/github.com/dgrijalva/jwt-go/.travis.yml
  vendor/github.com/dgrijalva/jwt-go/README.md
  vendor/github.com/dgrijalva/jwt-go/VERSION_HISTORY.md
  vendor/github.com/dgrijalva/jwt-go/errors.go
  vendor/github.com/dgrijalva/jwt-go/jwt.go
  vendor/github.com/dgrijalva/jwt-go/signing_method.go
  vendor/github.com/golang-jwt/jwt/.gitignore
  vendor/github.com/golang-jwt/jwt/LICENSE
  vendor/github.com/golang-jwt/jwt/MIGRATION_GUIDE.md
  vendor/github.com/golang-jwt/jwt/README.md
  vendor/github.com/golang-jwt/jwt/VERSION_HISTORY.md
  vendor/github.com/golang-jwt/jwt/claims.go
  vendor/github.com/golang-jwt/jwt/doc.go
  vendor/github.com/golang-jwt/jwt/ecdsa.go
  vendor/github.com/golang-jwt/jwt/ecdsa_utils.go
  vendor/github.com/golang-jwt/jwt/ed25519.go
  vendor/github.com/golang-jwt/jwt/ed25519_utils.go
  vendor/github.com/golang-jwt/jwt/errors.go
  vendor/github.com/golang-jwt/jwt/hmac.go
  vendor/github.com/golang-jwt/jwt/map_claims.go
  vendor/github.com/golang-jwt/jwt/none.go
  vendor/github.com/golang-jwt/jwt/parser.go
  vendor/github.com/golang-jwt/jwt/rsa.go
  vendor/github.com/golang-jwt/jwt/rsa_pss.go
  vendor/github.com/golang-jwt/jwt/rsa_utils.go
  vendor/github.com/golang-jwt/jwt/signing_method.go
  vendor/github.com/golang-jwt/jwt/token.go
  vendor/modules.txt
Labels: security, dependencies, backport

#330 Rename cmd agent and server folders and binaries
  Dockerfile
  Dockerfile.agent
  Dockerfile.agent.alpine
  Dockerfile.alpine
  Makefile
  cmd/agent/agent.go
  cmd/agent/flags.go
  cmd/agent/health.go
  cmd/agent/health_test.go
  cmd/agent/main.go
  cmd/agent/signal.go
  cmd/server/flags.go
  cmd/server/main.go
  cmd/server/server.go
  cmd/server/setup.go
Labels: refactor

#331 Remove legacy/unused code + misc cleanups
  cncd/pipeline/pipec/compile.go
  cncd/pipeline/pipec/exec.go
  cncd/pipeline/pipec/lint.go
  cncd/pipeline/pipec/main.go
  cncd/pipeline/piped/main.go
  cncd/pipeline/piped/once.go
  cncd/pipeline/pipeline/rpc/client.go
  cncd/pipeline/pipeline/rpc/client_test.go
  cncd/pipeline/pipeline/rpc/option.go
  cncd/pipeline/pipeline/rpc/option_test.go
  cncd/pipeline/pipeline/rpc/server.go
  cncd/pipeline/pipeline/rpc/server_test.go
  drone-go/drone/client.go
  go.mod
  go.sum
  remote/github/parse.go
  server/swagger/files/swagger.yml
  vendor/github.com/gorilla/websocket/.gitignore
  vendor/github.com/gorilla/websocket/AUTHORS
  vendor/github.com/gorilla/websocket/LICENSE
  vendor/github.com/gorilla/websocket/README.md
  vendor/github.com/gorilla/websocket/client.go
  vendor/github.com/gorilla/websocket/client_clone.go
  vendor/github.com/gorilla/websocket/client_clone_legacy.go
  vendor/github.com/gorilla/websocket/compression.go
  vendor/github.com/gorilla/websocket/conn.go
  vendor/github.com/gorilla/websocket/conn_write.go
  vendor/github.com/gorilla/websocket/conn_write_legacy.go
  vendor/github.com/gorilla/websocket/doc.go
  vendor/github.com/gorilla/websocket/go.mod
  vendor/github.com/gorilla/websocket/go.sum
  vendor/github.com/gorilla/websocket/join.go
  vendor/github.com/gorilla/websocket/json.go
  vendor/github.com/gorilla/websocket/mask.go
  vendor/github.com/gorilla/websocket/mask_safe.go
  vendor/github.com/gorilla/websocket/prepared.go
  vendor/github.com/gorilla/websocket/proxy.go
  vendor/github.com/gorilla/websocket/server.go
  vendor/github.com/gorilla/websocket/trace.go
  vendor/github.com/gorilla/websocket/trace_17.go
  vendor/github.com/gorilla/websocket/util.go
  vendor/github.com/gorilla/websocket/x_net_proxy.go
  vendor/github.com/sourcegraph/jsonrpc2/.travis.yml
  vendor/github.com/sourcegraph/jsonrpc2/LICENSE
  vendor/github.com/sourcegraph/jsonrpc2/README.md
  vendor/github.com/sourcegraph/jsonrpc2/async.go
  vendor/github.com/sourcegraph/jsonrpc2/call_opt.go
  vendor/github.com/sourcegraph/jsonrpc2/conn_opt.go
  vendor/github.com/sourcegraph/jsonrpc2/go.mod
  vendor/github.com/sourcegraph/jsonrpc2/go.sum
  vendor/github.com/sourcegraph/jsonrpc2/handler_with_error.go
  vendor/github.com/sourcegraph/jsonrpc2/jsonrpc2.go
  vendor/github.com/sourcegraph/jsonrpc2/stream.go
  vendor/github.com/sourcegraph/jsonrpc2/websocket/stream.go
  vendor/modules.txt
Labels: refactor

#334 Changelog for v0.14.1
  .changelog.yml
  CHANGELOG.md
Labels: documentation, skip-changelog

#337 Refactor: Reorganize into server/{api,grpc,shared} packages
  cmd/server/main.go
  cmd/server/server.go
  cmd/server/setup.go
  router/router.go
  server/api/badge.go
  server/api/build.go
  server/api/debug/debug.go
  server/api/file.go
  server/api/hook.go
  server/api/login.go
  server/api/metrics/prometheus.go
  server/api/registry.go
  server/api/repo.go
  server/api/secret.go
  server/api/stream.go
  server/api/user.go
  server/api/users.go
  server/api/z.go
  server/config.go
  server/grpc/rpc.go
  server/shared/buildStatus.go
  server/shared/buildStatus_test.go
  server/shared/configFetcher.go
  server/shared/configFetcher_test.go
  server/shared/procBuilder.go
  server/shared/procBuilder_test.go
  server/shared/procStatus.go
  server/shared/procStatus_test.go
  server/shared/userSyncer.go
Labels: refactor

#339 Refactor: move router/ to server/router/
  cmd/server/server.go
  server/api/build.go
  server/api/file.go
  server/api/registry.go
  server/api/repo.go
  server/api/secret.go
  server/api/stream.go
  server/api/user.go
  server/router/middleware/config.go
  server/router/middleware/header/header.go
  server/router/middleware/remote.go
  server/router/middleware/session/agent.go
  server/router/middleware/session/repo.go
  server/router/middleware/session/repo_test.go
  server/router/middleware/session/user.go
  server/router/middleware/store.go
  server/router/middleware/token/token.go
  server/router/middleware/version.go
  server/router/router.go
Labels: refactor

#340 Changelog for v0.14.1 (#334)
  .changelog.yml
  CHANGELOG.md
Labels: documentation, skip-changelog

#338 Refactor: Create agent/ package for backend agnostic logic
  agent/runner.go
  agent/state.go
  cmd/agent/agent.go
  cmd/agent/health.go
  cmd/agent/health_test.go
Labels: refactor

#333 Improve docs deployment
  .woodpecker/docs.yml
Labels: documentation, build

#302 Release Helm charts
  .woodpecker/helm.yml
  charts/README.md
  charts/woodpecker-agent/Chart.yaml
  charts/woodpecker-agent/values.yaml
  charts/woodpecker-server/Chart.yaml
  charts/woodpecker-server/values.yaml
  docs/docs/30-administration/80-kubernetes.md
Labels: enhancement

#350 Correct headline level
  docs/docs/30-administration/80-kubernetes.md
Labels: documentation, skip-changelog

#348 Cleanup Code
  cli/exec/exec.go
  cmd/server/server.go
  go.mod
  model/queue.go
  pipeline/backend/docker/convert.go
  pipeline/backend/docker/docker.go
  pipeline/doc.go
  pipeline/frontend/yaml/compiler/params.go
  pipeline/frontend/yaml/constraint.go
  pipeline/frontend/yaml/matrix/matrix.go
  pipeline/rpc/client_grpc.go
  pipeline/rpc/client_grpc_health.go
  pipeline/version/version.go
  server/api/build.go
  server/api/hook.go
  server/api/login.go
  server/api/repo.go
  server/api/user.go
  server/plugins/registry/filesystem.go
  server/plugins/sender/plugin.go
  server/queue/fifo.go
  server/remote/bitbucketserver/bitbucketserver.go
  server/remote/coding/coding.go
  server/remote/gerrit/gerrit.go
  server/remote/gitea/gitea.go
  server/remote/gitea/gitea_oauth.go
  server/remote/github/github.go
  server/remote/gitlab/gitlab.go
  server/remote/gitlab3/gitlab.go
  server/remote/gogs/gogs.go
  server/shared/configFetcher_test.go
  server/shared/procStatus_test.go
  server/shared/userSyncer.go
  server/store/datastore/init.go
  server/store/datastore/init_cgo.go
  shared/oauth2/oauth2.go
  tools.go
  vendor/modules.txt
Labels: refactor

#354 If config is no dir assume its a folder
  server/shared/configFetcher.go
Labels: enhancement

#355 Update license files
  LICENSE
  docs/LICENSE
Labels: skip-changelog

#359 Fix launch config
  .vscode/launch.json
Labels: documentation, skip-changelog

#357 Make configFetcher fallback work for gitea
  server/shared/configFetcher.go
  server/shared/configFetcher_test.go
Labels: bug, gitea, skip-changelog

#361 Explain open registration setting
  docs/docs/30-administration/10-server-config.md
Labels: documentation

#248 Replace www-path with www-proxy option for development
  cmd/server/flags.go
  cmd/server/server.go
  cmd/server/setup.go
  server/router/router.go
  server/web/opts.go
  server/web/opts_test.go
  server/web/web.go
Labels: feature

#342 Add json schema and cli lint command
  cli/lint/lint.go
  cmd/cli/main.go
  go.mod
  go.sum
  pipeline/schema/.woodpecker/test-branches-array.yml
  pipeline/schema/.woodpecker/test-branches-exclude-include.yml
  pipeline/schema/.woodpecker/test-branches.yml
  pipeline/schema/.woodpecker/test-broken.yml
  pipeline/schema/.woodpecker/test-clone-skip.yml
  pipeline/schema/.woodpecker/test-clone.yml
  pipeline/schema/.woodpecker/test-matrix.yml
  pipeline/schema/.woodpecker/test-multi.yml
  pipeline/schema/.woodpecker/test-plugin.yml
  pipeline/schema/.woodpecker/test-run-on.yml
  pipeline/schema/.woodpecker/test-service.yml
  pipeline/schema/.woodpecker/test-step.yml
  pipeline/schema/.woodpecker/test-when.yml
  pipeline/schema/.woodpecker/test-workspace.yml
  pipeline/schema/schema.go
  pipeline/schema/schema.json
  pipeline/schema/schema_test.go
  shared/yml/yml.go
  vendor/github.com/xeipuuv/gojsonpointer/LICENSE-APACHE-2.0.txt
  vendor/github.com/xeipuuv/gojsonpointer/README.md
  vendor/github.com/xeipuuv/gojsonpointer/pointer.go
  vendor/github.com/xeipuuv/gojsonreference/LICENSE-APACHE-2.0.txt
  vendor/github.com/xeipuuv/gojsonreference/README.md
  vendor/github.com/xeipuuv/gojsonreference/reference.go
  vendor/github.com/xeipuuv/gojsonschema/.gitignore
  vendor/github.com/xeipuuv/gojsonschema/.travis.yml
  vendor/github.com/xeipuuv/gojsonschema/LICENSE-APACHE-2.0.txt
  vendor/github.com/xeipuuv/gojsonschema/README.md
  vendor/github.com/xeipuuv/gojsonschema/draft.go
  vendor/github.com/xeipuuv/gojsonschema/errors.go
  vendor/github.com/xeipuuv/gojsonschema/format_checkers.go
  vendor/github.com/xeipuuv/gojsonschema/glide.yaml
  vendor/github.com/xeipuuv/gojsonschema/go.mod
  vendor/github.com/xeipuuv/gojsonschema/go.sum
  vendor/github.com/xeipuuv/gojsonschema/internalLog.go
  vendor/github.com/xeipuuv/gojsonschema/jsonContext.go
  vendor/github.com/xeipuuv/gojsonschema/jsonLoader.go
  vendor/github.com/xeipuuv/gojsonschema/locales.go
  vendor/github.com/xeipuuv/gojsonschema/result.go
  vendor/github.com/xeipuuv/gojsonschema/schema.go
  vendor/github.com/xeipuuv/gojsonschema/schemaLoader.go
  vendor/github.com/xeipuuv/gojsonschema/schemaPool.go
  vendor/github.com/xeipuuv/gojsonschema/schemaReferencePool.go
  vendor/github.com/xeipuuv/gojsonschema/schemaType.go
  vendor/github.com/xeipuuv/gojsonschema/subSchema.go
  vendor/github.com/xeipuuv/gojsonschema/types.go
  vendor/github.com/xeipuuv/gojsonschema/utils.go
  vendor/github.com/xeipuuv/gojsonschema/validation.go
  vendor/modules.txt
Labels: documentation, feature

#365 Remote Gitea drop basic auth support
  cmd/server/setup.go
  server/remote/gitea/gitea.go
  server/remote/gitea/gitea_oauth.go
  server/remote/gitea/gitea_test.go
  server/remote/gitea/helper.go
Labels: gitea, refactor, breaking

#356 Simplify docker-compose samples
  docs/docs/20-usage/50-environment.md
  docs/docs/30-administration/00-setup.md
  docs/docs/30-administration/10-server-config.md
  docs/docs/30-administration/20-vcs/20-github.md
  docs/docs/30-administration/20-vcs/30-gitea.md
  docs/docs/30-administration/20-vcs/40-gitlab.md
  docs/docs/30-administration/20-vcs/50-bitbucket.md
  docs/docs/30-administration/20-vcs/60-bitbucket_server.md
  docs/docs/30-administration/30-database.md
  docs/docs/30-administration/60-ssl.md
Labels: documentation

#372 Delete Gerrit placeholder
  docs/docs/30-administration/20-vcs/10-overview.md
  server/remote/gerrit/gerrit.go
Labels: documentation, refactor

#371 Pass context.Context down
  server/api/build.go
  server/api/hook.go
  server/api/repo.go
  server/api/user.go
  server/grpc/rpc.go
  server/plugins/environments/filesystem.go
  server/plugins/internal/http.go
  server/plugins/sender/plugin.go
  server/queue/queue.go
  server/remote/bitbucket/bitbucket.go
  server/remote/bitbucket/bitbucket_test.go
  server/remote/bitbucket/internal/client.go
  server/remote/bitbucketserver/bitbucketserver.go
  server/remote/bitbucketserver/internal/client.go
  server/remote/coding/coding.go
  server/remote/coding/coding_test.go
  server/remote/coding/internal/coding.go
  server/remote/gitea/gitea.go
  server/remote/gitea/gitea_test.go
  server/remote/github/github.go
  server/remote/github/github_test.go
  server/remote/gitlab/gitlab.go
  server/remote/gitlab/gitlab_test.go
  server/remote/gitlab3/gitlab.go
  server/remote/gitlab3/gitlab_test.go
  server/remote/gogs/gogs.go
  server/remote/gogs/gogs_test.go
  server/remote/mocks/Remote.go
  server/remote/mocks/remote.go
  server/remote/remote.go
  server/router/middleware/session/repo.go
  server/router/middleware/token/token.go
  server/shared/configFetcher.go
  server/shared/configFetcher_test.go
  server/shared/userSyncer.go
Labels: enhancement, refactor

#373 Remove unsupported pipeline file extension "yaml"
  server/shared/configFetcher.go
Labels: refactor, skip-changelog

#218 Clean up config environment variables for server and agent
  .woodpecker/main.yml
  Dockerfile
  Dockerfile.alpine
  cli/exec/exec.go
  cmd/agent/flags.go
  cmd/cli/main.go
  cmd/server/flags.go
  cmd/server/server.go
  cmd/server/setup.go
  docker-compose.example.yml
  docs/docs/30-administration/00-setup.md
  docs/docs/30-administration/80-kubernetes.md
  docs/docs/91-migrations.md
  server/model/user.go
  server/store/datastore/store.go
Labels: refactor, breaking

#351 Update Generated Proto Code
  cmd/server/server.go
  pipeline/rpc/client_grpc.go
  pipeline/rpc/proto/drone.pb.go
  pipeline/rpc/proto/generate.go
  pipeline/rpc/proto/woodpecker.pb.go
  pipeline/rpc/proto/woodpecker.proto
  pipeline/rpc/proto/woodpecker_grpc.pb.go
  server/grpc/rpc.go
Labels: refactor

#382 Use go embed for web files and remove httptreemux
  .gitignore
  Makefile
  cmd/server/setup.go
  go.mod
  go.sum
  server/web/web.go
  vendor/github.com/dimfeld/httptreemux/.gitignore
  vendor/github.com/dimfeld/httptreemux/.travis.yml
  vendor/github.com/dimfeld/httptreemux/LICENSE
  vendor/github.com/dimfeld/httptreemux/README.md
  vendor/github.com/dimfeld/httptreemux/context.go
  vendor/github.com/dimfeld/httptreemux/group.go
  vendor/github.com/dimfeld/httptreemux/panichandler.go
  vendor/github.com/dimfeld/httptreemux/path.go
  vendor/github.com/dimfeld/httptreemux/router.go
  vendor/github.com/dimfeld/httptreemux/tree.go
  vendor/github.com/dimfeld/httptreemux/treemux_16.go
  vendor/github.com/dimfeld/httptreemux/treemux_17.go
  vendor/github.com/dimfeld/httptreemux/unescape_17.go
  vendor/github.com/dimfeld/httptreemux/unescape_18.go
  vendor/modules.txt
  web/dist/.gitkeep
  web/dist/dist.go
  web/dist/dist_gen.go
  web/web.go
  web/webpack.config.js
Labels: server, refactor

#386 [Docs] Add Migrations to header
  docs/docs/20-usage/30-matrix-builds.md
  docs/docusaurus.config.js
Labels: documentation
