Repository woodpecker-ci/woodpecker, pull requests merged in 2021-11, with the labels that each got.

#501 Use Goblin Assert as intended
  pipeline/frontend/yaml/matrix/matrix_test.go
  pipeline/frontend/yaml/types/bool_test.go
  server/model/secret_test.go
  server/remote/bitbucket/bitbucket_test.go
  server/remote/bitbucket/parse_test.go
  server/remote/coding/coding_test.go
  server/remote/coding/hook_test.go
  server/remote/gitea/gitea_test.go
  server/remote/gitea/helper_test.go
  server/remote/gitea/parse_test.go
  server/remote/github/github_test.go
  server/remote/github/parse_test.go
  server/remote/gitlab/gitlab_test.go
  server/remote/gogs/gogs_test.go
  server/remote/gogs/helper_test.go
  server/store/datastore/builds_test.go
  server/store/datastore/repos_test.go
  server/store/datastore/users_test.go
Labels: refactor, tests

#510 Fix reggression, save not activated repos to database on sync again
  server/api/user.go
  server/model/config.go
  server/store/datastore/repo.go
  server/store/datastore/repo_test.go
Labels: bug, skip-changelog

#509 format do 'simplify' and check via CI
  .golangci.yml
  Makefile
  agent/runner.go
  server/shared/procBuilder_test.go
Labels: refactor, tests

#512 Update only relevant cols on repo sync
  server/store/datastore/repo.go
  server/store/datastore/repo_test.go
Labels: bug, skip-changelog

#513 Update database in one transaction on syncing user repositorys
  server/model/perm.go
  server/shared/userSyncer.go
  server/store/datastore/feed_test.go
  server/store/datastore/permission.go
  server/store/datastore/repo.go
  server/store/datastore/repo_test.go
  server/store/datastore/users_test.go
  server/store/store.go
Labels: refactor

#506 Update Agent and Pipeline syntax documentation
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/20-usage/22-conditional-execution.md
  docs/docs/20-usage/25-multi-pipeline.md
  docs/docs/20-usage/30-matrix-builds.md
  docs/docs/30-administration/11-agent-config.md
Labels: documentation

#470 Update docs about selecting agent based on platform
  docs/docs/20-usage/20-pipeline-syntax.md
Labels: documentation

#523 Rename struct field and add new types into server/model's
  cli/repo/repo_info.go
  cmd/server/setup.go
  server/api/hook.go
  server/api/repo.go
  server/grpc/rpc.go
  server/model/build.go
  server/model/const.go
  server/model/perm.go
  server/model/proc.go
  server/model/repo.go
  server/queue/README.md
  server/queue/fifo.go
  server/queue/persistent.go
  server/queue/queue.go
  server/remote/bitbucket/convert.go
  server/remote/bitbucket/convert_test.go
  server/remote/bitbucketserver/convert.go
  server/remote/bitbucketserver/convert_test.go
  server/remote/bitbucketserver/parse.go
  server/remote/coding/coding.go
  server/remote/coding/coding_test.go
  server/remote/coding/hook.go
  server/remote/coding/hook_test.go
  server/remote/gitea/gitea.go
  server/remote/gitea/gitea_test.go
  server/remote/gitea/helper.go
  server/remote/gitea/helper_test.go
  server/remote/github/convert.go
  server/remote/github/convert_test.go
  server/remote/github/github_test.go
  server/remote/gitlab/convert.go
  server/remote/gitlab/gitlab_test.go
  server/remote/gitlab/status.go
  server/remote/gogs/gogs_test.go
  server/remote/gogs/helper.go
  server/remote/gogs/helper_test.go
  server/shared/buildStatus.go
  server/shared/procBuilder.go
  server/store/datastore/feed_test.go
  server/store/datastore/proc_test.go
Labels: refactor

#527 Use monospace font for build logs
  web/src/components/repo/build/BuildLogs.vue
Labels: ui

#526 Show environ in every BuildProc
  web/src/components/repo/build/BuildProcs.vue
  web/src/lib/api/types/build.ts
Labels: ui, enhancement

#522 store migrations: cache migrations and add note
  server/store/datastore/migration/migration.go
Labels: server, enhancement

#514 Drop error only on purpose or else report back or log
  .golangci.yml
  agent/runner.go
  cli/build/build_list.go
  cli/build/build_queue.go
  cli/exec/exec.go
  cli/lint/lint.go
  cli/registry/registry_list.go
  cli/repo/repo_list.go
  cli/repo/repo_sync.go
  cli/secret/secret_list.go
  cli/user/user_list.go
  cmd/agent/health.go
  cmd/agent/signal.go
  cmd/server/main.go
  cmd/server/server.go
  go.mod
  pipeline/backend/docker/convert.go
  pipeline/backend/docker/docker.go
  pipeline/frontend/metadata.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/compiler/params_test.go
  pipeline/frontend/yaml/constraint.go
  pipeline/frontend/yaml/constraint_test.go
  pipeline/frontend/yaml/linter/linter.go
  pipeline/frontend/yaml/types/bool.go
  pipeline/frontend/yaml/types/types_yaml_test.go
  pipeline/pipeline.go
  pipeline/rpc/client_grpc.go
  pipeline/rpc/line.go
  server/api/build.go
  server/api/file.go
  server/api/hook.go
  server/api/login.go
  server/api/repo.go
  server/api/stream.go
  server/api/user.go
  server/api/z.go
  server/grpc/rpc.go
  server/logging/log.go
  server/logging/log_test.go
  server/pubsub/pub_test.go
  server/queue/fifo_test.go
  server/queue/persistent.go
  server/remote/bitbucket/bitbucket.go
  server/remote/bitbucket/internal/client.go
  server/remote/bitbucket/parse.go
  server/remote/coding/fixtures/handler.go
  server/remote/gitea/fixtures/handler.go
  server/remote/github/convert.go
  server/remote/github/github.go
  server/remote/github/github_test.go
  server/remote/gogs/fixtures/handler.go
  server/router/middleware/session/repo.go
  server/router/middleware/session/user.go
  server/router/middleware/token/token.go
  server/shared/userSyncer.go
  server/web/config.go
  server/web/web.go
  vendor/modules.txt
Labels: enhancement, refactor

#528 Fix overflowing commit messages
  web/src/components/build-feed/BuildFeedItem.vue
  web/src/components/repo/build/BuildItem.vue
  web/src/views/repo/RepoBuild.vue
Labels: bug, ui

#531 Add linter whitespace
  .golangci.yml
  agent/runner.go
  cli/build/build_queue.go
  cmd/server/server.go
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/config_test.go
  pipeline/frontend/yaml/matrix/matrix.go
  pipeline/frontend/yaml/matrix/matrix_test.go
  pipeline/frontend/yaml/types/bool_test.go
  pipeline/frontend/yaml/types/types_yaml.go
  pipeline/frontend/yaml/types/ulimit_test.go
  server/api/login.go
  server/grpc/rpc.go
  server/model/cc_test.go
  server/model/secret_test.go
  server/remote/bitbucket/bitbucket_test.go
  server/remote/bitbucket/convert_test.go
  server/remote/bitbucket/parse_test.go
  server/remote/bitbucketserver/bitbucketserver.go
  server/remote/bitbucketserver/convert.go
  server/remote/bitbucketserver/convert_test.go
  server/remote/bitbucketserver/internal/client.go
  server/remote/coding/coding_test.go
  server/remote/coding/hook_test.go
  server/remote/coding/util_test.go
  server/remote/gitea/gitea_test.go
  server/remote/gitea/helper_test.go
  server/remote/github/convert_test.go
  server/remote/github/github_test.go
  server/remote/github/parse_test.go
  server/remote/gogs/gogs_test.go
  server/remote/gogs/helper_test.go
  server/router/middleware/session/repo.go
  server/shared/procBuilder_test.go
  server/store/datastore/repo_test.go
  server/store/datastore/users_test.go
  shared/token/token.go
Labels: refactor, tests

#530 Add linter misspell
  .golangci.yml
  agent/runner.go
  cmd/agent/signal.go
  cmd/server/server.go
  pipeline/error.go
  pipeline/frontend/yaml/container.go
  pipeline/frontend/yaml/network.go
  pipeline/frontend/yaml/secret.go
  pipeline/frontend/yaml/types/types_yaml.go
  pipeline/frontend/yaml/types/ulimit.go
  pipeline/frontend/yaml/types/volume.go
  pipeline/frontend/yaml/volume.go
  pipeline/interrupt/interrupt.go
  pipeline/rpc/peer.go
  server/api/build.go
  server/model/event.go
  server/queue/fifo_test.go
  server/queue/queue.go
  server/swagger/files/swagger.yml
Labels: refactor, tests

#535 Add linter staticcheck
  .golangci.yml
  cli/loglevel/loglevel.go
  cmd/server/setup.go
  pipeline/backend/docker/docker.go
  server/grpc/rpc.go
  server/pubsub/pub.go
  server/queue/fifo_test.go
  server/remote/bitbucketserver/internal/client.go
  server/remote/gitea/gitea.go
  server/remote/github/convert.go
  server/remote/github/github.go
Labels: refactor

#532 Fix registry delete
  cmd/server/server.go
  cmd/server/setup.go
  server/model/registry.go
  server/plugins/registry/db.go
  server/router/router.go
  server/store/datastore/registry.go
  server/store/store.go
  web/src/components/repo/settings/RegistriesTab.vue
Labels: bug, server, enhancement

#427 Replace DRONE_ with CI_ variables in pipeline steps
  .woodpecker/docs.yml
  .woodpecker/helm.yml
  .woodpecker/main.yml
  Makefile
  agent/runner.go
  cli/exec/exec.go
  cli/exec/flags.go
  docs/docs/20-usage/50-environment.md
  docs/docs/91-migrations.md
  pipeline/frontend/metadata.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/compiler/option.go
  pipeline/frontend/yaml/compiler/option_test.go
  pipeline/frontend/yaml/compiler/script_posix.go
  pipeline/frontend/yaml/compiler/script_posix_test.go
  pipeline/frontend/yaml/compiler/script_win.go
  pipeline/pipeline.go
  pipeline/samples/sample_1/.env
  pipeline/samples/sample_1/pipeline.json
  pipeline/samples/sample_10_windows/.env
  pipeline/samples/sample_10_windows/pipeline.json
  pipeline/samples/sample_2/.env
  pipeline/samples/sample_2/pipeline.json
  pipeline/samples/sample_3/.env
  pipeline/samples/sample_3/pipeline.json
  pipeline/samples/sample_4/.env
  pipeline/samples/sample_4/pipeline.json
  pipeline/samples/sample_5/.env
  pipeline/samples/sample_5/pipeline.json
  pipeline/samples/sample_6/.env
  pipeline/samples/sample_6/pipeline.json
  pipeline/samples/sample_7_redis/pipeline.json
  pipeline/samples/sample_8_network_mode/pipeline.json
  pipeline/samples/sample_9_cache/.env
  pipeline/samples/sample_9_cache/pipeline.json
  server/shared/procBuilder.go
  server/shared/procBuilder_test.go
Labels: refactor, breaking

#492 Fix passing of netrc credentials to clone step
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/option.go
  pipeline/frontend/yaml/compiler/option_test.go
Labels: bug, server

#538 Add linter varcheck
  .golangci.yml
  woodpecker-go/woodpecker/client.go
Labels: refactor

#537 Add linter structcheck
  .golangci.yml
  server/logging/log.go
  server/queue/fifo.go
Labels: refactor

#539 serve index.html directly without template
  server/web/template.go
  server/web/template_test.go
  server/web/web.go
Labels: server, refactor

#463 Add backend selection for agent
  agent/runner.go
  cli/exec/exec.go
  cmd/agent/agent.go
  cmd/agent/flags.go
  pipeline/backend/backend.go
  pipeline/backend/docker/convert.go
  pipeline/backend/docker/docker.go
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/types.go
  pipeline/backend/types/auth.go
  pipeline/backend/types/config.go
  pipeline/backend/types/conn.go
  pipeline/backend/types/engine.go
  pipeline/backend/types/network.go
  pipeline/backend/types/secret.go
  pipeline/backend/types/stage.go
  pipeline/backend/types/state.go
  pipeline/backend/types/step.go
  pipeline/backend/types/volume.go
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/logger.go
  pipeline/option.go
  pipeline/parse.go
  pipeline/pipeline.go
  pipeline/rpc/client_grpc.go
  pipeline/rpc/peer.go
  server/shared/procBuilder.go
Labels: enhancement, refactor

#541 Simplify web router code
  cmd/server/main.go
  cmd/server/server.go
  cmd/server/setup.go
  server/router/middleware/logger.go
  server/router/router.go
  server/web/config.go
  server/web/opts.go
  server/web/opts_test.go
  server/web/web.go
Labels: server, refactor

#540 Server obtain remote from glob config not from context
  cmd/server/server.go
  cmd/server/setup.go
  server/api/build.go
  server/api/hook.go
  server/api/login.go
  server/api/repo.go
  server/api/user.go
  server/config.go
  server/remote/context.go
  server/remote/remote.go
  server/router/middleware/remote.go
  server/router/middleware/session/repo.go
  server/router/middleware/token/token.go
Labels: server, refactor

#545 Fix pipeline backend autodetect
  pipeline/backend/backend.go
  pipeline/backend/docker/docker.go
  pipeline/backend/docker/pool.go
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/types/engine.go
Labels: bug, skip-changelog

#548 godotenv use autoload everywhere
  cmd/server/main.go
Labels: enhancement, skip-changelog

#544 Postgress can exec Sync2 after migration only in own transactions
  server/store/datastore/migration/migration.go
Labels: bug, server, skip-changelog

#550 Add linter ineffassign
  .golangci.yml
  server/queue/fifo.go
Labels: refactor

#553 Update docs dependencies
  docs/package.json
  docs/plugins/woodpecker-plugins/package.json
  docs/plugins/woodpecker-plugins/src/markdown.ts
  docs/plugins/woodpecker-plugins/yarn.lock
  docs/yarn.lock
Labels: documentation, dependencies

#551 Add linter unused
  .golangci.yml
  server/remote/bitbucketserver/internal/client.go
Labels: refactor

#543 Let normal repo admins change timeout to lower values
  server/api/repo.go
Labels: bug, server

#353 Improve ci tests
  .woodpecker/docs.yml
  .woodpecker/helm.yml
  .woodpecker/main.yml
  .woodpecker/test.yml
  .woodpecker/web.yml
  Makefile
Labels: tests
