Repository woodpecker-ci/woodpecker, pull requests merged in 2021-08, with the labels that each got.

#262 [Charts] Add option to pass in topology pod constraints
  charts/woodpecker-agent/Chart.yaml
  charts/woodpecker-agent/templates/deployment.yaml
  charts/woodpecker-agent/values.yaml
Labels: enhancement

#263 code.gitea.io/sdk/gitea v0.14.1 -> v0.15.0
  go.mod
  go.sum
Labels: dependencies

#264 Use woodpecker env variable instead of drone in docker-compose
  docker-compose.example.yml
Labels: documentation

#251 Use server-host as source for public links and warn if it is set to localhost
  cmd/drone-server/server.go
  remote/bitbucket/bitbucket.go
  remote/coding/coding.go
  remote/gitea/gitea_oauth.go
  remote/github/github.go
  remote/gitlab/gitlab.go
  remote/gitlab3/gitlab.go
  server/build.go
  server/configFetcher.go
  server/configFetcher_test.go
  server/hook.go
  server/repo.go
  shared/httputil/httputil.go
Labels: enhancement

#280 fix: use custom config path to sanitize build names
  server/hook.go
  server/procBuilder.go
Labels: bug

#287 [CI] Run "build" on pull too
  .woodpecker/main.yml
  go.mod
  go.sum
  tools.go
  vendor/github.com/bmatcuk/doublestar/.gitignore
  vendor/github.com/bmatcuk/doublestar/.travis.yml
  vendor/github.com/bmatcuk/doublestar/LICENSE
  vendor/github.com/bmatcuk/doublestar/README.md
  vendor/github.com/bmatcuk/doublestar/doublestar.go
  vendor/github.com/bmatcuk/doublestar/go.mod
  vendor/github.com/bradrydzewski/togo/parser/parser.go
  vendor/github.com/bradrydzewski/togo/template/format.go
  vendor/github.com/bradrydzewski/togo/template/funcs.go
  vendor/github.com/bradrydzewski/togo/template/template.go
  vendor/github.com/bradrydzewski/togo/template/template_gen.go
  vendor/github.com/woodpecker-ci/togo/action_ddl.go
  vendor/github.com/woodpecker-ci/togo/action_http.go
  vendor/github.com/woodpecker-ci/togo/action_httptest.go
  vendor/github.com/woodpecker-ci/togo/action_i18n.go
  vendor/github.com/woodpecker-ci/togo/action_sql.go
  vendor/github.com/woodpecker-ci/togo/action_tmpl.go
  vendor/github.com/woodpecker-ci/togo/main.go
  vendor/modules.txt
Labels: tests, wip, build

#279 fix: filter pipeline config files
  remote/mocks/Remote.go
  server/configFetcher.go
  server/configFetcher_test.go
Labels: bug

#289 fix: ignore pushes to tags for gitea
  remote/gitea/parse.go
Labels: bug
