Repository woodpecker-ci/woodpecker, pull requests merged in 2022-05, with the labels that each got.

#901 Add documentation about Podman usage
  docs/docs/30-administration/22-backends/10-docker.md
Labels: documentation

#831 Add support for superseding runs
  cmd/server/flags.go
  cmd/server/server.go
  docs/docs/20-usage/71-project-settings.md
  docs/docs/30-administration/10-server-config.md
  server/api/build.go
  server/api/repo.go
  server/config.go
  server/model/repo.go
  server/store/datastore/build.go
  server/store/store.go
  web/src/components/repo/settings/GeneralTab.vue
  web/src/lib/api/types/repo.ts
Labels: feature

#905 auto cancel blocked pipelines
  server/api/build.go
  server/store/datastore/build.go
Labels: enhancement

#817 Added support for step errors when executing backend
  agent/runner.go
  pipeline/backend/types/state.go
  pipeline/pipeline.go
  web/src/components/repo/build/BuildLog.vue
  web/src/compositions/useBuildProc.ts
Labels: enhancement

#900 Allow to change forge status messages
  cmd/server/flags.go
  cmd/server/server.go
  docs/docs/30-administration/10-server-config.md
  server/config.go
  server/remote/common/status.go
  server/remote/common/status_test.go
Labels: enhancement, ux

#908 Move Badge & CCMenue into own packages
  server/api/badge.go
  server/badges/badges.go
  server/ccmenu/cc.go
  server/ccmenu/cc_test.go
  server/store/datastore/build.go
Labels: refactor

#914 Allow gitea dev version
  go.mod
  go.sum
  server/remote/gitea/gitea.go
  vendor/code.gitea.io/sdk/gitea/attachment.go
  vendor/code.gitea.io/sdk/gitea/client.go
  vendor/code.gitea.io/sdk/gitea/fork.go
  vendor/code.gitea.io/sdk/gitea/go.mod
  vendor/code.gitea.io/sdk/gitea/go.sum
  vendor/code.gitea.io/sdk/gitea/hook_validate.go
  vendor/code.gitea.io/sdk/gitea/issue.go
  vendor/code.gitea.io/sdk/gitea/issue_milestone.go
  vendor/code.gitea.io/sdk/gitea/list_options.go
  vendor/code.gitea.io/sdk/gitea/notifications.go
  vendor/code.gitea.io/sdk/gitea/org_team.go
  vendor/code.gitea.io/sdk/gitea/pull.go
  vendor/code.gitea.io/sdk/gitea/pull_review.go
  vendor/code.gitea.io/sdk/gitea/release.go
  vendor/code.gitea.io/sdk/gitea/repo.go
  vendor/code.gitea.io/sdk/gitea/repo_collaborator.go
  vendor/code.gitea.io/sdk/gitea/repo_commit.go
  vendor/code.gitea.io/sdk/gitea/repo_migrate.go
  vendor/code.gitea.io/sdk/gitea/repo_transfer.go
  vendor/code.gitea.io/sdk/gitea/repo_tree.go
  vendor/code.gitea.io/sdk/gitea/repo_watch.go
  vendor/code.gitea.io/sdk/gitea/user.go
  vendor/code.gitea.io/sdk/gitea/user_app.go
  vendor/code.gitea.io/sdk/gitea/version.go
  vendor/modules.txt
Labels: forge/gitea, enhancement

#824 fix redirect after login
  server/api/login.go
  server/badges/badges.go
  web/src/compositions/useAuthentication.ts
  web/src/compositions/useUserConfig.ts
  web/src/router.ts
  web/src/views/Login.vue
  web/src/views/repo/RepoWrapper.vue
Labels: bug, ui

#912 Support localized web UI
  docs/docs/92-development/07-translations.md
  web/.eslintignore
  web/package.json
  web/src/assets/locales/en.json
  web/src/components/build-feed/BuildFeedItem.vue
  web/src/components/build-feed/BuildFeedSidebar.vue
  web/src/components/layout/header/Navbar.vue
  web/src/components/repo/build/BuildList.vue
  web/src/components/repo/build/BuildLog.vue
  web/src/components/repo/settings/ActionsTab.vue
  web/src/components/repo/settings/BadgeTab.vue
  web/src/components/repo/settings/GeneralTab.vue
  web/src/components/repo/settings/RegistriesTab.vue
  web/src/components/repo/settings/SecretsTab.vue
  web/src/compositions/useBuild.ts
  web/src/compositions/useDate.ts
  web/src/compositions/useI18n.ts
  web/src/main.ts
  web/src/utils/duration.ts
  web/src/utils/timeAgo.ts
  web/src/views/Login.vue
  web/src/views/NotFound.vue
  web/src/views/RepoAdd.vue
  web/src/views/Repos.vue
  web/src/views/ReposOwner.vue
  web/src/views/User.vue
  web/src/views/repo/RepoBranch.vue
  web/src/views/repo/RepoSettings.vue
  web/src/views/repo/RepoWrapper.vue
  web/src/views/repo/build/Build.vue
  web/src/views/repo/build/BuildChangedFiles.vue
  web/src/views/repo/build/BuildWrapper.vue
  web/vite.config.ts
  web/yarn.lock
Labels: ui, feature, translation

#918 Clarify the `when.tag` example
  docs/docs/20-usage/20-pipeline-syntax.md
Labels: documentation

#919 Drop VarArgs in steps in favour of settings
  pipeline/frontend/yaml/container.go
  pipeline/frontend/yaml/container_test.go
  pipeline/schema/.woodpecker/test-step.yml
Labels: breaking, pipeline-config

#923 remove senders
  cmd/server/flags.go
  cmd/server/server.go
  server/config.go
  server/model/sender.go
  server/plugins/sender/builtin.go
  server/plugins/sender/plugin.go
  server/store/datastore/migration/005_drop_senders.go
  server/store/datastore/migration/migration.go
  server/store/datastore/repo.go
  server/store/datastore/repo_test.go
  server/store/datastore/sender.go
  server/store/datastore/sender_test.go
  server/store/store.go
Labels: server, refactor

#925 Fix uppercase from_secrets (#842)
  pipeline/frontend/yaml/compiler/params.go
  pipeline/frontend/yaml/compiler/params_test.go
Labels: bug

#877 Do not run clone step if no pipeline step will run
  pipeline/frontend/yaml/compiler/compiler.go
  server/api/hook.go
  server/shared/procBuilder.go
Labels: feature

#930 Fix typo
  docs/docs/30-administration/100-external-configuration-api.md
Labels: bug, documentation

#928 Docs: Update YAML notes
  docs/docs/20-usage/10-intro.md
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/20-usage/30-matrix-builds.md
  docs/docs/20-usage/40-secrets.md
  docs/docs/20-usage/51-plugins/20-sample-plugin.md
  docs/docs/20-usage/60-services.md
  docs/docs/20-usage/70-volumes.md
Labels: documentation, skip-changelog

#927 Improve services docs
  docs/docs/20-usage/60-services.md
Labels: documentation

#942 fixed typo and actual name of json field
  docs/docs/30-administration/100-external-configuration-api.md
Labels: documentation

#902 Add agent tagging / filtering for pipelines
  agent/runner.go
  cli/exec/exec.go
  cli/exec/flags.go
  cmd/agent/agent.go
  cmd/agent/flags.go
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/20-usage/30-matrix-pipelines.md
  docs/docs/30-administration/15-agent-config.md
  docs/docs/91-migrations.md
  go.mod
  go.sum
  pipeline/frontend/metadata.go
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/constraint/constraint.go
  pipeline/frontend/yaml/constraint/constraint_test.go
  pipeline/rpc/client_grpc.go
  pipeline/rpc/peer.go
  pipeline/rpc/proto/generate.go
  pipeline/rpc/proto/woodpecker.pb.go
  pipeline/rpc/proto/woodpecker.proto
  pipeline/rpc/proto/woodpecker_grpc.pb.go
  pipeline/schema/.woodpecker/test-labels.yml
  pipeline/schema/.woodpecker/test-platform.yml
  pipeline/schema/schema.json
  pipeline/schema/schema_test.go
  server/grpc/filter.go
  server/grpc/filter_test.go
  server/grpc/rpc.go
  server/grpc/server.go
  server/queue/fifo.go
  server/queue/persistent.go
  server/queue/queue.go
  server/shared/procBuilder.go
  vendor/github.com/woodpecker-ci/expr/.gitignore
  vendor/github.com/woodpecker-ci/expr/README
  vendor/github.com/woodpecker-ci/expr/eval.go
  vendor/github.com/woodpecker-ci/expr/go.mod
  vendor/github.com/woodpecker-ci/expr/go.sum
  vendor/github.com/woodpecker-ci/expr/parse/lex.go
  vendor/github.com/woodpecker-ci/expr/parse/node.go
  vendor/github.com/woodpecker-ci/expr/parse/parse.go
  vendor/github.com/woodpecker-ci/expr/selector.go
  vendor/modules.txt
Labels: feature, breaking
