Repository woodpecker-ci/woodpecker, pull requests merged in 2022-04, with the labels that each got.

#871 Set default logging value of cli to info
  cli/common/flags.go
  cli/common/zerologger.go
Labels: bug, cli

#870 Display system CA error only if there is an error
  cli/internal/util.go
Labels: enhancement, cli

#872 Fix insecure /tmp usage in local backend
  pipeline/backend/local/local.go
Labels: agent, security

#876 Do not ignore failure to clean up the context
  pipeline/backend/local/local.go
Labels: agent, skip-changelog

#875 Add some warning regarding the local backend
  docs/docs/30-administration/22-backends/20-local.md
Labels: documentation

#879 fix: ansi logging
  web/src/components/repo/build/BuildLog.vue
Labels: bug, server

#880 fix: ansi logging (#879)
  web/src/components/repo/build/BuildLog.vue
Labels: bug, server

#881 Update changelog
  CHANGELOG.md
Labels: documentation, skip-changelog

#878 FIX: database docker-compose documentation
  docs/docs/30-administration/30-database.md
Labels: documentation

#882 Update helm chart releasing
  .woodpecker/helm.yml
  charts/woodpecker-agent/Chart.yaml
  charts/woodpecker-server/Chart.yaml
Labels: bug, backport, chart

#883 Add gitea with woodpecker blogpost
  docs/docs/92-awesome.md
Labels: documentation

#885 Take in an io.Reader instead of file path for schema linter
  cli/lint/lint.go
  pipeline/schema/schema.go
  pipeline/schema/schema_test.go
  shared/yml/yml.go
Labels: enhancement

#886 Initial version of CLI docs
  Makefile
  cmd/cli/app.go
  cmd/cli/docs.go
  cmd/cli/main.go
  docs/docs/40-cli.md
Labels: documentation

#887 Fix phrasing
  docs/docs/20-usage/25-multi-pipeline.md
Labels: documentation

#888 Update helm chart releasing (#882)
  .woodpecker/helm.yml
  charts/woodpecker-agent/Chart.yaml
  charts/woodpecker-server/Chart.yaml
Labels: bug, chart

#889 fix key/val format for dind env vars
  charts/woodpecker-agent/values.yaml
Labels: bug, chart

#890 fix key/val format for dind env vars (#889)
  charts/woodpecker-agent/values.yaml
Labels: bug, chart

#893 Add support to define a custom docker network and enable docker ipv6
  docs/docs/30-administration/15-agent-config.md
  docs/docs/30-administration/22-backends/10-docker.md
  docs/docs/40-cli.md
  pipeline/backend/docker/docker.go
Labels: feature

#897 Fix spelling
  docs/docs/30-administration/22-backends/10-docker.md
Labels: documentation
