Repository woodpecker-ci/woodpecker, pull requests merged in 2022-11, with the labels that each got.

#1380 Add pipeline.step.when.branch string-array type to schema.json
  pipeline/schema/schema.json
Labels: bug, documentation

#1388 Support .yaml as file-ending for workflow config too
  cli/common/pipeline.go
  docs/docs/20-usage/25-multi-pipeline.md
  docs/docs/20-usage/71-project-settings.md
  docs/docs/91-migrations.md
  server/shared/configFetcher.go
  server/shared/configFetcher_test.go
  server/shared/stepBuilder.go
  server/shared/stepBuilder_test.go
  shared/constant/constant.go
Labels: enhancement, pipeline-config

#1392 Wait for gitea to start in gitpod
  .gitpod.yml
Labels: devx

#1384 Update json schema for cli lint to cover valid cases
  pipeline/schema/schema.json
Labels: bug, cli

#1387 Fix indentation for pipeline-global `when` documentation
  docs/docs/20-usage/20-pipeline-syntax.md
Labels: documentation

#1383 Show workflow state in ui and collapse completed workflows
  web/src/components/repo/pipeline/PipelineStepList.vue
  web/src/views/repo/pipeline/Pipeline.vue
Labels: ui, enhancement

#1395 Fix `local` and `ssh` backends
  pipeline/backend/local/local.go
  pipeline/backend/ssh/ssh.go
Labels: bug, agent, skip-changelog, backend/local, backend/ssh

#1397 GenerateScript should not return encoded script
  go.mod
  go.sum
  pipeline/backend/common/script.go
  pipeline/backend/common/script_posix.go
  pipeline/backend/common/script_posix_test.go
  pipeline/backend/common/script_win.go
  pipeline/backend/local/local.go
  pipeline/backend/ssh/ssh.go
Labels: refactor, skip-changelog

#1403 web: remove unused @meforma/vue-toaster
  web/package.json
  web/pnpm-lock.yaml
Labels: ui, security, dependencies

#1402 Fix cut of woodpecker animation
  web/src/components/repo/pipeline/PipelineRunningIcon.vue
Labels: bug, ui

#1404 Bump Frontend Deps and remove unused
  web/package.json
  web/yarn.lock
Labels: ui, dependencies

#1399 Match notification font size to rest of the UI
  web/src/style.css
Labels: ui

#1405 Spelling
  .woodpecker/docs.yml
  CHANGELOG.md
  charts/woodpecker-agent/values.yaml
  cmd/server/flags.go
  cmd/server/server.go
  cmd/server/setup.go
  docs/docs/30-administration/10-server-config.md
  docs/docs/30-administration/100-external-configuration-api.md
  docs/docs/91-migrations.md
  docs/docs/92-awesome.md
  docs/docs/92-development/01-getting-started.md
  docs/plugins/woodpecker-plugins/plugins.json
  docs/versioned_docs/version-0.15/30-administration/10-server-config.md
  docs/versioned_docs/version-0.15/30-administration/15-agent-config.md
  docs/versioned_docs/version-0.15/91-migrations.md
  docs/versioned_docs/version-0.15/92-awesome.md
  docs/versioned_docs/version-0.15/92-development/01-getting-started.md
  pipeline/backend/local/local.go
  server/api/pipeline.go
  server/api/stream.go
  server/cron/cron.go
  server/forge/bitbucket/bitbucket.go
  server/forge/bitbucket/internal/types.go
  server/forge/bitbucketserver/bitbucketserver.go
  server/forge/coding/coding.go
  server/forge/coding/coding_test.go
  server/forge/coding/hook.go
  server/forge/coding/hook_test.go
  server/forge/coding/internal/webhook.go
  server/forge/gitea/gitea.go
  server/forge/github/fixtures/hooks.go
  server/forge/github/github.go
  server/forge/github/github_test.go
  server/forge/github/parse_test.go
  server/forge/gitlab/gitlab.go
  server/forge/gitlab/testdata/projects.go
  server/forge/gitlab/testdata/testdata.go
  server/forge/gogs/gogs_test.go
  server/forge/remote.go
  server/logging/log.go
  server/model/step.go
  server/pubsub/pubsub.go
  server/store/datastore/migration/000_legacy_to_xorm.go
  server/store/store.go
  server/swagger/files/swagger.yml
  shared/constant/constant.go
  shared/utils/context.go
  web/src/compositions/useTabs.ts
  web/src/store/pipelines.ts
Labels: refactor

#1413 Fix broken link in FAQ
  docs/src/pages/faq.md
Labels: documentation

#1409 Use icons for step and workflow states
  web/components.d.ts
  web/src/assets/locales/en.json
  web/src/components/atomic/Icon.vue
  web/src/components/pipeline-feed/PipelineFeedItem.vue
  web/src/components/repo/pipeline/PipelineItem.vue
  web/src/components/repo/pipeline/PipelineStatusIcon.vue
  web/src/components/repo/pipeline/PipelineStepList.vue
  web/src/components/repo/pipeline/pipeline-status.ts
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: ui, enhancement

#1300 Fix reopening gitpod workspace
  .gitpod.yml
Labels: devx

#1368 Use pipeline wrapper and improve scaffold UI
  web/src/components/layout/FluidContainer.vue
  web/src/components/layout/scaffold/Scaffold.vue
  web/src/components/layout/scaffold/Tab.vue
  web/src/views/repo/pipeline/Pipeline.vue
  web/src/views/repo/pipeline/PipelineChangedFiles.vue
  web/src/views/repo/pipeline/PipelineConfig.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: ui

#1418 Rename forge-id to forge-remote-id
  server/api/hook.go
  server/api/repo.go
  server/forge/bitbucket/bitbucket.go
  server/forge/bitbucket/convert.go
  server/forge/bitbucketserver/bitbucketserver.go
  server/forge/bitbucketserver/convert.go
  server/forge/coding/coding.go
  server/forge/forge.go
  server/forge/gitea/gitea.go
  server/forge/gitea/gitea_test.go
  server/forge/gitea/helper.go
  server/forge/github/convert.go
  server/forge/github/github.go
  server/forge/github/github_test.go
  server/forge/gitlab/convert.go
  server/forge/gitlab/gitlab.go
  server/forge/gogs/gogs.go
  server/forge/gogs/gogs_test.go
  server/forge/gogs/helper.go
  server/forge/mocks/forge.go
  server/model/repo.go
  server/store/datastore/feed_test.go
  server/store/datastore/migration/013_rename_forge_id_to_forge_remote_id.go
  server/store/datastore/migration/migration.go
  server/store/datastore/permission.go
  server/store/datastore/permission_test.go
  server/store/datastore/repo.go
  server/store/datastore/repo_test.go
  server/store/datastore/users_test.go
  server/store/mocks/store.go
  server/store/store.go
Labels: refactor

#1219 Add option to ignore failures on steps
  docs/docs/20-usage/20-pipeline-syntax.md
  pipeline/backend/types/step.go
  pipeline/frontend/metadata.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/container.go
  pipeline/pipeline.go
  pipeline/schema/schema.json
Labels: server, enhancement, pipeline-config

#1317 Unify buttons, links and improve focus styles
  web/src/assets/locales/en.json
  web/src/components/atomic/Button.vue
  web/src/components/atomic/IconButton.vue
  web/src/components/atomic/ListItem.vue
  web/src/components/form/Checkbox.vue
  web/src/components/form/RadioField.vue
  web/src/components/form/SelectField.vue
  web/src/components/form/TextField.vue
  web/src/components/layout/Panel.vue
  web/src/components/layout/header/ActivePipelines.vue
  web/src/components/layout/header/Navbar.vue
  web/src/components/layout/header/NavbarIcon.vue
  web/src/components/layout/scaffold/Header.vue
  web/src/components/repo/pipeline/PipelineItem.vue
  web/src/components/repo/pipeline/PipelineList.vue
  web/src/components/repo/pipeline/PipelineStepList.vue
  web/src/views/RepoAdd.vue
  web/src/views/Repos.vue
  web/src/views/ReposOwner.vue
  web/src/views/repo/RepoBranches.vue
  web/src/views/repo/RepoWrapper.vue
  web/windi.config.ts
Labels: bug, ui

#1424 Fix pipeline feed initially loaded not updated by events
  server/model/feed.go
  server/store/datastore/feed.go
Labels: bug, ui

#1426 Dismiss popup with escape
  web/src/components/layout/Popup.vue
Labels: ui, enhancement

#1423 Change healtcheck port into address format, redo #1197
  cmd/agent/agent.go
  cmd/agent/flags.go
  cmd/agent/health.go
  docs/docs/30-administration/15-agent-config.md
Labels: enhancement

#1434 Point docs nav bar items to selected version
  docs/docusaurus.config.js
  docs/package.json
  docs/plugins/woodpecker-plugins/package.json
  docs/plugins/woodpecker-plugins/pnpm-lock.yaml
  docs/pnpm-lock.yaml
Labels: documentation

#1432 Refresh token when running cron
  server/cron/cron.go
Labels: bug, server

#1419 Fix wrong drone env vars
  agent/runner.go
  pipeline/drone_compatibility.go
  pipeline/frontend/drone_compatibility.go
  pipeline/frontend/metadata.go
  pipeline/pipeline.go
  pipeline/tracer.go
Labels: bug

#1439 CI: pin xgo and go to v1.18.7
  .woodpecker/binaries.yml
  .woodpecker/docker.yml
  .woodpecker/docs.yml
  .woodpecker/test.yml
Labels: build

#1441 Refactor agent: split code in subfunctions
  agent/logger.go
  agent/runner.go
  agent/tracer.go
  cli/exec/exec.go
  pipeline/pipeline.go
  server/grpc/rpc.go
Labels: bug, agent, refactor

#1456 Improve button and input contrast in dark mode
  web/src/components/atomic/Button.vue
  web/src/components/form/Checkbox.vue
  web/src/components/form/RadioField.vue
Labels: ui, enhancement
