Repository woodpecker-ci/woodpecker, pull requests merged in 2022-08, with the labels that each got.

#1076 Fix gitpod docs link
  README.md
Labels: documentation

#1067 Remove xterm and use ansi converter for logs
  web/package.json
  web/src/components/repo/build/BuildLog.vue
  web/src/style/console.css
  web/yarn.lock
Labels: server, ui, refactor

#1064 Add `logs` command to CLI & update forges features docs
  cli/build/build_logs.go
  docs/docs/30-administration/11-forges/10-overview.md
  woodpecker-go/woodpecker/client.go
  woodpecker-go/woodpecker/interface.go
  woodpecker-go/woodpecker/types.go
Labels: documentation, feature, cli

#1083 Update dependencies and tiny adjustments to UI
  web/.eslintignore
  web/.eslintrc.js
  web/.prettierignore
  web/components.d.ts
  web/package.json
  web/src/components/atomic/Button.vue
  web/src/components/atomic/IconButton.vue
  web/src/components/atomic/ListItem.vue
  web/src/components/build-feed/BuildFeedSidebar.vue
  web/src/components/form/Checkbox.vue
  web/src/components/form/RadioField.vue
  web/src/components/form/TextField.vue
  web/src/components/layout/header/ActiveBuilds.vue
  web/src/components/repo/build/BuildItem.vue
  web/src/components/repo/build/BuildLog.vue
  web/src/components/repo/build/BuildProcList.vue
  web/src/components/repo/build/BuildRunningIcon.vue
  web/src/components/tabs/Tabs.vue
  web/src/views/Login.vue
  web/src/views/repo/RepoWrapper.vue
  web/src/views/repo/build/BuildWrapper.vue
  web/tsconfig.eslint.json
  web/yarn.lock
Labels: bug, ui, dependencies

#1082 Add syntax highlighting for pipeline config
  web/package.json
  web/src/components/atomic/SyntaxHighlight.ts
  web/src/style/prism.css
  web/src/views/repo/build/BuildConfig.vue
  web/vite.config.ts
  web/yarn.lock
Labels: server, ui, feature

#1086 Hide log output container if step does not have logs
  web/src/components/repo/build/BuildLog.vue
Labels: bug, ui

#1093 Use local search and update docusaurus
  .woodpecker/docs.yml
  docs/docusaurus.config.js
  docs/package.json
  docs/yarn.lock
Labels: documentation

#1103 Fix agent filter cli attribute name
  cmd/agent/agent.go
Labels: bug, agent

#1075 Support Docker credential helpers
  docs/docs/30-administration/22-backends/10-docker.md
  server/plugins/registry/filesystem.go
Labels: documentation, enhancement, backend/docker

#1106 Install missing peer dependency
  web/package.json
  web/yarn.lock
Labels: ui

#1107 Add more documentation for local backend
  docs/docs/30-administration/22-backends/20-local.md
Labels: documentation

#1104 Add depends_on to pipeline syntax docs
  docs/docs/20-usage/20-pipeline-syntax.md
Labels: documentation

#1072 Publish preview docker images of pulls
  .woodpecker/docker.yml
  .woodpecker/test.yml
Labels: build

#1087 Allow multiple when conditions
  docs/docs/20-usage/20-pipeline-syntax.md
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/config_test.go
  pipeline/frontend/yaml/constraint/constraint.go
  pipeline/frontend/yaml/constraint/constraint_test.go
  pipeline/frontend/yaml/container.go
  pipeline/frontend/yaml/container_test.go
  pipeline/schema/.woodpecker/test-when.yml
  pipeline/schema/schema.json
Labels: feature, pipeline-config

#1108 Use fixed version of git clone plugin
  shared/constant/constant.go
Labels: server, enhancement

#1110 Checkout tags on tag pipeline
  pipeline/frontend/yaml/compiler/compiler.go
Labels: feature

#1066 Fix to show build pipeline parse error
  pipeline/frontend/yaml/error.go
  pipeline/frontend/yaml/matrix/matrix.go
  server/pipeline/create.go
  server/pipeline/items.go
  server/pipeline/restart.go
  server/shared/procBuilder.go
Labels: bug

#1112 refactor: use switch-case not try-err
  pipeline/frontend/yaml/constraint/constraint.go
Labels: refactor, skip-changelog

#1113 Add cli support for global and organization secrets
  cli/secret/secret.go
  cli/secret/secret_add.go
  cli/secret/secret_info.go
  cli/secret/secret_list.go
  cli/secret/secret_rm.go
  cli/secret/secret_set.go
  docs/docs/40-cli.md
Labels: feature, cli

#1118 Note change to /woodpecker in default workspace path
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/91-migrations.md
Labels: documentation

#1031 Implement Refresher for GitLab and refactor nits
  server/remote/gitea/gitea.go
  server/remote/gitlab/gitlab.go
Labels: bug, forge/gitlab, refactor

#1120 Implement Refresher for GitLab (#1031)
  server/remote/gitlab/gitlab.go
Labels: bug, forge/gitlab

#1124 update golang.org/x/crypto
  go.mod
  go.sum
  vendor/golang.org/x/crypto/AUTHORS
  vendor/golang.org/x/crypto/CONTRIBUTORS
  vendor/golang.org/x/crypto/acme/acme.go
  vendor/golang.org/x/crypto/acme/autocert/autocert.go
  vendor/golang.org/x/crypto/acme/autocert/cache.go
  vendor/golang.org/x/crypto/acme/autocert/listener.go
  vendor/golang.org/x/crypto/acme/jws.go
  vendor/golang.org/x/crypto/acme/rfc8555.go
  vendor/golang.org/x/crypto/openpgp/armor/armor.go
  vendor/golang.org/x/crypto/openpgp/armor/encode.go
  vendor/golang.org/x/crypto/openpgp/elgamal/elgamal.go
  vendor/golang.org/x/crypto/sha3/doc.go
  vendor/golang.org/x/crypto/sha3/sha3_s390x.go
  vendor/modules.txt
Labels: bug, security, dependencies

#1125 Bump deps
  go.mod
  go.sum
  pipeline/frontend/yaml/compiler/params.go
  pipeline/schema/schema.go
Labels: dependencies

#1123 move away from deprecated funcs
  agent/runner.go
  cli/exec/exec.go
  pipeline/backend/local/local.go
  server/store/datastore/file_test.go
  server/store/datastore/log.go
Labels: refactor

#1005 Pipeline compiler should not alter specified image
  pipeline/backend/local/local.go
  pipeline/backend/ssh/ssh.go
  pipeline/frontend/yaml/compiler/convert.go
Labels: bug, server, refactor

#1127 Remove own copy of oauth2 implementation
  server/remote/gitlab/gitlab.go
  shared/oauth2/oauth2.go
Labels: server, forge/gitlab, refactor

#1134 fix migration number
  server/store/datastore/migration/007_secrets_add_user.go
Labels: bug, skip-changelog

#1135 Fix local agent config example in docs
  docs/docs/30-administration/22-backends/20-local.md
Labels: bug, documentation, skip-changelog

#1136 Add Ansible-NAS to the awesome list
  docs/docs/92-awesome.md
Labels: documentation

#1140 Add default event filter
  Makefile
  docs/docs/20-usage/20-pipeline-syntax.md
  pipeline/frontend/yaml/constraint/constraint.go
  pipeline/frontend/yaml/constraint/constraint_test.go
  pipeline/schema/schema.json
  server/shared/procBuilder_test.go
Labels: feature

#1141 Dedup code and migrate away from deprecated funcs
  cli/common/flags.go
  cli/registry/registry_add.go
  cli/registry/registry_info.go
  cli/registry/registry_list.go
  cli/registry/registry_rm.go
  cli/registry/registry_set.go
  pipeline/multipart/reader_test.go
  server/plugins/utils/http.go
  server/remote/bitbucket/internal/client.go
  server/remote/bitbucket/parse.go
  server/remote/bitbucketserver/bitbucketserver.go
  server/remote/bitbucketserver/internal/client.go
  server/remote/coding/hook.go
  server/remote/coding/hook_test.go
  server/remote/coding/internal/coding.go
  server/remote/github/parse.go
  server/remote/remote.go
  server/shared/configFetcher_test.go
  server/shared/procBuilder.go
  server/store/datastore/file.go
  server/store/datastore/log_test.go
  server/store/datastore/migration/migration_test.go
  web/web.go
  woodpecker-go/woodpecker/client.go
  woodpecker-go/woodpecker/interface.go
Labels: refactor, skip-changelog

#1142 Make it clear that MariaDB is also a supported DB
  docs/docs/30-administration/30-database.md
Labels: documentation

#1143 use yaml alias and adjust build targets for docker images
  .woodpecker/docker.yml
  docker/Dockerfile.server.multiarch
Labels: enhancement, build

#1146 create mock for store and add unit tests for cron
  cmd/server/server.go
  server/cron/cron.go
  server/cron/cron_test.go
  server/store/mocks/store.go
  server/store/store.go
Labels: server, tests
