Repository woodpecker-ci/woodpecker, pull requests merged in 2022-03, with the labels that each got.

#816 Fix Makefile by exposing VERSION_NUMBER var for buldle targets
  Makefile
Labels: skip-changelog, build

#815 Allow loading sensitive flags from files
  cmd/agent/flags.go
  cmd/server/flags.go
  docs/docs/30-administration/10-server-config.md
  docs/docs/30-administration/11-vcs/20-github.md
  docs/docs/30-administration/11-vcs/30-gitea.md
  docs/docs/30-administration/11-vcs/40-gitlab.md
  docs/docs/30-administration/11-vcs/50-bitbucket.md
  docs/docs/30-administration/11-vcs/60-bitbucket_server.md
  docs/docs/30-administration/11-vcs/70-gogs.md
  docs/docs/30-administration/11-vcs/80-coding.md
  docs/docs/30-administration/15-agent-config.md
Labels: feature

#823 Add editing of secrets and registries
  web/package.json
  web/src/components/atomic/Button.vue
  web/src/components/atomic/Icon.vue
  web/src/components/form/TextField.vue
  web/src/components/repo/settings/RegistriesTab.vue
  web/src/components/repo/settings/SecretsTab.vue
  web/src/lib/api/index.ts
  web/yarn.lock
Labels: ui, feature

#825 Add missing flag and docs
  cmd/server/flags.go
  docs/docs/30-administration/10-server-config.md
Labels: documentation

#828 fix secret updating
  server/api/secret.go
  web/src/components/repo/settings/SecretsTab.vue
Labels: bug, skip-changelog

#832 Fix link in documentation
  docs/docs/20-usage/25-multi-pipeline.md
  docs/docs/30-administration/10-server-config.md
Labels: bug, documentation, skip-changelog

#835 Fix various typos
  CHANGELOG.md
  docs/docs/20-usage/71-project-settings.md
  docs/docs/30-administration/10-server-config.md
  docs/docs/30-administration/15-agent-config.md
  docs/docs/92-development/06-guides.md
  server/plugins/environments/parse.go
  server/shared/configFetcher.go
  server/store/datastore/repo.go
  shared/utils/strings.go
Labels: documentation, skip-changelog

#836 support conditional branch as an array to align with documentation
  pipeline/schema/.woodpecker/test-when.yml
  pipeline/schema/schema.json
Labels: bug, documentation

#709 Add support to run pipelines using a local backend
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/30-administration/15-agent-config.md
  pipeline/backend/backend.go
  pipeline/backend/local/local.go
Labels: agent, feature

#838 [Charts] Add option to pass in updateStrategy
  charts/woodpecker-server/templates/deployment.yaml
  charts/woodpecker-server/values.yaml
Labels: enhancement, chart

#842 Fix uppercase from_secrets
  pipeline/frontend/yaml/compiler/params.go
  pipeline/frontend/yaml/compiler/params_test.go
Labels: bug, backport

#844 Docs: Fix link on FAQ page
  docs/src/pages/faq.md
Labels: documentation

#852 Use Gogs' try instance as default value
  cmd/server/flags.go
  docs/docs/30-administration/11-vcs/70-gogs.md
Labels: documentation

#858 Add ingressClassName to ingress template
  charts/woodpecker-server/templates/ingress.yaml
  charts/woodpecker-server/values.yaml
Labels: chart
