Repository woodpecker-ci/woodpecker, pull requests merged in 2022-06, with the labels that each got.

#943 Improve UI colors to have more contrast
  web/src/components/layout/Panel.vue
  web/src/components/repo/build/BuildProcList.vue
Labels: ui, ux

#916 Use asym key to sign webhooks
  cmd/server/flags.go
  cmd/server/server.go
  cmd/server/setup.go
  docs/docs/30-administration/10-server-config.md
  docs/docs/30-administration/100-external-configuration-api.md
  docs/docs/91-migrations.md
  go.mod
  go.sum
  server/api/build.go
  server/api/signature_public_key.go
  server/config.go
  server/model/server_config.go
  server/plugins/config/extension.go
  server/plugins/config/http.go
  server/plugins/configuration/configuration.go
  server/plugins/internal/http.go
  server/plugins/utils/http.go
  server/plugins/utils/http_test.go
  server/router/api.go
  server/shared/configFetcher.go
  server/shared/configFetcher_test.go
  server/store/datastore/migration/migration.go
  server/store/datastore/server_config.go
  server/store/datastore/server_config_test.go
  server/store/store.go
  vendor/github.com/99designs/httpsignatures-go/.travis.yml
  vendor/github.com/99designs/httpsignatures-go/LICENSE
  vendor/github.com/99designs/httpsignatures-go/README.md
  vendor/github.com/99designs/httpsignatures-go/algorithm.go
  vendor/github.com/99designs/httpsignatures-go/signature.go
  vendor/github.com/99designs/httpsignatures-go/signer.go
  vendor/github.com/go-ap/httpsig/LICENSE
  vendor/github.com/go-ap/httpsig/Makefile
  vendor/github.com/go-ap/httpsig/README.md
  vendor/github.com/go-ap/httpsig/common.go
  vendor/github.com/go-ap/httpsig/ed25519.go
  vendor/github.com/go-ap/httpsig/go.mod
  vendor/github.com/go-ap/httpsig/go.sum
  vendor/github.com/go-ap/httpsig/handler.go
  vendor/github.com/go-ap/httpsig/hmac.go
  vendor/github.com/go-ap/httpsig/httpsig.go
  vendor/github.com/go-ap/httpsig/keystore.go
  vendor/github.com/go-ap/httpsig/rsa.go
  vendor/github.com/go-ap/httpsig/sign.go
  vendor/github.com/go-ap/httpsig/verify.go
  vendor/modules.txt
Labels: enhancement, breaking

#950 Fix nil pointer
  server/shared/configFetcher.go
Labels: bug

#962 fix name of field in the response from config api
  docs/docs/30-administration/100-external-configuration-api.md
Labels: bug, documentation

#965 replace run_on references with runs_on
  docs/docs/20-usage/25-multi-pipeline.md
  pipeline/schema/.woodpecker/test-run-on.yml
  pipeline/schema/schema.json
Labels: bug, documentation

#826 Add support for steps to be a list (instead of dict)
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/container.go
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/schema/schema.json
Labels: feature, pipeline-config

#967 Add Changelog v0.15.2 (#966)
  CHANGELOG.md
Labels: documentation, skip-changelog

#969 Update .vscode/launch.json
  .vscode/launch.json
Labels: skip-changelog

#970 Make pipeline runtime log with description
  agent/runner.go
  cli/exec/exec.go
  pipeline/option.go
  pipeline/pipeline.go
Labels: agent, enhancement, cli

#949 Move Server Pipeline Build code out of api into own package
  server/api/build.go
  server/api/helper.go
  server/api/hook.go
  server/pipeline/approve.go
  server/pipeline/cancel.go
  server/pipeline/config.go
  server/pipeline/create.go
  server/pipeline/decline.go
  server/pipeline/errors.go
  server/pipeline/filter.go
  server/pipeline/helper.go
  server/pipeline/items.go
  server/pipeline/queue.go
  server/pipeline/restart.go
  server/pipeline/start.go
  server/pipeline/topic.go
Labels: refactor

#975 Return to page after clicking login at navbar
  web/src/components/layout/header/Navbar.vue
Labels: bug, ui, ux

#972 Document package architecture
  docs/docs/92-development/05-architecture.md
  server/model/build.go
  server/model/proc.go
  server/shared/buildStatus.go
  server/shared/buildStatus_test.go
  server/shared/configFetcher.go
  server/shared/configFetcher_test.go
  server/shared/procBuilder.go
  server/shared/procBuilder_test.go
  server/shared/procStatus.go
  server/shared/procStatus_test.go
  server/shared/userSyncer.go
Labels: documentation

#981 Add Changelog for v0.15.3
  CHANGELOG.md
Labels: documentation, skip-changelog

#846 Use xterm.js for log outputs
  web/package.json
  web/src/assets/locales/en.json
  web/src/components/repo/build/BuildLog.vue
  web/src/components/repo/build/BuildProcList.vue
  web/src/compositions/useBuildProc.ts
  web/src/views/repo/RepoBranch.vue
  web/src/views/repo/build/Build.vue
  web/src/views/repo/build/BuildWrapper.vue
  web/yarn.lock
Labels: ui, enhancement

#984 Revert "hotfix to get no missmatch [1 & 2]"
  .woodpecker/binaries.yml
  .woodpecker/docker.yml
  .woodpecker/docs.yml
  .woodpecker/helm.yml
  .woodpecker/test.yml
  .woodpecker/web.yml
Labels: skip-changelog

#985 Improve dark style text color for better readibility
  web/src/App.vue
  web/src/assets/locales/en.json
  web/src/components/atomic/Button.vue
  web/src/components/atomic/IconButton.vue
  web/src/components/build-feed/BuildFeedItem.vue
  web/src/components/build-feed/BuildFeedSidebar.vue
  web/src/components/form/Checkbox.vue
  web/src/components/form/InputField.vue
  web/src/components/form/RadioField.vue
  web/src/components/form/SelectField.vue
  web/src/components/form/TextField.vue
  web/src/components/layout/header/Navbar.vue
  web/src/components/repo/build/BuildItem.vue
  web/src/components/repo/build/BuildList.vue
  web/src/components/repo/build/BuildLog.vue
  web/src/components/repo/settings/ActionsTab.vue
  web/src/components/repo/settings/BadgeTab.vue
  web/src/components/repo/settings/GeneralTab.vue
  web/src/components/repo/settings/RegistriesTab.vue
  web/src/components/repo/settings/SecretsTab.vue
  web/src/components/tabs/Tabs.vue
  web/src/main.ts
  web/src/style.css
  web/src/views/Login.vue
  web/src/views/RepoAdd.vue
  web/src/views/Repos.vue
  web/src/views/ReposOwner.vue
  web/src/views/User.vue
  web/src/views/repo/RepoBranch.vue
  web/src/views/repo/RepoBranches.vue
  web/src/views/repo/RepoSettings.vue
  web/src/views/repo/RepoWrapper.vue
  web/src/views/repo/build/Build.vue
  web/src/views/repo/build/BuildChangedFiles.vue
  web/src/views/repo/build/BuildConfig.vue
  web/src/views/repo/build/BuildWrapper.vue
Labels: ui

#988 Add option to launch all needed services for local development
  .gitignore
  .vscode/launch.json
  docs/docs/92-development/01-getting-started.md
Labels: documentation

#987 Show forge icons in UI
  server/remote/bitbucket/bitbucket.go
  server/remote/bitbucketserver/bitbucketserver.go
  server/remote/coding/coding.go
  server/remote/gitea/gitea.go
  server/remote/github/github.go
  server/remote/gitlab/gitlab.go
  server/remote/gogs/gogs.go
  server/remote/mocks/remote.go
  server/remote/remote.go
  server/web/config.go
  web/src/components/atomic/Icon.vue
  web/src/compositions/useConfig.ts
  web/src/views/repo/RepoWrapper.vue
Labels: server, ui, enhancement

#996 Extend FAQ with clone debugging howto
  docs/src/pages/faq.md
Labels: documentation

#997 Add German Translation
  web/src/assets/locales/de.json
  web/src/assets/locales/en.json
  web/src/assets/locales/lv.json
  web/src/compositions/useDate.ts
  web/src/utils/timeAgo.ts
Labels: translation
