Repository woodpecker-ci/woodpecker, pull requests merged in 2022-02, with the labels that each got.

#660 Add Codecov.io Upload
  .woodpecker/test.yml
  Makefile
  README.md
  docs/docs/20-usage/50-environment.md
Labels: tests

#743 fix codecov when
  .woodpecker/test.yml
Labels: bug, skip-changelog

#744 add awesome page
  docs/docs/92-awesome.md
  docs/docusaurus.config.js
  docs/package.json
  docs/plugins/woodpecker-plugins/package.json
  docs/yarn.lock
Labels: documentation

#750 Allow specifying dind container in values
  charts/woodpecker-agent/templates/deployment.yaml
  charts/woodpecker-agent/values.yaml
Labels: enhancement, chart

#666 Add documentation of all server configuration options
  cmd/server/flags.go
  docs/docs/30-administration/10-server-config.md
Labels: documentation

#753 Add repo-link to badge markdown in UI
  web/src/components/repo/settings/BadgeTab.vue
Labels: ui, enhancement

#760 Add flag to always authenticate when cloning public repositories
  cmd/server/flags.go
  cmd/server/server.go
  docs/docs/30-administration/10-server-config.md
  server/config.go
  server/shared/procBuilder.go
Labels: server, enhancement

#756 UI: show date time on hover over time items
  web/package.json
  web/src/components/build-feed/BuildFeedItem.vue
  web/src/components/repo/build/BuildItem.vue
  web/src/compositions/useBuild.ts
  web/src/main.ts
  web/src/views/repo/build/BuildWrapper.vue
  web/yarn.lock
Labels: ui, enhancement

#763 Use `DOCKER_HOST` env to search for docker before searching for a hardcode docker socket
  pipeline/backend/docker/docker.go
Labels: agent, enhancement

#755 Move vcs configs and hide some unstable options from docs
  docs/docs/30-administration/10-server-config.md
  docs/docs/30-administration/11-vcs/10-overview.md
  docs/docs/30-administration/11-vcs/20-github.md
  docs/docs/30-administration/11-vcs/30-gitea.md
  docs/docs/30-administration/11-vcs/40-gitlab.md
  docs/docs/30-administration/11-vcs/50-bitbucket.md
  docs/docs/30-administration/11-vcs/60-bitbucket_server.md
  docs/docs/30-administration/11-vcs/70-gogs.md
  docs/docs/30-administration/11-vcs/80-coding.md
  docs/docs/30-administration/11-vcs/_category_.yml
  docs/docs/30-administration/11-vcs/gitea_oauth.gif
  docs/docs/30-administration/11-vcs/github_oauth.png
  docs/docs/30-administration/15-agent-config.md
Labels: documentation, skip-changelog

#759 Add support for building in docker
  Makefile
  docker/Dockerfile.make
Labels: build

#769 Add support for default clone image environment variable
  cmd/server/flags.go
  cmd/server/server.go
  docs/docs/30-administration/10-server-config.md
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/option.go
  pipeline/frontend/yaml/compiler/option_test.go
  server/config.go
  server/shared/procBuilder.go
Labels: enhancement

#766 Follow-up for date tooltip
  web/package.json
  web/src/components/build-feed/BuildFeedItem.vue
  web/src/components/repo/build/BuildItem.vue
  web/src/compositions/useBuild.ts
  web/src/compositions/useDate.ts
  web/src/main.ts
  web/src/views/repo/build/BuildWrapper.vue
  web/yarn.lock
Labels: enhancement, skip-changelog

#779 Update docker hub link
  docs/docs/10-intro.md
Labels: documentation

#781 WOODPECKER_ENVIRONMENT: ignore items only containing a key and no value
  cmd/server/setup.go
  server/plugins/environments/filesystem.go
Labels: bug, server

#788 fix nfpm
  Makefile
  nfpm/nfpm-agent.yml
  nfpm/nfpm-cli.yml
  nfpm/nfpm-server.yml
Labels: skip-changelog, build

#787 make gRPC error "to many keepalive pings" only show up in trace logs
  pipeline/rpc/client_grpc.go
Labels: bug

#790 Changelog v0.15.0
  CHANGELOG.md
Labels: documentation, skip-changelog

#794 CI: bump golang version
  .woodpecker/binaries.yml
  .woodpecker/docker.yml
  .woodpecker/test.yml
Labels: skip-changelog, build

#797 Remove unused code
  cli/LICENSE
  pipeline/frontend/metadata_test.go
  pipeline/frontend/yaml/compiler/compiler_test.go
  pipeline/frontend/yaml/compiler/convert_test.go
  pipeline/frontend/yaml/compiler/script_win_test.go
  pipeline/multipart/coverage/coverage.go
  pipeline/parse.go
  pipeline/parse_test.go
  pipeline/rpc/peer.go
  server/logging/README.md
  server/plugins/environments/filesystem_test.go
  server/plugins/environments/parse.go
  server/plugins/registry/combine_test.go
  server/plugins/registry/db_test.go
  server/plugins/registry/filesystem_test.go
  server/plugins/secrets/builtin_test.go
  server/plugins/sender/builtin_test.go
  server/plugins/sender/plugin_test.go
  server/queue/worker.go
  server/queue/worker_test.go
  server/remote/gogs/parse_test.go
  server/router/middleware/session/repo_test.go
Labels: refactor

#803 Get Netrc machine from clone url (#800)
  cmd/server/setup.go
  server/remote/bitbucket/bitbucket_test.go
  server/remote/bitbucketserver/bitbucketserver.go
  server/remote/coding/coding.go
  server/remote/coding/coding_test.go
  server/remote/common/utils.go
  server/remote/common/utils_test.go
  server/remote/gitea/gitea.go
  server/remote/gitea/gitea_test.go
  server/remote/github/github.go
  server/remote/github/github_test.go
  server/remote/gitlab/gitlab.go
  server/remote/gogs/gogs.go
  server/remote/gogs/gogs_test.go
Labels: bug, server

#798 Split GRPC code of related contexts into separate files
  server/grpc/filter.go
  server/grpc/rpc.go
  server/grpc/server.go
Labels: server, refactor

#807 Add hint for not visibles trusted option in project settings for non-admins
  docs/docs/20-usage/71-project-settings.md
Labels: documentation, skip-changelog

#808 Branch list enhancements
  server/remote/gitea/gitea.go
  server/remote/github/github.go
  server/remote/gitlab/gitlab.go
  server/remote/gogs/gogs.go
Labels: bug, server

#805 Do not filter on linux/amd64 per default
  pipeline/frontend/metadata.go
  server/grpc/filter.go
  server/grpc/filter_test.go
Labels: enhancement

#809 Branch list enhancements (#808)
  server/remote/gitea/gitea.go
  server/remote/github/github.go
  server/remote/gitlab/gitlab.go
  server/remote/gogs/gogs.go
Labels: bug, server

#799 Use shared func for registering Sigterm on a context
  cli/exec/exec.go
  cmd/agent/agent.go
  cmd/agent/signal.go
  pipeline/interrupt/interrupt.go
  shared/utils/context.go
Labels: refactor

#804 Add support for pipeline configuration service
  cmd/server/flags.go
  cmd/server/server.go
  docs/docs/30-administration/100-external-configuration-api.md
  go.mod
  go.sum
  server/api/build.go
  server/api/hook.go
  server/config.go
  server/plugins/configuration/configuration.go
  server/shared/configFetcher.go
  server/shared/configFetcher_test.go
  vendor/github.com/99designs/httpsignatures-go/.travis.yml
  vendor/github.com/99designs/httpsignatures-go/LICENSE
  vendor/github.com/99designs/httpsignatures-go/README.md
  vendor/github.com/99designs/httpsignatures-go/algorithm.go
  vendor/github.com/99designs/httpsignatures-go/signature.go
  vendor/github.com/99designs/httpsignatures-go/signer.go
  vendor/modules.txt
Labels: feature, pipeline-config
