Repository woodpecker-ci/woodpecker, pull requests merged in 2022-07, with the labels that each got.

#1002 Gracefully handle non-zero exit code in local backend
  pipeline/backend/local/local.go
Labels: bug, backend/local

#1011 Avoid calling /bin/env in local backend (Fix #1001)
  pipeline/backend/local/local.go
Labels: bug, backend/local

#1024 Update base images
  .woodpecker/docker.yml
  docker/Dockerfile.agent.alpine.multiarch
  docker/Dockerfile.cli.alpine.multiarch
  docker/Dockerfile.server.alpine.multiarch
Labels: build, backport

#1025 Update base images (#1024)
  .woodpecker/binaries.yml
  .woodpecker/docker.yml
  Makefile
  docker/Dockerfile.agent.alpine.multiarch
  docker/Dockerfile.agent.multiarch
  docker/Dockerfile.cli.alpine.multiarch
  docker/Dockerfile.cli.multiarch
  docker/Dockerfile.make
  docker/Dockerfile.server.alpine.multiarch
  docker/Dockerfile.server.multiarch
Labels: build

#1028 use external lib to convert yaml to json
  go.mod
  go.sum
  pipeline/frontend/yaml/compiler/params.go
  pipeline/schema/schema.go
  shared/yml/yml.go
  shared/yml/yml_test.go
Labels: refactor

#1026 Use variables in pipeline
  .woodpecker/binaries.yml
  .woodpecker/docker.yml
  .woodpecker/test.yml
  .woodpecker/web.yml
  cli/lint/lint.go
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/20-usage/35-advanced-yaml-syntax.md
  pipeline/schema/schema.json
Labels: documentation, enhancement

#1029 fix docs: dont interupt section with unrelated new section
  docs/docs/20-usage/20-pipeline-syntax.md
Labels: bug, documentation, skip-changelog

#1023 Add pipeline log output download
  web/src/assets/locales/en.json
  web/src/assets/locales/lv.json
  web/src/components/atomic/Button.vue
  web/src/components/atomic/Icon.vue
  web/src/components/repo/build/BuildLog.vue
  web/src/compositions/useNotifications.ts
Labels: ui, feature

#1035 Fix docs
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/20-usage/35-advanced-yaml-syntax.md
Labels: documentation, skip-changelog

#1009 Let single line command be a single command
  go.mod
  go.sum
  pipeline/frontend/yaml/container_test.go
  pipeline/frontend/yaml/types/command.go
  pipeline/frontend/yaml/types/command_test.go
Labels: server, refactor, breaking, pipeline-config

#1036 Update jsonschema and define "services"
  pipeline/schema/schema.json
Labels: enhancement

#1037 Add method to check organization membership
  cmd/server/server.go
  cmd/server/setup.go
  go.mod
  go.sum
  server/cache/membership.go
  server/config.go
  server/model/perm.go
  server/remote/bitbucket/bitbucket.go
  server/remote/bitbucket/internal/client.go
  server/remote/bitbucket/internal/types.go
  server/remote/bitbucketserver/bitbucketserver.go
  server/remote/coding/coding.go
  server/remote/gitea/gitea.go
  server/remote/github/github.go
  server/remote/gitlab/gitlab.go
  server/remote/gogs/gogs.go
  server/remote/mocks/remote.go
  server/remote/remote.go
  server/router/middleware/session/user.go
Labels: feature

#1044 make ListItem component more accessible by using a button tag when clickable
  web/src/components/atomic/ListItem.vue
Labels: server, ui, ux

#1046 Make ListItem component more accessible by using a button tag when clickable (#1044)
  web/src/components/atomic/ListItem.vue
Labels: bug, server, ui, ux

#1050 Update type of 'log_data' from blob to longblob
  server/model/log.go
  server/store/datastore/migration/006_log_data_type.go
  server/store/datastore/migration/migration.go
Labels: bug, backport

#1052 Update type of 'log_data' from blob to longblob (#1050)
  server/model/log.go
  server/store/datastore/migration/006_log_data_type.go
  server/store/datastore/migration/migration.go
Labels: bug

#968 Provide global environment variables for pipeline substitution
  cli/exec/exec.go
  docs/docs/20-usage/50-environment.md
  server/shared/procBuilder.go
  server/shared/procBuilder_test.go
Labels: server, feature

#1054 Add pipline convert tool to docs
  docs/docs/92-awesome.md
Labels: documentation

#1020 add gitpod setup
  .gitpod.yml
  README.md
  docker-compose.gitpod.yml
  docs/docs/92-development/01-getting-started.md
  docs/static/img/logo-auto-darkmode.svg
Labels: documentation

#1010 Wait to finish reading logs before calling Wait() on pipeline
  pipeline/pipeline.go
Labels: bug, server

#1057 Fix broken link in documentation
  docs/docs/80-downloads.md
Labels: documentation
