Repository woodpecker-ci/woodpecker, pull requests merged in 2022-01, with the labels that each got.

#641 Do not exclude repo owner from gated rule
  server/api/hook.go
Labels: enhancement

#653 pass repo to remote perm func
  server/remote/bitbucket/bitbucket.go
  server/remote/bitbucket/bitbucket_test.go
  server/remote/bitbucketserver/bitbucketserver.go
  server/remote/coding/coding.go
  server/remote/coding/coding_test.go
  server/remote/gitea/gitea.go
  server/remote/gitea/gitea_test.go
  server/remote/github/github.go
  server/remote/github/github_test.go
  server/remote/gitlab/gitlab.go
  server/remote/gitlab/gitlab_test.go
  server/remote/gogs/gogs.go
  server/remote/gogs/gogs_test.go
  server/remote/mocks/remote.go
  server/remote/remote.go
  server/router/middleware/session/repo.go
  server/shared/userSyncer.go
Labels: refactor, skip-changelog

#652 hotfix gitlab sub repo listing
  server/remote/gitlab/convert.go
Labels: bug, gitlab

#656 skip nested GitLab repositories during sync
  server/remote/gitlab/gitlab.go
Labels: bug, gitlab

#658 API GetRepos() return empty list if no active repos exist
  server/api/user.go
Labels: bug, server

#659 Use global branch filter only on events containing branch info
  cmd/server/server.go
  pipeline/frontend/yaml/config.go
  server/api/build.go
  server/api/hook.go
  server/config.go
  server/shared/procBuilder.go
Labels: bug, server, refactor

#661 format code with `gofumpt -w -l -extra .`
  cli/internal/util.go
  cmd/agent/agent.go
  cmd/server/server.go
  pipeline/backend/backend.go
  pipeline/backend/types/engine.go
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/constraint.go
  pipeline/frontend/yaml/types/types_yaml.go
  server/api/build.go
  server/api/metrics/prometheus.go
  server/model/repo.go
  server/model/user_test.go
  server/queue/fifo.go
  server/remote/bitbucket/internal/client.go
  server/remote/bitbucketserver/bitbucketserver.go
  server/remote/bitbucketserver/convert.go
  server/remote/bitbucketserver/convert_test.go
  server/remote/bitbucketserver/internal/client.go
  server/remote/gitea/gitea.go
  server/remote/gitea/helper_test.go
  server/remote/gitlab/convert.go
  server/remote/gitlab/gitlab.go
  server/remote/gitlab/gitlab_test.go
  server/remote/gitlab/helper.go
  server/remote/gogs/helper_test.go
  server/router/middleware/session/repo_test.go
  server/shared/buildStatus_test.go
  server/shared/procBuilder_test.go
  server/shared/procStatus_test.go
  server/store/datastore/migration/common.go
  server/store/datastore/migration/migration_test.go
  server/web/config.go
  shared/oauth2/oauth2.go
  version/version.go
  woodpecker-go/woodpecker/client.go
Labels: refactor

#663 Add WoodpeckerCI tag to README
  README.md
Labels: documentation

#670 Update dev-docs & improve migration code
  .woodpecker/test.yml
  docs/docs/30-administration/30-database.md
  docs/docs/92-development/06-guides.md
  server/store/datastore/engine_test.go
  server/store/datastore/migration/migration.go
Labels: refactor

#671 Hide multi line secrets from log
  pipeline/rpc/line.go
  pipeline/shared/replace_secrets.go
  pipeline/shared/replace_secrets_test.go
Labels: enhancement, security

#673 Build ref link point to commit not compare if only one commit was pushed
  server/remote/gitea/helper.go
  server/remote/gitea/helper_test.go
Labels: gitea, enhancement

#675 getChangedFilesFromPushHook: use all commits
  server/remote/gitea/helper.go
  server/remote/gitea/helper_test.go
Labels: bug, gitea

#667 Add documentation of all agent configuration options
  docs/docs/30-administration/11-agent-config.md
Labels: documentation

#678 Update build layout
  web/src/components/build-feed/BuildFeedItem.vue
  web/src/components/layout/Panel.vue
  web/src/components/repo/build/BuildLog.vue
  web/src/components/repo/build/BuildProcList.vue
  web/src/components/repo/build/BuildProcs.vue
  web/src/components/tabs/Tab.vue
  web/src/components/tabs/Tabs.vue
  web/src/compositions/useBuild.ts
  web/src/lib/api/index.ts
  web/src/router.ts
  web/src/store/builds.ts
  web/src/views/repo/RepoBuild.vue
  web/src/views/repo/RepoWrapper.vue
  web/src/views/repo/build/Build.vue
  web/src/views/repo/build/BuildWrapper.vue
Labels: enhancement, skip-changelog

#679 add container registries docs
  docs/docs/20-usage/41-registries.md
  web/src/components/repo/settings/RegistriesTab.vue
Labels: documentation

#680 fix and improve decline events
  server/api/build.go
  server/api/hook.go
  server/model/event.go
Labels: bug

#649 Show yml config of pipeline in UI
  server/api/build.go
  server/router/api.go
  web/src/lib/api/index.ts
  web/src/lib/api/types/buildConfig.ts
  web/src/lib/api/types/index.ts
  web/src/router.ts
  web/src/views/repo/build/BuildConfig.vue
  web/src/views/repo/build/BuildWrapper.vue
Labels: ui, feature

#650 Show changed files of pipeline in UI
  web/src/components/tabs/Tab.vue
  web/src/router.ts
  web/src/views/repo/build/BuildChangedFiles.vue
  web/src/views/repo/build/BuildWrapper.vue
Labels: ui, feature

#682 remove "panic()" as much as posible from code
  server/remote/gitlab/gitlab.go
  server/remote/gitlab/gitlab_test.go
  shared/oauth2/oauth2.go
Labels: bug

#683 pipeline backend: remove unused var
  pipeline/backend/types/secret.go
Labels: refactor, skip-changelog

#676 Changelog for v0.15.0-rc1
  CHANGELOG.md
Labels: documentation, skip-changelog

#505 Only publish to latest on tags
  .woodpecker/main.yml
  docs/docs/80-downloads.md
Labels: build

#691 Update 80-downloads.md
  docs/docs/80-downloads.md
Labels: skip-changelog

#695 Fix some ui issues and mobile view
  web/src/components/atomic/Button.vue
  web/src/components/atomic/Icon.vue
  web/src/components/atomic/IconButton.vue
  web/src/components/form/Checkbox.vue
  web/src/components/form/RadioField.vue
  web/src/components/repo/build/BuildItem.vue
  web/src/components/repo/build/BuildLog.vue
  web/src/components/repo/build/BuildProcList.vue
  web/src/components/tabs/Tabs.vue
  web/src/compositions/useBuild.ts
  web/src/lib/api/types/build.ts
  web/src/views/Login.vue
  web/src/views/Repos.vue
  web/src/views/repo/RepoWrapper.vue
  web/src/views/repo/build/Build.vue
  web/src/views/repo/build/BuildConfig.vue
  web/src/views/repo/build/BuildWrapper.vue
Labels: ui, skip-changelog

#698 github tag pipelines should not have changed files
  server/remote/github/convert.go
Labels: bug

#700 Fix multiline secrets replacer
  pipeline/shared/replace_secrets.go
  pipeline/shared/replace_secrets_test.go
Labels: bug, skip-changelog

#702 tiny ui fixes
  web/src/components/repo/build/BuildItem.vue
  web/src/views/repo/build/BuildWrapper.vue
Labels: bug, ui, skip-changelog

#699 Improve compile pipeline
  docs/docs/20-usage/22-conditional-execution.md
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/config.go
  pipeline/frontend/yaml/constraint/constraint.go
  pipeline/frontend/yaml/constraint/constraint_test.go
  pipeline/frontend/yaml/container.go
  pipeline/frontend/yaml/container_test.go
Labels: enhancement, refactor, pipeline-config

#690 Automatically determine platform of agent
  cmd/agent/agent.go
  cmd/agent/flags.go
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/20-usage/22-conditional-execution.md
  docs/docs/30-administration/11-agent-config.md
  docs/docs/91-migrations.md
Labels: enhancement

#697 Support ChangedFiles for Github & Gitlab PRs and Gitlab pushes
  docs/docs/20-usage/22-conditional-execution.md
  server/api/hook.go
  server/remote/bitbucket/bitbucket.go
  server/remote/bitbucket/bitbucket_test.go
  server/remote/bitbucketserver/bitbucketserver.go
  server/remote/coding/coding.go
  server/remote/coding/coding_test.go
  server/remote/gitea/gitea.go
  server/remote/gitea/helper.go
  server/remote/github/convert.go
  server/remote/github/convert_test.go
  server/remote/github/fixtures/hooks.go
  server/remote/github/fixtures/mock_server.go
  server/remote/github/github.go
  server/remote/github/parse.go
  server/remote/github/parse_test.go
  server/remote/github/types.go
  server/remote/gitlab/convert.go
  server/remote/gitlab/gitlab.go
  server/remote/gitlab/gitlab_test.go
  server/remote/gitlab/testdata/hooks.go
  server/remote/gogs/gogs.go
  server/remote/mocks/remote.go
  server/remote/remote.go
  server/store/context.go
  shared/utils/strings.go
  shared/utils/strings_test.go
Labels: github, gitlab, gitea, enhancement, refactor

#703 Compile for more platforms on release
  .woodpecker/docker.yml
  .woodpecker/main.yml
Labels: agent, build, cli

#710 Fix avivable -> available typo in backend.go
  pipeline/backend/backend.go
Labels: refactor

#712 minor updates to docs
  docs/docs/20-usage/22-conditional-execution.md
  docs/docs/20-usage/25-multi-pipeline.md
  docs/docs/30-administration/20-vcs/40-gitlab.md
Labels: documentation

#714 Fix typo
  docs/docs/20-usage/25-multi-pipeline.md
Labels: documentation

#715 Fix helm chart release
  .gitignore
  .woodpecker/helm.yml
Labels: skip-changelog, build

#716 fix typo in docs
  docs/docs/30-administration/00-setup.md
Labels: documentation, skip-changelog

#711 Add note about Gitlab & Gitea internal connections to docs
  docs/docs/30-administration/20-vcs/30-gitea.md
  docs/docs/30-administration/20-vcs/40-gitlab.md
Labels: documentation

#722 Run pipeline for binary files on pull if go code changed
  .woodpecker/binaries.yml
  .woodpecker/docker.yml
  .woodpecker/main.yml
  .woodpecker/test.yml
  Makefile
Labels: build

#723 Fix path schema
  .woodpecker/binaries.yml
  .woodpecker/test.yml
  pipeline/schema/.woodpecker/test-when.yml
  pipeline/schema/schema.json
Labels: bug, skip-changelog

#674 Allow to change status context again
  cmd/server/flags.go
  cmd/server/server.go
  cmd/server/setup.go
  docs/docs/91-migrations.md
  server/config.go
  server/remote/common/status.go
  server/remote/gitea/gitea.go
  server/remote/gitea/gitea_test.go
  server/remote/github/github.go
  server/remote/github/github_test.go
Labels: bug, server

#728 Update 10-overview.md
  docs/docs/30-administration/20-vcs/10-overview.md
Labels: documentation, skip-changelog

#732 Fix tests and pipeline
  .woodpecker/binaries.yml
  server/remote/gitea/helper_test.go
  server/remote/gitea/parse_test.go
  server/store/datastore/engine_test.go
  server/store/datastore/migration/migration_test.go
  shared/utils/strings.go
  shared/utils/strings_test.go
Labels: bug, tests, skip-changelog, build

#693 Remove unused flags / options
  cmd/agent/agent.go
  cmd/agent/flags.go
  cmd/server/flags.go
  cmd/server/server.go
  cmd/server/setup.go
  docs/docs/30-administration/20-vcs/20-github.md
  docs/docs/30-administration/20-vcs/30-gitea.md
  docs/docs/30-administration/20-vcs/40-gitlab.md
  docs/docs/91-migrations.md
  server/remote/gitea/gitea.go
  server/remote/gitea/gitea_test.go
  server/remote/gitea/helper.go
  server/remote/gitea/helper_test.go
  server/remote/github/convert.go
  server/remote/github/convert_test.go
  server/remote/github/github.go
  server/remote/github/github_test.go
  server/remote/github/parse.go
  server/remote/github/parse_test.go
  server/remote/gitlab/convert.go
  server/remote/gitlab/gitlab.go
Labels: enhancement

#730 Fix pipeline timestamps
  server/grpc/rpc.go
  server/model/build.go
  server/model/proc.go
  web/src/compositions/useBuild.ts
  web/src/lib/api/types/build.ts
Labels: bug, refactor

#729 Let non required migration tasks fail and continue
  server/store/datastore/migration/000_legacy_to_xorm.go
  server/store/datastore/migration/migration.go
  server/store/datastore/migration/migration_test.go
Labels: server, enhancement

#727 Add step to release latest images for release branches
  .woodpecker/docker.yml
Labels: skip-changelog, build

#733 Changelog for v0.14.4
  CHANGELOG.md
Labels: documentation, skip-changelog

#737 fix .woodpecker/binaries.yml
  .woodpecker/binaries.yml
Labels: skip-changelog, build

#736 Changelog v0.15.0-rc2
  CHANGELOG.md
Labels: documentation, skip-changelog
