Repository woodpecker-ci/woodpecker, pull requests merged in 2022-09, with the labels that each got.

#1147 Add OpenSSF BP Badge
  README.md
Labels: documentation

#791 Delete old fallbacks and compatible stuff
  cmd/server/setup.go
  pipeline/frontend/metadata.go
  pipeline/pipeline.go
Labels: refactor, breaking

#1152 Respect WOODPECKER_GITEA_SKIP_VERIFY
  server/remote/gitea/gitea.go
Labels: bug, server, forge/gitea, backport

#1151 Respect WOODPECKER_GITEA_SKIP_VERIFY (#1152)
  Makefile
  server/remote/gitea/gitea.go
Labels: bug, server, forge/gitea

#1150 Extract commit message from branch creation
  server/remote/gitea/fixtures/hooks.go
  server/remote/gitea/helper.go
  server/remote/gitea/parse_test.go
  server/remote/gitea/types.go
  web/components.d.ts
Labels: bug, server, forge/gitea, backport

#1153 Extract commit message from branch creation (#1150)
  server/remote/gitea/fixtures/hooks.go
  server/remote/gitea/helper.go
  server/remote/gitea/parse_test.go
  server/remote/gitea/types.go
Labels: bug, server, forge/gitea

#1157 fix (auto) cancel of blocked pipelines
  server/pipeline/cancel.go
Labels: bug

#1162 Add a traefik example
  docs/docs/30-administration/70-proxy.md
Labels: documentation

#1159 Sort pipelines based on creation date
  web/src/utils/helpers.ts
Labels: enhancement

#1158 Improve logging
  cmd/agent/agent.go
  cmd/server/server.go
  cmd/server/setup.go
  server/router/middleware/logger.go
  server/router/middleware/token/token.go
  server/store/datastore/migration/migration.go
Labels: enhancement, refactor

#1163 Add dependency security check using trivy
  .woodpecker/docs.yml
  .woodpecker/test.yml
  .woodpecker/web.yml
Labels: security, build

#1160 Only enable debug endpoints if log level is debug or below
  server/router/api.go
Labels: enhancement

#360 Migrate to certmagic
  cmd/server/flags.go
  cmd/server/server.go
  docker/Dockerfile.server.alpine.multiarch
  docker/Dockerfile.server.multiarch
  docs/docs/30-administration/60-ssl.md
  go.mod
  go.sum
Labels: server, enhancement, breaking

#1168 Add Translation Platform to Docs
  README.md
  docs/docusaurus.config.js
Labels: documentation

#1165 Add Changelog for v0.15.4
  CHANGELOG.md
Labels: documentation, skip-changelog

#1167 Partial-Backport of pipeline from current master
  .woodpecker/binaries.yml
  .woodpecker/docker.yml
  .woodpecker/docs.yml
  .woodpecker/test.yml
  .woodpecker/web.yml
  Makefile
  docker/Dockerfile.server.multiarch
Labels: skip-changelog, build

#552 Adding initial version of Kubernetes backend
  charts/woodpecker-agent/templates/deployment.yaml
  charts/woodpecker-agent/values.yaml
  cli/exec/exec.go
  cli/exec/flags.go
  cmd/agent/agent.go
  cmd/agent/flags.go
  docs/docs/30-administration/80-kubernetes.md
  go.mod
  go.sum
  pipeline/backend/backend.go
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/kubernetes/service.go
  pipeline/backend/kubernetes/service_test.go
  pipeline/backend/kubernetes/utils.go
  pipeline/backend/kubernetes/volume.go
  pipeline/backend/kubernetes/volume_test.go
  pipeline/backend/types/config.go
Labels: feature

#1078 Fetch repositories with remote ID if possible
  Makefile
  server/api/hook.go
  server/api/repo.go
  server/model/perm.go
  server/model/redirection.go
  server/model/repo.go
  server/remote/bitbucket/bitbucket.go
  server/remote/bitbucket/bitbucket_test.go
  server/remote/bitbucket/convert.go
  server/remote/bitbucket/internal/types.go
  server/remote/bitbucketserver/bitbucketserver.go
  server/remote/bitbucketserver/convert.go
  server/remote/bitbucketserver/parse.go
  server/remote/coding/coding.go
  server/remote/coding/coding_test.go
  server/remote/coding/hook.go
  server/remote/coding/internal/coding.go
  server/remote/gitea/fixtures/handler.go
  server/remote/gitea/gitea.go
  server/remote/gitea/gitea_test.go
  server/remote/gitea/helper.go
  server/remote/github/convert.go
  server/remote/github/fixtures/handler.go
  server/remote/github/github.go
  server/remote/github/github_test.go
  server/remote/gitlab/convert.go
  server/remote/gitlab/gitlab.go
  server/remote/gitlab/gitlab_test.go
  server/remote/gogs/fixtures/handler.go
  server/remote/gogs/gogs.go
  server/remote/gogs/gogs_test.go
  server/remote/gogs/helper.go
  server/remote/mocks/remote.go
  server/remote/remote.go
  server/router/middleware/session/repo.go
  server/shared/userSyncer.go
  server/store/datastore/feed_test.go
  server/store/datastore/migration/migration.go
  server/store/datastore/permission.go
  server/store/datastore/permission_test.go
  server/store/datastore/redirection.go
  server/store/datastore/redirection_test.go
  server/store/datastore/repo.go
  server/store/datastore/repo_test.go
  server/store/datastore/users_test.go
  server/store/mocks/store.go
  server/store/store.go
  server/swagger/doc.go
  server/swagger/swagger.go
  web/src/store/repos.ts
  web/src/views/repo/RepoWrapper.vue
Labels: bug, enhancement, refactor

#1170 On Repo update, keep old "Clone" if update would empty it
  server/model/repo.go
Labels: enhancement

#1173 Fix readme grammar and increase golangci-lint timeout
  Makefile
  README.md
Labels: skip-changelog, translation

#1172 Use package's structs and fix missing clone
  server/model/repo.go
  server/remote/bitbucketserver/convert_test.go
  server/remote/bitbucketserver/internal/types.go
  server/remote/bitbucketserver/parse.go
  server/remote/coding/hook.go
  server/remote/coding/hook_test.go
  server/remote/gitea/fixtures/hooks.go
  server/remote/gitea/helper.go
  server/remote/gitea/helper_test.go
  server/remote/gitea/parse.go
  server/remote/gitea/types.go
  server/remote/gogs/gogs.go
  server/remote/gogs/helper.go
  server/remote/gogs/helper_test.go
  server/remote/gogs/parse.go
  server/remote/gogs/types.go
Labels: server, refactor

#1188 use example.com instead of foo.com
  docs/docs/20-usage/51-plugins/20-sample-plugin.md
  docs/docs/30-administration/60-ssl.md
  pipeline/frontend/yaml/compiler/option_test.go
  vendor/github.com/golangci/misspell/url.go
Labels: documentation, skip-changelog

#1184 Hide example of YAML override and extension
  docs/docs/20-usage/35-advanced-yaml-syntax.md
Labels: documentation

#1166 [Bitbucket] Use workspaces instead of deprecated/removed teams path
  server/remote/bitbucket/bitbucket.go
  server/remote/bitbucket/bitbucket_test.go
  server/remote/bitbucket/convert.go
  server/remote/bitbucket/convert_test.go
  server/remote/bitbucket/fixtures/handler.go
  server/remote/bitbucket/fixtures/hooks.go
  server/remote/bitbucket/internal/client.go
  server/remote/bitbucket/internal/types.go
  server/remote/bitbucket/parse_test.go
Labels: bug, forge/bitbucket

#1197 Make healthcheck port configurable
  cmd/agent/agent.go
  cmd/agent/flags.go
Labels: agent, enhancement

#1195 On Repo update, keep old "Clone" if update would empty it (#1170)
  server/model/repo.go
Labels: enhancement

#1196 Remove old CLI docs generation code
  .woodpecker/docs.yml
  cmd/cli/docs.go
  docs/docs/40-cli.md
Labels: documentation, refactor, cli

#1200 Improve plugins index
  README.md
  docs/docs/92-awesome.md
  docs/docusaurus.config.js
  docs/package.json
  docs/plugins/woodpecker-plugins/package.json
  docs/plugins/woodpecker-plugins/plugins.json
  docs/plugins/woodpecker-plugins/src/index.ts
  docs/plugins/woodpecker-plugins/src/markdown.ts
  docs/plugins/woodpecker-plugins/src/theme/Icons.tsx
  docs/plugins/woodpecker-plugins/src/theme/WoodpeckerPlugin.tsx
  docs/plugins/woodpecker-plugins/src/theme/WoodpeckerPluginList.tsx
  docs/plugins/woodpecker-plugins/src/theme/style.css
  docs/plugins/woodpecker-plugins/src/types.ts
  docs/plugins/woodpecker-plugins/tsconfig.json
  docs/plugins/woodpecker-plugins/tsconfig.jsx.json
  docs/plugins/woodpecker-plugins/yarn.lock
  docs/static/img/logo-auto-darkmode.svg
  docs/static/img/logo-darkmode.svg
  docs/static/img/logo.svg
  docs/yarn.lock
Labels: documentation

#770 Add support for pipeline root.when conditions
  docs/docs/20-usage/20-pipeline-syntax.md
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/config.go
  pipeline/frontend/yaml/config_test.go
  pipeline/frontend/yaml/constraint/constraint.go
  pipeline/frontend/yaml/constraint/constraint_test.go
  pipeline/schema/.woodpecker/test-pipeline-when.yml
  pipeline/schema/schema.json
  server/pipeline/create.go
  server/pipeline/filter.go
  server/shared/procBuilder.go
  server/shared/procBuilder_test.go
Labels: feature

#1156 Add ability to trigger manual builds
  cli/build/build.go
  cli/build/build_create.go
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/40-cli.md
  go.mod
  go.sum
  pipeline/frontend/metadata.go
  pipeline/frontend/yaml/constraint/constraint.go
  server/api/build.go
  server/model/build.go
  server/model/const.go
  server/pipeline/items.go
  server/router/api.go
  web/components.d.ts
  web/package.json
  web/src/assets/locales/en.json
  web/src/components/atomic/Icon.vue
  web/src/components/form/TextField.vue
  web/src/components/layout/Popup.vue
  web/src/components/layout/popups/ManualPipelinePopup.vue
  web/src/components/repo/build/BuildItem.vue
  web/src/components/repo/build/BuildProcList.vue
  web/src/components/secrets/SecretEdit.vue
  web/src/components/secrets/SecretList.vue
  web/src/compositions/useInjectProvide.ts
  web/src/lib/api/index.ts
  web/src/lib/api/types/build.ts
  web/src/lib/api/types/webhook.ts
  web/src/views/repo/RepoWrapper.vue
  web/yarn.lock
  woodpecker-go/woodpecker/client.go
  woodpecker-go/woodpecker/interface.go
  woodpecker-go/woodpecker/types.go
Labels: feature

#1209 Fix handling of empty strings for default docker volumes
  pipeline/backend/docker/docker.go
Labels: bug

#1212 Set a default value for `build-event` flag of `cli exec` command
  cli/exec/flags.go
  docs/docs/40-cli.md
Labels: enhancement, cli

#1217 Fix SCM visibility if user visibility is private
  server/remote/gitea/helper.go
Labels: bug, forge/gitea

#1218 Make exec run be detected as WoodpeckerCI
  .gitignore
  .woodpecker/docs.yml
  cli/exec/flags.go
  docs/docs/40-cli.md
Labels: bug, skip-changelog, cli

#1210 Add help command to makefile
  Makefile
Labels: enhancement, build

#1226 added manual to event enum
  pipeline/schema/schema.json
Labels: bug, skip-changelog

#1225 docs: add alternative naming options
  docs/docs/20-usage/20-pipeline-syntax.md
Labels: documentation

#1223 Sort secret lists and events
  server/model/const.go
  server/model/secret.go
  server/store/datastore/secret.go
Labels: ui, ux
