Repository woodpecker-ci/woodpecker, pull requests merged in 2022-10, with the labels that each got.

#1221 Add support sub-settings and secrets in sub-settings
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/compiler/params.go
  pipeline/frontend/yaml/compiler/settings/params.go
  pipeline/frontend/yaml/compiler/settings/params_test.go
Labels: server, enhancement

#1234 Fix invalid service names for Kubernetes
  pipeline/error.go
  pipeline/frontend/yaml/container.go
  server/shared/procBuilder.go
Labels: bug

#1213 Add when evaluate filter
  cli/exec/exec.go
  docs/docs/20-usage/20-pipeline-syntax.md
  go.mod
  go.sum
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/config_test.go
  pipeline/frontend/yaml/constraint/constraint.go
  pipeline/frontend/yaml/constraint/constraint_test.go
  pipeline/schema/.woodpecker/test-when.yml
  pipeline/schema/schema.json
  server/pipeline/filter.go
  server/shared/procBuilder.go
Labels: feature, pipeline-config

#1231 gitea: fetch all branches
  server/remote/gitea/gitea.go
  server/remote/remote.go
Labels: forge/gitea, enhancement

#1237 Fix gitpod prebuild
  .gitpod.yml
Labels: bug

#1239 Fix app and docs start directory
  .gitpod.yml
Labels: documentation, skip-changelog

#1241 Respect preferred color scheme in docs
  docs/docusaurus.config.js
Labels: documentation

#1242 Use html buttons to allow keyboard navigation
  web/src/components/atomic/IconButton.vue
  web/src/components/layout/header/ActiveBuilds.vue
  web/src/components/tabs/Tabs.vue
Labels: ui, enhancement

#1243 Remove unused eslint-disable directives
  web/.eslintrc.js
  web/src/components/atomic/DocsLink.vue
  web/src/components/form/Checkbox.vue
  web/src/components/form/CheckboxesField.vue
  web/src/components/form/NumberField.vue
  web/src/components/form/RadioField.vue
  web/src/components/form/SelectField.vue
  web/src/components/form/TextField.vue
  web/src/components/repo/build/BuildLog.vue
  web/src/components/repo/build/BuildRunningIcon.vue
  web/src/components/tabs/Tab.vue
  web/src/components/tabs/Tabs.vue
  web/src/views/User.vue
  web/src/views/org/OrgWrapper.vue
  web/src/views/repo/RepoBranch.vue
  web/src/views/repo/RepoWrapper.vue
  web/src/views/repo/build/Build.vue
  web/src/views/repo/build/BuildWrapper.vue
Labels: refactor

#1235 Imporve Navbar UI
  web/src/components/layout/header/ActiveBuilds.vue
  web/src/components/layout/header/Navbar.vue
Labels: ui, enhancement

#1240 Replace yarn with pnpm
  .gitpod.yml
  .vscode/launch.json
  .woodpecker/binaries.yml
  .woodpecker/docker.yml
  .woodpecker/docs.yml
  .woodpecker/web.yml
  Makefile
  docs/README.md
  docs/docs/92-development/01-getting-started.md
  docs/docs/92-development/03-ui.md
  docs/docs/92-development/04-docs.md
  docs/package.json
  docs/plugins/woodpecker-plugins/package.json
  docs/plugins/woodpecker-plugins/pnpm-lock.yaml
  docs/plugins/woodpecker-plugins/yarn.lock
  docs/pnpm-lock.yaml
  docs/versioned_docs/version-0.15/92-development/01-getting-started.md
  docs/yarn.lock
  web/.prettierignore
  web/pnpm-lock.yaml
  web/yarn.lock
Labels: build

#1236 Introduce and use Pagination helper func
  server/remote/common/utils.go
  server/remote/common/utils_test.go
  server/remote/gitea/gitea.go
Labels: refactor

#1247 Add fallback plugin image and display plugins in 1 to 3 columns
  docs/plugins/woodpecker-plugins/src/theme/Icons.tsx
  docs/plugins/woodpecker-plugins/src/theme/WoodpeckerPluginList.tsx
  docs/plugins/woodpecker-plugins/src/theme/style.css
Labels: documentation

#1249 Fix branch loading
  server/remote/gitea/gitea.go
Labels: bug, forge/gitea

#1130 CI: add branches filter
  .woodpecker/binaries.yml
  .woodpecker/docker.yml
  .woodpecker/docs.yml
  .woodpecker/helm.yml
  .woodpecker/test.yml
  .woodpecker/web.yml
  pipeline/schema/schema.json
Labels: build

#1252 Change build message column type to text
  server/model/build.go
Labels: bug, server, backport

#1253 Change build message column type to text (#1252)
  server/model/build.go
Labels: bug, server

#1254 [Backport] bump DefaultCloneImage version to v1.6.0
  cmd/server/flags.go
  pipeline/frontend/yaml/compiler/compiler.go
  shared/constant/constant.go
Labels: enhancement

#1255 Changelog v0.15.5
  CHANGELOG.md
Labels: documentation, skip-changelog

#1264 Update dep moby (#1263)
  go.mod
  go.sum
  vendor/github.com/containerd/containerd/log/context.go
  vendor/github.com/containerd/containerd/platforms/compare.go
  vendor/github.com/containerd/containerd/platforms/cpuinfo.go
  vendor/github.com/containerd/containerd/platforms/database.go
  vendor/github.com/containerd/containerd/platforms/defaults.go
  vendor/github.com/containerd/containerd/platforms/defaults_darwin.go
  vendor/github.com/containerd/containerd/platforms/defaults_unix.go
  vendor/github.com/containerd/containerd/platforms/defaults_windows.go
  vendor/github.com/containerd/containerd/platforms/platforms.go
  vendor/github.com/golangci/misspell/url.go
  vendor/github.com/moby/moby/client/client.go
  vendor/github.com/moby/moby/client/client_unix.go
  vendor/github.com/moby/moby/client/container_create.go
  vendor/github.com/moby/moby/client/request.go
  vendor/modules.txt
Labels: security, dependencies

#1263 Update dep moby & golang.org/x/text
  Makefile
  go.mod
  go.sum
Labels: security, dependencies, backport

#1265 Fix typo
  docs/versioned_docs/version-0.15/30-administration/11-vcs/30-gitea.md
Labels: documentation, skip-changelog

#1251 Refactor badge generation page, add HTML option
  web/src/assets/locales/en.json
  web/src/components/repo/settings/BadgeTab.vue
Labels: ui, enhancement

#1271 Improve wording on homepage features
  docs/src/components/HomepageFeatures.js
Labels: documentation, skip-changelog, hacktoberfest-accepted

#1273 Fix typos in docs
  .gitpod.yml
  docs/docs/30-administration/15-agent-config.md
  docs/docs/30-administration/70-proxy.md
  docs/docs/92-development/05-architecture.md
Labels: documentation

#1275 More spelling & style fixes
  docs/docs/30-administration/00-setup.md
  docs/docs/30-administration/10-server-config.md
  docs/docs/30-administration/100-external-configuration-api.md
  docs/docs/30-administration/11-forges/60-bitbucket_server.md
  docs/docs/30-administration/22-backends/10-docker.md
  docs/docs/30-administration/22-backends/20-local.md
  docs/docs/30-administration/30-database.md
  docs/docs/30-administration/60-ssl.md
  docs/docs/30-administration/70-proxy.md
  docs/docs/30-administration/90-prometheus.md
Labels: documentation

#1270 Add "Gitea Pull Comment" plugin to index
  docs/plugins/woodpecker-plugins/plugins.json
Labels: plugin, documentation, hacktoberfest-accepted

#1283 Remove old `build` api routes
  server/router/api.go
Labels: server, breaking

#1286 Display system CA error only if there is an error (#870)
  cli/internal/util.go
Labels: bug, cli

#1289 Add "Git Push" plugin to index
  docs/plugins/woodpecker-plugins/plugins.json
Labels: plugin

#1293 Update Administration Setup Docs
  docs/docs/30-administration/00-setup.md
  docs/docs/30-administration/70-proxy.md
Labels: documentation

#1298 Add title to docs links
  web/src/assets/locales/en.json
  web/src/components/admin/settings/AdminSecretsTab.vue
  web/src/components/atomic/DocsLink.vue
  web/src/components/form/InputField.vue
  web/src/components/org/settings/OrgSecretsTab.vue
  web/src/components/repo/settings/CronTab.vue
  web/src/components/repo/settings/RegistriesTab.vue
  web/src/components/repo/settings/SecretsTab.vue
Labels: ui

#1306 Prebuild server
  .gitpod.yml
Labels: devx

#1304 Make pipeline steps collapsible
  web/src/components/repo/pipeline/PipelineProcList.vue
  web/windi.config.ts
Labels: ui, feature

#1297 Check if repo exists before creating pipeline
  go.mod
  go.sum
  server/store/datastore/errors.go
  server/store/datastore/pipeline.go
  server/store/datastore/pipeline_test.go
Labels: server, enhancement

#1302 Make submit buttons green and add forms
  web/src/components/layout/popups/ManualPipelinePopup.vue
  web/src/components/repo/settings/CronTab.vue
  web/src/components/repo/settings/GeneralTab.vue
  web/src/components/repo/settings/RegistriesTab.vue
  web/src/components/secrets/SecretEdit.vue
  web/src/views/repo/RepoWrapper.vue
Labels: ui, enhancement

#1296 Rename to `pipeline` in DB and JSONs
  agent/state.go
  server/model/config.go
  server/model/event.go
  server/model/feed.go
  server/model/file.go
  server/model/pipeline.go
  server/model/proc.go
  server/plugins/config/http.go
  server/shared/configFetcher_test.go
  server/store/datastore/config.go
  server/store/datastore/feed.go
  server/store/datastore/file.go
  server/store/datastore/migration/010_columns_rename_builds_to_pipeline.go
  server/store/datastore/migration/common.go
  server/store/datastore/migration/migration.go
  server/store/datastore/pipeline.go
  server/store/datastore/proc.go
  server/store/datastore/repo.go
  web/src/compositions/useEvents.ts
  web/src/lib/api/index.ts
  web/src/lib/api/types/pipeline.ts
  web/src/lib/api/types/pipelineConfig.ts
  web/src/lib/api/types/repo.ts
  woodpecker-go/woodpecker/types.go
Labels: refactor, breaking

#1319 Don't show workflow name if it's only one
  web/src/components/repo/pipeline/PipelineProcList.vue
Labels: ui, enhancement, skip-changelog, ux

#1324 Add Codeberg-CI/examples to awesome
  docs/docs/92-awesome.md
Labels: documentation

#1320 Fix approval on mobile
  web/src/views/repo/pipeline/Pipeline.vue
Labels: bug, ui, ux

#1326 Use system font stack
  web/src/App.vue
  web/windi.config.ts
Labels: ui, enhancement

#1330 Update pipeline steps and logs background
  web/src/components/repo/pipeline/PipelineLog.vue
  web/src/components/repo/pipeline/PipelineProcList.vue
Labels: ui

#1337 Use native `directory` and run with Node 18
  .woodpecker/binaries.yml
  .woodpecker/docker.yml
  .woodpecker/docs.yml
  .woodpecker/test.yml
  .woodpecker/web.yml
Labels: build

#1338 Allow to run cron manually
  server/api/cron.go
  server/api/pipeline.go
  server/cron/cron.go
  server/cron/cron_test.go
  server/router/api.go
  web/components.d.ts
  web/src/assets/locales/en.json
  web/src/components/atomic/Icon.vue
  web/src/components/repo/settings/CronTab.vue
  web/src/components/repo/settings/GeneralTab.vue
  web/src/lib/api/index.ts
Labels: server, enhancement

#1343 Fix Gitpod Gitea OAuth2 client must be confidential
  .gitpod.yml
Labels: bug, skip-changelog

#1346 Fix display of long pipeline and job names
  web/src/components/repo/pipeline/PipelineProcList.vue
Labels: ui, enhancement

#1305 Change locale in user settings
  web/src/components/form/SelectField.vue
  web/src/components/layout/popups/ManualPipelinePopup.vue
  web/src/components/repo/settings/BadgeTab.vue
  web/src/utils/locale.ts
  web/src/views/User.vue
Labels: ui, feature

#1344 Support plugin-only secrets
  cli/secret/secret_add.go
  cli/secret/secret_set.go
  docs/docs/20-usage/40-secrets.md
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/compiler_test.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/container.go
  pipeline/frontend/yaml/container_test.go
  server/api/global_secret.go
  server/api/org_secret.go
  server/api/repo_secret.go
  server/model/secret.go
  server/shared/procBuilder.go
  web/src/assets/locales/en.json
  web/src/components/secrets/SecretEdit.vue
  web/src/lib/api/types/secret.ts
  woodpecker-go/woodpecker/types.go
Labels: enhancement

#1290 Header and Tabs UI Improvements
  web/components.d.ts
  web/src/components/atomic/Button.vue
  web/src/components/form/TextField.vue
  web/src/components/layout/header/Navbar.vue
  web/src/components/layout/scaffold/Header.vue
  web/src/components/layout/scaffold/Scaffold.vue
  web/src/components/layout/scaffold/Tab.vue
  web/src/components/layout/scaffold/Tabs.vue
  web/src/components/tabs/Tab.vue
  web/src/components/tabs/Tabs.vue
  web/src/components/tabs/types.ts
  web/src/compositions/useTabs.ts
  web/src/views/RepoAdd.vue
  web/src/views/Repos.vue
  web/src/views/ReposOwner.vue
  web/src/views/User.vue
  web/src/views/admin/AdminSettings.vue
  web/src/views/org/OrgSettings.vue
  web/src/views/org/OrgWrapper.vue
  web/src/views/repo/RepoSettings.vue
  web/src/views/repo/RepoWrapper.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: ui, enhancement

#1359 Add gitpod port names
  .gitpod.yml
Labels: documentation

#1360 Add Node PM plugin
  docs/plugins/woodpecker-plugins/plugins.json
Labels: plugin, documentation

#1342 Support changed files for Gitea PRs
  .golangci.yml
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/30-administration/11-forges/10-overview.md
  go.mod
  go.sum
  server/remote/gitea/fixtures/handler.go
  server/remote/gitea/gitea.go
  server/remote/gitea/gitea_test.go
  server/remote/gitea/parse_test.go
  server/store/context.go
Labels: forge/gitea, enhancement

#1364 Update Mastodon link
  docs/docusaurus.config.js
Labels: documentation

#1365 Add additional tag to `next` image with commit sha
  .woodpecker/docker.yml
Labels: build

#1372 Fix pipeline cancel API endpoint and update Web and CLI clients
  cli/pipeline/stop.go
  server/api/pipeline.go
  server/router/api.go
  web/src/lib/api/index.ts
  web/src/views/repo/pipeline/PipelineWrapper.vue
  woodpecker-go/woodpecker/client.go
  woodpecker-go/woodpecker/interface.go
Labels: bug, server, ui, skip-changelog, cli

#1373 Add RBAC to helm chart
  charts/woodpecker-agent/templates/role.yaml
  charts/woodpecker-agent/templates/rolebinding.yaml
  charts/woodpecker-agent/values.yaml
Labels: chart

#1032 Move constrain to only have a single command in backend to run to dedicated backends
  pipeline/backend/common/script.go
  pipeline/backend/common/script_posix.go
  pipeline/backend/common/script_posix_test.go
  pipeline/backend/common/script_win.go
  pipeline/backend/docker/convert.go
  pipeline/backend/docker/convert_test.go
  pipeline/backend/docker/docker.go
  pipeline/backend/docker/pool.go
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/local/local.go
  pipeline/backend/ssh/ssh.go
  pipeline/backend/types/step.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/container.go
  pipeline/frontend/yaml/container_test.go
  pipeline/frontend/yaml/linter/linter.go
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/frontend/yaml/types/command.go
  pipeline/frontend/yaml/types/command_test.go
Labels: enhancement, refactor

#1361 Use html landmark elements
  web/src/App.vue
  web/src/assets/locales/en.json
  web/src/components/layout/header/ActivePipelines.vue
  web/src/components/layout/header/Navbar.vue
  web/src/components/layout/scaffold/Header.vue
  web/src/components/pipeline-feed/PipelineFeedSidebar.vue
  web/src/views/Login.vue
Labels: ui, refactor

#1356 #1310 Migrate sql querys to xorm builder
  server/model/feed.go
  server/store/datastore/config.go
  server/store/datastore/feed.go
  server/store/datastore/feed_test.go
  server/store/datastore/permission.go
  server/store/datastore/user.go
Labels: refactor
