Repository woodpecker-ci/woodpecker, pull requests merged in 2023-07, with the labels that each got.

#1874 Enhance log view
  server/api/stream.go
  server/logging/log.go
  web/src/components/repo/pipeline/PipelineLog.vue
Labels: bug, skip-changelog, regression

#1916 Fix default value
  docs/docs/30-administration/10-server-config.md
Labels: documentation

#1888 Store agent ID in config file
  cmd/agent/agent.go
  cmd/agent/agent_test.go
  cmd/agent/flags.go
  docker/Dockerfile.agent.alpine.multiarch
  docker/Dockerfile.agent.multiarch
  docs/docs/30-administration/15-agent-config.md
  web/src/assets/locales/en.json
  web/src/components/admin/settings/AdminAgentsTab.vue
Labels: agent, enhancement

#1913 Removed env vars filtering
  pipeline/frontend/yaml/compiler/convert.go
Labels: bug, skip-changelog

#1907 Fixed when:evaluate on non-standard (non-CI*) env vars
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/20-usage/50-environment.md
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/constraint/constraint.go
  pipeline/frontend/yaml/constraint/constraint_test.go
  pipeline/frontend/yaml/parse_test.go
  pipeline/stepBuilder.go
  server/pipeline/filter.go
Labels: enhancement

#1919 Overwrite web dep version
  .woodpecker/web.yml
  web/package.json
  web/pnpm-lock.yaml
Labels: ui, skip-changelog, security, build

#1852 PipelineLog.vue: Link lines to anchors
  web/src/components/repo/pipeline/PipelineLog.vue
Labels: ui, enhancement

#1921 Added agent registration docs
  docs/docs/30-administration/15-agent-config.md
  docs/docs/30-administration/new-agent-connected.png
  docs/docs/30-administration/new-agent-created.png
  docs/docs/30-administration/new-agent-registration.png
Labels: documentation

#1927 Added Nextcloud Upload plugin
  docs/plugins/woodpecker-plugins/plugins.json
Labels: plugin, documentation

#1930 Add Kubernetes and Dockle Plugins
  docs/plugins/woodpecker-plugins/plugins.json
Labels: plugin, documentation

#1922 Fix selected line highlighting
  web/src/components/repo/pipeline/PipelineLog.vue
Labels: ui, skip-changelog, regression

#1903 Make sure step passed into go routine exist and does not change
  server/pipeline/start.go
Labels: refactor, skip-changelog

#1925 docs: user registration
  docs/docs/30-administration/10-server-config.md
Labels: documentation

#1926 Update go in gitpod
  .gitpod.yml
Labels: skip-changelog, devx

#1909 Refactored K8s Pod node selector
  pipeline/backend/kubernetes/pod.go
Labels: refactor, backend/kubernetes

#1940 Harden datastore
  server/store/datastore/config.go
  server/store/datastore/cron.go
  server/store/datastore/permission.go
  server/store/datastore/pipeline.go
  server/store/datastore/redirection.go
  server/store/datastore/registry.go
  server/store/datastore/secret.go
  server/store/datastore/server_config.go
  server/store/datastore/step.go
Labels: server, refactor, skip-changelog, security

#1939 save forge at the beginning and use it
  server/api/login.go
Labels: refactor, skip-changelog

#1914 Do not set Pod's Image pull policy if not explicitly set
  pipeline/backend/kubernetes/pod.go
Labels: feature, backend/kubernetes

#1952 Fix agent auth
  server/api/login.go
  server/grpc/auth_server.go
  server/model/settings.go
  server/router/middleware/config.go
Labels: security, backport

#1953 Fix agent auth (#1952)
  cmd/server/server.go
  go.sum
  server/model/settings.go
  server/router/middleware/config.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/modules.txt
Labels: security

#1949 Adjust model database type mapping
  server/model/pipeline.go
  server/model/step.go
  server/model/workflow.go
  server/store/datastore/migration/020_parent_steps_to_workflows.go
  server/store/datastore/step_test.go
Labels: enhancement, skip-changelog

#1938 Make secrets with "/" in name editable / deletable
  web/src/lib/api/index.ts
Labels: bug, ui

#1950 pipeline-StepBuilder extract item generation of workflow into own function
  cli/exec/exec.go
  pipeline/stepBuilder.go
Labels: refactor, skip-changelog

#1954 Changelog v0.15.10
  CHANGELOG.md
Labels: documentation, skip-changelog

#1957 Remove unused step options
  pipeline/frontend/yaml/types/container.go
  pipeline/frontend/yaml/types/container_test.go
  pipeline/frontend/yaml/types/ulimit.go
  pipeline/frontend/yaml/types/ulimit_test.go
Labels: refactor, skip-changelog

#1963 Fix platform to node-selector mapping for k8s
  pipeline/backend/kubernetes/pod.go
Labels: bug, skip-changelog

#1961 Changelog v0.15.10 (#1954)
  CHANGELOG.md
Labels: documentation, skip-changelog

#1956 Move docker specific volume & network settings into backend code
  pipeline/backend/docker/docker.go
  pipeline/backend/types/network.go
  pipeline/backend/types/volume.go
  pipeline/frontend/yaml/compiler/compiler.go
Labels: enhancement, refactor

#1964 Fix netrc passing to clone image
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/types/container.go
  pipeline/frontend/yaml/utils/image.go
  pipeline/frontend/yaml/utils/image_test.go
Labels: bug, skip-changelog

#1781 support custom .JS and .CSS files for custom banner messages (white-labeling)
  cmd/server/flags.go
  cmd/server/server.go
  docs/docs/30-administration/10-server-config.md
  server/config.go
  server/web/web.go
  server/web/web_test.go
  web/index.html
Labels: ui, enhancement

#1966 Speedup pipeline
  .woodpecker/docker.yml
  .woodpecker/test.yml
  .woodpecker/web.yml
Labels: build

#1967 docker: use uuid instead of name as identifyer
  pipeline/backend/docker/convert.go
  pipeline/backend/docker/docker.go
Labels: enhancement, backend/docker

#1972 Add option to read grpc-secret from file
  cmd/server/flags.go
  docs/docs/30-administration/10-server-config.md
Labels: server, enhancement

#1958 Let pipeline-compiler export step types
  cmd/server/docs/docs.go
  pipeline/backend/types/step.go
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/rpc/proto/woodpecker.pb.go
  pipeline/rpc/proto/woodpecker_grpc.pb.go
  pipeline/stepBuilder.go
  server/forge/mocks/forge.go
  server/model/step.go
  server/store/mocks/store.go
  web/src/lib/api/types/pipeline.ts
  woodpecker-go/woodpecker/const.go
  woodpecker-go/woodpecker/types.go
Labels: server, enhancement

#1969 Fix repo gate protection
  docs/docs/20-usage/71-project-settings.md
  server/pipeline/create.go
  server/pipeline/gated.go
Labels: bug

#1974 Correct api docs of PostRepo & GetRepos
  cmd/server/docs/docs.go
  server/api/repo.go
  server/api/user.go
Labels: bug, documentation, skip-changelog

#1978 Add a blog
  docs/blog/2023-06-11-hello-blog/index.md
  docs/docusaurus.config.js
Labels: documentation

#1982 Correct wording
  cmd/server/docs/docs.go
  server/api/user.go
  web/src/assets/locales/en.json
Labels: documentation

#1983 Run workflows only for PRs and master
  .woodpecker/docker.yml
  .woodpecker/docs.yml
  .woodpecker/test.yml
  .woodpecker/web.yml
Labels: build

#1988 Allow gitea dev version (#914)
  go.mod
  go.sum
  server/remote/gitea/gitea.go
  vendor/code.gitea.io/sdk/gitea/attachment.go
  vendor/code.gitea.io/sdk/gitea/client.go
  vendor/code.gitea.io/sdk/gitea/fork.go
  vendor/code.gitea.io/sdk/gitea/hook_validate.go
  vendor/code.gitea.io/sdk/gitea/issue.go
  vendor/code.gitea.io/sdk/gitea/issue_milestone.go
  vendor/code.gitea.io/sdk/gitea/list_options.go
  vendor/code.gitea.io/sdk/gitea/notifications.go
  vendor/code.gitea.io/sdk/gitea/org_team.go
  vendor/code.gitea.io/sdk/gitea/pull.go
  vendor/code.gitea.io/sdk/gitea/pull_review.go
  vendor/code.gitea.io/sdk/gitea/release.go
  vendor/code.gitea.io/sdk/gitea/repo.go
  vendor/code.gitea.io/sdk/gitea/repo_collaborator.go
  vendor/code.gitea.io/sdk/gitea/repo_commit.go
  vendor/code.gitea.io/sdk/gitea/repo_migrate.go
  vendor/code.gitea.io/sdk/gitea/repo_transfer.go
  vendor/code.gitea.io/sdk/gitea/repo_tree.go
  vendor/code.gitea.io/sdk/gitea/repo_watch.go
  vendor/code.gitea.io/sdk/gitea/user.go
  vendor/code.gitea.io/sdk/gitea/user_app.go
  vendor/code.gitea.io/sdk/gitea/version.go
  vendor/github.com/hashicorp/go-version/CHANGELOG.md
  vendor/github.com/hashicorp/go-version/README.md
  vendor/github.com/hashicorp/go-version/constraint.go
  vendor/github.com/hashicorp/go-version/version.go
  vendor/modules.txt
Labels: forge/gitea, enhancement

#1994 Drop support for Bitbucket Server
  cmd/server/flags.go
  cmd/server/setup.go
  docs/docs/30-administration/10-server-config.md
  docs/docs/30-administration/11-forges/10-overview.md
  docs/docs/30-administration/11-forges/60-bitbucket_server.md
  docs/docs/91-migrations.md
  server/forge/bitbucketserver/bitbucketserver.go
  server/forge/bitbucketserver/convert.go
  server/forge/bitbucketserver/convert_test.go
  server/forge/bitbucketserver/internal/client.go
  server/forge/bitbucketserver/internal/types.go
  server/forge/bitbucketserver/parse.go
  web/src/views/repo/RepoWrapper.vue
Labels: refactor, breaking, forge/bitbucket

#1984 Link swagger in navbar
  web/src/assets/locales/en.json
  web/src/components/layout/header/Navbar.vue
Labels: ui

#1942 let HookParse func explicit ignore events
  server/api/hook.go
  server/forge/bitbucket/parse.go
  server/forge/bitbucket/parse_test.go
  server/forge/forge.go
  server/forge/gitea/gitea.go
  server/forge/gitea/parse.go
  server/forge/gitea/parse_test.go
  server/forge/github/parse.go
  server/forge/github/parse_test.go
  server/forge/gitlab/gitlab.go
  server/forge/mocks/forge.go
  server/forge/types/errors.go
  server/store/mocks/store.go
Labels: server, enhancement

#1997 Use global logger for xorm logs and add options
  cmd/server/flags.go
  cmd/server/setup.go
  docs/docs/30-administration/10-server-config.md
  server/store/common.go
  server/store/datastore/engine.go
  server/store/datastore/xorm.go
Labels: server, enhancement

#2000 Use unified rounded corners for all elements in the nav bar
  web/src/components/atomic/IconButton.vue
  web/src/components/layout/header/ActivePipelines.vue
  web/src/components/layout/header/Navbar.vue
Labels: ui, skip-changelog, ux

#2006 Index stepID for logEntries so loading time decrease significantly
  server/model/log.go
Labels: server, skip-changelog, regression

#2008 Fix agent config reading error handling
  cmd/agent/config.go
Labels: bug, skip-changelog

#1753 Move securitychecks into own workflow
  .woodpecker/docs.yml
  .woodpecker/securityscan.yml
  .woodpecker/test.yml
  .woodpecker/web.yml
Labels: build

#2013 make pending pipelines cancable
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: bug, ui, skip-changelog

#2012 Release windows build for server too
  .woodpecker/binaries.yml
  Makefile
  nfpm/nfpm-cli.yml
  nfpm/nfpm-server.yml
Labels: skip-changelog, build

#2009 Remove code to read agent-id.conf
  cmd/agent/agent.go
  cmd/agent/config.go
  cmd/agent/config_test.go
  cmd/agent/flags.go
Labels: agent, refactor, skip-changelog

#2022 Enhance development on windows
  .gitattributes
  Makefile
Labels: devx

#2021 Refactor agent
  agent/logger.go
  agent/runner.go
  cmd/agent/agent.go
  pipeline/backend/docker/docker.go
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/local/local.go
  pipeline/backend/ssh/ssh.go
  pipeline/backend/types/engine.go
  pipeline/option.go
  pipeline/pipeline.go
Labels: agent, refactor

#2024 Fix "check_swagger" step
  .gitattributes
Labels: skip-changelog, build

#1873 Use id to access orgs
  cli/common/flags.go
  cli/secret/secret.go
  cli/secret/secret_add.go
  cli/secret/secret_info.go
  cli/secret/secret_list.go
  cli/secret/secret_rm.go
  cli/secret/secret_set.go
  cmd/server/docs/docs.go
  server/api/login.go
  server/api/org.go
  server/api/org_secret.go
  server/api/repo.go
  server/cache/membership.go
  server/forge/bitbucket/bitbucket.go
  server/forge/bitbucket/internal/client.go
  server/forge/forge.go
  server/forge/gitea/gitea.go
  server/forge/github/github.go
  server/forge/gitlab/gitlab.go
  server/forge/mocks/forge.go
  server/model/org.go
  server/model/repo.go
  server/model/secret.go
  server/plugins/encryption/wrapper/store/secret_store.go
  server/plugins/secrets/builtin.go
  server/router/api.go
  server/router/middleware/session/user.go
  server/store/datastore/log_test.go
  server/store/datastore/migration/021_add_orgs.go
  server/store/datastore/migration/migration.go
  server/store/datastore/org.go
  server/store/datastore/org_test.go
  server/store/datastore/secret.go
  server/store/datastore/secret_test.go
  server/store/mocks/store.go
  server/store/store.go
  web/src/components/org/settings/OrgSecretsTab.vue
  web/src/compositions/useInjectProvide.ts
  web/src/lib/api/index.ts
  web/src/lib/api/types/org.ts
  web/src/lib/api/types/repo.ts
  web/src/router.ts
  web/src/views/org/OrgDeprecatedRedirect.vue
  web/src/views/org/OrgRepos.vue
  web/src/views/org/OrgSettings.vue
  web/src/views/org/OrgWrapper.vue
  web/src/views/repo/RepoSettings.vue
  web/src/views/repo/RepoWrapper.vue
  woodpecker-go/woodpecker/client.go
  woodpecker-go/woodpecker/interface.go
  woodpecker-go/woodpecker/types.go
Labels: refactor, breaking

#2025 fix docs nits
  docs/docs/30-administration/00-setup.md
  docs/docs/91-migrations.md
  go.mod
  go.sum
Labels: documentation, skip-changelog

#2018 docs: advanced pipeline management
  docs/docs/20-usage/90-pipeline-management.md
Labels: documentation, skip-changelog

#1854 Add Changelog for v1.0.0 RC1
  CHANGELOG.md
Labels: documentation, skip-changelog

#2028 Always use a static back route
  web/src/compositions/useRouteBack.ts
  web/src/compositions/useRouteBackOrDefault.ts
  web/src/views/RepoAdd.vue
  web/src/views/org/OrgSettings.vue
  web/src/views/repo/RepoSettings.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: ui, regression

#2030 Add ping command to server to allow container healthchecks
  cmd/server/health.go
  cmd/server/main.go
  docker/Dockerfile.server.alpine.multiarch
  docker/Dockerfile.server.multiarch
Labels: server, feature

#2033 Fix release branch and tagging
  .woodpecker/docker.yml
  .woodpecker/docs.yml
  .woodpecker/securityscan.yml
  .woodpecker/test.yml
  .woodpecker/web.yml
Labels: skip-changelog, build

#2034 Set v1.0 documents as default and mark v0.15 as unmaintained
  docs/docusaurus.config.js
Labels: documentation

#2037 Fix wrong repo url used by badges
  web/src/components/repo/settings/BadgeTab.vue
Labels: backport, regression

#2043 update docs about versioning
  docs/docs/80-downloads.md
  docs/src/pages/faq.md
Labels: documentation

#2041 let generic datastore error include func name
  server/store/datastore/helper.go
Labels: server, enhancement

#2042 Handle case where there is no latest pipeline for GetBadge
  server/api/badge.go
Labels: bug, server, backport

#2050 Handle case where there is no latest pipeline for GetBadge (#2042)
  server/api/badge.go
Labels: bug, server

#2046 Remove fallback check for old sqlite file location
  cmd/server/setup.go
  docs/docs/30-administration/20-migrate-from-drone.md
Labels: server, refactor

#2047 Missed deprecation
  agent/tracer.go
  docs/docs/30-administration/22-backends/40-kubernetes.md
  docs/versioned_docs/version-1.0/30-administration/22-backends/40-kubernetes.md
  pipeline/backend/kubernetes/pod.go
Labels: bug, skip-changelog, backend/kubernetes

#2048 Drop deprecated built-in environment variables
  agent/tracer.go
  cli/exec/flags.go
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/20-usage/50-environment.md
  docs/docs/30-administration/22-backends/40-kubernetes.md
  docs/docs/91-migrations.md
  docs/versioned_docs/version-1.0/20-usage/20-pipeline-syntax.md
  docs/versioned_docs/version-1.0/20-usage/50-environment.md
  docs/versioned_docs/version-1.0/30-administration/22-backends/40-kubernetes.md
  pipeline/backend/kubernetes/pod.go
  pipeline/frontend/metadata/drone_compatibility_test.go
  pipeline/frontend/metadata/environment.go
  pipeline/frontend/metadata_test.go
  pipeline/samples/sample_1/.env
  pipeline/samples/sample_1/pipeline.json
  pipeline/samples/sample_10_windows/.env
  pipeline/samples/sample_10_windows/pipeline.json
  pipeline/samples/sample_2/.env
  pipeline/samples/sample_2/pipeline.json
  pipeline/samples/sample_3/.env
  pipeline/samples/sample_3/pipeline.json
  pipeline/samples/sample_4/.env
  pipeline/samples/sample_4/pipeline.json
  pipeline/samples/sample_5/.env
  pipeline/samples/sample_5/pipeline.json
  pipeline/samples/sample_6/.env
  pipeline/samples/sample_6/pipeline.json
  pipeline/samples/sample_9_cache/.env
  pipeline/samples/sample_9_cache/pipeline.json
  pipeline/schema/.woodpecker/test-when.yml
  pipeline/tracer.go
Labels: refactor, breaking

#2053 Bump default clone image version to 2.1.0
  shared/constant/constant.go
Labels: dependencies

#2056 Add breaking note for `command:` removal
  CHANGELOG.md
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/91-migrations.md
  docs/versioned_docs/version-1.0/20-usage/20-pipeline-syntax.md
  docs/versioned_docs/version-1.0/91-migrations.md
Labels: bug, documentation, skip-changelog, backport

#2058 Update Changelog for v1.0.0 Release
  CHANGELOG.md
Labels: documentation, skip-changelog, backport

#2061 Prepair docs for v1.0.0 release
  CHANGELOG.md
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/91-migrations.md
  docs/versioned_docs/version-1.0/20-usage/20-pipeline-syntax.md
  docs/versioned_docs/version-1.0/91-migrations.md
Labels: documentation, skip-changelog

#2055 Blog post for v1.0.0 release
  docs/blog/2023-06-11-hello-blog/index.md
  docs/blog/2023-07-28-release-v1.0.0/admin_queue_ui.png
  docs/blog/2023-07-28-release-v1.0.0/index.md
  docs/blog/2023-07-28-release-v1.0.0/org_secrets.png
Labels: documentation, skip-changelog

#2066 Improve bitbucket docs
  docs/docs/30-administration/11-forges/50-bitbucket.md
  docs/docs/30-administration/11-forges/bitbucket_oauth.png
  docs/docs/30-administration/11-forges/bitbucket_permissions.png
Labels: documentation

#2065 Remove default branch fallbacks
  server/forge/bitbucket/bitbucket.go
  server/forge/bitbucket/convert.go
  server/forge/bitbucket/internal/types.go
  server/forge/github/convert.go
  server/forge/github/parse.go
  server/forge/gitlab/convert.go
Labels: refactor

#2070 fix: global registry docs
  docs/docs/30-administration/10-server-config.md
Labels: documentation

#2069 Publish releases and branch tags to quay.io too
  .woodpecker/docker.yml
Labels: build

#2044 Change master to main
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/plugin_index.yml.disabled
  README.md
  cli/deploy/deploy.go
  cli/pipeline/last.go
  docs/README.md
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/20-usage/50-environment.md
  docs/docs/20-usage/80-badges.md
  docs/docs/30-administration/10-server-config.md
  docs/docs/30-administration/100-external-configuration-api.md
  docs/docs/30-administration/90-prometheus.md
  docs/docs/92-awesome.md
  docs/docs/92-development/03-ui.md
  docs/docs/92-development/06-guides.md
  docs/docs/92-development/08-swagger.md
  docs/docusaurus.config.js
  docs/plugins/woodpecker-plugins/plugins.json
  docs/plugins/woodpecker-plugins/src/theme/WoodpeckerPluginList.tsx
  pipeline/frontend/yaml/compiler/cacher.go
  pipeline/frontend/yaml/constraint/constraint_test.go
  pipeline/frontend/yaml/types/container_test.go
  pipeline/samples/sample_1/pipeline.json
  pipeline/samples/sample_10_windows/pipeline.json
  pipeline/samples/sample_2/pipeline.json
  pipeline/samples/sample_3/pipeline.json
  pipeline/samples/sample_4/pipeline.json
  pipeline/samples/sample_5/pipeline.json
  pipeline/samples/sample_6/pipeline.json
  pipeline/samples/sample_9_cache/pipeline.json
  pipeline/schema/.woodpecker/test-branches-array.yml
  pipeline/schema/.woodpecker/test-branches-exclude-include.yml
  pipeline/schema/.woodpecker/test-branches.yml
  pipeline/schema/.woodpecker/test-broken.yml
  pipeline/schema/.woodpecker/test-pipeline-when.yml
  pipeline/schema/.woodpecker/test-when.yml
  pipeline/stepBuilder_test.go
  server/forge/bitbucket/convert_test.go
  server/forge/bitbucket/fixtures/hooks.go
  server/forge/gitea/fixtures/hooks.go
  server/forge/gitea/helper_test.go
  server/forge/github/convert_test.go
  server/forge/github/fixtures/hooks.go
  server/forge/gitlab/gitlab_test.go
  server/forge/gitlab/testdata/hooks.go
  server/forge/gitlab/testdata/projects.go
  server/store/datastore/pipeline_test.go
Labels: governance, refactor
