Repository woodpecker-ci/woodpecker, pull requests merged in 2023-05, with the labels that each got.

#1733 Add forgejo in docs
  docs/docs/30-administration/11-forges/10-overview.md
  docs/docs/30-administration/11-forges/30-gitea.md
Labels: documentation

#1728 feat: let agent retry to connecting to server
  cmd/agent/agent.go
  cmd/agent/flags.go
  cmd/agent/main.go
  docs/docs/30-administration/15-agent-config.md
Labels: agent, enhancement

#1744 Update dependencies
  go.mod
  go.sum
  pipeline/backend/docker/docker.go
Labels: security, dependencies

#1741 Add ntfy plugin
  docs/plugins/woodpecker-plugins/plugins.json
Labels: plugin, documentation

#1732 Identify users using their remote ID
  server/api/login.go
  server/forge/bitbucket/convert.go
  server/forge/bitbucket/internal/types.go
  server/forge/bitbucketserver/convert.go
  server/forge/bitbucketserver/internal/client.go
  server/forge/gitea/gitea.go
  server/forge/github/github.go
  server/forge/gitlab/gitlab.go
  server/forge/gogs/gogs.go
  server/forge/mocks/forge.go
  server/model/user.go
  server/store/datastore/user.go
  server/store/mocks/store.go
  server/store/store.go
Labels: refactor

#1735 Allow to configure listener port for SSL
  cmd/server/flags.go
  cmd/server/server.go
  docs/docs/30-administration/10-server-config.md
  server/config.go
Labels: server, enhancement

#1746 Add Changelog v0.15.9
  CHANGELOG.md
Labels: documentation, skip-changelog

#1747 Improve `skip_clone` documentation
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/20-usage/25-workflows.md
Labels: documentation

#1752 Drop Gogs support
  cmd/server/flags.go
  cmd/server/setup.go
  docs/docs/30-administration/10-server-config.md
  docs/docs/30-administration/11-forges/10-overview.md
  docs/docs/30-administration/11-forges/70-gogs.md
  docs/docs/91-migrations.md
  go.mod
  go.sum
  server/forge/gogs/fixtures/handler.go
  server/forge/gogs/fixtures/hooks.go
  server/forge/gogs/gogs.go
  server/forge/gogs/gogs_test.go
  server/forge/gogs/helper.go
  server/forge/gogs/helper_test.go
  server/forge/gogs/parse.go
  server/forge/gogs/types.go
Labels: refactor, breaking, forge/gogs

#1758 Fix pipeline used for status reporting
  server/pipeline/cancel.go
Labels: skip-changelog

#1754 Add agent functions
  woodpecker-go/woodpecker/client.go
  woodpecker-go/woodpecker/interface.go
  woodpecker-go/woodpecker/types.go
Labels: enhancement

#1755 Add reset token button
  web/src/assets/locales/en.json
  web/src/lib/api/index.ts
  web/src/views/User.vue
Labels: enhancement

#1762 Improve local backend
  pipeline/backend/local/local.go
  pipeline/backend/types/engine.go
Labels: agent, enhancement

#1765 Base images on alpine 3.18
  docker/Dockerfile.agent.alpine.multiarch
  docker/Dockerfile.cli.alpine.multiarch
  docker/Dockerfile.server.alpine.multiarch
Labels: dependencies

#1763 Adding Android CI example to awesome woodpecker
  docs/docs/92-awesome.md
Labels: documentation

#1769 Add Trivy Plugin
  docs/plugins/woodpecker-plugins/plugins.json
Labels: plugin, documentation

#1770 Add MkDocs Plugin
  docs/plugins/woodpecker-plugins/plugins.json
Labels: plugin, documentation

#1772 Add first video
  docs/docs/92-awesome.md
Labels: documentation

#1775 PipelineLog.vue: Make it possible to link to a log line
  web/src/components/repo/pipeline/PipelineLog.vue
Labels: ui

#1783 Fix static assets with subpath
  server/web/web.go
Labels: bug, server, ui

#1795 Drop ".drone.yml" as default pipeline config
  docs/docs/20-usage/71-project-settings.md
  docs/docs/91-migrations.md
  server/forge/configFetcher_test.go
  shared/constant/constant.go
  web/src/assets/locales/de.json
  web/src/assets/locales/en.json
  web/src/assets/locales/es.json
  web/src/assets/locales/fr.json
  web/src/assets/locales/id.json
  web/src/assets/locales/it.json
  web/src/assets/locales/lv.json
  web/src/assets/locales/pl.json
  web/src/assets/locales/ru.json
  web/src/assets/locales/uk.json
  web/src/assets/locales/zh-Hans.json
Labels: refactor, breaking

#1794 Buildin Env Vars, use _URL for all links/urls
  cli/exec/flags.go
  docs/docs/20-usage/50-environment.md
  docs/docs/91-migrations.md
  docs/docs/92-development/09-terms.md
  pipeline/drone_compatibility.go
  pipeline/frontend/metadata.go
  pipeline/frontend/yaml/compiler/option_test.go
  pipeline/samples/sample_1/pipeline.json
  pipeline/samples/sample_10_windows/pipeline.json
  pipeline/samples/sample_2/pipeline.json
  pipeline/samples/sample_3/pipeline.json
  pipeline/samples/sample_4/pipeline.json
  pipeline/samples/sample_5/pipeline.json
  pipeline/samples/sample_6/pipeline.json
  pipeline/samples/sample_7_redis/pipeline.json
  pipeline/samples/sample_8_network_mode/pipeline.json
  pipeline/samples/sample_9_cache/pipeline.json
Labels: server, governance, refactor, breaking
