Repository woodpecker-ci/woodpecker, pull requests merged in 2023-02, with the labels that each got.

#1558 Define WOODPECKER_FORGE_TIMEOUT server config
  cmd/server/flags.go
  cmd/server/server.go
  docs/docs/30-administration/10-server-config.md
  server/config.go
  server/forge/configFetcher.go
  server/forge/configFetcher_test.go
  server/pipeline/create.go
Labels: server, enhancement

#1569 allow custom dnsConfig in agent deployment
  charts/woodpecker-agent/templates/deployment.yaml
  charts/woodpecker-agent/values.yaml
  charts/woodpecker-server/templates/deployment.yaml
  charts/woodpecker-server/values.yaml
Labels: enhancement, chart

#1327 Use modern error handling and enforce it via lint
  .golangci.yml
  .vscode/settings.json
  go.mod
  go.sum
  pipeline/backend/local/local.go
  pipeline/frontend/yaml/compiler/compiler_test.go
  pipeline/frontend/yaml/config.go
  pipeline/frontend/yaml/config_test.go
  pipeline/frontend/yaml/constraint/constraint.go
  pipeline/frontend/yaml/container.go
  pipeline/frontend/yaml/container_test.go
  pipeline/frontend/yaml/error.go
  pipeline/frontend/yaml/types/types_yaml.go
  pipeline/frontend/yaml/types/types_yaml_test.go
  server/api/helper.go
  server/cron/cron.go
  server/forge/coding/internal/coding.go
  server/forge/configFetcher.go
  server/forge/gitea/gitea.go
  server/forge/gitlab/gitlab.go
  server/forge/userSyncer.go
  server/model/cron.go
  server/model/secret.go
  server/model/user_test.go
  server/pipeline/approve.go
  server/pipeline/cancel.go
  server/pipeline/decline.go
  server/pipeline/errors.go
  server/pipeline/restart.go
  server/plugins/encryption/aes_builder.go
  server/plugins/encryption/tink_builder.go
  server/plugins/encryption/tink_state.go
  server/pubsub/pub_test.go
  server/queue/fifo_test.go
  server/store/datastore/migration/000_legacy_to_xorm.go
  server/store/datastore/migration/common.go
  server/store/datastore/migration/migration.go
Labels: refactor

#1578 Update 15-agent-config.md
  docs/versioned_docs/version-0.15/30-administration/15-agent-config.md
Labels: documentation

#1585 Ensure the SharedInformerFactory closes eventually
  pipeline/backend/kubernetes/kubernetes.go
Labels: bug, backend/kubernetes

#1589 Move helm charts to own repo "helm"
  .woodpecker/helm.yml
  charts/woodpecker-agent/.helmignore
  charts/woodpecker-agent/Chart.yaml
  charts/woodpecker-agent/templates/_helpers.tpl
  charts/woodpecker-agent/templates/deployment.yaml
  charts/woodpecker-agent/templates/role.yaml
  charts/woodpecker-agent/templates/rolebinding.yaml
  charts/woodpecker-agent/templates/serviceaccount.yaml
  charts/woodpecker-agent/values.yaml
  charts/woodpecker-server/.helmignore
  charts/woodpecker-server/Chart.yaml
  charts/woodpecker-server/templates/NOTES.txt
  charts/woodpecker-server/templates/_helpers.tpl
  charts/woodpecker-server/templates/deployment.yaml
  charts/woodpecker-server/templates/ingress.yaml
  charts/woodpecker-server/templates/persistentvolumeclaim.yaml
  charts/woodpecker-server/templates/service.yaml
  charts/woodpecker-server/templates/serviceaccount.yaml
  charts/woodpecker-server/values.yaml
Labels: governance

#1592 Add version notes to docs
  docs/docs/10-intro.md
  docs/docs/30-administration/00-setup.md
  docs/docs/80-downloads.md
  docs/docs/91-migrations.md
  docs/docusaurus.config.js
  docs/src/pages/faq.md
  docs/versioned_docs/version-0.15/10-intro.md
  docs/versioned_docs/version-0.15/30-administration/00-setup.md
  docs/versioned_docs/version-0.15/80-downloads.md
Labels: documentation

#1593 Change issue template labels
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: governance, skip-changelog
