Repository woodpecker-ci/woodpecker, pull requests merged in 2023-08, with the labels that each got.

#2003 Use consistent woodpecker color scheme
  .gitignore
  web/package.json
  web/pnpm-lock.yaml
  web/src/App.vue
  web/src/assets/locales/en.json
  web/src/components/admin/settings/AdminAgentsTab.vue
  web/src/components/admin/settings/AdminQueueTab.vue
  web/src/components/admin/settings/AdminSecretsTab.vue
  web/src/components/admin/settings/AdminUsersTab.vue
  web/src/components/admin/settings/queue/AdminQueueStats.vue
  web/src/components/atomic/Badge.vue
  web/src/components/atomic/Button.vue
  web/src/components/atomic/DocsLink.vue
  web/src/components/atomic/ListItem.vue
  web/src/components/atomic/Warning.vue
  web/src/components/form/Checkbox.vue
  web/src/components/form/InputField.vue
  web/src/components/form/RadioField.vue
  web/src/components/form/SelectField.vue
  web/src/components/form/TextField.vue
  web/src/components/layout/Panel.vue
  web/src/components/layout/header/Navbar.vue
  web/src/components/layout/popups/DeployPipelinePopup.vue
  web/src/components/layout/popups/ManualPipelinePopup.vue
  web/src/components/layout/scaffold/Header.vue
  web/src/components/layout/scaffold/Tabs.vue
  web/src/components/org/settings/OrgSecretsTab.vue
  web/src/components/pipeline-feed/PipelineFeedItem.vue
  web/src/components/pipeline-feed/PipelineFeedSidebar.vue
  web/src/components/repo/pipeline/PipelineItem.vue
  web/src/components/repo/pipeline/PipelineList.vue
  web/src/components/repo/pipeline/PipelineLog.vue
  web/src/components/repo/pipeline/PipelineRunningIcon.vue
  web/src/components/repo/pipeline/PipelineStatusIcon.vue
  web/src/components/repo/pipeline/PipelineStepList.vue
  web/src/components/repo/settings/ActionsTab.vue
  web/src/components/repo/settings/BadgeTab.vue
  web/src/components/repo/settings/CronTab.vue
  web/src/components/repo/settings/GeneralTab.vue
  web/src/components/repo/settings/RegistriesTab.vue
  web/src/components/repo/settings/SecretsTab.vue
  web/src/components/secrets/SecretList.vue
  web/src/compositions/useDarkMode.ts
  web/src/style.css
  web/src/views/Login.vue
  web/src/views/RepoAdd.vue
  web/src/views/Repos.vue
  web/src/views/User.vue
  web/src/views/org/OrgRepos.vue
  web/src/views/repo/RepoBranch.vue
  web/src/views/repo/RepoBranches.vue
  web/src/views/repo/RepoPullRequest.vue
  web/src/views/repo/RepoPullRequests.vue
  web/src/views/repo/pipeline/Pipeline.vue
  web/src/views/repo/pipeline/PipelineChangedFiles.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
  web/windi.config.ts
Labels: ui, ux

#2045 Support bitbucket Dir()
  docs/docs/30-administration/11-forges/10-overview.md
  server/forge/bitbucket/bitbucket.go
  server/forge/bitbucket/bitbucket_test.go
  server/forge/bitbucket/fixtures/handler.go
  server/forge/bitbucket/internal/client.go
  server/forge/bitbucket/internal/types.go
Labels: forge/bitbucket

#2095 Add blog posts/tutorials
  docs/docs/92-awesome.md
Labels: documentation

#2097 Test/forge/bitbucket add tests
  server/forge/bitbucket/bitbucket_test.go
  server/forge/bitbucket/fixtures/handler.go
Labels: tests, forge/bitbucket

#2090 client lib: remove useles "sync" option from RepoListOpts
  cli/repo/repo_sync.go
  woodpecker-go/woodpecker/client.go
  woodpecker-go/woodpecker/interface.go
Labels: bug, refactor, breaking

#2093 Allow to disable swagger
  cmd/server/flags.go
  cmd/server/server.go
  docs/docs/30-administration/10-server-config.md
  server/config.go
  server/router/router.go
  server/web/config.go
  web/src/components/layout/header/Navbar.vue
  web/src/compositions/useConfig.ts
  web/src/views/User.vue
Labels: server, ui, enhancement

#2098 Fix translation key
  web/src/components/pipeline-feed/PipelineFeedItem.vue
Labels: bug, ui

#2104 Forge Github Org: Use `login` instead of `name`
  server/forge/github/github.go
  server/forge/gitlab/gitlab.go
Labels: bug, forge/github, forge/gitlab, backport

#2106 Forge Github Org: Use `login` instead of `name` (#2104)
  server/forge/github/github.go
  server/forge/gitlab/gitlab.go
Labels: bug, forge/github, forge/gitlab

#2103 CLI repo sync: Show `forge-remote-id`
  cli/repo/repo_list.go
Labels: bug, backport, cli

#2107 Fix en.json file syntax
  web/src/assets/locales/en.json
Labels: bug, skip-changelog, regression

#2108 lint en.json locales file
  .woodpecker/web.yml
  web/.prettierignore
  web/package.json
  web/src/assets/locales/en.json
Labels: skip-changelog, build

#2105 Only run docs workflow on main branch
  .woodpecker/docs.yml
  .woodpecker/securityscan.yml
Labels: skip-changelog, build, backport

#2110 Only run docs workflow on main branch (#2105)
  .woodpecker/docs.yml
  .woodpecker/securityscan.yml
Labels: skip-changelog, build

#2119 Fix swagger response code
  cmd/server/docs/docs.go
  server/api/global_secret.go
  server/api/org_secret.go
  server/api/repo_secret.go
Labels: bug, documentation, backport

#2121 Fix swagger response code (#2119)
  cmd/server/docs/docs.go
  server/api/global_secret.go
  server/api/org_secret.go
  server/api/repo_secret.go
Labels: bug, documentation

#2122 docs: Environment Variable Seems to be `DOCKER_HOST`, not `DOCKER_SOCK`
  docs/docs/30-administration/22-backends/10-docker.md
  docs/versioned_docs/version-1.0/30-administration/22-backends/10-docker.md
Labels: bug, documentation

#2129 Fix workflows again
  .woodpecker/docs.yml
  .woodpecker/test.yml
  .woodpecker/web.yml
Labels: build

#2130 Don't show badge without information
  web/src/components/admin/settings/AdminAgentsTab.vue
Labels: ui, enhancement

#2132 Fix missing translation
  web/src/components/admin/settings/AdminAgentsTab.vue
Labels: bug, ui, skip-changelog

#2017 Enhance local backend
  pipeline/backend/local/clone.go
  pipeline/backend/local/const.go
  pipeline/backend/local/local.go
  pipeline/frontend/yaml/linter/linter_test.go
Labels: enhancement, backend/local

#1799 Fix UI and backend paths with subpath
  cmd/server/flags.go
  cmd/server/server.go
  docs/docs/30-administration/00-setup.md
  docs/docs/30-administration/10-server-config.md
  server/api/login.go
  server/config.go
  server/forge/bitbucket/bitbucket.go
  server/forge/gitea/gitea.go
  server/forge/github/github.go
  server/forge/gitlab/gitlab.go
  server/router/api.go
  server/router/router.go
  server/web/config.go
  server/web/web.go
  web/index.html
  web/package.json
  web/src/assets/logo.svg
  web/src/components/layout/header/Navbar.vue
  web/src/components/repo/pipeline/PipelineRunningIcon.vue
  web/src/components/repo/settings/BadgeTab.vue
  web/src/components/user/UserAPITab.vue
  web/src/compositions/useApiClient.ts
  web/src/compositions/useAuthentication.ts
  web/src/compositions/useConfig.ts
  web/src/compositions/useFavicon.ts
  web/src/lib/api/client.ts
  web/src/router.ts
  web/src/views/Login.vue
  web/src/views/User.vue
  web/src/views/repo/RepoWrapper.vue
Labels: bug, regression

#2134 Fix vite server
  server/web/web.go
  web/index.html
Labels: bug, regression

#2115 Add opt save global log output to file
  agent/rpc/auth_interceptor.go
  cli/common/flags.go
  cli/common/zerologger.go
  cmd/agent/agent.go
  cmd/agent/flags.go
  cmd/cli/app.go
  cmd/common/common.go
  cmd/common/logger.go
  cmd/server/flags.go
  cmd/server/server.go
  go.mod
  go.sum
Labels: server, agent, feature, refactor, cli

#2138 Use fix width for pipeline step list
  web/src/components/repo/pipeline/PipelineStepList.vue
Labels: ui, ux

#2140 Add header to pipeline log and always show buttons
  web/src/assets/locales/en.json
  web/src/components/repo/pipeline/PipelineLog.vue
Labels: ui, enhancement

#2117 Fix 'add-orgs' migration
  go.mod
  go.sum
  server/store/datastore/migration/021_add_orgs.go
Labels: bug, server, backport

#2141 Use min/max width for pipeline step list
  web/src/components/repo/pipeline/PipelineStepList.vue
Labels: ui

#2145 Fix 'add-orgs' migration (#2117)
  go.mod
  go.sum
  server/store/datastore/migration/021_add_orgs.go
Labels: bug, server

#2150 Add changelog v1.0.1
  CHANGELOG.md
Labels: documentation, skip-changelog

#2182 Better blog title/desc
  docs/docusaurus.config.js
Labels: documentation

#2180 fail hard on deprecated pipeline keys
  docs/docs/91-migrations.md
  pipeline/frontend/yaml/parse.go
  pipeline/frontend/yaml/parse_test.go
  pipeline/stepBuilder_test.go
Labels: refactor, breaking, pipeline-config

#2181 Deprecate "platform" filter in favour of "labels"
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/91-migrations.md
  docs/versioned_docs/version-1.0/20-usage/20-pipeline-syntax.md
  pipeline/frontend/yaml/parse.go
  pipeline/frontend/yaml/parse_test.go
  pipeline/frontend/yaml/types/base/map.go
  pipeline/frontend/yaml/types/workflow.go
  pipeline/stepBuilder.go
  server/pipeline/queue.go
Labels: refactor, breaking, pipeline-config

#2185 bump xorm.io to db7c2640627d
  go.mod
  go.sum
Labels: refactor, skip-changelog, dependencies, backport

#2183 Add TestCompilerCompile
  pipeline/frontend/yaml/compiler/compiler_test.go
Labels: tests

#2190 Show all steps
  web/src/components/repo/pipeline/PipelineStepList.vue
Labels: bug, ui, backport

#2191 Show all steps (#2190)
  web/src/components/repo/pipeline/PipelineStepList.vue
Labels: bug, ui

#2196 Update list of "projects using Woodpecker"
  docs/docs/92-awesome.md
Labels: documentation

#2198 Add SSH clone URL env var
  cli/exec/flags.go
  cli/exec/metadata.go
  cmd/server/docs/docs.go
  docs/docs/20-usage/50-environment.md
  pipeline/frontend/metadata.go
  pipeline/frontend/metadata/environment.go
  pipeline/frontend/metadata/types.go
  pipeline/frontend/metadata_test.go
  server/forge/bitbucket/convert.go
  server/forge/gitea/helper.go
  server/forge/github/convert.go
  server/forge/gitlab/convert.go
  server/model/repo.go
Labels: enhancement

#2193 Restructure k8s documentation
  docs/docs/30-administration/00-setup.md
  docs/docs/30-administration/22-backends/40-kubernetes.md
  docs/docs/30-administration/80-kubernetes.md
Labels: documentation, backend/kubernetes

#2212 Move hook and events-stream routes to use `/api` prefix
  server/api/hook.go
  server/api/repo.go
  server/router/api.go
  web/src/lib/api/index.ts
Labels: server, refactor

#2217 Rename build -> pipeline in docs for external configuration service
  docs/docs/30-administration/100-external-configuration-api.md
  docs/versioned_docs/version-1.0/30-administration/100-external-configuration-api.md
Labels: bug, documentation, skip-changelog

#2215 Bump default git clone plugin
  pipeline/frontend/yaml/compiler/compiler_test.go
  shared/constant/constant.go
Labels: bug, dependencies, backport

#2222 Validate webhook before change any data (#2221)
  server/api/hook.go
Labels: refactor

#2220 Bump default git clone plugin (#2215)
  shared/constant/constant.go
Labels: bug, dependencies

#2223 Changelog v1.0.2
  CHANGELOG.md
Labels: documentation, skip-changelog

#2224 Changelog v1.0.2 (#2223)
  CHANGELOG.md
Labels: documentation, skip-changelog

#2227 Set correct version for release branch releases
  Makefile
Labels: bug, build, backport

#2229 Set correct version for release branch releases (#2227)
  Makefile
Labels: bug, build

#2230 Return 204 not 500 on filtered pipeline
  server/pipeline/create.go
  server/pipeline/errors.go
Labels: bug, server

#2216 Move "skip ci" logic into global pipeline conditions
  .vscode/settings.json
  Makefile
  pipeline/frontend/yaml/constraint/constraint.go
  server/api/hook.go
  server/pipeline/create.go
  server/pipeline/errors.go
Labels: refactor

#2242 Skip settings proxy config with WithProxy if its empty
  pipeline/frontend/yaml/compiler/option.go
Labels: enhancement

#2243 Handle parsed hooks that should be ignored
  server/forge/gitea/gitea.go
Labels: bug, server, forge/gitea, backport

#2241 fix regression and add trace in clone for local backend
  pipeline/backend/local/clone.go
Labels: backend/local, regression

#2205 Improve agent rpc retry logic with exponential backoff
  agent/rpc/client_grpc.go
  go.mod
  go.sum
Labels: agent, enhancement

#2240 bump github.com/6543/logfile-open ...
  go.mod
  go.sum
Labels: skip-changelog, dependencies, regression

#2238 Docker build dont ignore ci env vars
  .woodpecker/docker.yml
  docker/Dockerfile.agent.alpine.multiarch
  docker/Dockerfile.agent.multiarch
  docker/Dockerfile.cli.alpine.multiarch
  docker/Dockerfile.cli.multiarch
Labels: bug, agent, build, backport, cli

#2246 Docker build dont ignore ci env vars (#2238)
  .woodpecker/docker.yml
  docker/Dockerfile.agent.alpine.multiarch
  docker/Dockerfile.agent.multiarch
  docker/Dockerfile.cli.alpine.multiarch
  docker/Dockerfile.cli.multiarch
Labels: bug, agent, build, cli

#2247 Change token logging to trace level
  agent/rpc/auth_interceptor.go
Labels: agent, enhancement, security, backport

#2248 Change token logging to trace level (#2247)
  agent/rpc/auth_interceptor.go
Labels: agent, enhancement, security

#2250 Fix usage description for backend-http-proxy flag
  cli/exec/flags.go
  cmd/server/flags.go
Labels: documentation

#2252 Improve explanation for globs in when:path
  docs/versioned_docs/version-1.0/20-usage/20-pipeline-syntax.md
Labels: documentation

#2189 Use browser-native tooltips
  web/package.json
  web/pnpm-lock.yaml
  web/src/assets/locales/en.json
  web/src/components/pipeline-feed/PipelineFeedItem.vue
  web/src/components/repo/pipeline/PipelineItem.vue
  web/src/main.ts
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: ui, refactor

#2177 Create settings-panel vue component and use InputFields
  web/components.d.ts
  web/src/components/admin/settings/AdminAgentsTab.vue
  web/src/components/admin/settings/AdminQueueTab.vue
  web/src/components/admin/settings/AdminSecretsTab.vue
  web/src/components/admin/settings/AdminUsersTab.vue
  web/src/components/form/InputField.vue
  web/src/components/layout/Settings.vue
  web/src/components/org/settings/OrgSecretsTab.vue
  web/src/components/repo/settings/ActionsTab.vue
  web/src/components/repo/settings/BadgeTab.vue
  web/src/components/repo/settings/CronTab.vue
  web/src/components/repo/settings/GeneralTab.vue
  web/src/components/repo/settings/RegistriesTab.vue
  web/src/components/repo/settings/SecretsTab.vue
  web/src/components/user/UserAPITab.vue
  web/src/components/user/UserGeneralTab.vue
Labels: ui, refactor

#2310 Pass netrc data to external config service request
  docs/docs/30-administration/100-external-configuration-api.md
  server/api/pipeline.go
  server/forge/configFetcher.go
  server/forge/configFetcher_test.go
  server/pipeline/restart.go
  server/plugins/config/extension.go
  server/plugins/config/http.go
Labels: server, enhancement

#2319 Fix migration
  server/store/datastore/migration/022_add_org_id.go
Labels: bug, server, regression

#2239 Add "plugin" support to local backend
  docs/docs/30-administration/22-backends/20-local.md
  docs/versioned_docs/version-1.0/30-administration/22-backends/20-local.md
  pipeline/backend/local/clone.go
  pipeline/backend/local/local.go
Labels: enhancement, backend/local

#2249 [Feature] Configure tolerations in kubernetes backend
  docs/docs/30-administration/22-backends/40-kubernetes.md
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/types/backend_kubernetes.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/types/backend_options.go
Labels: backend/kubernetes

#2320 Refactor version handling in Makefile
  Makefile
Labels: skip-changelog, build

#2322 make: autodetect host platform
  Makefile
Labels: enhancement, build

#2326 add spacing to pipeline feed spinner
  web/src/components/layout/header/ActivePipelines.vue
Labels: ui, enhancement

#2333 Fix button loading spinner when activating repos
  web/src/views/RepoAdd.vue
Labels: bug, ui

#2332 Fix mobile login view
  web/src/views/Login.vue
Labels: ui

#2336 Fix grid column size in pipeline log view
  web/src/components/repo/pipeline/PipelineLog.vue
Labels: bug, ui

#2335 Add min height to mobile pipeline view and fix overflow
  web/src/components/repo/pipeline/PipelineStepList.vue
  web/src/views/repo/pipeline/Pipeline.vue
Labels: ui

#2340 Show that repo is disabled
  server/api/badge.go
  server/api/user.go
  web/src/assets/locales/en.json
  web/src/views/RepoAdd.vue
Labels: enhancement

#2346 Use html list for changed files list
  web/src/views/repo/pipeline/PipelineChangedFiles.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: ui, ux

#2327 Use full width header on pipeline view and show repo name
  web/src/components/layout/FluidContainer.vue
  web/src/components/layout/scaffold/Header.vue
  web/src/components/layout/scaffold/Scaffold.vue
  web/src/components/layout/scaffold/Tabs.vue
  web/src/components/repo/pipeline/PipelineLog.vue
  web/src/components/repo/pipeline/PipelineStepList.vue
  web/src/views/repo/RepoWrapper.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: ui, enhancement, ux

#2349 Clarify env var `CI` in docs
  docs/docs/20-usage/50-environment.md
Labels: documentation
