Repository woodpecker-ci/woodpecker, pull requests merged in 2023-11, with the labels that each got.

#2686 Fix secret image filter regex (#2674)
  server/model/secret.go
  server/model/secret_test.go
Labels: bug

#2687 Fix secrets UI
  web/components.d.ts
  web/src/components/repo/settings/SecretsTab.vue
  web/src/lib/api/types/secret.ts
Labels: bug, ui, regression

#2681 Stop steps after they are done
  .woodpecker/docker.yml
  pipeline/backend/docker/docker.go
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/local/local.go
  pipeline/backend/types/engine.go
  pipeline/pipeline.go
Labels: enhancement

#2689 Use path.Join for server side path generation
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/compiler/option.go
Labels: server, enhancement

#2102 Report problems with listening to ports and exit
  cmd/server/server.go
Labels: server, enhancement

#2678 Print local backend command logs
  .vscode/settings.json
  pipeline/backend/local/command.go
Labels: enhancement, backend/local

#1488 Showing the pending pipelines on top
  web/src/store/pipelines.ts
  web/src/utils/helpers.ts
Labels: ui, enhancement, wip

#2688 Let the backend engine report the current platform
  cli/exec/exec.go
  cmd/agent/agent.go
  pipeline/backend/common/script.go
  pipeline/backend/common/script_win_test.go
  pipeline/backend/docker/convert.go
  pipeline/backend/docker/docker.go
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/local/local.go
  pipeline/backend/types/engine.go
Labels: agent, enhancement, backend/docker

#2696 Fix typo in golang image name
  docker/Dockerfile.cli.multiarch
Labels: bug, skip-changelog, regression

#2695 Unique status for matrix
  cmd/server/flags.go
  docs/docs/30-administration/10-server-config.md
  pipeline/stepBuilder.go
  server/forge/common/status.go
  server/model/workflow.go
Labels: bug, server

#2649 Pin alpine versions in Dockerfile
  docker/Dockerfile.agent.alpine.multiarch
  docker/Dockerfile.cli.alpine.multiarch
  docker/Dockerfile.make
  docker/Dockerfile.server.alpine.multiarch
Labels: build, dependencies

#2606 Unregister stateless agents from server on termination
  agent/rpc/client_grpc.go
  cmd/agent/agent.go
  cmd/agent/config.go
  cmd/agent/config_test.go
  cmd/agent/flags.go
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/rpc/peer.go
  pipeline/rpc/proto/version.go
  pipeline/rpc/proto/woodpecker.pb.go
  pipeline/rpc/proto/woodpecker.proto
  pipeline/rpc/proto/woodpecker_grpc.pb.go
  server/grpc/rpc.go
  server/grpc/server.go
  shared/utils/context.go
Labels: agent, enhancement

#2656 Add ports into pipeline backend step model
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/kubernetes/service.go
  pipeline/backend/kubernetes/service_test.go
  pipeline/backend/types/step.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/types/container.go
  pipeline/frontend/yaml/types/container_test.go
Labels: enhancement, backend/kubernetes

#2703 Use int64 for IDs in woodpecker client lib
  cli/deploy/deploy.go
  cli/log/log_purge.go
  cli/pipeline/approve.go
  cli/pipeline/decline.go
  cli/pipeline/info.go
  cli/pipeline/kill.go
  cli/pipeline/logs.go
  cli/pipeline/ps.go
  cli/pipeline/start.go
  cli/pipeline/stop.go
  woodpecker-go/woodpecker/client.go
  woodpecker-go/woodpecker/interface.go
  woodpecker-go/woodpecker/types.go
Labels: breaking, lib

#2702 Option to change temp dir for local backend
  docs/docs/30-administration/15-agent-config.md
  docs/docs/30-administration/22-backends/20-local.md
  pipeline/backend/local/command.go
  pipeline/backend/local/flags.go
  pipeline/backend/local/local.go
Labels: enhancement, backend/local

#1572 Enhance linter and errors
  .pre-commit-config.yaml
  cli/exec/exec.go
  cli/lint/lint.go
  cmd/server/docs/docs.go
  go.mod
  go.sum
  pipeline/errors/error.go
  pipeline/errors/error_test.go
  pipeline/frontend/yaml/constraint/constraint.go
  pipeline/frontend/yaml/linter/error.go
  pipeline/frontend/yaml/linter/linter.go
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-branches-array.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-branches-exclude-include.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-branches.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-broken.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-clone-skip.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-clone.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-labels.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-matrix.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-merge-map-and-sequence.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-multi.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-pipeline-when.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-platform.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-plugin.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-run-on.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-service.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-step.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-when.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-workspace.yml
  pipeline/frontend/yaml/linter/schema/schema.go
  pipeline/frontend/yaml/linter/schema/schema.json
  pipeline/frontend/yaml/linter/schema/schema_test.go
  pipeline/frontend/yaml/matrix/matrix.go
  pipeline/stepBuilder.go
  pipeline/stepBuilder_test.go
  server/model/const.go
  server/model/pipeline.go
  server/pipeline/approve.go
  server/pipeline/create.go
  server/pipeline/items.go
  server/pipeline/pipelineStatus.go
  server/pipeline/pipelineStatus_test.go
  server/pipeline/restart.go
  server/store/datastore/migration/026_convert_to_new_pipeline_errors_format.go
  server/store/datastore/migration/migration.go
  web/src/assets/locales/en.json
  web/src/components/layout/scaffold/Tab.vue
  web/src/components/repo/pipeline/PipelineInfo.vue
  web/src/lib/api/types/pipeline.ts
  web/src/router.ts
  web/src/views/repo/pipeline/Pipeline.vue
  web/src/views/repo/pipeline/PipelineErrors.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
  woodpecker-go/woodpecker/types.go
Labels: enhancement

#2715 Fix default status
  cmd/server/flags.go
  docs/docs/30-administration/10-server-config.md
  server/forge/common/status.go
Labels: bug, server, regression

#2717 Fix axisID for non-matrix
  pipeline/stepBuilder.go
Labels: bug, regression

#2719 Fix step selection
  web/src/views/repo/pipeline/Pipeline.vue
Labels: bug, regression

#2713 Fix pinned alpine package versions
  docker/Dockerfile.make
Labels: build, regression

#2712 Fix active tab not updating on prop change
  web/src/components/layout/scaffold/Header.vue
  web/src/components/layout/scaffold/Scaffold.vue
  web/src/components/layout/scaffold/Tabs.vue
  web/src/compositions/useTabs.ts
  web/src/views/repo/RepoWrapper.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: bug, ui

#2698 Some UI fixes
  server/logging/log.go
  server/pipeline/create.go
  server/pipeline/decline.go
  server/pipeline/start.go
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: bug, server, ui

#2723 Use unique label selector for pod label for kubernetes services
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/kubernetes/service.go
  pipeline/backend/kubernetes/service_test.go
Labels: bug, backend/kubernetes

#2722 Add version and update notes
  .woodpecker/docs.yml
  web/components.d.ts
  web/src/assets/locales/en.json
  web/src/components/admin/settings/AdminInfoTab.vue
  web/src/components/layout/header/Navbar.vue
  web/src/compositions/useVersion.ts
  web/src/views/admin/AdminSettings.vue
Labels: ui, feature

#2725 Add deprecation warnings
  cli/exec/exec.go
  cli/lint/lint.go
  pipeline/errors/error.go
  pipeline/frontend/yaml/linter/error.go
  pipeline/frontend/yaml/linter/linter.go
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/stepBuilder.go
  web/src/lib/api/types/pipeline.ts
  web/src/views/repo/pipeline/PipelineErrors.vue
Labels: server, enhancement

#2738 Add changelog 1.0.4
  CHANGELOG.md
Labels: skip-changelog

#2740 Fix the wrong link to the cron job document
  web/src/components/repo/settings/CronTab.vue
Labels: documentation

#2749 Fail on missing secrets
  docs/docusaurus.config.ts
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/compiler_test.go
  pipeline/frontend/yaml/compiler/convert.go
Labels: server, enhancement

#2476 Add workflow version
  .woodpecker/binaries.yml
  .woodpecker/docker.yml
  .woodpecker/docs.yml
  .woodpecker/release-helper.yml
  .woodpecker/securityscan.yml
  .woodpecker/test.yml
  .woodpecker/web.yml
  contrib/woodpecker-test-repo/.woodpecker/demo.yml
  contrib/woodpecker-test-repo/.woodpecker/test.yml
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-branches-array.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-branches-exclude-include.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-branches.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-broken.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-clone-skip.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-clone.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-labels.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-matrix.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-merge-map-and-sequence.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-multi.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-pipeline-when.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-platform.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-plugin.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-run-on.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-service.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-step.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-when.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-workspace.yml
  pipeline/frontend/yaml/linter/schema/schema.json
  pipeline/frontend/yaml/parse.go
  pipeline/frontend/yaml/parse_test.go
  pipeline/frontend/yaml/types/workflow.go
  pipeline/frontend/yaml/version.go
  pipeline/stepBuilder_test.go
  shared/constant/constant.go
Labels: enhancement, pipeline-config

#2756 Mark kubernetes backend as fully supported
  docs/docs/30-administration/22-backends/40-kubernetes.md
Labels: documentation, backend/kubernetes

#2735 Migrate pipeline errors using pagination
  server/store/datastore/migration/026_convert_to_new_pipeline_errors_format.go
Labels: bug, regression, build_pr_images

#2772 Fix sidepanel not closable via button
  web/package.json
  web/pnpm-lock.yaml
  web/src/components/layout/header/ActivePipelines.vue
  web/src/components/pipeline-feed/PipelineFeedSidebar.vue
Labels: bug, ui

#2765 Replace linter icons to match theme
  web/components.d.ts
  web/src/components/admin/settings/AdminInfoTab.vue
  web/src/components/atomic/Icon.vue
  web/src/components/atomic/Warning.vue
  web/src/components/layout/scaffold/Tab.vue
  web/src/components/layout/scaffold/Tabs.vue
  web/src/compositions/useTabs.ts
  web/src/views/repo/pipeline/PipelineErrors.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: ui, enhancement

#2778 Fix error color contrast in dark theme
  web/src/components/atomic/Button.vue
  web/src/components/form/RadioField.vue
  web/src/components/repo/settings/ActionsTab.vue
  web/src/views/Login.vue
  web/windi.config.ts
Labels: ui

#2776 Add changelog 1.0.5
  CHANGELOG.md
Labels: skip-changelog

#2785 Fix css loading order in head
  web/index.html
  web/vite.config.ts
Labels: ui

#2777 Add `privileged` schema definition
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-step.yml
  pipeline/frontend/yaml/linter/schema/schema.json
Labels: bug

#2786 Revert to previous red colors but do not use red color for text
  web/components.d.ts
  web/src/components/admin/settings/AdminInfoTab.vue
  web/src/components/atomic/Button.vue
  web/src/components/atomic/Error.vue
  web/src/components/atomic/Icon.vue
  web/src/components/atomic/Warning.vue
  web/src/components/layout/Container.vue
  web/src/components/layout/Settings.vue
  web/src/components/repo/settings/ActionsTab.vue
  web/src/views/Login.vue
  web/src/views/repo/pipeline/Pipeline.vue
  web/windi.config.ts
Labels: ui, regression

#2795 Sort agents list by ID
  server/store/datastore/agent.go
Labels: server, enhancement

#2801 Update release-helper
  .woodpecker/docs.yml
  .woodpecker/release-helper.yml
Labels: dependencies

#2798 Add tests on renovate branches
  .woodpecker/docker.yml
  .woodpecker/docs.yml
  .woodpecker/securityscan.yml
  .woodpecker/test.yml
  .woodpecker/web.yml
Labels: skip-changelog, build

#2799 Update docs npm deps non-major
  docs/package.json
  docs/pnpm-lock.yaml
Labels: documentation, security, dependencies, blocked

#2807 Replace `interface{}` with `any`
  agent/rpc/auth_interceptor.go
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/errors/error.go
  pipeline/frontend/yaml/compiler/cacher.go
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/settings/params.go
  pipeline/frontend/yaml/compiler/settings/params_test.go
  pipeline/frontend/yaml/constraint/constraint.go
  pipeline/frontend/yaml/types/base/int.go
  pipeline/frontend/yaml/types/base/map.go
  pipeline/frontend/yaml/types/base/slice.go
  pipeline/frontend/yaml/types/container.go
  pipeline/frontend/yaml/types/container_test.go
  pipeline/frontend/yaml/types/network.go
  pipeline/frontend/yaml/types/volume.go
  pipeline/rpc/proto/woodpecker.pb.go
  server/forge/bitbucket/internal/client.go
  server/forge/common/status.go
  server/forge/gitea/fixtures/handler.go
  server/forge/github/github.go
  server/forge/mocks/forge.go
  server/grpc/authorizer.go
  server/grpc/jwt_manager.go
  server/plugins/utils/http.go
  server/router/middleware/logger.go
  server/store/context.go
  server/store/datastore/engine_test.go
  server/store/datastore/migration/026_convert_to_new_pipeline_errors_format.go
  server/store/datastore/migration/migration.go
  server/store/datastore/xorm.go
  server/store/mocks/store.go
  server/web/config.go
  shared/token/token.go
  woodpecker-go/woodpecker/client.go
  woodpecker-go/woodpecker/types.go
Labels: refactor

#2817 Fix jq syntax
  .woodpecker/docs.yml
Labels: bug, skip-changelog, build

#2826 Signal to clients the hook and event routes where removed
  server/router/api.go
Labels: enhancement

#2762 Add `prettier` pre-commit hook
  .pre-commit-config.yaml
Labels: skip-changelog, build

#2847 Add extend env plugin
  docs/plugins/woodpecker-plugins/plugins.json
Labels: plugin, documentation

#2850 Fix plugin URLs
  docs/plugins/woodpecker-plugins/plugins.json
Labels: bug, plugin, documentation

#2852 Bump default clone image version to 2.4.0
  shared/constant/constant.go
Labels: enhancement, dependencies

#2856 Cleanup plugins plugins
  docs/plugins/woodpecker-plugins/plugins.json
  docs/plugins/woodpecker-plugins/src/index.ts
  docs/plugins/woodpecker-plugins/src/types.ts
Labels: plugin, documentation, refactor

#2855 Fix repo listing
  server/plugins/permissions/repo_owners.go
Labels: bug, regression

#2857 Add repo owner test
  server/plugins/permissions/repo_owners_test.go
Labels: tests

#2863 Update release-helper
  .woodpecker/release-helper.yml
Labels: build

#2864 Add 2.0.0 post
  docs/blog/2023-07-28-release-v1.0.0/index.md
  docs/blog/2023-11-09-release-v2.0.0/admin_repos.png
  docs/blog/2023-11-09-release-v2.0.0/index.md
  docs/blog/2023-11-09-release-v2.0.0/linter_warnings_errors.png
Labels: documentation

#2823 Changes PullRequest Index to ForgeRemoteID type
  cmd/server/docs/docs.go
  server/forge/bitbucket/bitbucket.go
  server/forge/bitbucket/bitbucket_test.go
  server/forge/gitea/gitea.go
  server/forge/github/github.go
  server/forge/gitlab/gitlab.go
  server/forge/mocks/forge.go
  server/model/pull_request.go
  server/store/mocks/store.go
  web/src/lib/api/types/pull_request.ts
Labels: enhancement, refactor

#2877 Add a blog post
  docs/docs/92-awesome.md
Labels: documentation

#2879 Improve code blocks in docu
  docs/docs/10-intro.md
  docs/docs/20-usage/20-workflow-syntax.md
  docs/docs/20-usage/25-workflows.md
  docs/docs/30-administration/00-deployment/10-docker-compose.md
  docs/docs/30-administration/10-server-config.md
  docs/docs/30-administration/11-forges/30-gitea.md
  docs/docs/30-administration/11-forges/40-gitlab.md
  docs/docs/30-administration/11-forges/50-bitbucket.md
  docs/docs/30-administration/15-agent-config.md
  docs/docs/30-administration/22-backends/20-local.md
  docs/docs/30-administration/30-database.md
  docs/docs/30-administration/60-ssl.md
  docs/docusaurus.config.ts
Labels: documentation

#2881 Add usage with Tunnelmole to docs
  docs/docs/30-administration/70-proxy.md
Labels: documentation

#2892 Only deploy docs on `main`
  .woodpecker/docs.yml
Labels: bug, build

#2893 Add linting for `any`
  .golangci.yml
  server/store/datastore/migration/logger.go
Labels: refactor, tests
