Repository woodpecker-ci/woodpecker, pull requests merged in 2023-10, with the labels that each got.

#2519 Renovate config updates
  .github/renovate.json
  .woodpecker/docker.yml
  .woodpecker/docs.yml
  .woodpecker/release.yml
  .woodpecker/securityscan.yml
  .woodpecker/test.yml
Labels: build

#2525 Fix plugin-ready-release-go version
  .woodpecker/release-helper.yml
Labels: skip-changelog

#2536 Adds bitbucket tag support in docs
  docs/docs/30-administration/11-forges/10-overview.md
  docs/versioned_docs/version-1.0/30-administration/11-forges/10-overview.md
Labels: documentation

#2540 Trim last "/" from WOODPECKER_HOST config (#2538)
  cmd/server/server.go
Labels: bug, server

#2537 Fix gitlab hooks and simplify config extension
  server/forge/configFetcher.go
  server/forge/configFetcher_test.go
  server/forge/gitlab/gitlab.go
  server/forge/gitlab/gitlab_test.go
  server/pipeline/restart.go
  server/plugins/config/extension.go
  server/plugins/config/http.go
Labels: bug, forge/gitlab, refactor, backport

#2541 frontend: bump postcss to 8.4.31
  web/components.d.ts
  web/package.json
  web/pnpm-lock.yaml
Labels: security, dependencies

#2539 Fix PR event trigger and list for bitbucket repos
  server/forge/bitbucket/bitbucket.go
  web/src/views/repo/RepoWrapper.vue
Labels: bug, forge/bitbucket

#2353 Update issue config
  .github/ISSUE_TEMPLATE/config.yml
Labels: governance

#2548 UI cleanups and improvements
  web/components.d.ts
  web/src/assets/locales/en.json
  web/src/components/atomic/Button.vue
  web/src/components/atomic/IconButton.vue
  web/src/components/form/CheckboxesField.vue
  web/src/components/form/SelectField.vue
  web/src/components/form/TextField.vue
  web/src/components/layout/Container.vue
  web/src/components/layout/Panel.vue
  web/src/components/layout/scaffold/Header.vue
  web/src/components/layout/scaffold/Scaffold.vue
  web/src/components/repo/pipeline/PipelineLog.vue
  web/src/compositions/useTabs.ts
  web/src/lib/api/client.ts
  web/src/views/repo/RepoBranches.vue
  web/src/views/repo/pipeline/Pipeline.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: bug, ui

#2555 Move skip-ci back into central place
  pipeline/frontend/yaml/constraint/constraint.go
  server/pipeline/create.go
Labels: bug, regression

#2562 Fix fetch request content type
  web/src/lib/api/client.ts
Labels: bug, regression

#2559 Bump to mysql 8
  .woodpecker/test.yml
  docs/docs/20-usage/30-matrix-workflows.md
  docs/docs/30-administration/30-database.md
Labels: tests, dependencies

#2567 renovate: add `golang` group
  .github/renovate.json
Labels: build

#2580 Fix missing web dist
  .woodpecker/test.yml
Labels: build

#2584 Add plugin "Release helper"
  docs/plugins/woodpecker-plugins/plugins.json
Labels: documentation

#2599 Fix secret priority
  docs/docs/20-usage/40-secrets.md
  server/plugins/secrets/builtin.go
  server/plugins/secrets/builtin_test.go
Labels: bug, backport

#2591 Frontport changelog
  CHANGELOG.md
Labels: skip-changelog

#2603 [doc] improve documentation WOODPECKER_SESSION_EXPIRES
  docs/docs/30-administration/10-server-config.md
  docs/versioned_docs/version-0.15/30-administration/10-server-config.md
  docs/versioned_docs/version-1.0/30-administration/10-server-config.md
Labels: documentation

#2608 Only publish PR images when label is set
  .woodpecker/docker.yml
Labels: build, build_pr_images

#2616 docs add nixos install instructions
  docs/docs/30-administration/00-setup.md
  docs/docs/30-administration/22-backends/50-nixos.md
Labels: documentation

#2627 Fix `CI_WORKSPACE` in local backend
  pipeline/backend/local/clone.go
  pipeline/backend/local/const.go
  pipeline/backend/local/local.go
Labels: bug, backend/local

#2626 Do not run docker prepare steps
  .woodpecker/docker.yml
Labels: build

#2617 doc: improve prometheus docs
  docs/docs/30-administration/90-prometheus.md
Labels: documentation

#2630 Rework setup docs
  docs/docs/10-intro.md
  docs/docs/30-administration/00-deployment/00-overview.md
  docs/docs/30-administration/00-deployment/10-docker-compose.md
  docs/docs/30-administration/00-deployment/20-kubernetes.md
  docs/docs/30-administration/00-deployment/30-nixos.md
  docs/docs/30-administration/00-deployment/_category_.yml
  docs/docs/30-administration/00-setup.md
  docs/docs/30-administration/20-migrate-from-drone.md
  docs/docs/80-downloads.md
  docs/docs/91-migrations.md
  docs/src/pages/faq.md
Labels: documentation

#2631 Add autoscaler docs
  docs/docs/30-administration/80-autoscaler.md
Labels: documentation

#2635 Remove SSH backend
  cli/exec/exec.go
  cmd/agent/main.go
  docs/docs/30-administration/15-agent-config.md
  docs/docs/30-administration/22-backends/30-ssh.md
  docs/docs/91-migrations.md
  go.mod
  go.sum
  pipeline/backend/backend.go
  pipeline/backend/ssh/flags.go
  pipeline/backend/ssh/ssh.go
Labels: breaking, backend/ssh

#2642 Add "Repair all" button
  cmd/server/docs/docs.go
  server/api/repo.go
  server/router/api.go
  web/src/assets/locales/en.json
  web/src/components/admin/settings/AdminReposTab.vue
  web/src/lib/api/index.ts
Labels: enhancement

#2643 Fix codecov plugin version
  .woodpecker/test.yml
Labels: build

#2639 Remove deprecated API paths
  cmd/server/docs/docs.go
  docs/docs/91-migrations.md
  server/api/pipeline.go
  server/api/stream.go
  server/router/api.go
Labels: server, refactor, breaking

#2644 Bump codecov version to fix build
  .woodpecker/test.yml
Labels: build

#2213 Remove plugin-only option from secrets
  cli/secret/secret_add.go
  cli/secret/secret_set.go
  cmd/server/docs/docs.go
  docs/docs/20-usage/40-secrets.md
  docs/docs/91-migrations.md
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/compiler_test.go
  pipeline/stepBuilder.go
  server/api/global_secret.go
  server/api/org_secret.go
  server/api/repo_secret.go
  server/model/secret.go
  server/store/datastore/migration/025_remove_secrets_plugin_only_col.go
  server/store/datastore/migration/migration.go
  web/src/components/secrets/SecretEdit.vue
  web/src/components/secrets/SecretList.vue
  web/src/lib/api/types/secret.ts
  woodpecker-go/woodpecker/types.go
Labels: breaking, security, ux

#2647 Remove `WOODPECKER_DOCS` config
  cmd/server/flags.go
  cmd/server/server.go
  docs/docs/30-administration/10-server-config.md
  docs/docs/91-migrations.md
  server/config.go
  server/web/config.go
  web/src/components/atomic/DocsLink.vue
  web/src/components/layout/header/Navbar.vue
  web/src/compositions/useConfig.ts
Labels: refactor, breaking

#2652 Add some tests
  cmd/server/docs/docs.go
  pipeline/backend/kubernetes/service_test.go
  pipeline/backend/kubernetes/volume_test.go
  pipeline/backend/local/const_test.go
  pipeline/frontend/yaml/types/base/base_types_test.go
  pipeline/frontend/yaml/types/network_test.go
  pipeline/frontend/yaml/types/volume_test.go
  pipeline/rpc/proto/woodpecker.pb.go
  pipeline/rpc/proto/woodpecker_grpc.pb.go
  server/api/hook.go
  server/api/repo.go
  server/badges/badges_test.go
  server/forge/github/parse.go
  server/forge/mocks/forge.go
  server/forge/types/meta_test.go
  server/model/step.go
  server/model/step_test.go
  server/plugins/encryption/aes_test.go
  server/store/datastore/agent_test.go
  server/store/datastore/helper_test.go
  server/store/datastore/server_config.go
  server/store/datastore/server_config_test.go
  server/store/datastore/step.go
  server/store/datastore/step_test.go
  server/store/mocks/store.go
  server/store/store.go
Labels: tests

#2636 local backend ignore errors in commands inbetween
  go.mod
  pipeline/backend/common/script.go
  pipeline/backend/common/script_posix.go
  pipeline/backend/common/script_posix_test.go
  pipeline/backend/local/command.go
  pipeline/backend/local/local.go
Labels: bug, backend/local

#2669 `pre-commit` fixes
  .pre-commit-config.yaml
  .woodpecker/securityscan.yml
  CHANGELOG.md
  Makefile
  README.md
  SECURITY.md
  cli/README.md
  docs/README.md
  docs/blog/2023-06-11-hello-blog/index.md
  docs/blog/2023-07-28-release-v1.0.0/index.md
  docs/docs/20-usage/10-intro.md
  docs/docs/20-usage/15-terminiology/architecture.svg
  docs/docs/20-usage/15-terminiology/pipeline-workflow-step.svg
  docs/docs/20-usage/20-workflow-syntax.md
  docs/docs/30-administration/00-deployment/00-overview.md
  docs/docs/30-administration/10-server-config.md
  docs/docs/30-administration/11-forges/20-github.md
  docs/docs/30-administration/40-encryption.md
  docs/docs/30-administration/90-prometheus.md
  docs/docs/92-development/01-getting-started.md
  docs/docs/92-development/03-ui.md
  docs/docs/92-development/08-swagger.md
  docs/docs/92-development/09-security.md
  docs/docs/92-development/ui-proxy.svg
  docs/versioned_docs/version-0.15/20-usage/22-conditional-execution.md
  docs/versioned_docs/version-0.15/20-usage/40-secrets.md
  docs/versioned_docs/version-0.15/20-usage/71-project-settings.md
  docs/versioned_docs/version-0.15/30-administration/15-agent-config.md
  docs/versioned_docs/version-0.15/30-administration/80-kubernetes.md
  docs/versioned_docs/version-0.15/92-development/ui-proxy.svg
  docs/versioned_docs/version-1.0/20-usage/71-project-settings.md
  docs/versioned_docs/version-1.0/30-administration/10-server-config.md
  docs/versioned_docs/version-1.0/30-administration/22-backends/20-local.md
  docs/versioned_docs/version-1.0/30-administration/40-encryption.md
  docs/versioned_docs/version-1.0/40-cli.md
  docs/versioned_docs/version-1.0/92-development/03-ui.md
  docs/versioned_docs/version-1.0/92-development/09-security.md
  docs/versioned_docs/version-1.0/92-development/ui-proxy.svg
  pipeline/samples/sample_1/README.md
  pipeline/samples/sample_10_windows/README.md
  pipeline/samples/sample_8_network_mode/README.md
  web/public/favicons/favicon-dark-error.svg
  web/public/favicons/favicon-dark-pending.svg
  web/public/favicons/favicon-dark-success.svg
  web/public/favicons/favicon-light-default.svg
  web/public/favicons/favicon-light-error.svg
  web/public/favicons/favicon-light-pending.svg
  web/public/favicons/favicon-light-success.svg
  woodpecker-go/LICENSE
Labels: skip-changelog

#2676 Fix where syntax
  server/store/datastore/server_config.go
Labels: refactor

#2668 Pin `trivy` docker image version
  .woodpecker/securityscan.yml
Labels: skip-changelog, build

#2674 Fix secret image filter regex
  server/model/secret.go
  server/model/secret_test.go
Labels: bug, backport

#2680 Do not sanitzie secrets with 3 or less chars
  pipeline/shared/replace_secrets.go
  pipeline/shared/replace_secrets_test.go
Labels: enhancement, breaking, security

#2683 Fix docker preview images
  .woodpecker/docker.yml
Labels: skip-changelog, build
