Repository woodpecker-ci/woodpecker, pull requests merged in 2023-12, with the labels that each got.

#2891 Unify date/time dependencies
  web/.gitignore
  web/package.json
  web/pnpm-lock.yaml
  web/src/components/admin/settings/AdminAgentsTab.vue
  web/src/components/repo/pipeline/PipelineStepDuration.vue
  web/src/components/user/UserGeneralTab.vue
  web/src/compositions/useDate.ts
  web/src/compositions/useI18n.ts
  web/src/compositions/usePipeline.ts
  web/src/compositions/useTimeAgo.ts
  web/src/utils/duration.ts
  web/vite.config.ts
Labels: ui, refactor, dependencies

#2920 Fix schema validation with array syntax for clone and services
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-array-syntax.yml
  pipeline/frontend/yaml/linter/schema/schema.json
  pipeline/frontend/yaml/linter/schema/schema_test.go
Labels: bug

#2914 Fix flags added multiple times
  cli/cron/cron.go
  cli/cron/cron_add.go
  cli/cron/cron_info.go
  cli/cron/cron_list.go
  cli/cron/cron_rm.go
  cli/cron/cron_update.go
  cli/deploy/deploy.go
  cli/exec/exec.go
  cli/info/info.go
  cli/lint/lint.go
  cli/log/log.go
  cli/log/log_purge.go
  cli/loglevel/loglevel.go
  cli/pipeline/approve.go
  cli/pipeline/create.go
  cli/pipeline/decline.go
  cli/pipeline/info.go
  cli/pipeline/kill.go
  cli/pipeline/last.go
  cli/pipeline/list.go
  cli/pipeline/logs.go
  cli/pipeline/pipeline.go
  cli/pipeline/ps.go
  cli/pipeline/queue.go
  cli/pipeline/start.go
  cli/pipeline/stop.go
  cli/registry/registry.go
  cli/registry/registry_add.go
  cli/registry/registry_info.go
  cli/registry/registry_list.go
  cli/registry/registry_rm.go
  cli/registry/registry_set.go
  cli/repo/repo.go
  cli/repo/repo_add.go
  cli/repo/repo_chown.go
  cli/repo/repo_info.go
  cli/repo/repo_list.go
  cli/repo/repo_repair.go
  cli/repo/repo_rm.go
  cli/repo/repo_sync.go
  cli/repo/repo_update.go
  cli/secret/secret.go
  cli/secret/secret_add.go
  cli/secret/secret_info.go
  cli/secret/secret_list.go
  cli/secret/secret_rm.go
  cli/secret/secret_set.go
  cli/user/user.go
  cli/user/user_add.go
  cli/user/user_info.go
  cli/user/user_list.go
  cli/user/user_rm.go
Labels: bug, cli

#2934 init CI_COMMIT_TAG if commit ref is a tag
  pipeline/frontend/metadata/environment.go
Labels: enhancement

#2923 Fix skipped pipelines model
  cmd/server/docs/docs.go
  server/forge/mocks/forge.go
  server/model/const.go
  server/pipeline/create.go
  server/store/datastore/pipeline.go
  server/store/datastore/repo.go
  server/store/mocks/store.go
  server/store/store.go
Labels: bug

#2950 Rename `engine` to `backend`
  agent/runner.go
  cli/exec/exec.go
  cmd/agent/agent.go
  cmd/agent/flags.go
  pipeline/backend/backend.go
  pipeline/backend/docker/docker.go
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/local/local.go
  pipeline/backend/types/backend.go
  pipeline/backend/types/engine.go
  pipeline/option.go
  pipeline/pipeline.go
Labels: refactor

#2873 Show secrets from org and global level
  cmd/server/docs/docs.go
  server/model/secret.go
  server/plugins/secrets/builtin.go
  server/plugins/secrets/builtin_test.go
  server/store/datastore/secret_test.go
  web/src/assets/locales/en.json
  web/src/components/atomic/Button.vue
  web/src/components/repo/settings/SecretsTab.vue
  web/src/components/secrets/SecretEdit.vue
  web/src/components/secrets/SecretList.vue
  web/src/compositions/usePaginate.ts
  web/src/lib/api/types/secret.ts
  woodpecker-go/woodpecker/types.go
Labels: ui, enhancement

#2957 Fix error container overflow
  web/src/components/repo/pipeline/PipelineLog.vue
  web/src/components/repo/pipeline/PipelineStepList.vue
  web/src/views/repo/pipeline/Pipeline.vue
Labels: bug, ui

#2935 Export changed files via builtin environment variables
  docs/docs/20-usage/50-environment.md
  docs/versioned_docs/version-2.0/20-usage/50-environment.md
  pipeline/frontend/metadata/environment.go
  pipeline/frontend/metadata_test.go
Labels: server, enhancement

#2964 Update pronoun in documentation
  docs/docs/20-usage/71-project-settings.md
Labels: documentation, skip-changelog

#2933 feat(k8s): Add a port name to service definition
  pipeline/backend/kubernetes/service.go
  pipeline/backend/kubernetes/service_test.go
Labels: bug, backend/kubernetes

#2966 update golang.org/x/crypto v0.16.0 => v0.17.0
  go.mod
  go.sum
Labels: security, dependencies

#2794 Kubernetes refactor
  go.mod
  go.sum
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/kubernetes/pod_test.go
  pipeline/backend/kubernetes/service.go
  pipeline/backend/kubernetes/service_test.go
  pipeline/backend/kubernetes/utils.go
  pipeline/backend/kubernetes/volume.go
  pipeline/backend/kubernetes/volume_test.go
Labels: refactor, backend/kubernetes

#2783 Update pipeline icons
  web/src/components/atomic/Icon.vue
  web/src/components/repo/pipeline/PipelineStatusIcon.vue
  web/src/components/repo/pipeline/pipeline-status.ts
Labels: ui, enhancement

#2968 Add check for storage where repo/org name is empty
  server/store/datastore/org.go
  server/store/datastore/org_test.go
  server/store/datastore/repo.go
  server/store/datastore/repo_test.go
Labels: server, enhancement

#2965 Improve error handling when activating a repository
  server/api/repo.go
Labels: server, enhancement

#2967 Gitea driver: ignore GetOrg error if we get a valid user.
  server/forge/gitea/gitea.go
Labels: bug, forge/gitea

#2962 Update slogan & logo
  README.md
  cmd/server/swagger.go
  docs/docs/10-intro.md
  docs/docusaurus.config.ts
  docs/src/pages/index.tsx
  docs/static/img/logo.svg
  server/forge/github/fixtures/hooks.go
Labels: documentation, enhancement

#2936 RegisterAgent with hostname
  server/grpc/rpc.go
  server/grpc/rpc_test.go
Labels: server, enhancement

#2973 Fix go in gitpod
  .gitpod.yml
Labels: devx

#2974 Link labels to input and select
  web/src/components/admin/settings/AdminAgentsTab.vue
  web/src/components/admin/settings/AdminUsersTab.vue
  web/src/components/form/InputField.vue
  web/src/components/layout/popups/DeployPipelinePopup.vue
  web/src/components/layout/popups/ManualPipelinePopup.vue
  web/src/components/layout/scaffold/Header.vue
  web/src/components/repo/settings/BadgeTab.vue
  web/src/components/repo/settings/CronTab.vue
  web/src/components/repo/settings/GeneralTab.vue
  web/src/components/repo/settings/RegistriesTab.vue
  web/src/components/secrets/SecretEdit.vue
  web/src/components/user/UserGeneralTab.vue
Labels: ui

#2975 Fix static file caching
  server/web/web.go
Labels: bug, server

#2751 Support go plugins for forges and agent backends
  cmd/agent/agent.go
  cmd/agent/flags.go
  cmd/server/flags.go
  cmd/server/setup.go
  docs/docs/30-administration/10-server-config.md
  docs/docs/30-administration/15-agent-config.md
  docs/docs/30-administration/75-addons/00-overview.md
  docs/docs/30-administration/75-addons/20-creating-addons.md
  docs/docs/30-administration/75-addons/_category_.yml
  shared/addon/addon.go
  shared/addon/types/types.go
Labels: feature

#2981 gitlab: support nested repos
  server/forge/gitlab/gitlab.go
Labels: forge/gitlab, feature

#2949 Ignore pipelines without config
  docs/docs/91-migrations.md
  server/api/helper.go
  server/forge/configFetcher.go
  server/forge/gitea/gitea.go
  server/forge/github/github.go
  server/forge/gitlab/gitlab.go
  server/forge/types/errors.go
  server/pipeline/create.go
Labels: server, enhancement

#2986 Switch to ULID
  go.mod
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/pipeline.go
Labels: enhancement, dependencies

#2990 Replace multi-pipelines with workflows on docs frontpage
  docs/src/components/HomepageFeatures.js
  docs/static/img/workflows.svg
Labels: documentation

#2995 Fix cli lint throwing error on warnings
  cli/lint/lint.go
  pipeline/backend/docker/docker.go
Labels: bug

#2996 fix(deps): update docs npm deps non-major
  docs/package.json
  docs/pnpm-lock.yaml
Labels: documentation, skip-changelog, dependencies

#2997 chore(deps): update web npm deps non-major
  web/package.json
  web/pnpm-lock.yaml
Labels: ui, skip-changelog, dependencies

#2999 chore(deps): update golang packages
  go.mod
  go.sum
Labels: skip-changelog, dependencies

#3000 Fix gitlab project fetching
  server/forge/gitlab/gitlab.go
Labels: server, forge/gitlab, regression

#3002 Add cookbook blog and improve docs
  docs/cookbook/2023-12-23-hello-cookbook/index.md
  docs/docs/10-intro.md
  docs/docs/92-development/06-guides.md
  docs/docs/92-development/08-swagger.md
  docs/docs/92-development/09-security.md
  docs/docusaurus.config.ts
  docs/package.json
  docs/pnpm-lock.yaml
Labels: documentation

#3004 Hide PR tab if PRs are disabled
  cmd/server/docs/docs.go
  pipeline/rpc/proto/woodpecker.pb.go
  pipeline/rpc/proto/woodpecker_grpc.pb.go
  server/forge/bitbucket/bitbucket.go
  server/forge/bitbucket/convert.go
  server/forge/gitea/helper.go
  server/forge/github/convert.go
  server/forge/gitlab/convert.go
  server/forge/mocks/forge.go
  server/model/repo.go
  server/store/mocks/store.go
  web/components.d.ts
  web/src/lib/api/types/repo.ts
  web/src/views/repo/RepoPullRequest.vue
  web/src/views/repo/RepoPullRequests.vue
  web/src/views/repo/RepoWrapper.vue
Labels: enhancement

#2771 Add depends_on support for steps
  cli/lint/lint.go
  docs/docs/20-usage/20-workflow-syntax.md
  docs/docs/91-migrations.md
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/compiler_test.go
  pipeline/frontend/yaml/compiler/dag.go
  pipeline/frontend/yaml/compiler/dag_test.go
  pipeline/frontend/yaml/compiler/errors.go
  pipeline/frontend/yaml/linter/linter.go
  pipeline/frontend/yaml/linter/schema/schema.json
  pipeline/frontend/yaml/types/container.go
  server/grpc/rpc.go
Labels: feature, pipeline-config

#3007 fix and lint swagger file
  Makefile
  cmd/server/docs/docs.go
  cmd/server/swagger.go
  cmd/server/woodpecker_docs_gen.go
  server/api/agent.go
  server/api/badge.go
  server/api/cron.go
  server/api/global_secret.go
  server/api/hook.go
  server/api/org_secret.go
  server/api/orgs.go
  server/api/pipeline.go
  server/api/registry.go
  server/api/repo.go
  server/api/repo_secret.go
  server/api/stream.go
  server/api/user.go
  server/api/users.go
Labels: bug, documentation

#3019 Show default branch on top
  web/src/views/repo/RepoBranches.vue
Labels: ui, enhancement

#3017 Correct http cache headers for firefox
  server/api/stream.go
  server/web/web.go
Labels: bug, server, regression

#3022 Document `WOODPECKER_LOG_FILE`
  cmd/common/logger.go
  docs/docs/30-administration/10-server-config.md
  docs/versioned_docs/version-2.0/30-administration/10-server-config.md
Labels: documentation, skip-changelog

#2684 Add pull request closed event
  cmd/server/docs/docs.go
  docs/docs/20-usage/15-terminiology/index.md
  docs/docs/20-usage/20-workflow-syntax.md
  docs/docs/20-usage/50-environment.md
  pipeline/frontend/metadata/const.go
  pipeline/frontend/yaml/linter/schema/schema.json
  server/forge/bitbucket/convert.go
  server/forge/bitbucket/fixtures/hooks.go
  server/forge/bitbucket/parse.go
  server/forge/bitbucket/parse_test.go
  server/forge/gitea/fixtures/hooks.go
  server/forge/gitea/helper.go
  server/forge/gitea/helper_test.go
  server/forge/gitea/parse.go
  server/forge/gitea/parse_test.go
  server/forge/github/fixtures/hooks.go
  server/forge/github/parse.go
  server/forge/github/parse_test.go
  server/forge/gitlab/convert.go
  server/forge/gitlab/gitlab_test.go
  server/forge/gitlab/testdata/hooks.go
  server/model/const.go
  web/src/components/atomic/Icon.vue
  web/src/components/repo/pipeline/PipelineItem.vue
  web/src/components/repo/pipeline/PipelineStepList.vue
  web/src/compositions/usePipeline.ts
  web/src/lib/api/types/webhook.ts
  web/src/views/repo/RepoBranch.vue
  web/src/views/repo/RepoPullRequest.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
  woodpecker-go/woodpecker/const.go
Labels: feature

#3024 readme: update go reference badge
  README.md
Labels: documentation, skip-changelog

#3031 Fix go report badge
  README.md
Labels: documentation, skip-changelog, regression

#3030 Add some tests
  cmd/server/swagger_test.go
  pipeline/backend/common/script_test.go
  server/plugins/environments/parse.go
  server/plugins/environments/parse_test.go
  server/plugins/permissions/admins.go
  server/plugins/permissions/admins_test.go
  server/plugins/permissions/orgs_test.go
  shared/utils/slices.go
  shared/utils/slices_test.go
Labels: tests

#3033 Fix Wrong badgeUrl repo badge tab when rootPath is not empty
  web/src/components/repo/settings/BadgeTab.vue
Labels: bug, ui

#3037 make backend step dag generation deterministic
  pipeline/frontend/yaml/compiler/dag.go
  web/components.d.ts
Labels: enhancement

#3026 Add build option to Makefile for removing static compile flags
  Makefile
Labels: skip-changelog, build

#3039 trim v on version check
  web/src/compositions/useVersion.ts
Labels: bug, ui

#3040 Add option to disable version check in admin web UI
  cmd/server/flags.go
  cmd/server/server.go
  docs/docs/30-administration/10-server-config.md
  server/config.go
  server/router/router.go
  server/web/config.go
  web/src/compositions/useConfig.ts
  web/src/compositions/useVersion.ts
Labels: ui, enhancement

#3049 Fix DAG cycle detection
  pipeline/frontend/yaml/compiler/dag.go
  pipeline/frontend/yaml/compiler/dag_test.go
Labels: bug, server

#3052 Revert "Add workflow version"
  .woodpecker/binaries.yml
  .woodpecker/docker.yml
  .woodpecker/docs.yml
  .woodpecker/release-helper.yml
  .woodpecker/securityscan.yml
  .woodpecker/test.yml
  .woodpecker/web.yml
  contrib/woodpecker-test-repo/.woodpecker/demo.yml
  contrib/woodpecker-test-repo/.woodpecker/test.yml
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-branches-array.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-branches-exclude-include.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-branches.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-broken.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-clone-skip.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-clone.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-labels.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-matrix.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-merge-map-and-sequence.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-multi.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-pipeline-when.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-platform.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-plugin.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-run-on.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-service.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-step.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-when.yml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-workspace.yml
  pipeline/frontend/yaml/parse.go
  pipeline/frontend/yaml/parse_test.go
  pipeline/frontend/yaml/types/workflow.go
  pipeline/frontend/yaml/version.go
  pipeline/stepBuilder_test.go
  shared/constant/constant.go
Labels: refactor

#3063 Fix `when` and `depends_on`
  .woodpecker/test.yml
Labels: bug, build

#3065 Fix build output paths
  Makefile
  docker/Dockerfile.server.alpine.multiarch
  docker/Dockerfile.server.multiarch
Labels: bug, server, build, build_pr_images

#3056 Add imports checks to linter
  .golangci.yml
  Makefile
  cli/exec/exec.go
  pipeline/frontend/metadata/subsitution.go
  pipeline/frontend/metadata/subsitution_test.go
  pipeline/frontend/yaml/constraint/constraint_test.go
  server/pipeline/config.go
  server/pipeline/items.go
  server/pipeline/items_test.go
  server/pipeline/queue.go
  server/pipeline/start.go
  server/pipeline/stepbuilder/metadata.go
  server/pipeline/stepbuilder/metadata_test.go
  server/pipeline/stepbuilder/stepBuilder.go
  server/pipeline/stepbuilder/stepBuilder_test.go
Labels: refactor, tests

#3072 Fix `make release-server-xgo` in CI and localy
  .woodpecker/docker.yml
  Makefile
Labels: build, regression

#3067 Load changed files for closed PR
  server/forge/gitea/gitea.go
Labels: bug, forge/gitea

#3078 Indicate if step is service
  web/src/components/repo/pipeline/PipelineStatusIcon.vue
  web/src/components/repo/pipeline/PipelineStepList.vue
  web/src/components/repo/pipeline/pipeline-status.ts
Labels: ui, enhancement

#3077 Remove old files
  .changelog.yml
  .prettierignore
  .prettierrc.json
  docs/.prettierrc.js
  pipeline/samples/sample_1/.env
  pipeline/samples/sample_1/README.md
  pipeline/samples/sample_1/pipeline.json
  pipeline/samples/sample_1/pipeline.yml
  pipeline/samples/sample_10_windows/.env
  pipeline/samples/sample_10_windows/README.md
  pipeline/samples/sample_10_windows/pipeline.json
  pipeline/samples/sample_10_windows/pipeline.yml
  pipeline/samples/sample_2/.env
  pipeline/samples/sample_2/pipeline.json
  pipeline/samples/sample_2/pipeline.yml
  pipeline/samples/sample_3/.env
  pipeline/samples/sample_3/pipeline.json
  pipeline/samples/sample_3/pipeline.yml
  pipeline/samples/sample_4/.env
  pipeline/samples/sample_4/pipeline.json
  pipeline/samples/sample_4/pipeline.yml
  pipeline/samples/sample_5/.env
  pipeline/samples/sample_5/pipeline.json
  pipeline/samples/sample_5/pipeline.yml
  pipeline/samples/sample_6/.env
  pipeline/samples/sample_6/pipeline.json
  pipeline/samples/sample_6/pipeline.yml
  pipeline/samples/sample_7_redis/pipeline.json
  pipeline/samples/sample_7_redis/pipeline.yml
  pipeline/samples/sample_8_network_mode/README.md
  pipeline/samples/sample_8_network_mode/pipeline.json
  pipeline/samples/sample_8_network_mode/pipeline.yml
  pipeline/samples/sample_8_postgres/pipeline.yml
  pipeline/samples/sample_9_cache/.env
  pipeline/samples/sample_9_cache/pipeline.json
  pipeline/samples/sample_9_cache/pipeline.yml
  web/.prettierrc.js
Labels: refactor

#3083 add just more dag tests
  pipeline/frontend/yaml/compiler/dag_test.go
Labels: tests, skip-changelog

#3062 Extend create plugin docs
  docs/docs/20-usage/40-secrets.md
  docs/docs/20-usage/51-plugins/10-plugins.md
  docs/docs/20-usage/51-plugins/20-creating-plugins.md
  docs/docs/20-usage/51-plugins/20-sample-plugin.md
Labels: documentation, enhancement

#3042 use semver for version comparsion
  web/package.json
  web/pnpm-lock.yaml
  web/src/compositions/useVersion.ts
Labels: ui, enhancement

#3084 Allow PR secrets to be used on close
  server/model/secret.go
  server/model/secret_test.go
Labels: bug, server

#3089 make sure cross-compile-server does not run with other compile steps
  .woodpecker/docker.yml
Labels: build

#3092 Move `cmd/common` to `shared`
  .golangci.yml
  cli/common/flags.go
  cli/common/zerologger.go
  cmd/agent/agent.go
  cmd/agent/main.go
  cmd/server/flags.go
  cmd/server/server.go
  shared/logger/logger.go
  shared/logger/terminal.go
Labels: refactor
