Repository woodpecker-ci/woodpecker, pull requests merged in 2023-03, with the labels that each got.

#1598 Update when-path for Gitea
  docs/docs/20-usage/20-pipeline-syntax.md
Labels: documentation

#1600 Return 404 on badge endpoint for inactive repos
  server/api/badge.go
Labels: bug

#1601 feat: add collapsable support to panel elements
  web/src/components/layout/Panel.vue
  web/src/views/repo/pipeline/PipelineConfig.vue
Labels: ui, enhancement

#1597 docs: add note about image cleanup
  docs/docs/30-administration/22-backends/10-docker.md
Labels: documentation

#1612 Update dependencies golang/x libs
  go.mod
  go.sum
Labels: security, dependencies

#1610 Persist `DepStatus` of tasks
  server/model/task.go
  server/queue/persistent.go
  server/store/datastore/task_test.go
Labels: bug

#1616 fix: docker backend should not close 'engine.Tail' result
  pipeline/backend/docker/docker.go
Labels: bug, cli

#1603 fix: apply permissions when flatPermissions enabled
  server/forge/userSyncer.go
Labels: bug, skip-changelog

#1596 docs: update docs to include plugin repositories
  docs/docs/20-usage/51-plugins/10-plugins.md
Labels: documentation

#1620 fix: docker backend should not close 'engine.Tail' result (#1616)
  pipeline/backend/docker/docker.go
Labels: bug, cli

#1622 Changelog v0.15.7
  CHANGELOG.md
Labels: documentation, skip-changelog

#1623 Changelog v0.15.7 (#1622)
  CHANGELOG.md
Labels: documentation, skip-changelog

#1627 Return 404 if pipeline not exist and handle 404 errors in WebUI
  server/api/pipeline.go
  web/src/App.vue
  web/src/assets/locales/en.json
Labels: server, enhancement

#1321 Add pull request labels as environment variable
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/20-usage/50-environment.md
  pipeline/frontend/metadata.go
  pipeline/stepBuilder.go
  server/forge/gitea/helper.go
  server/forge/github/convert.go
  server/forge/github/parse.go
  server/forge/gitlab/convert.go
  server/model/pipeline.go
Labels: enhancement

#1626 pipeline compiler: handle nil entrys in settings list
  pipeline/frontend/yaml/compiler/settings/params.go
  pipeline/frontend/yaml/compiler/settings/params_test.go
Labels: bug, server

#1639 Correct pipeline loading
  web/src/store/pipelines.ts
Labels: bug, ui, skip-changelog

#1642 Fix button margin if button doesn't have text
  web/components.d.ts
  web/src/components/atomic/Button.vue
Labels: ui, enhancement

#1634 Add users UI for admins
  server/api/login.go
  server/api/users.go
  server/model/user.go
  server/router/middleware/session/user.go
  server/store/datastore/migration/014_remove_active_from_users.go
  server/store/datastore/migration/migration.go
  server/store/datastore/users_test.go
  web/components.d.ts
  web/src/assets/locales/en.json
  web/src/components/admin/settings/AdminUsersTab.vue
  web/src/components/atomic/Badge.vue
  web/src/components/secrets/SecretEdit.vue
  web/src/lib/api/index.ts
  web/src/views/admin/AdminSettings.vue
Labels: ui, feature

#1640 UI improvements
  web/src/components/layout/popups/DeployPipelinePopup.vue
  web/src/components/layout/scaffold/Header.vue
  web/src/components/repo/pipeline/PipelineStepList.vue
  web/src/lib/api/index.ts
  web/src/store/pipelines.ts
  web/src/views/repo/RepoBranch.vue
  web/src/views/repo/pipeline/Pipeline.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: ui, enhancement

#1646 Only grant privileged to plugins
  pipeline/frontend/yaml/compiler/convert.go
Labels: enhancement, security

#1641 Add PR pipeline list
  pipeline/rpc/proto/woodpecker.pb.go
  pipeline/rpc/proto/woodpecker_grpc.pb.go
  server/api/repo.go
  server/forge/bitbucket/bitbucket.go
  server/forge/bitbucketserver/bitbucketserver.go
  server/forge/forge.go
  server/forge/gitea/gitea.go
  server/forge/github/github.go
  server/forge/gitlab/gitlab.go
  server/forge/gogs/gogs.go
  server/forge/mocks/forge.go
  server/model/pagination.go
  server/model/pull_request.go
  server/router/api.go
  server/router/middleware/session/pagination.go
  server/store/mocks/store.go
  web/components.d.ts
  web/src/assets/locales/en.json
  web/src/lib/api/index.ts
  web/src/lib/api/types/index.ts
  web/src/lib/api/types/pull_request.ts
  web/src/router.ts
  web/src/views/repo/RepoPullRequest.vue
  web/src/views/repo/RepoPullRequests.vue
  web/src/views/repo/RepoWrapper.vue
Labels: enhancement

#1655 Update frontend dependencies
  web/components.d.ts
  web/package.json
  web/pnpm-lock.yaml
  web/src/components/admin/settings/AdminUsersTab.vue
  web/vite.config.ts
Labels: ui, dependencies

#1632 Add queue details UI for admins
  docs/docs/91-migrations.md
  server/grpc/filter.go
  server/grpc/filter_test.go
  server/model/task.go
  server/pipeline/queue.go
  server/queue/fifo.go
  server/queue/fifo_test.go
  server/queue/persistent.go
  server/queue/queue.go
  server/router/api.go
  server/store/datastore/task_test.go
  web/components.d.ts
  web/src/assets/locales/en.json
  web/src/components/admin/settings/AdminQueueTab.vue
  web/src/components/atomic/Icon.vue
  web/src/lib/api/index.ts
  web/src/lib/api/types/index.ts
  web/src/lib/api/types/queue.ts
  web/src/views/admin/AdminSettings.vue
Labels: ui, feature, breaking

#1657 Implement visual display of queue statistics
  web/components.d.ts
  web/package.json
  web/pnpm-lock.yaml
  web/src/assets/locales/en.json
  web/src/components/admin/settings/AdminQueueTab.vue
  web/src/components/admin/settings/queue/AdminQueueStats.vue
  web/src/lib/api/types/queue.ts
Labels: ui, enhancement

#1352 Only inject netrc to trusted clone plugins
  cmd/server/server.go
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/option.go
  pipeline/frontend/yaml/container.go
  pipeline/stepBuilder.go
  server/api/repo.go
  server/model/repo.go
  shared/constant/constant.go
  web/src/assets/locales/en.json
  web/src/components/repo/settings/GeneralTab.vue
  web/src/lib/api/types/repo.ts
Labels: security

#1650 Update Go dependencies and minimal Go version to 1.20
  .golangci.yml
  .woodpecker/binaries.yml
  .woodpecker/docker.yml
  .woodpecker/docs.yml
  .woodpecker/test.yml
  Makefile
  cmd/server/server.go
  docker/Dockerfile.agent.alpine.multiarch
  docker/Dockerfile.agent.multiarch
  docker/Dockerfile.cli.alpine.multiarch
  docker/Dockerfile.cli.multiarch
  docker/Dockerfile.make
  docker/Dockerfile.server.multiarch
  docs/docs/92-development/01-getting-started.md
  go.mod
  go.sum
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/kubernetes/utils.go
  pipeline/frontend/yaml/constraint/constraint.go
  pipeline/stepBuilder.go
  server/api/hook.go
  server/api/stream.go
  server/forge/gitlab/convert.go
  server/logging/log_test.go
  server/plugins/utils/http_test.go
  server/pubsub/pub_test.go
  server/web/web.go
  shared/utils/context.go
  web/web.go
Labels: dependencies

#1661 fix(backend/kubernetes): Ensure valid naming of name field
  .woodpecker/test.yml
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/kubernetes/service.go
  pipeline/backend/kubernetes/utils.go
  pipeline/backend/kubernetes/volume.go
  pipeline/backend/kubernetes/volume_test.go
  pipeline/stepBuilder.go
Labels: bug, backend/kubernetes

#1676 web: use i18n-t to avoid v-html directive
  web/src/assets/locales/en.json
  web/src/components/repo/settings/GeneralTab.vue
Labels: ui
