Repository woodpecker-ci/woodpecker, pull requests merged in 2023-09, with the labels that each got.

#2363 clarify setup with gitlab with RFC1918 nets and non standard TLDs
  docs/docs/30-administration/11-forges/40-gitlab.md
Labels: documentation, forge/gitlab

#2372 fix(server/api/repo): Fix repair webhook host
  server/api/repo.go
Labels: bug

#1976 Add release helper
  .woodpecker/release.yml
  release-config.ts
Labels: build

#2325 close sidebar on outside click
  web/package.json
  web/pnpm-lock.yaml
  web/src/components/pipeline-feed/PipelineFeedSidebar.vue
  web/src/compositions/usePipelineFeed.ts
Labels: ui, enhancement, ux

#2347 Add repos list for admins
  cmd/server/docs/docs.go
  server/api/repo.go
  server/router/api.go
  server/store/datastore/repo.go
  server/store/mocks/store.go
  server/store/store.go
  web/components.d.ts
  web/src/assets/locales/en.json
  web/src/components/admin/settings/AdminReposTab.vue
  web/src/lib/api/index.ts
  web/src/views/admin/AdminSettings.vue
Labels: ui, feature

#2443 Add hint about alternative pipeline skip syntax
  docs/docs/20-usage/20-pipeline-syntax.md
Labels: documentation

#2467 Add devx lable to compose file PRs
  .github/renovate.json
Labels: devx

#2472 Update GH app installation instructions
  docs/docs/30-administration/11-forges/20-github.md
Labels: documentation

#2499 Update github auth install
  docs/docs/30-administration/11-forges/20-github.md
Labels: documentation, forge/github

#2501 Fix docs duplicate WOODPECKER_HOST assignment
  docs/versioned_docs/version-1.0/30-administration/00-setup.md
Labels: documentation
