Repository woodpecker-ci/woodpecker, pull requests merged in 2023-04, with the labels that each got.

#1686 Set 'HOME' during local pipeline step
  pipeline/backend/local/local.go
Labels: bug, backend/local

#1690 Fix docs build
  .woodpecker/docs.yml
  docs/package.json
  docs/plugins/woodpecker-plugins/package.json
  docs/plugins/woodpecker-plugins/pnpm-lock.yaml
  docs/pnpm-lock.yaml
  docs/pnpm-workspace.yaml
Labels: documentation, build, dependencies

#1692 Add backend label to agents
  cmd/agent/agent.go
  docs/docs/20-usage/20-pipeline-syntax.md
Labels: agent, enhancement

#1694 Refactor plugin-index plugin for docs
  docs/plugins/woodpecker-plugins/src/theme/WoodpeckerPluginList.tsx
Labels: documentation, refactor

#1698 Fix Bitbucket Server branches
  server/forge/bitbucketserver/internal/client.go
  server/forge/bitbucketserver/internal/types.go
Labels: bug, forge/bitbucket

#1693 Add env for workflow and step name
  cli/exec/exec.go
  cli/exec/flags.go
  docs/docs/20-usage/50-environment.md
  pipeline/frontend/metadata.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/constraint/constraint.go
  pipeline/stepBuilder.go
  pipeline/stepBuilder_test.go
  server/pipeline/queue.go
Labels: server

#1701 Adjust documentation of "CI_PIPELINE_LINK" to reflect actual behavior.
  docs/docs/20-usage/50-environment.md
Labels: bug, documentation

#1703 Consistent status on delete
  server/api/cron.go
  server/api/global_secret.go
  server/api/org_secret.go
  server/api/registry.go
  server/api/repo_secret.go
  server/store/datastore/agent.go
  server/store/datastore/cron.go
  server/store/datastore/helper.go
  server/store/datastore/permission.go
  server/store/datastore/secret.go
  server/store/datastore/server_config.go
  server/store/datastore/task.go
  server/store/datastore/user.go
Labels: bug

#1706 Local Backend should create SubDirs
  pipeline/backend/local/local.go
Labels: bug, skip-changelog, backend/local

#1710 Remove unnecessary parenthesis
  docs/versioned_docs/version-0.15/10-intro.md
Labels: documentation, skip-changelog

#1717 Correct label argument parsing in agent code
  cmd/agent/agent.go
  cmd/agent/agent_test.go
Labels: bug, agent

#1719 Use codeberg.org/6543/go-yaml2json
  go.mod
  go.sum
  shared/yml/yml.go
  vendor/codeberg.org/6543/go-yaml2json/.gitignore
  vendor/codeberg.org/6543/go-yaml2json/.woodpecker.yml
  vendor/codeberg.org/6543/go-yaml2json/LICENSE
  vendor/codeberg.org/6543/go-yaml2json/README.md
  vendor/codeberg.org/6543/go-yaml2json/yml.go
  vendor/github.com/stretchr/objx/.travis.yml
  vendor/github.com/stretchr/objx/accessors.go
  vendor/github.com/stretchr/objx/map.go
  vendor/github.com/stretchr/objx/type_specific_codegen.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/mock/mock.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/modules.txt
Labels: bug

#1720 Implement YAML Map Merge, Overrides, and Sequence Merge Support
  docs/docs/20-usage/35-advanced-yaml-syntax.md
  go.mod
  go.sum
  pipeline/frontend/yaml/config.go
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/frontend/yaml/matrix/matrix.go
  pipeline/schema/.woodpecker/test-merge-map-and-sequence.yml
  pipeline/schema/schema.go
  pipeline/schema/schema_test.go
Labels: feature

#1714 Support path prefix
  cmd/server/flags.go
  cmd/server/server.go
  docs/docs/30-administration/00-setup.md
  docs/docs/30-administration/10-server-config.md
  server/config.go
  server/web/config.go
  server/web/web.go
  web/src/compositions/useApiClient.ts
  web/src/compositions/useConfig.ts
Labels: enhancement

#1723 Changelog 0.15.8
  CHANGELOG.md
Labels: documentation, skip-changelog

#1726 Drop Gogs private mode
  cmd/server/flags.go
  cmd/server/setup.go
  docs/docs/30-administration/11-forges/70-gogs.md
  docs/docs/91-migrations.md
  server/api/repo.go
  server/forge/gitlab/convert.go
  server/forge/gogs/gogs.go
  server/forge/gogs/gogs_test.go
  server/forge/gogs/helper.go
  server/forge/gogs/helper_test.go
  server/forge/gogs/parse.go
  server/forge/types/errors.go
  server/model/const.go
  server/model/repo.go
Labels: refactor, forge/gogs

#1727 Some smal code refactorings
  server/api/pipeline.go
  server/forge/configFetcher.go
  server/model/const.go
  server/model/secret.go
  web/src/lib/api/index.ts
  web/src/lib/api/types/pipeline.ts
Labels: refactor, skip-changelog

#1729 docs: change broken twitter url
  README.md
Labels: documentation, skip-changelog
