Repository woodpecker-ci/woodpecker, pull requests merged in 2023-01, with the labels that each got.

#1516 Update Owners 2023
  CONTRIBUTING.md
Labels: documentation, skip-changelog

#1515 Rework status constraint logic for successes
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/constraint/constraint.go
  pipeline/frontend/yaml/constraint/constraint_test.go
Labels: bug, server

#1519 Updating Example configuration to override depth
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/versioned_docs/version-0.15/20-usage/20-pipeline-syntax.md
Labels: documentation

#1521 Add Aptly publish plugin
  docs/plugins/woodpecker-plugins/plugins.json
Labels: plugin, documentation

#1528 kubernetes ignore labels and annotations if not set
  pipeline/backend/kubernetes/kubernetes.go
Labels: bug, skip-changelog

#1531 Add pipeline trigger plugin
  docs/plugins/woodpecker-plugins/plugins.json
Labels: plugin, documentation, blocked

#1526 Pin official default images
  docs/docs/30-administration/10-server-config.md
  docs/docs/92-development/06-guides.md
  docs/versioned_docs/version-0.15/30-administration/10-server-config.md
  shared/constant/constant.go
Labels: agent, governance, backport

#1475 Secrets encryption in database
  cmd/server/flags.go
  cmd/server/server.go
  cmd/server/setup.go
  docs/docs/30-administration/10-server-config.md
  docs/docs/30-administration/40-encryption.md
  go.mod
  go.sum
  server/model/encryption.go
  server/model/secret.go
  server/plugins/encryption/aes.go
  server/plugins/encryption/aes_builder.go
  server/plugins/encryption/aes_encryption.go
  server/plugins/encryption/aes_state.go
  server/plugins/encryption/aes_test.go
  server/plugins/encryption/constants.go
  server/plugins/encryption/encryption.go
  server/plugins/encryption/encryption_builder.go
  server/plugins/encryption/no_encryption.go
  server/plugins/encryption/tink.go
  server/plugins/encryption/tink_builder.go
  server/plugins/encryption/tink_keyset.go
  server/plugins/encryption/tink_keyset_watcher.go
  server/plugins/encryption/tink_state.go
  server/plugins/encryption/wrapper/store/constants.go
  server/plugins/encryption/wrapper/store/secret_store.go
  server/plugins/encryption/wrapper/store/secret_store_wrapper.go
  server/store/datastore/secret.go
  server/store/datastore/secret_test.go
  server/store/datastore/server_config.go
  server/store/mocks/store.go
  server/store/store.go
Labels: server, feature, security

#1538 Bump xgo and go to v1.19.5
  .woodpecker/binaries.yml
  .woodpecker/docker.yml
  .woodpecker/docs.yml
  .woodpecker/test.yml
  Makefile
Labels: build

#1539 Update golangci-linter config
  .golangci.yml
Labels: tests

#1540 use same sql for set default statement on mysql/mariadb and postgres
  server/store/datastore/migration/common.go
Labels: bug, skip-changelog

#1545 Add Email plugin
  docs/plugins/woodpecker-plugins/plugins.json
Labels: plugin, documentation

#1455 Consistent and more descriptive naming of parameters in index.ts
  web/src/lib/api/index.ts
Labels: ui, refactor

#1547 Bump xgo and go to v1.19.5 (#1538)
  .woodpecker/binaries.yml
  .woodpecker/docker.yml
  .woodpecker/test.yml
  Makefile
Labels: build

#1549 Disable secret encryption until its fixed
  cmd/server/server.go
Labels: skip-changelog

#1553 Dont require secret value on secret edit (#1552)
  web/src/components/secrets/SecretEdit.vue
Labels: bug, ui

#1189 Store an agents list and add agent heartbeats
  agent/rpc/auth_client_grpc.go
  agent/rpc/auth_interceptor.go
  agent/rpc/client_grpc.go
  cmd/agent/agent.go
  cmd/agent/flags.go
  cmd/server/server.go
  pipeline/rpc/client_grpc_health.go
  pipeline/rpc/health.go
  pipeline/rpc/peer.go
  pipeline/rpc/proto/woodpecker.pb.go
  pipeline/rpc/proto/woodpecker.proto
  pipeline/rpc/proto/woodpecker_grpc.pb.go
  server/api/agent.go
  server/config.go
  server/grpc/auth_server.go
  server/grpc/authorizer.go
  server/grpc/jwt_manager.go
  server/grpc/rpc.go
  server/grpc/server.go
  server/model/agent.go
  server/router/api.go
  server/store/datastore/agent.go
  server/store/datastore/migration/008_recreate_agents_table.go
  server/store/datastore/migration/common.go
  server/store/datastore/migration/migration.go
  server/store/mocks/store.go
  server/store/store.go
  web/components.d.ts
  web/src/assets/locales/en.json
  web/src/components/admin/settings/AdminAgentsTab.vue
  web/src/components/atomic/Icon.vue
  web/src/lib/api/index.ts
  web/src/lib/api/types/agent.ts
  web/src/lib/api/types/index.ts
  web/src/views/admin/AdminSettings.vue
Labels: server, agent, feature

#1567 Add agent no-schedule flag
  server/api/agent.go
  server/grpc/rpc.go
  server/model/agent.go
  web/components.d.ts
  web/src/assets/locales/en.json
  web/src/components/admin/settings/AdminAgentsTab.vue
  web/src/lib/api/types/agent.ts
Labels: server, feature

#1568 Show platform, backend and capacity as badges in agent list
  web/components.d.ts
  web/src/assets/locales/en.json
  web/src/components/admin/settings/AdminAgentsTab.vue
  web/src/components/atomic/Badge.vue
  web/src/components/repo/pipeline/PipelineStepList.vue
Labels: ui, enhancement

#1453 Hide not owned repos from sidebar and repo list
  web/.eslintrc.js
  web/components.d.ts
  web/src/components/layout/header/ActivePipelines.vue
  web/src/components/repo/settings/GeneralTab.vue
  web/src/compositions/useEvents.ts
  web/src/compositions/usePipelineFeed.ts
  web/src/lib/api/client.ts
  web/src/store/pipelines.ts
  web/src/store/repos.ts
  web/src/views/Repos.vue
  web/src/views/ReposOwner.vue
  web/src/views/repo/RepoWrapper.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: bug, ui

#1571 Deduplicate step docker container volumes
  pipeline/backend/docker/docker.go
  shared/utils/strings.go
Labels: bug
