Repository woodpecker-ci/woodpecker, pull requests merged in 2023-06, with the labels that each got.

#1792 Revert to docker 20.10.x for API 1.41 compatibility
  go.mod
  go.sum
  pipeline/backend/docker/docker.go
Labels: dependencies

#1803 Do not use oauth client without token
  server/forge/bitbucketserver/bitbucketserver.go
  server/forge/common/utils.go
  server/forge/gitea/gitea.go
  server/forge/github/github.go
  server/forge/gitlab/gitlab.go
Labels: bug, server, forge/github

#1812 Added Hardware Requirements documentation
  docs/docs/30-administration/00-setup.md
Labels: documentation

#1800 Define Glossary
  docs/docs/20-usage/15-terminology.md
  docs/docs/92-development/09-terms.md
  server/forge/mocks/forge.go
  server/store/mocks/store.go
Labels: documentation

#1817 Fix missing table name
  server/store/datastore/migration/017_remove_machine_col.go
Labels: bug, regression

#1782 Update swagger API specification
  .ecrc
  .gitignore
  .golangci.yml
  .woodpecker/test.yml
  Makefile
  cmd/server/docs/docs.go
  cmd/server/main.go
  cmd/server/swagger.go
  cmd/server/woodpecker_docs_gen.go
  docs/docs/92-development/08-swagger.md
  go.mod
  go.sum
  server/api/agent.go
  server/api/badge.go
  server/api/cron.go
  server/api/debug/debug.go
  server/api/global_secret.go
  server/api/hook.go
  server/api/org.go
  server/api/org_secret.go
  server/api/pipeline.go
  server/api/registry.go
  server/api/repo.go
  server/api/repo_secret.go
  server/api/signature_public_key.go
  server/api/user.go
  server/api/users.go
  server/api/z.go
  server/model/agent.go
  server/model/config.go
  server/model/const.go
  server/model/cron.go
  server/model/environ.go
  server/model/feed.go
  server/model/perm.go
  server/model/pipeline.go
  server/model/pull_request.go
  server/model/registry.go
  server/model/repo.go
  server/model/secret.go
  server/model/step.go
  server/model/task.go
  server/model/team.go
  server/model/user.go
  server/queue/queue.go
  server/router/router.go
  server/swagger/doc.go
  server/swagger/files/swagger.yml
  web/src/views/User.vue
Labels: server, enhancement

#1767 Allow setting resources for kubernetes on a per-step basis
  docs/docs/30-administration/15-agent-config.md
  docs/docs/30-administration/22-backends/40-kubernetes.md
  docs/docs/30-administration/80-kubernetes.md
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/types/backend.go
  pipeline/backend/types/backend_kubernetes.go
  pipeline/backend/types/step.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/container.go
  pipeline/schema/schema.json
Labels: enhancement, backend/kubernetes

#1818 [Docs] use redocusaurus to display swagger file
  .gitignore
  cmd/server/swagger.go
  cmd/server/woodpecker_docs_gen.go
  docs/docusaurus.config.js
  docs/package.json
  docs/pnpm-lock.yaml
  go.mod
  go.sum
Labels: documentation

#1819 drop tarball release
  .woodpecker/binaries.yml
  Makefile
Labels: build

#1820 [Docs] Remove never implemented "tag"-filter and document "ref"-filter to do the same
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/versioned_docs/version-0.15/20-usage/22-conditional-execution.md
Labels: documentation

#1790 Resolve built-in variables for global when filtered too
  cli/exec/exec.go
  cli/exec/flags.go
  cli/exec/metadata.go
  docs/docs/20-usage/50-environment.md
  pipeline/frontend/metadata.go
  pipeline/frontend/metadata/const.go
  pipeline/frontend/metadata/drone_compatibility.go
  pipeline/frontend/metadata/drone_compatibility_test.go
  pipeline/frontend/metadata/environment.go
  pipeline/frontend/metadata/types.go
  pipeline/frontend/metadata_test.go
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/compiler/option.go
  pipeline/frontend/yaml/compiler/option_test.go
  pipeline/frontend/yaml/config.go
  pipeline/frontend/yaml/config_test.go
  pipeline/frontend/yaml/constraint/constraint.go
  pipeline/frontend/yaml/constraint/constraint_test.go
  pipeline/pipeline.go
  pipeline/stepBuilder.go
  pipeline/stepBuilder_test.go
  server/pipeline/create.go
  server/pipeline/filter.go
  server/pipeline/items.go
Labels: bug, server, refactor, breaking

#1822 Database migrations run in seperate sessions and commit on success right away
  server/store/datastore/migration/017_remove_machine_col.go
  server/store/datastore/migration/migration.go
Labels: bug, regression

#1829 Rename pipeline frontend types
  docs/docs/20-usage/25-workflows.md
  pipeline/frontend/yaml/compiler/cacher.go
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/compiler_test.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/constraint/constraint.go
  pipeline/frontend/yaml/container.go
  pipeline/frontend/yaml/linter/linter.go
  pipeline/frontend/yaml/parse.go
  pipeline/frontend/yaml/parse_test.go
  pipeline/frontend/yaml/types/backend_options.go
  pipeline/frontend/yaml/types/base/base_types_test.go
  pipeline/frontend/yaml/types/base/bool.go
  pipeline/frontend/yaml/types/base/bool_test.go
  pipeline/frontend/yaml/types/base/int.go
  pipeline/frontend/yaml/types/base/map.go
  pipeline/frontend/yaml/types/base/slice.go
  pipeline/frontend/yaml/types/container.go
  pipeline/frontend/yaml/types/container_test.go
  pipeline/frontend/yaml/types/secret.go
  pipeline/frontend/yaml/types/secret_test.go
  pipeline/frontend/yaml/types/types_yaml.go
  pipeline/frontend/yaml/types/workflow.go
  pipeline/frontend/yaml/types/workflow_network.go
  pipeline/frontend/yaml/types/workflow_network_test.go
  pipeline/frontend/yaml/types/workflow_volume.go
  pipeline/frontend/yaml/types/workflow_volume_test.go
  pipeline/stepBuilder.go
Labels: server, refactor

#1830 make in_docker work again
  Makefile
  docker/Dockerfile.make
Labels: skip-changelog, build

#1833 Rename yaml pipeline to steps
  .woodpecker/binaries.yml
  .woodpecker/docker.yml
  .woodpecker/docs.yml
  .woodpecker/test.yml
  .woodpecker/web.yml
  docs/docs/10-intro.md
  docs/docs/20-usage/10-intro.md
  docs/docs/20-usage/15-terminology.md
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/docs/20-usage/25-workflows.md
  docs/docs/20-usage/30-matrix-workflows.md
  docs/docs/20-usage/35-advanced-yaml-syntax.md
  docs/docs/20-usage/40-secrets.md
  docs/docs/20-usage/45-cron.md
  docs/docs/20-usage/50-environment.md
  docs/docs/20-usage/51-plugins/10-plugins.md
  docs/docs/20-usage/51-plugins/20-sample-plugin.md
  docs/docs/20-usage/60-services.md
  docs/docs/20-usage/70-volumes.md
  docs/docs/30-administration/100-external-configuration-api.md
  docs/docs/30-administration/22-backends/20-local.md
  docs/docs/30-administration/22-backends/40-kubernetes.md
  docs/docs/91-migrations.md
  pipeline/frontend/metadata_test.go
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/frontend/yaml/parse.go
  pipeline/frontend/yaml/parse_test.go
  pipeline/frontend/yaml/types/workflow.go
  pipeline/samples/sample_1/pipeline.yml
  pipeline/samples/sample_10_windows/pipeline.yml
  pipeline/samples/sample_2/pipeline.yml
  pipeline/samples/sample_3/pipeline.yml
  pipeline/samples/sample_4/pipeline.yml
  pipeline/samples/sample_5/pipeline.yml
  pipeline/samples/sample_6/pipeline.yml
  pipeline/samples/sample_7_redis/pipeline.yml
  pipeline/samples/sample_8_network_mode/pipeline.yml
  pipeline/samples/sample_8_postgres/pipeline.yml
  pipeline/samples/sample_9_cache/pipeline.yml
  pipeline/schema/.woodpecker/test-branches-array.yml
  pipeline/schema/.woodpecker/test-branches-exclude-include.yml
  pipeline/schema/.woodpecker/test-branches.yml
  pipeline/schema/.woodpecker/test-broken.yml
  pipeline/schema/.woodpecker/test-clone-skip.yml
  pipeline/schema/.woodpecker/test-clone.yml
  pipeline/schema/.woodpecker/test-labels.yml
  pipeline/schema/.woodpecker/test-matrix.yml
  pipeline/schema/.woodpecker/test-merge-map-and-sequence.yml
  pipeline/schema/.woodpecker/test-multi.yml
  pipeline/schema/.woodpecker/test-pipeline-when.yml
  pipeline/schema/.woodpecker/test-platform.yml
  pipeline/schema/.woodpecker/test-plugin.yml
  pipeline/schema/.woodpecker/test-run-on.yml
  pipeline/schema/.woodpecker/test-service.yml
  pipeline/schema/.woodpecker/test-step.yml
  pipeline/schema/.woodpecker/test-when.yml
  pipeline/schema/.woodpecker/test-workspace.yml
  pipeline/schema/schema.json
  pipeline/stepBuilder_test.go
Labels: breaking, pipeline-config

#1839 Get workflow id from clone steps
  pipeline/backend/local/local.go
Labels: backend/local

#1841 [Docs] Fix schema to replace "tag" by "ref"-filter
  docs/docs/20-usage/20-pipeline-syntax.md
  pipeline/schema/.woodpecker/test-when.yml
  pipeline/schema/schema.json
Labels: bug, documentation

#1846 Print ongoing alive sign for migrations after 20s
  server/store/datastore/migration/migration.go
Labels: server, enhancement

#1849 01-getting-started.md: fix WOODPECKER_HOST example
  docs/docs/92-development/01-getting-started.md
Labels: documentation, skip-changelog

#1858 logs stream: fix url parameter
  server/router/api.go
Labels: regression

#1859 Fix links in docs
  docs/docs/20-usage/20-pipeline-syntax.md
  docs/versioned_docs/version-0.15/20-usage/25-multi-pipeline.md
  docs/versioned_docs/version-0.15/30-administration/10-server-config.md
Labels: documentation, skip-changelog

#1869 Added Woodpecker Host Config used for Webhooks
  cmd/server/flags.go
  cmd/server/server.go
  docs/docs/30-administration/10-server-config.md
  server/api/repo.go
  server/config.go
Labels: enhancement

#1875 Return after error
  server/api/repo.go
Labels: bug, security

#1853 sync repo permissions on login
  server/api/login.go
Labels: server

#1878 Add minimum usage for CLI v0.15.x to docs
  docs/versioned_docs/version-0.15/40-cli.md
Labels: documentation, skip-changelog

#1887 Fix bitbucket forge add repo
  server/forge/bitbucket/bitbucket.go
Labels: bug, forge/bitbucket

#1889 Add pull-request implementation for bitbucket forge
  server/forge/bitbucket/bitbucket.go
  server/forge/bitbucket/internal/client.go
  server/forge/bitbucket/internal/types.go
Labels: server, enhancement, forge/bitbucket

#1890 Fix empty agent token
  server/store/datastore/agent.go
  server/store/datastore/agent_test.go
Labels: security

#1891 Refactor AgentFindByToken
  server/store/datastore/agent.go
Labels: refactor, skip-changelog

#1898 Fix pipeline status calculation/reporting
  cmd/server/flags.go
  pipeline/stepBuilder.go
  server/model/step.go
  server/model/workflow.go
  server/pipeline/workflowStatus.go
  server/store/datastore/migration/020_parent_steps_to_workflows.go
Labels: bug, regression

#1896 Document k8s volume usage
  docs/docs/30-administration/80-kubernetes.md
Labels: documentation, skip-changelog, backend/kubernetes

#1901 Optimize pipeline and switch to "steps"
  .woodpecker/binaries.yml
  .woodpecker/docker.yml
  .woodpecker/docs.yml
  .woodpecker/test.yml
  .woodpecker/web.yml
Labels: refactor, skip-changelog, build
