Repository woodpecker-ci/woodpecker, pull requests merged in 2024-11, with the labels that each got.

#4025 Split repo trusted setting
  cli/exec/exec.go
  cli/exec/flags.go
  cli/exec/metadata.go
  cli/lint/lint.go
  cmd/server/docs/docs.go
  docs/docs/20-usage/50-environment.md
  docs/docs/91-migrations.md
  pipeline/frontend/metadata/drone_compatibility_test.go
  pipeline/frontend/metadata/environment.go
  pipeline/frontend/metadata/types.go
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/option.go
  pipeline/frontend/yaml/linter/linter.go
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/frontend/yaml/linter/option.go
  server/api/repo.go
  server/model/repo.go
  server/pipeline/stepbuilder/metadata.go
  server/pipeline/stepbuilder/metadata_test.go
  server/pipeline/stepbuilder/stepBuilder.go
  server/store/datastore/migration/017_split_trusted.go
  server/store/datastore/migration/common.go
  server/store/datastore/migration/migration.go
  web/src/assets/locales/en.json
  web/src/components/repo/settings/GeneralTab.vue
  web/src/lib/api/types/repo.ts
Labels: feature, breaking

#4151 Kubernetes | Docker: Add support for rootless images
  pipeline/backend/common/script.go
  pipeline/backend/common/script_posix.go
  pipeline/backend/common/script_posix_test.go
  pipeline/backend/common/script_test.go
  pipeline/backend/common/script_win.go
  pipeline/backend/common/script_win_test.go
  pipeline/backend/docker/convert_test.go
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/kubernetes/pod_test.go
  pipeline/backend/types/step.go
  pipeline/frontend/yaml/compiler/compiler_test.go
  pipeline/frontend/yaml/compiler/convert.go
Labels: breaking, backend/docker, backend/kubernetes, build_pr_images

#4284 Refresh token before loading branches
  server/api/repo.go
Labels: bug, server

#4287 pin xgo image
  .woodpecker/binaries.yaml
  .woodpecker/docker.yaml
Labels: skip-changelog, build

#4214 Changelog for v2.7.2
  CHANGELOG.md
Labels: documentation, skip-changelog

#4300 Use release-helper for release/* branches
  .woodpecker/release-helper.yaml
Labels: build

#4301 Use release-helper for release/* branches
  .woodpecker/release-helper.yaml
Labels: build

#4302 Use release-helper for release/* branches
  .woodpecker/release-helper.yaml
Labels: build

#4298 Upgrade vue-i18n
  web/.prettierrc.js
  web/package.json
  web/pnpm-lock.yaml
  web/vite.config.ts
Labels: bug, ui, dependencies

#4292 Add changelog for v2.7.2
  CHANGELOG.md
Labels: documentation, skip-changelog

#4291 Improve migration notes
  .cspell.json
  docs/blog/2023-11-09-release-v2.0.0/index.md
  docs/blog/2023-12-12-podman-image-builds/index.md
  docs/blog/2023-12-13-debug-pipeline-steps/index.md
  docs/blog/2023-12-15-podman-sigstore/index.md
  docs/blog/2024-05-27-release-v2.5.0/index.md
  docs/docs/30-administration/05-deployment-methods/40-nixos.md
  docs/docusaurus.config.ts
  docs/src/pages/about.md
  docs/src/pages/awesome.md
  docs/src/pages/migrations.md
  docs/src/pages/versions.md
Labels: documentation

#4252 Move Queue creation behind new func that evaluates queue type
  cmd/server/setup.go
  server/queue/fifo.go
  server/queue/fifo_test.go
  server/queue/queue.go
Labels: refactor

#4305 gitea: add check if pull_request webhook is missing pull info
  server/forge/gitea/parse.go
Labels: bug, forge/gitea

#4212 Add options to controll the database connections (open,idle,timeout)
  cmd/server/flags.go
  cmd/server/setup.go
  docs/docs/30-administration/10-server-config.md
  docs/src/pages/migrations.md
  server/store/common.go
  server/store/datastore/engine.go
Labels: server, enhancement

#4309 pin xgo image
  .woodpecker/binaries.yaml
  .woodpecker/docker.yaml
Labels: skip-changelog, build

#4308 Remove pulls from Changelog that are backported
  release-config.ts
Labels: skip-changelog, build

#4311 Bump release plugin
  .woodpecker/release-helper.yaml
Labels: skip-changelog, build

#4310 Adjust config for release plugin
  release-config.ts
Labels: documentation, skip-changelog, build

#4315 dont release docs from release branch
  .woodpecker/docs.yaml
Labels: skip-changelog, build

#4316 dont release docs from release branch
  .woodpecker/docs.yaml
Labels: skip-changelog, build

#4312 Start a trivy server service (#4288)
  .woodpecker/securityscan.yaml
Labels: skip-changelog, build

#4317 Upgrade vue-i18n
  web/.prettierrc.js
  web/package.json
  web/pnpm-lock.yaml
  web/vite.config.ts
Labels: bug, skip-changelog

#4318 Bump release plugin
  .woodpecker/release-helper.yaml
Labels: skip-changelog, build

#4307 Add migration to autofix corrupted users.org_id entrys in db
  server/store/datastore/migration/018_fix-orgs-users-match.go
  server/store/datastore/migration/migration.go
Labels: bug, server, backport-needed

#4329 Bump release plugin
  .woodpecker/release-helper.yaml
Labels: skip-changelog, build

#4328 Bump release plugin
  .woodpecker/release-helper.yaml
Labels: skip-changelog, build

#4319 Respect `directory` option for steps again
  pipeline/backend/common/script.go
  pipeline/backend/common/script_posix.go
  pipeline/backend/common/script_posix_test.go
  pipeline/backend/common/script_test.go
  pipeline/backend/common/script_win.go
  pipeline/backend/common/script_win_test.go
  pipeline/backend/docker/convert.go
  pipeline/backend/docker/convert_test.go
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/kubernetes/pod_test.go
Labels: bug, regression, build_pr_images

#4334 Move update notifier dot into settings button
  web/src/components/layout/header/Navbar.vue
Labels: bug, ui

#4335 Unpin xgo
  .woodpecker/binaries.yaml
  .woodpecker/docker.yaml
Labels: skip-changelog, build

#4283 Fix deployment event note
  docs/docs/20-usage/20-workflow-syntax.md
  docs/docs/30-administration/11-forges/11-overview.md
Labels: documentation

#4293 Inline model types for migrations
  server/store/datastore/migration/000_legacy_to_xormigrate.go
  server/store/datastore/migration/001_add_org_id.go
  server/store/datastore/migration/004_remove_secrets_plugin_only_col.go
  server/store/datastore/migration/005_convert_to_new_pipeline_errors_format.go
  server/store/datastore/migration/007_clean_registry_pipeline.go
  server/store/datastore/migration/008_set_default_forge_id.go
  server/store/datastore/migration/009_unify_columns_tables.go
  server/store/datastore/migration/012_rename_start_end_time.go
  server/store/datastore/migration/015_add_org_agents.go
  server/store/datastore/migration/016_add_custom_labels_to_agent.go
  server/store/datastore/migration/017_split_trusted.go
Labels: server, refactor

#4338 Pass settings to services
  pipeline/frontend/yaml/compiler/convert.go
Labels: enhancement

#4345 Remove `secrets` from schema
  pipeline/frontend/yaml/linter/schema/schema.json
Labels: skip-changelog, schema

#4347 Update plugin docs link
  docs/plugins/woodpecker-plugins/plugins.json
Labels: plugin, documentation, skip-changelog

#4353 Fix schema test
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-step.yaml
Labels: tests, skip-changelog

#4354 address review lint issues
  pipeline/backend/kubernetes/kubernetes.go
  server/store/datastore/migration/common.go
  server/store/datastore/migration/migration_test.go
Labels: refactor, skip-changelog

#4206 Add server config to disable user registered agents
  cmd/server/flags.go
  cmd/server/setup.go
  docs/docs/30-administration/10-server-config.md
  server/api/agent_test.go
  server/config.go
  server/queue/mocks/queue.go
  server/queue/queue.go
  server/router/api.go
  server/web/config.go
  web/src/compositions/useConfig.ts
  web/src/views/User.vue
  web/src/views/org/OrgSettings.vue
Labels: enhancement, security

#4357 address review lint issues (#4354)
  pipeline/backend/kubernetes/kubernetes.go
  server/store/datastore/migration/common.go
  server/store/datastore/migration/migration_test.go
Labels: refactor, skip-changelog

#4351 Improve linter messages in UI
  pipeline/frontend/yaml/linter/linter.go
  pipeline/frontend/yaml/linter/linter_test.go
  web/package.json
  web/pnpm-lock.yaml
  web/src/components/atomic/DocsLink.vue
  web/src/components/atomic/RenderMarkdown.vue
  web/src/components/repo/settings/GeneralTab.vue
  web/src/style.css
  web/src/views/repo/pipeline/PipelineErrors.vue
Labels: server, ui, ux

#4371 Add EditorConfig-Checker Plugin to docs
  .woodpecker/static.yaml
  docs/plugins/woodpecker-plugins/plugins.json
Labels: documentation

#4359 On wrong secrets/environment config syntax, fail with good error message
  pipeline/frontend/yaml/types/base/deprecations.go
  pipeline/frontend/yaml/types/base/deprecations_test.go
  pipeline/frontend/yaml/types/container.go
Labels: enhancement, skip-changelog

#4372 ci: remove last "secrets" usage and migrate to from_secret
  .woodpecker/docs.yaml
Labels: skip-changelog, build

#4356 Process workflow logs in batches (#4045)
  agent/rpc/client_grpc.go
  cmd/agent/core/agent.go
  pipeline/log/line_writer.go
  pipeline/log/line_writer_test.go
  pipeline/rpc/mocks/peer.go
  pipeline/rpc/peer.go
  pipeline/rpc/proto/version.go
  pipeline/rpc/proto/woodpecker.pb.go
  pipeline/rpc/proto/woodpecker.proto
  server/api/stream.go
  server/grpc/rpc.go
  server/grpc/server.go
  server/logging/log.go
  server/logging/log_test.go
  server/logging/logging.go
  server/services/log/file/file.go
  server/services/log/service.go
  server/store/datastore/log.go
  server/store/datastore/log_test.go
  server/store/mocks/store.go
  server/store/store.go
Labels: server, agent, enhancement, highlight

#4373 Add `cli lint` option to treat warnings as errors
  .woodpecker/test.yaml
  cli/exec/exec.go
  cli/lint/lint.go
  cli/lint/utils.go
Labels: enhancement

#4326 Add server configuration option to add default set of labels for workflows that has no labels specified
  cmd/server/flags.go
  cmd/server/setup.go
  docs/docs/30-administration/10-server-config.md
  server/config.go
  server/pipeline/items.go
  server/pipeline/stepbuilder/stepBuilder.go
Labels: server, enhancement, build_pr_images

#4379 Use squared spinner for active pipelines
  web/src/components/layout/header/ActivePipelines.vue
Labels: ui, enhancement

#4383 Fix responsiveness of the settings template
  web/src/components/admin/settings/AdminInfoTab.vue
  web/src/components/atomic/Button.vue
  web/src/components/atomic/Warning.vue
  web/src/components/layout/Settings.vue
  web/src/components/user/UserRegistriesTab.vue
  web/src/components/user/UserSecretsTab.vue
Labels: ui, enhancement

#4387 Remove enableManagers from renovate config
  .github/renovate.json
Labels: skip-changelog, build

#4393 Add back button to repo pipeline list
  web/src/views/repo/RepoWrapper.vue
Labels: ui, enhancement, ux

#4400 Add microsoft teams plugin
  docs/plugins/woodpecker-plugins/plugins.json
Labels: documentation

#3348 Extend approval options
  cli/repo/repo_info.go
  cli/repo/repo_update.go
  cmd/server/docs/docs.go
  docs/docs/20-usage/75-project-settings.md
  docs/docs/20-usage/project-settings.png
  server/api/repo.go
  server/forge/bitbucket/convert.go
  server/forge/bitbucketdatacenter/convert.go
  server/forge/forgejo/helper.go
  server/forge/gitea/helper.go
  server/forge/github/parse.go
  server/forge/gitlab/convert.go
  server/model/pipeline.go
  server/model/repo.go
  server/pipeline/approve.go
  server/pipeline/create.go
  server/pipeline/decline.go
  server/pipeline/gated.go
  server/pipeline/gated_test.go
  server/store/datastore/migration/017_gated_to_require_approval.go
  server/store/datastore/migration/migration.go
  web/src/assets/locales/en.json
  web/src/components/form/RadioField.vue
  web/src/components/layout/Settings.vue
  web/src/components/repo/settings/GeneralTab.vue
  web/src/lib/api/types/repo.ts
  woodpecker-go/woodpecker/types.go
Labels: enhancement, security, ux, backport-needed

#4403 Untangle settings / header slots
  web/src/components/admin/settings/AdminAgentsTab.vue
  web/src/components/admin/settings/AdminOrgsTab.vue
  web/src/components/admin/settings/AdminQueueTab.vue
  web/src/components/admin/settings/AdminRegistriesTab.vue
  web/src/components/admin/settings/AdminReposTab.vue
  web/src/components/admin/settings/AdminSecretsTab.vue
  web/src/components/admin/settings/AdminUsersTab.vue
  web/src/components/agent/AgentManager.vue
  web/src/components/layout/Settings.vue
  web/src/components/layout/scaffold/Header.vue
  web/src/components/layout/scaffold/Scaffold.vue
  web/src/components/org/settings/OrgAgentsTab.vue
  web/src/components/org/settings/OrgRegistriesTab.vue
  web/src/components/org/settings/OrgSecretsTab.vue
  web/src/components/repo/settings/BadgeTab.vue
  web/src/components/repo/settings/CronTab.vue
  web/src/components/repo/settings/RegistriesTab.vue
  web/src/components/repo/settings/SecretsTab.vue
  web/src/components/user/UserAgentsTab.vue
  web/src/components/user/UserCLIAndAPITab.vue
  web/src/components/user/UserRegistriesTab.vue
  web/src/components/user/UserSecretsTab.vue
  web/src/views/Repos.vue
  web/src/views/User.vue
  web/src/views/org/OrgRepos.vue
  web/src/views/org/OrgWrapper.vue
  web/src/views/repo/RepoWrapper.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: ui, refactor

#4360 Deprecate `secrets` in favor of `from_secret`
  pipeline/frontend/yaml/linter/linter.go
  pipeline/frontend/yaml/linter/linter_test.go
Labels: enhancement, refactor, engine

#4285 Use separate routes instead of anchors
  web/src/components/layout/scaffold/Scaffold.vue
  web/src/components/layout/scaffold/Tab.vue
  web/src/components/layout/scaffold/Tabs.vue
  web/src/compositions/useInjectProvide.ts
  web/src/compositions/useTabs.ts
  web/src/router.ts
  web/src/views/User.vue
  web/src/views/admin/AdminAgents.vue
  web/src/views/admin/AdminInfo.vue
  web/src/views/admin/AdminOrgs.vue
  web/src/views/admin/AdminQueue.vue
  web/src/views/admin/AdminRegistries.vue
  web/src/views/admin/AdminRepos.vue
  web/src/views/admin/AdminSecrets.vue
  web/src/views/admin/AdminSettings.vue
  web/src/views/admin/AdminSettingsWrapper.vue
  web/src/views/admin/AdminUsers.vue
  web/src/views/org/OrgRepos.vue
  web/src/views/org/OrgWrapper.vue
  web/src/views/org/settings/OrgAgents.vue
  web/src/views/org/settings/OrgRegistries.vue
  web/src/views/org/settings/OrgSecrets.vue
  web/src/views/org/settings/OrgSettingsWrapper.vue
  web/src/views/repo/RepoWrapper.vue
  web/src/views/repo/pipeline/PipelineConfig.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
  web/src/views/repo/settings/Actions.vue
  web/src/views/repo/settings/Badge.vue
  web/src/views/repo/settings/Crons.vue
  web/src/views/repo/settings/General.vue
  web/src/views/repo/settings/Registries.vue
  web/src/views/repo/settings/RepoSettings.vue
  web/src/views/repo/settings/Secrets.vue
  web/src/views/user/UserAgents.vue
  web/src/views/user/UserCLIAndAPI.vue
  web/src/views/user/UserGeneral.vue
  web/src/views/user/UserRegistries.vue
  web/src/views/user/UserSecrets.vue
  web/src/views/user/UserWrapper.vue
Labels: ui, refactor

#4412 Use KeyValueEditor for DeployPipelinePopup too
  web/src/components/layout/popups/DeployPipelinePopup.vue
Labels: ui, refactor

#4406 Dont run pipeline on push events to renovate branches
  .woodpecker/docker.yaml
  .woodpecker/docs.yaml
  .woodpecker/securityscan.yaml
  .woodpecker/static.yaml
  .woodpecker/test.yaml
  .woodpecker/web.yaml
Labels: build

#4417 Bump minimum nodejs to v20
  docs/docs/92-development/01-getting-started.md
  web/package.json
Labels: documentation

#4386 Redesign repo list and include last pipeline
  web/src/assets/locales/en.json
  web/src/components/repo/RepoItem.vue
  web/src/components/repo/pipeline/PipelineLog.vue
  web/src/compositions/useRepos.ts
  web/src/compositions/useUserConfig.ts
  web/src/lib/api/types/repo.ts
  web/src/store/pipelines.ts
  web/src/store/repos.ts
  web/src/utils/locale.ts
  web/src/views/Repos.vue
  web/src/views/org/OrgRepos.vue
  web/src/views/repo/RepoWrapper.vue
  web/src/views/repo/settings/Badge.vue
  web/src/views/repo/settings/General.vue
  web/src/views/user/UserGeneral.vue
Labels: ui, enhancement

#4420 Fix not working overflow on repo list message
  web/src/components/repo/RepoItem.vue
Labels: bug, ui

#4419 Add count badge to visualize counters in tab title
  web/src/assets/locales/en.json
  web/src/components/atomic/CountBadge.vue
  web/src/components/layout/scaffold/Tab.vue
  web/src/components/layout/scaffold/Tabs.vue
  web/src/compositions/useTabs.ts
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: ui, enhancement

#4363 Remove `secrets` in favor of `from_secret`
  pipeline/frontend/yaml/compiler/compiler_test.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/compiler/environment.go
  pipeline/frontend/yaml/linter/linter.go
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/frontend/yaml/types/base/deprecations.go
  pipeline/frontend/yaml/types/base/deprecations_test.go
  pipeline/frontend/yaml/types/container.go
  pipeline/frontend/yaml/types/container_test.go
Labels: breaking, pipeline-config, engine

#4410 Improve project settings descriptions
  cli/lint/lint.go
  cmd/server/flags.go
  docs/docs/20-usage/75-project-settings.md
  docs/docs/30-administration/10-server-config.md
  docs/versioned_docs/version-1.0/20-usage/71-project-settings.md
  docs/versioned_docs/version-2.5/20-usage/75-project-settings.md
  docs/versioned_docs/version-2.6/20-usage/75-project-settings.md
  docs/versioned_docs/version-2.7/20-usage/75-project-settings.md
  web/src/assets/locales/en.json
  web/src/views/repo/settings/General.vue
Labels: enhancement, ux

#4414 Unify pipeline status icons
  web/src/components/atomic/Icon.vue
Labels: ui, enhancement

#4437 Remove `renovate` branch triggers
  .woodpecker/docker.yaml
  .woodpecker/static.yaml
  .woodpecker/test.yaml
Labels: build

#4438 add dark hover color for tabsets
  web/src/components/layout/scaffold/Tabs.vue
Labels: ui, regression

#4331 Cleanup openapi generation
  .cspell.json
  .ecrc
  .gitignore
  .woodpecker/test.yaml
  Makefile
  cmd/server/main.go
  cmd/server/openapi.go
  cmd/server/openapi/docs.go
  cmd/server/openapi_json_gen.go
  cmd/server/openapi_test.go
  cmd/server/swagger.go
  cmd/server/swagger_test.go
  docs/docs/92-development/09-openapi.md
  docs/docusaurus.config.ts
  flake.nix
  go.mod
  go.sum
  server/api/agent.go
  server/api/forge.go
  server/api/global_registry.go
  server/api/org_registry.go
  server/api/pipeline.go
  server/api/repo.go
  server/api/z.go
  server/router/router.go
  tools/tools.go
Labels: bug

#4451 Normalize aarch64 -> arm64 for docker backend
  pipeline/backend/docker/docker.go
Labels: bug, backend/docker

#4418 Add dns config option to official feature set
  docs/docs/20-usage/20-workflow-syntax.md
  pipeline/backend/kubernetes/pod.go
  pipeline/frontend/yaml/linter/schema/schema.json
  pipeline/frontend/yaml/types/container.go
Labels: pipeline-config, backend/docker, backend/kubernetes

#4457 Normalize aarch64 -> arm64 for docker backend (#4451)
  pipeline/backend/docker/docker.go
Labels: bug, backend/docker

#4460 Add visibility icon to repo list
  web/src/components/atomic/Icon.vue
  web/src/components/repo/RepoItem.vue
Labels: ui, enhancement, ux

#4429 Extend approval options (#3348)
  cli/repo/repo_info.go
  cli/repo/repo_update.go
  cmd/server/docs/docs.go
  docs/docs/20-usage/75-project-settings.md
  docs/docs/20-usage/project-settings.png
  docs/docs/91-migrations.md
  server/api/repo.go
  server/forge/bitbucket/convert.go
  server/forge/bitbucketdatacenter/convert.go
  server/forge/forgejo/helper.go
  server/forge/gitea/helper.go
  server/forge/github/parse.go
  server/forge/gitlab/convert.go
  server/model/pipeline.go
  server/model/repo.go
  server/pipeline/approve.go
  server/pipeline/create.go
  server/pipeline/decline.go
  server/pipeline/gated.go
  server/pipeline/gated_test.go
  server/store/datastore/migration/034_gated_to_require_approval.go
  server/store/datastore/migration/migration.go
  web/src/assets/locales/en.json
  web/src/components/form/RadioField.vue
  web/src/components/repo/settings/GeneralTab.vue
  web/src/lib/api/types/repo.ts
  woodpecker-go/woodpecker/types.go
Labels: enhancement, security, highlight

#4352 Allow to set custom trusted clone plugins
  cmd/server/openapi/docs.go
  docs/docs/20-usage/75-project-settings.md
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/option.go
  server/api/repo.go
  server/model/repo.go
  server/pipeline/stepbuilder/stepBuilder.go
  server/store/datastore/migration/020_remove_repo_netrc_only_trusted.go
  server/store/datastore/migration/migration.go
  web/src/assets/locales/en.json
  web/src/lib/api/types/repo.ts
  web/src/views/repo/settings/General.vue
Labels: enhancement, breaking, security

#4458 Change default icon size to 20
  web/src/components/atomic/Icon.vue
  web/src/components/layout/scaffold/Header.vue
  web/src/components/layout/scaffold/Tabs.vue
  web/src/components/repo/RepoItem.vue
  web/src/components/repo/pipeline/PipelineStatusIcon.vue
  web/src/views/repo/pipeline/Pipeline.vue
Labels: ui, enhancement

#4466 Sanitize strings in table output
  cli/output/table.go
  cli/pipeline/pipeline_test.go
Labels: bug, cli

#4465 Trim space from agent token
  cmd/agent/core/agent.go
Labels: agent, enhancement, ux

#4464 Docker Backend: fully support windows container (#4381)
  pipeline/backend/docker/convert.go
  pipeline/backend/docker/convert_test.go
  pipeline/backend/docker/convert_win.go
  pipeline/backend/docker/convert_win_test.go
Labels: feature, backend/docker

#4463 Add pagination options to all supported endpoints in sdk
  cli/admin/registry/registry_list.go
  cli/cron/cron_list.go
  cli/org/registry/registry_list.go
  cli/repo/registry/registry_list.go
  cli/secret/secret_list.go
  cli/user/user_list.go
  pipeline/rpc/proto/woodpecker.pb.go
  pipeline/rpc/proto/woodpecker_grpc.pb.go
  woodpecker-go/woodpecker/global_registry.go
  woodpecker-go/woodpecker/global_secret.go
  woodpecker-go/woodpecker/interface.go
  woodpecker-go/woodpecker/mocks/client.go
  woodpecker-go/woodpecker/org.go
  woodpecker-go/woodpecker/repo.go
  woodpecker-go/woodpecker/user.go
  woodpecker-go/woodpecker/user_test.go
Labels: enhancement, breaking, lib

#4455 Queue tests: extend time in waitForProcess() to work agents under load too
  server/queue/fifo_test.go
Labels: skip-changelog, build

#4473 Enforce exact matching for GitLab groups
  server/api/repo.go
  server/forge/gitlab/gitlab.go
Labels: bug, forge/gitlab

#4474 Enforce exact matching for GitLab groups (#4473)
  server/api/repo.go
  server/forge/gitlab/gitlab.go
Labels: bug, forge/gitlab

#4416 Add filter to list repository pipelines API
  cmd/server/openapi/docs.go
  server/api/pipeline.go
  server/model/pipeline.go
  server/store/datastore/helper.go
  server/store/datastore/pipeline.go
  server/store/datastore/pipeline_test.go
  web/src/lib/api/index.ts
Labels: server, enhancement

#4476 Add migration notes for restructured cli commands
  docs/src/pages/migrations.md
Labels: documentation

#4479 Fix woodpecker-go repo model to match server
  cli/pipeline/deploy/deploy.go
  woodpecker-go/woodpecker/types.go
Labels: breaking, lib

#4480 Move pipeline logs command
  cli/pipeline/log/log.go
  cli/pipeline/log/log_show.go
  cli/pipeline/pipeline.go
  docs/src/pages/migrations.md
Labels: enhancement, breaking, cli

#4470 Add pipeline purge command to cli
  cli/pipeline/kill.go
  cli/pipeline/list.go
  cli/pipeline/list_test.go
  cli/pipeline/pipeline.go
  cli/pipeline/purge.go
  cli/pipeline/purge_test.go
  woodpecker-go/woodpecker/interface.go
  woodpecker-go/woodpecker/mocks/client.go
  woodpecker-go/woodpecker/repo.go
Labels: enhancement, cli

#4488 Use JS-native date/time formatting
  web/.gitignore
  web/.prettierignore
  web/eslint.config.js
  web/package.json
  web/pnpm-lock.yaml
  web/src/assets/locales/en.json
  web/src/compositions/useDate.ts
  web/vite.config.ts
Labels: ui, refactor

#4481 Unify cli commands and flags
  cli/admin/loglevel/loglevel.go
  cli/admin/registry/registry.go
  cli/admin/registry/registry_add.go
  cli/admin/registry/registry_show.go
  cli/admin/secret/secret.go
  cli/admin/secret/secret_add.go
  cli/admin/secret/secret_show.go
  cli/admin/user/user.go
  cli/admin/user/user_add.go
  cli/admin/user/user_show.go
  cli/common/hooks.go
  cli/internal/config/config.go
  cli/lint/lint.go
  cli/org/registry/registry.go
  cli/org/registry/registry_add.go
  cli/org/registry/registry_show.go
  cli/org/secret/secret.go
  cli/org/secret/secret_add.go
  cli/org/secret/secret_set.go
  cli/org/secret/secret_show.go
  cli/pipeline/deploy/deploy.go
  cli/pipeline/last.go
  cli/pipeline/list.go
  cli/pipeline/pipeline.go
  cli/pipeline/show.go
  cli/pipeline/start.go
  cli/repo/cron/cron.go
  cli/repo/cron/cron_show.go
  cli/repo/registry/registry.go
  cli/repo/registry/registry_add.go
  cli/repo/registry/registry_show.go
  cli/repo/repo.go
  cli/repo/repo_show.go
  cli/repo/repo_update.go
  cli/repo/secret/secret.go
  cli/repo/secret/secret_add.go
  cli/repo/secret/secret_set.go
  cli/repo/secret/secret_show.go
  cli/setup/setup.go
  cli/setup/token_fetcher.go
  cli/update/command.go
  cli/update/updater.go
  docs/src/pages/migrations.md
Labels: enhancement, breaking, cli
