Repository woodpecker-ci/woodpecker, pull requests merged in 2024-07, with the labels that each got.

#3820 Add dummy backend
  .vscode/settings.json
  cli/exec/exec.go
  cmd/agent/main.go
  docs/docs/92-development/09-testing.md
  pipeline/backend/dummy/dummy.go
  pipeline/backend/dummy/dummy_noop.go
  pipeline/backend/dummy/dummy_test.go
Labels: tests, build, backend

#3850 Cleanup state reporting
  agent/logger.go
  agent/rpc/client_grpc.go
  agent/runner.go
  agent/tracer.go
  pipeline/pipeline.go
  pipeline/rpc/mocks/peer.go
  pipeline/rpc/peer.go
  pipeline/rpc/proto/version.go
  pipeline/rpc/proto/woodpecker.pb.go
  pipeline/rpc/proto/woodpecker.proto
  pipeline/tracer.go
  server/grpc/rpc.go
  server/grpc/server.go
  server/model/step.go
  server/model/workflow.go
  server/pipeline/step_status.go
  server/pipeline/step_status_test.go
  server/pipeline/workflow_status.go
Labels: bug, refactor

#3859 Adjust logger types
  agent/logger.go
  cli/exec/exec.go
  pipeline/log/line_writer.go
  pipeline/log/line_writer_test.go
  pipeline/log/utils.go
  pipeline/log/utils_test.go
  pipeline/logger.go
Labels: refactor

#3844 Add timestamp for last work done by agent
  cmd/server/docs/docs.go
  server/grpc/rpc.go
  server/model/agent.go
  woodpecker-go/woodpecker/types.go
Labels: server, enhancement

#3863 Fix an invalid example in docu
  docs/docs/20-usage/10-intro.md
Labels: documentation, skip-changelog

#3867 Get default branch and show message in pipeline list
  cli/deploy/deploy.go
  cli/pipeline/pipeline.go
  cli/pipeline/pipeline_test.go
Labels: enhancement, cli

#3868 Ignore warnings for cli exec
  cli/exec/exec.go
  cli/lint/lint.go
  cli/lint/utils.go
Labels: bug, cli

#3871 Fix registry migration
  server/store/datastore/migration/032_registries_add_user.go
Labels: regression

#3878 Fix deploy task env
  cli/exec/flags.go
  cli/exec/metadata.go
  pipeline/frontend/metadata/environment.go
  pipeline/frontend/metadata/types.go
  pipeline/frontend/yaml/constraint/constraint.go
  server/api/pipeline.go
  server/forge/github/parse.go
  server/forge/github/parse_test.go
  server/model/pipeline.go
  server/pipeline/stepbuilder/metadata.go
Labels: bug, refactor

#3880 Fix vscode settings
  .vscode/settings.json
Labels: bug, devx

#3887 docs: Fix spelling
  docs/docs/92-development/01-getting-started.md
  docs/versioned_docs/version-1.0/92-development/01-getting-started.md
  docs/versioned_docs/version-2.4/92-development/01-getting-started.md
  docs/versioned_docs/version-2.5/92-development/01-getting-started.md
  docs/versioned_docs/version-2.6/92-development/01-getting-started.md
Labels: documentation, skip-changelog

#3874 Fix helper functions for MySQL syntax
  server/store/datastore/migration/032_registries_add_user.go
  server/store/datastore/migration/common.go
Labels: bug, server, skip-changelog

#3890 Fix update flake
  flake.lock
  flake.nix
Labels: skip-changelog, devx

#3891 Sort users by login
  server/store/datastore/user.go
Labels: enhancement

#3893 Let agents continuously report their health
  cmd/agent/core/agent.go
Labels: bug, agent

#3894 agent dont report error if terminated gracefully
  agent/rpc/client_grpc.go
Labels: bug, agent

#3888 Add user registries UI
  web/components.d.ts
  web/src/assets/locales/en.json
  web/src/components/user/UserRegistriesTab.vue
  web/src/views/User.vue
Labels: enhancement

#3822 Allow login using multiple forges
  cmd/server/server.go
  pipeline/rpc/proto/woodpecker.pb.go
  server/api/hook.go
  server/api/hook_test.go
  server/api/login.go
  server/services/config/mocks/service.go
  server/services/config/service.go
  server/services/environment/mocks/service.go
  server/services/environment/service.go
  server/services/manager.go
  server/services/mocks/manager.go
  server/services/registry/mocks/service.go
  server/services/registry/service.go
  server/services/secret/mocks/service.go
  server/services/secret/service.go
  server/store/datastore/user.go
  web/src/assets/locales/en.json
  web/src/compositions/useAuthentication.ts
  web/src/views/Login.vue
Labels: server, feature

#3899 Move setupEvilGlobals from server.go into setup.go
  cmd/server/server.go
  cmd/server/setup.go
Labels: server, refactor

#3898 Enhance pipeline list
  web/src/assets/locales/en.json
  web/src/components/pipeline-feed/PipelineFeedItem.vue
  web/src/components/repo/pipeline/PipelineItem.vue
  web/src/compositions/usePipeline.ts
  web/src/utils/locale.ts
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: ui, enhancement

#3897 Convert to openapi 3.0
  cmd/server/docs/docs.go
  cmd/server/swagger.go
  cmd/server/woodpecker_docs_gen.go
  go.mod
  go.sum
  server/api/z.go
Labels: enhancement

#3904 Convert urls in logs to links
  web/src/components/repo/pipeline/PipelineLog.vue
Labels: ui, feature

#3901 Update plugin-git and add renovate trigger
  .github/renovate.json
  shared/constant/constant.go
Labels: dependencies

#3895 Gracefully shutdown agent
  agent/rpc/auth_client_grpc.go
  agent/rpc/auth_interceptor.go
  agent/rpc/client_grpc.go
  agent/runner.go
  cmd/agent/core/agent.go
  cmd/agent/core/health.go
  pipeline/pipeline.go
  pipeline/shutdown.go
Labels: agent, feature

#3896 Gracefully shutdown server
  cmd/server/grpc_server.go
  cmd/server/main.go
  cmd/server/metrics_server.go
  cmd/server/server.go
  cmd/server/setup.go
  server/cron/cron.go
  server/queue/persistent.go
  server/store/datastore/engine.go
  server/store/datastore/migration/020_alter_logs_table.go
  server/store/datastore/migration/migration.go
  server/store/datastore/migration/migration_test.go
  server/store/mocks/store.go
  server/store/store.go
Labels: server, feature

#3906 Release windows binaries as zip file
  .woodpecker/binaries.yaml
  .woodpecker/docker.yaml
  Makefile
  flake.nix
Labels: enhancement, build

#3909 Disalow to set arbitrary environments for plugins
  cmd/server/woodpecker_docs_gen.go
  pipeline/frontend/yaml/linter/linter.go
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-broken-plugin.yaml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-broken-plugin2.yaml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-step.yaml
  pipeline/frontend/yaml/linter/schema/schema.json
  pipeline/frontend/yaml/linter/schema/schema_test.go
  pipeline/frontend/yaml/types/container.go
  pipeline/log/utils_test.go
Labels: enhancement, security

#3917 Update alpine package dep for docker images
  docker/Dockerfile.agent.alpine.multiarch
  docker/Dockerfile.cli.alpine.multiarch
  docker/Dockerfile.server.alpine.multiarch
Labels: bug, dependencies

#3803 Streamline docs for new users
  docs/blog/2024-01-01-continuous-deployment/index.md
  docs/cookbook/2023-12-23-hello-cookbook/index.md
  docs/docs/10-intro.md
  docs/docs/10-intro/index.md
  docs/docs/20-usage/10-intro.md
  docs/docs/20-usage/15-terminology/index.md
  docs/docs/20-usage/20-workflow-syntax.md
  docs/docs/20-usage/51-plugins/51-overview.md
  docs/docs/20-usage/pipeline.png
  docs/docs/20-usage/repo-list.png
  docs/docs/20-usage/repo-new.png
  docs/docs/30-administration/00-deployment/00-overview.md
  docs/docs/30-administration/00-getting-started.md
  docs/docs/30-administration/05-deployment-methods/10-docker-compose.md
  docs/docs/30-administration/05-deployment-methods/20-kubernetes.md
  docs/docs/30-administration/05-deployment-methods/30-third-party.md
  docs/docs/30-administration/05-deployment-methods/40-nixos.md
  docs/docs/30-administration/05-deployment-methods/_category_.yaml
  docs/docs/30-administration/10-database.md
  docs/docs/30-administration/10-server-config.md
  docs/docs/30-administration/40-advanced/10-proxy.md
  docs/docs/30-administration/40-advanced/100-external-configuration-api.md
  docs/docs/30-administration/40-advanced/20-ssl.md
  docs/docs/30-administration/40-advanced/30-autoscaler.md
  docs/docs/30-administration/40-advanced/40-advanced.md
  docs/docs/30-administration/40-advanced/90-prometheus.md
  docs/docs/30-administration/40-advanced/_category_.yaml
  docs/docs/91-migrations.md
  docs/docs/92-development/02-core-ideas.md
  docs/docs/pipeline-list.png
  docs/docusaurus.config.ts
Labels: documentation

#3809 Remove `unplugin-icons`
  web/package.json
  web/pnpm-lock.yaml
  web/src/components/admin/settings/AdminReposTab.vue
  web/src/components/admin/settings/AdminUsersTab.vue
  web/src/components/atomic/Button.vue
  web/src/components/atomic/Error.vue
  web/src/components/atomic/Icon.vue
  web/src/components/atomic/SvgIcon.vue
  web/src/components/atomic/Warning.vue
  web/src/components/layout/popups/DeployPipelinePopup.vue
  web/src/components/layout/popups/ManualPipelinePopup.vue
  web/src/components/layout/scaffold/Header.vue
  web/src/components/layout/scaffold/Tabs.vue
  web/src/components/user/UserGeneralTab.vue
  web/src/compositions/useTabs.ts
  web/src/views/User.vue
  web/src/views/repo/RepoBranches.vue
  web/src/views/repo/RepoWrapper.vue
  web/src/views/repo/pipeline/Pipeline.vue
  web/src/views/repo/pipeline/PipelineErrors.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
  web/vite.config.ts
Labels: ui, refactor

#3914 Allow to change the working directory also plugins and services
  pipeline/frontend/yaml/compiler/convert.go
Labels: enhancement

#3925 fix: internal server error when listing PRs for empty repositories
  server/forge/gitea/gitea.go
Labels: bug, forge/gitea

#3913 Cli fix pipeline logs
  cli/internal/util.go
  cli/pipeline/logs.go
  cli/pipeline/ps.go
  docs/versioned_docs/version-2.7/40-cli.md
Labels: enhancement, cli

#3926 Revert pipeline list
  web/src/assets/locales/en.json
  web/src/components/repo/pipeline/PipelineItem.vue
Labels: ui, refactor, skip-changelog

#3927 CLI: remove step-id and add step-number as option to logs
  cli/internal/util.go
  cli/pipeline/logs.go
Labels: enhancement, breaking, cli

#3940 Fix typos and optimize wording
  web/src/assets/locales/en.json
Labels: ui, translation

#3948 Update Forgejo SDK
  go.mod
  go.sum
Labels: security, dependencies, forge/forgejo

#3951 Improve wording
  web/src/assets/locales/en.json
Labels: ui, translation

#3952 Truncate creation in list
  web/src/components/repo/pipeline/PipelineItem.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: bug, ui

#2700 Refactor docker backend and add more test coverage
  pipeline/backend/common/script_test.go
  pipeline/backend/docker/convert.go
  pipeline/backend/docker/convert_test.go
  pipeline/backend/docker/docker.go
  pipeline/backend/kubernetes/kubernetes.go
Labels: enhancement, refactor, wip

#3845 server: remove old unused routes
  server/router/api.go
Labels: refactor, breaking

#3916 Remove deprecated pipeline settings
  docs/docs/91-migrations.md
  pipeline/frontend/yaml/linter/linter.go
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-branches-array.yaml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-branches-exclude-include.yaml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-branches.yaml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-platform.yaml
  pipeline/frontend/yaml/linter/schema/.woodpecker/test-when.yaml
  pipeline/frontend/yaml/linter/schema/schema.json
  pipeline/frontend/yaml/linter/schema/schema_test.go
  pipeline/frontend/yaml/parse.go
  pipeline/frontend/yaml/parse_test.go
  pipeline/frontend/yaml/types/workflow.go
  server/pipeline/stepbuilder/stepBuilder_test.go
Labels: refactor, breaking

#3961 Remove `WOODPECKER_DEV_OAUTH_HOST` and `WOODPECKER_DEV_GITEA_OAUTH_URL`
  cmd/server/flags.go
  cmd/server/setup.go
  docs/docs/91-migrations.md
Labels: refactor, breaking

#3965 Change Bitbucket PR hook to point the source branch, commit & ref
  server/forge/bitbucket/convert.go
  server/forge/bitbucket/convert_test.go
  server/forge/bitbucket/internal/types.go
  server/forge/bitbucket/parse_test.go
Labels: bug, forge/bitbucket

#3966 Require gitlab 12.4
  docs/docs/30-administration/11-forges/40-gitlab.md
Labels: documentation, forge/gitlab, breaking

#3972 Update docker to v27
  go.mod
  go.sum
  pipeline/backend/docker/convert_test.go
  pipeline/backend/docker/docker.go
Labels: breaking, dependencies, backend/docker

#3970 Drop version in schema
  pipeline/frontend/yaml/linter/schema/schema.json
Labels: breaking, schema

#3978 Remove oauth env
  docs/docs/92-development/01-getting-started.md
Labels: documentation, skip-changelog

#3979 Show logs if step has error
  web/src/assets/locales/en.json
  web/src/components/repo/pipeline/PipelineLog.vue
  web/src/views/repo/pipeline/Pipeline.vue
Labels: ui, enhancement

#3984 Use Bitbucket PR title for pipeline message
  server/forge/bitbucket/convert.go
  server/forge/bitbucket/convert_test.go
Labels: enhancement, forge/bitbucket
