Repository woodpecker-ci/woodpecker, pull requests merged in 2024-12, with the labels that each got.

#4494 Add status filter to list pipeline API
  cmd/server/openapi/docs.go
  server/api/pipeline.go
  server/model/const.go
  server/model/pipeline.go
  server/store/datastore/pipeline.go
  server/store/datastore/pipeline_test.go
Labels: server, enhancement

#4497 Some UI improvements
  web/src/components/atomic/Badge.vue
  web/src/views/org/settings/OrgSettingsWrapper.vue
  web/src/views/user/UserCLIAndAPI.vue
Labels: ui, enhancement

#4478 Use pagination helper to list pipelines in cli
  cli/pipeline/create.go
  cli/pipeline/last.go
  cli/pipeline/list.go
  cli/pipeline/list_test.go
  cli/pipeline/pipeline.go
  cli/pipeline/pipeline_test.go
  cli/pipeline/show.go
  woodpecker-go/woodpecker/repo.go
Labels: enhancement, cli

#4498 Fix events filter in GetPipelines API
  server/api/pipeline.go
  server/api/pipeline_test.go
Labels: server, regression

#4193 Do not set empty environment variables
  docs/docs/20-usage/50-environment.md
  docs/src/pages/migrations.md
  pipeline/frontend/metadata/environment.go
  pipeline/frontend/yaml/compiler/compiler_test.go
  server/pipeline/stepbuilder/metadata_test.go
Labels: breaking

#4512 fix: addon JSON pointers (#4508)
  docs/docs/30-administration/11-forges/100-addon.md
  server/forge/addon/client.go
  server/forge/addon/server.go
  server/services/config/forge.go
Labels: bug, addon

#4528 Use docusaurus faster
  docs/babel.config.js
  docs/docusaurus.config.ts
  docs/package.json
  docs/pnpm-lock.yaml
Labels: documentation, refactor

#4526 Add user as docker backend_option
  docs/docs/30-administration/22-backends/10-docker.md
  docs/docs/30-administration/22-backends/40-kubernetes.md
  pipeline/backend/docker/backend_options.go
  pipeline/backend/docker/backend_options_test.go
  pipeline/backend/docker/convert.go
  pipeline/backend/docker/convert_test.go
  pipeline/backend/docker/docker.go
  pipeline/backend/kubernetes/backend_options.go
  pipeline/backend/kubernetes/backend_options_test.go
Labels: server, feature

#4515 Move link checks into cron-curated issue dashboard
  .woodpecker/links.yaml
  .woodpecker/static.yaml
Labels: build

#4531 set `depends_on` for link checker
  .woodpecker/links.yaml
Labels: skip-changelog, build, regression

#4533 link checker: ignore failures
  .woodpecker/links.yaml
Labels: skip-changelog, build, regression

#4534 link-checker: various fixes
  .woodpecker/links.yaml
Labels: skip-changelog, build, regression

#4535 disable cron event for securityscan job
  .woodpecker/links.yaml
  .woodpecker/securityscan.yaml
Labels: skip-changelog, build, regression

#4538 Don't pre-eval custom env var in links pipeline
  .woodpecker/links.yaml
Labels: skip-changelog, build, regression

#4541 Drop native Let's Encrypt support
  cmd/server/flags.go
  cmd/server/health.go
  cmd/server/server.go
  docs/docs/30-administration/10-server-config.md
  docs/docs/30-administration/40-advanced/20-ssl.md
  docs/src/pages/migrations.md
  go.mod
  go.sum
Labels: server, refactor, breaking

#4573 Replace discontinued mitchellh/mapstructure by maintained fork
  cli/output/table.go
  go.mod
  go.sum
  pipeline/backend/docker/backend_options.go
  pipeline/backend/kubernetes/backend_options.go
Labels: dependencies

#4555 Update About
  docs/docs/50-about.md
Labels: documentation

#4574 Add client error to sdk and fix purge cli
  cli/pipeline/purge.go
  cli/pipeline/purge_test.go
  woodpecker-go/woodpecker/client.go
Labels: bug, cli, lib

#4577 Weakly decode backend options
  pipeline/backend/docker/backend_options.go
  pipeline/backend/kubernetes/backend_options.go
  pipeline/backend/kubernetes/backend_options_test.go
Labels: bug, backend/kubernetes

#4572 Remove related pipeline logs during pipeline deletion
  server/store/datastore/log.go
  server/store/datastore/step.go
Labels: bug, server

#4581 Disable corepack auto-pin during build
  docker/Dockerfile.make
Labels: skip-changelog, build

#4582 Ignore blocked pipelines for badge rendering
  pipeline/rpc/proto/woodpecker.pb.go
  server/api/badge.go
  server/forge/mocks/forge.go
  server/queue/mocks/queue.go
  server/services/mocks/manager.go
  server/store/datastore/pipeline.go
  server/store/mocks/store.go
  server/store/store.go
  woodpecker-go/woodpecker/mocks/client.go
Labels: bug, server

#4548 Migrations for 3.x
  docs/src/pages/migrations.md
Labels: documentation, skip-changelog

#4589 Don't log DB passwords (#4583)
  cmd/server/setup.go
Labels: bug, security

#4592 Backport gitea and forgejo sdk updates
  go.mod
  go.sum
Labels: security, dependencies

#4593 Fix version.json updates
  .woodpecker/docs.yaml
Labels: skip-changelog, build

#4600 Add rolling semver tags, remove `latest` tag
  .woodpecker/docker.yaml
  docker-compose.example.yaml
  docs/docs/30-administration/05-deployment-methods/10-docker-compose.md
  docs/src/pages/migrations.md
Labels: feature, breaking, build

#4602 Fix avatar column type (#4340)
  server/model/pipeline.go
Labels: bug, server

#4575 Use icon sizes relative to font size
  docs/static/img/feat-docker.svg
  docs/static/img/feat-opensource.svg
  docs/static/img/workflows.svg
  web/src/components/atomic/Icon.vue
  web/src/components/atomic/IconButton.vue
  web/src/components/form/Checkbox.vue
  web/src/components/form/RadioField.vue
  web/src/components/layout/Container.vue
  web/src/components/layout/header/ActivePipelines.vue
  web/src/components/layout/header/Navbar.vue
  web/src/components/repo/pipeline/PipelineItem.vue
  web/src/components/repo/pipeline/PipelineStatusIcon.vue
  web/src/views/repo/RepoWrapper.vue
  web/src/views/repo/pipeline/Pipeline.vue
Labels: ui, feature, build_pr_images

#4608 pre-commit prettier: switch to maintained fork
  .pre-commit-config.yaml
Labels: skip-changelog, build

#4609 Fix misaligned step list indentation
  web/src/components/repo/pipeline/PipelineStepList.vue
Labels: bug, ui, build_pr_images

#4618 Update docs section about "Custom clone plugins"
  .cspell.json
  docs/docs/20-usage/75-project-settings.md
Labels: documentation

#4613 Fix misleading example in Workflow syntax/Privileged mode
  docs/docs/20-usage/20-workflow-syntax.md
  docs/versioned_docs/version-2.8/20-usage/20-workflow-syntax.md
Labels: documentation

#4623 Reduce PR preview images
  .woodpecker/docker.yaml
  .woodpecker/test.yaml
Labels: skip-changelog, build, build_pr_images

#4621 fixed a typo
  docs/versioned_docs/version-2.8/30-administration/00-getting-started.md
Labels: documentation

#4612 Typo fix: instace -> instance
  docs/versioned_docs/version-2.8/10-intro/index.md
Labels: documentation, skip-changelog

#4346 Support Git as only VCS
  cli/exec/flags.go
  cli/exec/metadata.go
  cmd/server/openapi/docs.go
  docs/docs/20-usage/20-workflow-syntax.md
  docs/docs/20-usage/50-environment.md
  docs/src/pages/migrations.md
  pipeline/backend/local/clone.go
  pipeline/frontend/metadata/drone_compatibility.go
  pipeline/frontend/metadata/drone_compatibility_test.go
  pipeline/frontend/metadata/environment.go
  pipeline/frontend/metadata/types.go
  server/forge/bitbucket/convert.go
  server/forge/bitbucket/convert_test.go
  server/forge/bitbucket/parse_test.go
  server/forge/bitbucketdatacenter/convert.go
  server/forge/bitbucketdatacenter/convert_test.go
  server/forge/forgejo/helper.go
  server/forge/forgejo/parse_test.go
  server/forge/gitea/helper.go
  server/forge/gitea/parse_test.go
  server/forge/github/convert.go
  server/forge/github/convert_test.go
  server/model/const.go
  server/model/repo.go
  server/pipeline/stepbuilder/metadata.go
  server/pipeline/stepbuilder/metadata_test.go
  server/store/datastore/migration/008_set_default_forge_id.go
  server/store/datastore/migration/023_remove_repo_scm.go
  server/store/datastore/migration/migration.go
Labels: refactor, breaking

#4629 Avoid usage of inline css style
  web/src/components/repo/pipeline/PipelineStepList.vue
Labels: ui, refactor

#4611 Add lighter red shades for error messages
  web/src/components/admin/settings/queue/AdminQueueStats.vue
  web/src/components/agent/AgentList.vue
  web/src/components/atomic/Button.vue
  web/src/components/atomic/Error.vue
  web/src/components/layout/header/Navbar.vue
  web/src/components/registry/RegistryList.vue
  web/src/components/repo/pipeline/PipelineItem.vue
  web/src/components/repo/pipeline/PipelineStatusIcon.vue
  web/src/components/secrets/SecretList.vue
  web/src/style.css
  web/src/views/admin/AdminOrgs.vue
  web/src/views/admin/AdminQueue.vue
  web/src/views/admin/AdminUsers.vue
  web/src/views/repo/pipeline/Pipeline.vue
  web/src/views/repo/pipeline/PipelineDebug.vue
  web/src/views/repo/pipeline/PipelineErrors.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
  web/src/views/repo/settings/Crons.vue
  web/windi.config.ts
Labels: ui, build_pr_images

#4628 Add `prettier` to `docs/`
  .prettierignore
  .woodpecker/docs.yaml
  docs/.prettierignore
  docs/.prettierrc.js
  docs/docusaurus.config.ts
  docs/plugins/woodpecker-plugins/src/index.ts
  docs/plugins/woodpecker-plugins/src/theme/WoodpeckerPlugin.tsx
  docs/plugins/woodpecker-plugins/src/theme/WoodpeckerPluginList.tsx
  docs/plugins/woodpecker-plugins/src/theme/style.css
  docs/src/components/HomepageFeatures.js
  docs/src/pages/index.tsx
  docs/versioned_docs/version-1.0/20-usage/10-intro.md
  docs/versioned_docs/version-1.0/20-usage/15-terminology.md
  docs/versioned_docs/version-1.0/20-usage/20-pipeline-syntax.md
  docs/versioned_docs/version-1.0/20-usage/35-advanced-yaml-syntax.md
  docs/versioned_docs/version-1.0/20-usage/40-secrets.md
  docs/versioned_docs/version-1.0/20-usage/45-cron.md
  docs/versioned_docs/version-1.0/20-usage/51-plugins/10-plugins.md
  docs/versioned_docs/version-1.0/20-usage/90-pipeline-management.md
  docs/versioned_docs/version-1.0/30-administration/00-setup.md
  docs/versioned_docs/version-1.0/30-administration/10-server-config.md
  docs/versioned_docs/version-1.0/30-administration/100-external-configuration-api.md
  docs/versioned_docs/version-1.0/30-administration/11-forges/10-overview.md
  docs/versioned_docs/version-1.0/30-administration/11-forges/20-github.md
  docs/versioned_docs/version-1.0/30-administration/11-forges/30-gitea.md
  docs/versioned_docs/version-1.0/30-administration/11-forges/40-gitlab.md
  docs/versioned_docs/version-1.0/30-administration/11-forges/50-bitbucket.md
  docs/versioned_docs/version-1.0/30-administration/15-agent-config.md
  docs/versioned_docs/version-1.0/30-administration/22-backends/10-docker.md
  docs/versioned_docs/version-1.0/30-administration/22-backends/20-local.md
  docs/versioned_docs/version-1.0/30-administration/22-backends/30-ssh.md
  docs/versioned_docs/version-1.0/30-administration/22-backends/40-kubernetes.md
  docs/versioned_docs/version-1.0/30-administration/40-encryption.md
  docs/versioned_docs/version-1.0/30-administration/70-proxy.md
  docs/versioned_docs/version-1.0/30-administration/90-prometheus.md
  docs/versioned_docs/version-1.0/40-cli.md
  docs/versioned_docs/version-1.0/80-downloads.md
  docs/versioned_docs/version-1.0/91-migrations.md
  docs/versioned_docs/version-1.0/92-development/01-getting-started.md
  docs/versioned_docs/version-1.0/92-development/03-ui.md
  docs/versioned_docs/version-1.0/92-development/05-architecture.md
  docs/versioned_docs/version-1.0/92-development/06-guides.md
  docs/versioned_docs/version-1.0/92-development/08-swagger.md
  docs/versioned_docs/version-2.7/92-development/05-architecture.md
  docs/versioned_docs/version-2.8/20-usage/40-secrets.md
  docs/versioned_docs/version-2.8/20-usage/90-advanced-usage.md
Labels: documentation, skip-changelog, build

#4637 fix `depends_on` for docs workflow
  .woodpecker/docs.yaml
Labels: skip-changelog, build, regression

#4638 Drop dependency chain from docs workflow
  .woodpecker/docs.yaml
Labels: build, regression

#4636 Remove workflow-level volumes and networks
  pipeline/backend/docker/docker.go
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/types/config.go
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/compiler_test.go
  pipeline/frontend/yaml/parse_test.go
  pipeline/frontend/yaml/types/workflow.go
  pipeline/frontend/yaml/types/workflow_network.go
  pipeline/frontend/yaml/types/workflow_network_test.go
  pipeline/frontend/yaml/types/workflow_volume.go
  pipeline/frontend/yaml/types/workflow_volume_test.go
Labels: refactor

#4625 Two row layout for title and context of pipeline list
  web/src/components/repo/pipeline/PipelineItem.vue
Labels: ui, enhancement

#4584 Refactor icons: harmonize contextually, use filled status icons
  web/src/components/atomic/Button.vue
  web/src/components/atomic/Error.vue
  web/src/components/atomic/Icon.vue
  web/src/components/atomic/Warning.vue
  web/src/components/form/KeyValueEditor.vue
  web/src/components/layout/scaffold/Header.vue
  web/src/views/admin/AdminOrgs.vue
  web/src/views/admin/AdminQueue.vue
  web/src/views/admin/AdminRepos.vue
  web/src/views/repo/pipeline/PipelineErrors.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
  web/src/views/repo/settings/Crons.vue
Labels: ui, build_pr_images
