Repository woodpecker-ci/woodpecker, pull requests merged in 2024-04, with the labels that each got.

#3570 Allow to disable deployments
  cmd/server/docs/docs.go
  docs/docs/20-usage/71-project-settings.md
  server/api/pipeline.go
  server/api/repo.go
  server/model/repo.go
  web/src/assets/locales/en.json
  web/src/components/repo/settings/GeneralTab.vue
  web/src/lib/api/types/repo.ts
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: server, enhancement

#3589 Avoid brances in group names
  .github/renovate.json
Labels: skip-changelog, dependencies

#3588 Temp exclude huh/spinner from renovate
  .github/renovate.json
Labels: skip-changelog, dependencies

#3599 agent: Continue to retry indefinitely
  agent/rpc/client_grpc.go
Labels: bug, agent

#3612 Apply skip ci filter only on push events
  server/pipeline/create.go
Labels: bug, forge/github

#3451 Step logs removing API and Button
  cmd/server/docs/docs.go
  server/api/pipeline.go
  server/router/api.go
  web/src/assets/locales/en.json
  web/src/components/repo/pipeline/PipelineLog.vue
  web/src/lib/api/index.ts
Labels: ui, feature

#3580 Handle ImagePullBackOff pod status
  pipeline/backend/kubernetes/kubernetes.go
Labels: bug, backend/kubernetes

#3615 Fix docs
  .github/renovate.json
  docs/docs/10-intro.md
  docs/docs/30-administration/11-forges/60-bitbucket_datacenter.md
Labels: documentation

#3617 Remove review button from approval view
  web/src/assets/locales/en.json
  web/src/views/repo/pipeline/Pipeline.vue
Labels: ui, refactor

#3616 Fix make in_docker generate
  .cspell.json
  .mockery.yaml
  .pre-commit-config.yaml
  Makefile
  docker/Dockerfile.make
  pipeline/rpc/proto/generate.go
  pipeline/rpc/proto/woodpecker.pb.go
  pipeline/rpc/proto/woodpecker_grpc.pb.go
  server/forge/forge.go
  server/forge/mocks/forge.go
  server/store/mocks/store.go
  server/store/store.go
Labels: skip-changelog, build

#3618 fix cli config loading and correct comment
  cli/common/hooks.go
  cli/internal/config/config.go
Labels: bug, cli

#1417 Use forge from db
  cmd/server/docs/docs.go
  cmd/server/flags.go
  cmd/server/server.go
  cmd/server/setup.go
  pipeline/rpc/proto/woodpecker_grpc.pb.go
  server/api/cron.go
  server/api/helper.go
  server/api/hook.go
  server/api/login.go
  server/api/org.go
  server/api/pipeline.go
  server/api/repo.go
  server/api/user.go
  server/api/users.go
  server/cache/membership.go
  server/config.go
  server/cron/cron.go
  server/cron/cron_test.go
  server/forge/setup/setup.go
  server/grpc/rpc.go
  server/grpc/server.go
  server/model/forge.go
  server/model/org.go
  server/model/repo.go
  server/model/user.go
  server/pipeline/approve.go
  server/pipeline/cancel.go
  server/pipeline/create.go
  server/pipeline/decline.go
  server/pipeline/helper.go
  server/pipeline/items.go
  server/pipeline/restart.go
  server/pipeline/start.go
  server/router/middleware/session/repo.go
  server/router/middleware/session/user.go
  server/router/middleware/token/token.go
  server/services/environment/service.go
  server/services/manager.go
  server/services/mocks/manager.go
  server/services/setup.go
  server/store/datastore/forge.go
  server/store/datastore/forge_test.go
  server/store/datastore/migration/030_set_default_forge_id.go
  server/store/datastore/migration/migration.go
  server/store/mocks/store.go
  server/store/store.go
  server/web/config.go
  web/src/views/repo/RepoWrapper.vue
Labels: server, enhancement

#3628 bump golang.org/x/net to v0.24.0
  go.mod
  go.sum
Labels: security, dependencies

#3624 Use our github-release plugin
  .woodpecker/binaries.yaml
Labels: build

#3636 Add task details to queue info in woodpecker-go
  woodpecker-go/woodpecker/types.go
Labels: enhancement, lib

#3645 Add filter options to GetPipelines API
  cmd/server/docs/docs.go
  server/api/badge.go
  server/api/pipeline.go
  server/api/pipeline_test.go
  server/model/pipeline.go
  server/services/mocks/manager.go
  server/store/datastore/pipeline.go
  server/store/datastore/pipeline_test.go
  server/store/mocks/store.go
  server/store/store.go
Labels: server, enhancement

#3506 Add DeletePipeline API
  cmd/server/docs/docs.go
  server/api/helper.go
  server/api/pipeline.go
  server/api/pipeline_test.go
  server/router/api.go
Labels: server, enhancement

#3647 Split client into multiple files and add more tests
  .gitignore
  woodpecker-go/woodpecker/agent.go
  woodpecker-go/woodpecker/agent_test.go
  woodpecker-go/woodpecker/client.go
  woodpecker-go/woodpecker/client_test.go
  woodpecker-go/woodpecker/const.go
  woodpecker-go/woodpecker/global_secret.go
  woodpecker-go/woodpecker/interface.go
  woodpecker-go/woodpecker/org.go
  woodpecker-go/woodpecker/pipeline.go
  woodpecker-go/woodpecker/queue.go
  woodpecker-go/woodpecker/queue_test.go
  woodpecker-go/woodpecker/repo.go
  woodpecker-go/woodpecker/types.go
  woodpecker-go/woodpecker/user.go
  woodpecker-go/woodpecker/user_test.go
Labels: refactor, lib

#3620 Fix secret loading
  README.md
  server/router/api.go
  web/.eslintignore
  web/package.json
  web/pnpm-lock.yaml
  web/src/components/repo/settings/SecretsTab.vue
  web/src/compositions/usePaginate.test.ts
  web/src/compositions/usePaginate.ts
  web/vite.config.ts
Labels: bug

#3662 Add discord plugin
  docs/plugins/woodpecker-plugins/plugins.json
Labels: plugin, documentation

#2605 Allow running tests on arm64 runners
  .woodpecker/binaries.yaml
  .woodpecker/docker.yaml
Labels: build, build_pr_images
