Repository woodpecker-ci/woodpecker, pull requests merged in 2024-01, with the labels that each got.

#3097 Fix slice unmarshaling
  pipeline/frontend/yaml/compiler/dag.go
  pipeline/frontend/yaml/compiler/dag_test.go
  pipeline/frontend/yaml/parse_test.go
  pipeline/frontend/yaml/types/base/base_types_test.go
  pipeline/frontend/yaml/types/base/slice.go
Labels: bug, server

#3102 Add Reviewdog ESLint plugin
  docs/plugins/woodpecker-plugins/plugins.json
Labels: documentation

#3104 Pin Gitea version
  docker-compose.gitpod.yml
Labels: bug

#3103 Use WOODPECKER_AGENT_SECRET instead of deprecated alternative
  .gitpod.yml
  docs/docs/92-development/01-getting-started.md
  docs/versioned_docs/version-0.15/92-development/01-getting-started.md
  docs/versioned_docs/version-1.0/92-development/01-getting-started.md
  docs/versioned_docs/version-2.0/92-development/01-getting-started.md
  docs/versioned_docs/version-2.1/92-development/01-getting-started.md
Labels: documentation, devx

#3100 Remove env argument of addons
  docs/docs/30-administration/75-addons/20-creating-addons.md
  shared/addon/addon.go
Labels: refactor, addon

#3106 Unfold workflow when opening via URL
  web/src/components/repo/pipeline/PipelineStepList.vue
  web/src/views/repo/pipeline/Pipeline.vue
Labels: ui, enhancement

#3057 Fix `version.json` updates
  .woodpecker/docs.yml
Labels: build

#3112 Fix timeout settings contrast
  web/src/components/repo/settings/GeneralTab.vue
Labels: ui, enhancement

#3113 Add loading spinner and no pull request text
  web/src/assets/locales/en.json
  web/src/components/atomic/Icon.vue
  web/src/views/repo/RepoBranches.vue
  web/src/views/repo/RepoPullRequests.vue
Labels: ui, enhancement

#3114 Always show pipeline step list
  web/src/components/repo/pipeline/PipelineStepList.vue
  web/src/views/repo/pipeline/Pipeline.vue
Labels: ui, enhancement, ux

#3144 docs: bump follow-redirects because of sec issue
  docs/package.json
  docs/pnpm-lock.yaml
Labels: documentation, skip-changelog, dependencies

#3145 fix(deps): update docs npm deps non-major
  docs/package.json
  docs/pnpm-lock.yaml
Labels: documentation, skip-changelog, dependencies

#3146 Use js-base64 on pipeline log page
  web/src/components/repo/pipeline/PipelineLog.vue
Labels: ui, enhancement

#3141 Use step type to detect services in Kubernetes backend
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/kubernetes/pod.go
Labels: bug, backend/kubernetes

#3136 Use UUID instead of step name where possible
  pipeline/backend/local/clone.go
  pipeline/backend/local/local.go
  pipeline/error.go
  pipeline/error_test.go
  pipeline/pipeline.go
Labels: bug, backend/local

#3137 Add step name as label to docker containers
  pipeline/backend/docker/convert.go
  pipeline/backend/docker/convert_test.go
Labels: enhancement, backend/docker

#3149 Make service icon rotate
  web/src/components/repo/pipeline/PipelineStatusIcon.vue
  web/src/style.css
Labels: ui, enhancement

#3081 Make k8s backend configuration docs in the same format as others
  docs/docs/30-administration/22-backends/40-kubernetes.md
Labels: documentation, backend/kubernetes

#3139 Remove duplicate assignment of `CI_STEP_NAME`
  pipeline/frontend/yaml/compiler/convert.go
Labels: server, refactor, skip-changelog

#3142 Use name in backend types instead of alias
  agent/logger.go
  agent/tracer.go
  cli/exec/exec.go
  pipeline/backend/types/stage.go
  pipeline/backend/types/step.go
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/compiler_test.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/compiler/dag.go
  pipeline/frontend/yaml/compiler/dag_test.go
  pipeline/pipeline.go
  server/pipeline/items.go
Labels: refactor

#3143 Use step uuid instead of name in GRPC status calls
  agent/rpc/client_grpc.go
  agent/tracer.go
  pipeline/rpc/peer.go
  pipeline/rpc/proto/version.go
  pipeline/rpc/proto/woodpecker.pb.go
  pipeline/rpc/proto/woodpecker.proto
  server/grpc/rpc.go
  server/grpc/server.go
Labels: bug, server, agent

#3150 use animate-spin class
  web/src/components/repo/pipeline/PipelineStatusIcon.vue
  web/src/style.css
Labels: ui, refactor

#3153 ci: run release/publish cli after agent to have less ram consumption
  .woodpecker/docker.yml
Labels: skip-changelog, build

#3152 Add `make clean-all`
  Makefile
Labels: devx

#3154 TestToConfigSmall ignore sort order of env vars
  pipeline/backend/docker/convert_test.go
Labels: tests, skip-changelog

#3151 Step status update dont set to running again once it got stoped
  server/grpc/rpc.go
  server/pipeline/step_status.go
  server/pipeline/step_status_test.go
Labels: bug, server

#3079 Remove prefix from services
  .woodpecker/test.yml
Labels: skip-changelog, build

#3098 Add continous deployment cookbook
  docs/cookbook/2024-1-1-continous-deployment/index.md
Labels: documentation

#3155 Fix feed sorting
  web/src/utils/helpers.ts
Labels: bug, ui

#3129 Enable some linters
  .golangci.yml
  agent/state.go
  cmd/agent/agent.go
  cmd/agent/health.go
  cmd/server/server.go
  cmd/server/setup.go
  docs/docs/30-administration/10-server-config.md
  pipeline/backend/kubernetes/service.go
  pipeline/backend/kubernetes/service_test.go
  pipeline/frontend/metadata/environment.go
  server/forge/configFetcher.go
  server/forge/gitea/helper.go
  server/forge/github/convert_test.go
  server/forge/github/parse.go
  server/grpc/filter.go
  server/grpc/filter_test.go
  server/grpc/rpc.go
  server/grpc/server.go
  server/pipeline/queue.go
  server/pipeline/topic.go
  server/web/config.go
Labels: refactor

#3160 Fix startup panic
  cmd/server/server.go
Labels: bug, server, important, regression

#3125 Remove steps for publishing release branches
  .woodpecker/docker.yml
  .woodpecker/docs.yml
  .woodpecker/securityscan.yml
  .woodpecker/test.yml
  .woodpecker/web.yml
Labels: refactor, build

#3159 Enable `gocritic` and don't ignore globally
  .golangci.yml
  agent/runner.go
  cli/common/zerologger.go
  cli/secret/secret_info.go
  cli/secret/secret_list.go
  cmd/agent/agent.go
  cmd/agent/main.go
  cmd/cli/main.go
  cmd/server/main.go
  cmd/server/server.go
  cmd/server/setup.go
  pipeline/backend/common/script_win.go
  pipeline/backend/kubernetes/utils.go
  pipeline/frontend/yaml/compiler/cacher.go
  pipeline/frontend/yaml/constraint/constraint.go
  pipeline/frontend/yaml/matrix/matrix.go
  pipeline/frontend/yaml/parse.go
  server/api/helper.go
  server/api/user.go
  server/forge/bitbucket/fixtures/handler.go
  server/forge/common/status.go
  server/forge/gitea/helper.go
  server/forge/github/parse.go
  server/forge/gitlab/convert.go
  server/pipeline/pipelineStatus_test.go
  server/pipeline/step_status_test.go
  server/plugins/encryption/encryption_builder.go
  server/plugins/encryption/tink_keyset_watcher.go
  server/queue/fifo_test.go
  server/router/middleware/session/agent.go
  server/store/context.go
  server/store/datastore/migration/common.go
  server/web/web.go
  shared/logger/logger.go
Labels: refactor

#3161 Clean up logging
  agent/rpc/client_grpc.go
  cli/internal/util.go
  cmd/agent/agent.go
  cmd/server/setup.go
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/local/local.go
  server/api/login.go
  server/api/org.go
  server/api/repo.go
  server/api/stream.go
  server/grpc/auth_server.go
  server/grpc/rpc.go
  server/pipeline/restart.go
  server/plugins/encryption/tink_keyset.go
  server/plugins/encryption/tink_keyset_watcher.go
  server/queue/persistent.go
  server/router/middleware/session/repo.go
  server/router/middleware/session/user.go
  server/web/config.go
Labels: refactor

#3167 Enable golangci linter stylecheck
  .golangci.yml
  cli/common/flags.go
  cli/deploy/deploy.go
  cli/user/user_info.go
  docs/versioned_docs/version-1.0/30-administration/22-backends/20-local.md
  docs/versioned_docs/version-1.0/30-administration/22-backends/30-ssh.md
  docs/versioned_docs/version-2.0/30-administration/22-backends/20-local.md
  docs/versioned_docs/version-2.1/30-administration/22-backends/20-local.md
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/local/const.go
  pipeline/frontend/yaml/constraint/constraint.go
  pipeline/frontend/yaml/linter/schema/schema.go
  pipeline/frontend/yaml/types/base/base_types_test.go
  pipeline/frontend/yaml/types/base/int.go
  pipeline/frontend/yaml/types/base/map.go
  pipeline/frontend/yaml/types/base/slice.go
  pipeline/frontend/yaml/types/network.go
  pipeline/frontend/yaml/types/volume.go
  server/api/agent.go
  server/api/badge.go
  server/api/cron.go
  server/api/global_secret.go
  server/api/helper.go
  server/api/hook.go
  server/api/login.go
  server/api/metrics/prometheus.go
  server/api/org.go
  server/api/org_secret.go
  server/api/orgs.go
  server/api/pipeline.go
  server/api/registry.go
  server/api/repo.go
  server/api/repo_secret.go
  server/api/stream.go
  server/api/users.go
  server/forge/bitbucket/bitbucket.go
  server/forge/common/utils.go
  server/forge/configFetcher.go
  server/forge/configFetcher_test.go
  server/forge/gitea/gitea.go
  server/forge/github/github.go
  server/forge/gitlab/convert.go
  server/forge/gitlab/gitlab.go
  server/grpc/auth_server.go
  server/grpc/rpc.go
  server/model/registry.go
  server/model/secret.go
  server/pipeline/decline.go
  server/pipeline/stepbuilder/stepBuilder.go
  server/plugins/config/http.go
  server/plugins/encryption/constants.go
  server/plugins/registry/filesystem.go
  server/plugins/utils/http.go
  server/store/datastore/agent.go
  server/store/datastore/cron_test.go
  server/store/datastore/migration/migration.go
  server/web/web.go
  web/src/views/repo/pipeline/Pipeline.vue
Labels: refactor

#3135 Use UUID as podName and cleanup arguments for Kubernetes backend
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/kubernetes/pod_test.go
  pipeline/backend/kubernetes/service.go
  pipeline/backend/kubernetes/service_test.go
  pipeline/backend/kubernetes/utils.go
  pipeline/backend/kubernetes/utils_test.go
  pipeline/backend/kubernetes/volume_test.go
Labels: bug, refactor, backend/kubernetes

#3173 Lowercase all log strings
  cli/loglevel/loglevel.go
  cmd/agent/agent.go
  cmd/server/server.go
  cmd/server/setup.go
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/kubernetes/service.go
  pipeline/backend/kubernetes/volume.go
  pipeline/pipeline.go
  server/api/login.go
  server/api/org.go
  server/api/repo.go
  server/cron/cron.go
  server/forge/configFetcher.go
  server/forge/github/github.go
  server/grpc/auth_server.go
  server/grpc/rpc.go
  server/pipeline/items.go
  server/pipeline/start.go
  server/pipeline/stepbuilder/stepBuilder.go
  server/router/middleware/session/repo.go
  server/router/middleware/session/user.go
  shared/logger/logger.go
Labels: refactor

#3156 More docker backend test remove more undocumented
  pipeline/backend/docker/convert.go
  pipeline/backend/docker/convert_test.go
  pipeline/backend/types/step.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/linter/linter.go
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/frontend/yaml/types/container.go
Labels: refactor, backend/docker

#3162 Remove panic recovering
  server/queue/fifo.go
Labels: refactor

#3170 Enable golangci linter contextcheck
  .golangci.yaml
  agent/runner.go
  cli/exec/exec.go
  cmd/agent/agent.go
  pipeline/backend/backend.go
  pipeline/backend/docker/docker.go
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/pipeline.go
  server/pipeline/queue.go
  server/pipeline/start.go
Labels: refactor

#3168 Enable golangci linter forcetypeassert
  .golangci.yaml
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/local/local.go
  pipeline/frontend/yaml/constraint/constraint.go
  pipeline/frontend/yaml/types/network.go
  server/forge/bitbucket/bitbucket_test.go
  server/forge/gitea/gitea_test.go
  server/forge/github/github.go
  server/forge/github/github_test.go
  server/queue/fifo.go
  server/queue/fifo_test.go
  server/router/middleware/session/agent.go
  server/store/context.go
Labels: refactor

#3176 declare different when statements once and reuse them
  .woodpecker/docker.yaml
Labels: build

#3140 `cli exec`: let override existing environment values but print a warning
  cli/exec/exec.go
Labels: enhancement, cli

#3123 Kubernetes AppArmor and seccomp
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/kubernetes/pod_test.go
  pipeline/backend/types/backend_kubernetes.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/linter/schema/schema.json
  pipeline/frontend/yaml/types/backend_options.go
Labels: enhancement, backend/kubernetes, build_pr_images

#2993 Added protocol in port configuration
  docs/docs/20-usage/60-services.md
  pipeline/backend/docker/convert_test.go
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/kubernetes/pod_test.go
  pipeline/backend/kubernetes/service.go
  pipeline/backend/kubernetes/service_test.go
  pipeline/backend/types/network.go
  pipeline/backend/types/step.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/compiler/convert_test.go
  pipeline/frontend/yaml/types/container.go
  pipeline/frontend/yaml/types/container_test.go
Labels: enhancement, backend/kubernetes

#3185 fix(deps): update golang (packages)
  go.mod
  go.sum
Labels: dependencies

#3184 Document core development ideas
  docs/docs/92-development/01-getting-started.md
Labels: documentation

#3186 chore(deps): update docker.io/woodpeckerci/plugin-docker-buildx
  .woodpecker/docker.yaml
Labels: dependencies

#3198 Fix spelling in test description
  pipeline/shared/replace_secrets_test.go
Labels: tests, skip-changelog

#3202 Replace `goimports` with `gci`
  .golangci.yaml
  agent/rpc/auth_client_grpc.go
  cli/pipeline/create.go
  cmd/server/main.go
  cmd/server/server.go
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/kubernetes/pod_test.go
  pipeline/backend/kubernetes/service_test.go
  pipeline/backend/local/clone.go
  pipeline/frontend/metadata/drone_compatibility_test.go
  pipeline/frontend/yaml/compiler/convert_test.go
  pipeline/frontend/yaml/compiler/dag_test.go
  pipeline/frontend/yaml/matrix/matrix.go
  pipeline/frontend/yaml/types/base/base_types_test.go
  pipeline/frontend/yaml/types/network_test.go
  pipeline/frontend/yaml/types/volume_test.go
  server/api/global_secret.go
  server/api/org.go
  server/api/org_secret.go
  server/api/signature_public_key.go
  server/badges/badges_test.go
  server/cache/membership.go
  server/forge/bitbucket/internal/client.go
  server/grpc/rpc_test.go
  server/logging/log_test.go
  server/pipeline/stepbuilder/stepBuilder.go
  server/pipeline/topic.go
  server/plugins/encryption/aes_encryption.go
  server/plugins/permissions/repo_owners_test.go
  server/plugins/secrets/builtin_test.go
  server/plugins/utils/http_test.go
  server/queue/fifo.go
  server/queue/fifo_test.go
  server/router/middleware/session/pagination.go
  server/router/middleware/session/repo.go
  server/router/middleware/session/user.go
  server/store/datastore/cron.go
  server/store/datastore/engine.go
  server/store/datastore/engine_test.go
  server/store/datastore/helper_test.go
  server/store/datastore/log_test.go
  server/store/datastore/migration/migration_test.go
  server/web/web_test.go
Labels: refactor

#3201 Use `assert`
  cli/internal/util_test.go
  cmd/agent/config_test.go
  cmd/agent/health_test.go
  pipeline/backend/docker/convert_test.go
  pipeline/error_test.go
  pipeline/errors/error_test.go
  pipeline/frontend/yaml/compiler/option_test.go
  pipeline/frontend/yaml/constraint/constraint_test.go
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/frontend/yaml/parse_test.go
  pipeline/frontend/yaml/utils/image_test.go
  pipeline/rpc/log_entry_test.go
  server/api/helper_test.go
  server/forge/common/utils_test.go
  server/forge/gitlab/gitlab_test.go
  server/grpc/rpc_test.go
  server/model/user_test.go
  server/pipeline/pipelineStatus_test.go
  server/pipeline/step_status_test.go
  server/plugins/utils/http_test.go
  server/queue/fifo_test.go
  server/store/datastore/agent_test.go
  server/store/datastore/config_test.go
  server/store/datastore/feed_test.go
  server/store/datastore/permission_test.go
  server/store/datastore/redirection_test.go
  server/store/datastore/registry_test.go
  server/store/datastore/repo_test.go
  server/store/datastore/secret_test.go
  server/store/datastore/server_config_test.go
  server/store/datastore/step_test.go
  server/store/datastore/task_test.go
  server/store/datastore/workflow_test.go
  woodpecker-go/woodpecker/client_test.go
Labels: refactor, tests

#3196 Do not run prettier with pre-commit
  .pre-commit-config.yaml
  .prettierignore
  .woodpecker/test.yaml
  web/.prettierignore
Labels: build

#3204 Secured kubernetes backend configuration
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/kubernetes/kubernetes_test.go
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/kubernetes/service.go
  pipeline/backend/kubernetes/service_test.go
  pipeline/backend/kubernetes/volume.go
  pipeline/backend/kubernetes/volume_test.go
Labels: refactor, backend/kubernetes

#3211 Retrieve all user repo perms with a single API call
  server/forge/bitbucket/bitbucket.go
  server/forge/bitbucket/fixtures/handler.go
  server/forge/bitbucket/internal/client.go
  server/forge/bitbucket/internal/types.go
Labels: enhancement, forge/bitbucket

#2985 Support custom steps entrypoint
  docs/docs/20-usage/20-workflow-syntax.md
  pipeline/backend/common/script.go
  pipeline/backend/common/script_test.go
  pipeline/backend/docker/convert.go
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/kubernetes/pod_test.go
  pipeline/backend/local/local.go
  pipeline/frontend/metadata/const.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/types/container.go
  pipeline/frontend/yaml/types/container_test.go
Labels: feature, pipeline-config

#3220 Remove some interfaces
  cmd/server/server.go
  server/forge/configFetcher.go
  server/router/middleware/store.go
  server/store/context.go
Labels: refactor, skip-changelog

#3235 Fix Bitbucket get pull requests that ignores pagination
  server/forge/bitbucket/internal/client.go
Labels: bug, forge/bitbucket

#3236 Fixed Pods creation of WP services
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/kubernetes/pod.go
Labels: bug, backend/kubernetes

#3243 Add gitea/forgejo driver check, to handle ErrUnknownVersion error
  server/forge/gitea/gitea.go
Labels: bug, forge/gitea

#3244 Build tarball for distribution packages
  .woodpecker/binaries.yaml
  .woodpecker/docker.yaml
  Makefile
Labels: build

#3246 build: fix nfpm path for server binary
  nfpm/server.yaml
Labels: build

#3250 Update UI building in Makefile
  Makefile
Labels: build

#3259 Fix prettier
  docs/plugins/woodpecker-plugins/tsconfig.json
  docs/tsconfig.json
Labels: build

#3260 Pin prettier version
  .woodpecker/test.yaml
  pipeline/backend/kubernetes/kubernetes.go
Labels: build

#3258 Fix disabling PRs
  server/api/hook.go
Labels: bug, server

#3275 Sanitize pod's step label
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/kubernetes/pod_test.go
  pipeline/backend/kubernetes/utils.go
  pipeline/backend/kubernetes/utils_test.go
Labels: bug, backend/kubernetes

#3271 Improve secret available checks
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/compiler_test.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/compiler/settings/params.go
  pipeline/frontend/yaml/compiler/settings/params_test.go
  server/model/secret.go
  server/model/secret_test.go
  server/pipeline/stepbuilder/stepBuilder.go
Labels: enhancement, ux

#3289 Fix deprecated `group`
  .woodpecker/test.yaml
Labels: build

#3296 Reload site on theme change
  web/src/compositions/useTheme.ts
Labels: ui, enhancement, build_pr_images

#3299 Fix Gitpod: Gitea auth token creation
  .gitpod.yml
Labels: bug, devx

#3303 Add release types
  docs/docs/20-usage/15-terminiology/index.md
  docs/docs/20-usage/20-workflow-syntax.md
  server/api/queue.go
Labels: documentation

#3304 Remove accidentally added file
  server/api/queue.go
Labels: skip-changelog
