Repository woodpecker-ci/woodpecker, pull requests merged in 2024-08, with the labels that each got.

#3985 Fix BB PR pipeline ref
  server/forge/bitbucket/convert.go
  server/forge/bitbucket/convert_test.go
Labels: bug, forge/bitbucket

#3995 Overhaul README
  README.md
  cmd/server/swagger.go
  docs/docs/30-administration/05-deployment-methods/30-third-party.md
  docs/docs/woodpecker.png
  docs/docusaurus.config.ts
  docs/src/pages/index.tsx
  docs/versioned_docs/version-2.5/10-intro.md
  docs/versioned_docs/version-2.6/10-intro.md
  server/forge/github/fixtures/hooks.go
Labels: documentation

#4003 Remove reverted PR from changelog
  CHANGELOG.md
Labels: skip-changelog

#4010 [Bitbucket Datacenter] Return empty list instead of null
  server/forge/bitbucketdatacenter/bitbucketdatacenter.go
Labels: bug, forge/bitbucket

#3785 Migrate to maintained cron lib and remove seconds
  docs/docs/20-usage/45-cron.md
  docs/docs/91-migrations.md
  go.mod
  go.sum
  server/cron/cron.go
  server/model/cron.go
  server/store/datastore/migration/033_cron_without_sec.go
  server/store/datastore/migration/migration.go
  web/src/components/repo/settings/CronTab.vue
Labels: refactor, breaking, dependencies, build_pr_images

#3981 Move manual popup to own page
  server/api/repo.go
  web/src/assets/locales/en.json
  web/src/components/layout/popups/ManualPipelinePopup.vue
  web/src/router.ts
  web/src/views/repo/RepoManualPipeline.vue
  web/src/views/repo/RepoWrapper.vue
Labels: ui, refactor

#3968 Refactor JSON and SDK fields
  cmd/server/docs/docs.go
  docs/docs/91-migrations.md
  server/model/cron.go
  server/model/feed.go
  server/model/pipeline.go
  server/model/step.go
  server/model/workflow.go
  server/store/datastore/migration/034_rename_start_end_time.go
  server/store/datastore/migration/migration.go
  web/src/components/repo/pipeline/PipelineLog.vue
  web/src/components/repo/pipeline/PipelineStepDuration.vue
  web/src/components/repo/pipeline/PipelineStepList.vue
  web/src/compositions/usePipeline.ts
  web/src/lib/api/types/pipeline.ts
  web/src/utils/helpers.ts
  woodpecker-go/woodpecker/types.go
Labels: refactor, breaking

#4006 Improved Local backend detection
  docker/Dockerfile.agent.alpine.multiarch
  docker/Dockerfile.agent.multiarch
  pipeline/backend/local/local.go
Labels: breaking, backend/local

#3980 Show error returned from API
  web/src/compositions/useAsyncAction.ts
  web/src/lib/api/client.ts
Labels: ui, enhancement

#4014 Show error if secret name is missing
  cli/secret/secret_info.go
Labels: cli, ux

#4021 Set refspec for gitlab MR
  server/forge/gitlab/convert.go
Labels: bug, forge/gitlab

#4020 Fix cron migration
  server/store/datastore/migration/033_cron_without_sec.go
Labels: bug, server, regression, build_pr_images

#4032 Fix lint
  pipeline/backend/kubernetes/pod_test.go
  pipeline/frontend/yaml/linter/linter.go
  server/grpc/rpc.go
  server/pipeline/approve.go
  server/pipeline/create.go
  server/pipeline/decline.go
  server/pipeline/restart.go
Labels: refactor, skip-changelog

#4031 Only update agent.LastWork if not done recently
  server/grpc/rpc.go
Labels: server, enhancement

#4027 Warn if using secrets/env with plugin
  docs/docs/20-usage/51-plugins/51-overview.md
  pipeline/frontend/yaml/linter/linter.go
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/frontend/yaml/linter/schema/schema.json
  pipeline/frontend/yaml/types/container.go
Labels: security, backport

#4047 cspell: ignore all Go files generated by protobuf
  .cspell.json
Labels: skip-changelog

#4044 move arbitrary number into const
  server/grpc/rpc.go
Labels: refactor, skip-changelog

#4009 Add examples of CI environment variable values
  docs/docs/20-usage/50-environment.md
Labels: documentation

#3986 Add systemd unit files to the RPM/DEB packages
  nfpm/agent.yaml
  nfpm/server.yaml
  nfpm/woodpecker-agent.env.example
  nfpm/woodpecker-agent.service
  nfpm/woodpecker-server.env.example
  nfpm/woodpecker-server.service
Labels: build

#4048 Read long log lines from file storage correctly
  agent/logger.go
  cli/exec/exec.go
  pipeline/const.go
  server/services/log/file/file.go
Labels: bug, server

#4054 chore(deps): update docker.io/woodpeckerci/plugin-docker-buildx docker tag to v4.2.0
  .woodpecker/docker.yaml
Labels: skip-changelog, build, dependencies

#4068 Wait for tracer to be done before finishing workflow
  agent/rpc/client_grpc.go
  agent/runner.go
  agent/tracer.go
  pipeline/pipeline.go
Labels: bug, server

#4062 Move event type descriptions from Terminology to Workflow Syntax
  docs/docs/20-usage/15-terminology/index.md
  docs/docs/20-usage/20-workflow-syntax.md
  docs/docs/20-usage/50-environment.md
Labels: documentation

#4069 Add option to filter secrets by plugins with specific tags
  docs/docs/20-usage/40-secrets.md
  docs/docs/91-migrations.md
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/utils/image.go
  pipeline/frontend/yaml/utils/image_test.go
Labels: enhancement, breaking, security

#4070 Add some posts and videos
  .cspell.json
  docs/docs/92-awesome.md
Labels: documentation

#3918 Remove all default 3rd party privileged plugins
  cmd/server/flags.go
  cmd/server/setup.go
  docs/docs/91-migrations.md
  pipeline/frontend/yaml/linter/linter.go
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/frontend/yaml/linter/option.go
  pipeline/frontend/yaml/utils/image_test.go
  server/config.go
  server/pipeline/stepbuilder/stepBuilder.go
  shared/constant/constant.go
Labels: enhancement, breaking, security
