Repository woodpecker-ci/woodpecker, pull requests merged in 2024-03, with the labels that each got.

#3384 Cli setup command
  cli/common/flags.go
  cli/common/hooks.go
  cli/common/zerologger.go
  cli/internal/config/config.go
  cli/setup/setup.go
  cli/setup/token_fetcher.go
  cli/setup/ui/ask.go
  cli/setup/ui/confirm.go
  cmd/cli/app.go
  go.mod
  go.sum
  web/components.d.ts
  web/src/assets/locales/en.json
  web/src/components/user/UserCLIAndAPITab.vue
  web/src/router.ts
  web/src/views/User.vue
  web/src/views/cli/Auth.vue
Labels: feature, cli

#3482 Improve security context handling
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/kubernetes/pod_test.go
Labels: bug

#3488 Bump follow-redirects and fix broken anchors
  docs/docs/20-usage/30-matrix-workflows.md
  docs/docs/20-usage/51-plugins/20-creating-plugins.md
  docs/docs/30-administration/15-agent-config.md
  docs/docs/92-development/03-ui.md
  docs/package.json
  docs/plugins/woodpecker-plugins/plugins.json
  docs/pnpm-lock.yaml
  docs/versioned_docs/version-0.15/30-administration/15-agent-config.md
  docs/versioned_docs/version-0.15/92-development/03-ui.md
  docs/versioned_docs/version-0.15/92-development/04-docs.md
  docs/versioned_docs/version-1.0/92-development/03-ui.md
  docs/versioned_docs/version-2.0/20-usage/30-matrix-workflows.md
  docs/versioned_docs/version-2.0/30-administration/10-server-config.md
  docs/versioned_docs/version-2.0/30-administration/15-agent-config.md
  docs/versioned_docs/version-2.0/92-development/03-ui.md
  docs/versioned_docs/version-2.1/20-usage/30-matrix-workflows.md
  docs/versioned_docs/version-2.1/30-administration/15-agent-config.md
  docs/versioned_docs/version-2.1/92-development/03-ui.md
  docs/versioned_docs/version-2.2/20-usage/30-matrix-workflows.md
  docs/versioned_docs/version-2.2/30-administration/15-agent-config.md
  docs/versioned_docs/version-2.2/92-development/03-ui.md
  docs/versioned_docs/version-2.3/20-usage/30-matrix-workflows.md
  docs/versioned_docs/version-2.3/30-administration/15-agent-config.md
  docs/versioned_docs/version-2.3/92-development/03-ui.md
Labels: documentation

#3497 Temp rename CI services to avoid duplicate name issues
  .woodpecker/test.yaml
Labels: build

#3498 Fix skip setup for some general cli commands
  cli/internal/config/config.go
Labels: bug, cli

#3502 rename stepID to workflowID to reflect value
  server/pipeline/stepbuilder/stepBuilder.go
Labels: refactor, skip-changelog

#3504 Update pipeline state on server as a whole on approval
  server/forge/mocks/forge.go
  server/pipeline/approve.go
  server/pipeline/items.go
  server/store/datastore/pipeline.go
  server/store/datastore/workflow.go
  server/store/mocks/store.go
  server/store/store.go
  web/components.d.ts
Labels: bug, regression

#3505 Revert service names in CI
  .woodpecker/test.yaml
Labels: skip-changelog

#3509 Post on mastodon when releasing a new version
  .woodpecker/social.yaml
Labels: build

#3521 Fix golangci-lint version pinning
  Makefile
Labels: skip-changelog, build

#3516 Fix uppercased env
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/compiler/settings/params.go
  pipeline/frontend/yaml/compiler/settings/params_test.go
Labels: bug

#3522 Only allow to deploy from push, tag and release
  server/api/pipeline.go
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: security

#3524 Add option to set the local repository path to the cli command exec.
  cli/exec/exec.go
  cli/exec/flags.go
  docs/versioned_docs/version-2.4/40-cli.md
Labels: enhancement, cli

#3527 Switch back to latest version of golangci
  .pre-commit-config.yaml
  Makefile
Labels: skip-changelog, build

#3534 Fix flag name
  cmd/server/flags.go
  server/services/setup.go
Labels: bug

#3542 Remove `esbuild-loader`
  docs/docusaurus.config.ts
  docs/package.json
  docs/pnpm-lock.yaml
Labels: documentation
