Repository woodpecker-ci/woodpecker, pull requests merged in 2024-09, with the labels that each got.

#4072 Use kaniko plugin in docs as example
  docs/docs/20-usage/20-workflow-syntax.md
  docs/docs/20-usage/50-environment.md
  docs/docs/20-usage/51-plugins/51-overview.md
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/frontend/yaml/utils/image_test.go
Labels: documentation

#4074 Allow alter trusted clone plugins and filter them via tag
  cli/exec/exec.go
  cli/lint/lint.go
  cmd/server/flags.go
  cmd/server/setup.go
  docs/docs/30-administration/10-server-config.md
  docs/docs/91-migrations.md
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/compiler_test.go
  pipeline/frontend/yaml/compiler/option.go
  pipeline/frontend/yaml/compiler/option_test.go
  pipeline/frontend/yaml/linter/linter.go
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/frontend/yaml/linter/option.go
  pipeline/frontend/yaml/types/container.go
  server/config.go
  server/pipeline/stepbuilder/stepBuilder.go
  shared/constant/constant.go
Labels: server, enhancement, security

#4075 Allow admins to specify priviledged plugins by name **and tag**
  docs/docs/30-administration/10-server-config.md
  docs/docs/91-migrations.md
  pipeline/frontend/yaml/compiler/convert.go
Labels: server, enhancement, security

#4076 Allow admins to specify priviledged plugins by name **and tag** (#4075)
  docs/docs/30-administration/10-server-config.md
  docs/versioned_docs/version-2.7/30-administration/10-server-config.md
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/utils/image.go
  pipeline/frontend/yaml/utils/image_test.go
Labels: server, enhancement, security

#4083 Linter: respect tags for linting of global privileged plugins
  pipeline/frontend/yaml/linter/linter.go
  pipeline/frontend/yaml/linter/linter_test.go
Labels: enhancement, skip-changelog

#4088 Better migration wording in docs for remove of all default privileged plugins
  docs/docs/91-migrations.md
Labels: documentation, skip-changelog

#4084 [Backport] Lint privileged plugin match and allow to be set empty
  cmd/server/flags.go
  cmd/server/setup.go
  pipeline/frontend/yaml/linter/linter.go
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/frontend/yaml/linter/option.go
  server/pipeline/stepbuilder/stepBuilder.go
Labels: enhancement, security

#4087 Add indices to repo table
  server/model/repo.go
Labels: server, enhancement

#4089 Correct migrations text
  docs/docs/91-migrations.md
Labels: documentation

#4093 Fix org settings page (#4002)
  web/src/views/org/OrgSettings.vue
Labels: bug, ui

#4090 🎉 Release 2.7.1
  CHANGELOG.md
Labels: documentation, skip-changelog

#4091 🎉 Release 2.7.1 (#4090)
  CHANGELOG.md
Labels: documentation, skip-changelog, blocked

#3846 Remove some ci environment variables
  agent/tracer.go
  cli/exec/flags.go
  docs/docs/20-usage/50-environment.md
  docs/docs/91-migrations.md
  pipeline/frontend/metadata/drone_compatibility.go
  pipeline/frontend/metadata/drone_compatibility_test.go
  pipeline/frontend/metadata/environment.go
  pipeline/tracer.go
  server/pipeline/stepbuilder/metadata_test.go
Labels: refactor, breaking

#4109 Allow to restart declined pipelines
  server/pipeline/restart.go
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: enhancement

#4108 Don't expose task data via api
  cmd/server/docs/docs.go
  server/model/task.go
  web/src/lib/api/types/queue.ts
  woodpecker-go/woodpecker/agent_test.go
  woodpecker-go/woodpecker/queue_test.go
  woodpecker-go/woodpecker/types.go
Labels: enhancement, breaking, security

#4119 Make cli exec metadata on pair with build in server generated metadata
  cli/exec/exec.go
  cli/exec/flags.go
  cli/exec/metadata.go
  pipeline/frontend/metadata/environment.go
  pipeline/frontend/metadata/types.go
  server/pipeline/stepbuilder/metadata.go
  server/pipeline/stepbuilder/metadata_test.go
Labels: enhancement, cli

#4120 Remove unused struct from metadata
  pipeline/frontend/metadata/types.go
  pipeline/rpc/proto/woodpecker.pb.go
  pipeline/rpc/proto/woodpecker_grpc.pb.go
Labels: refactor, skip-changelog

#4045 Process workflow logs in batches
  agent/rpc/client_grpc.go
  cmd/agent/core/agent.go
  pipeline/log/line_writer.go
  pipeline/log/line_writer_test.go
  pipeline/rpc/mocks/peer.go
  pipeline/rpc/peer.go
  pipeline/rpc/proto/version.go
  pipeline/rpc/proto/woodpecker.pb.go
  pipeline/rpc/proto/woodpecker.proto
  server/api/stream.go
  server/grpc/rpc.go
  server/grpc/server.go
  server/logging/log.go
  server/logging/log_test.go
  server/logging/logging.go
  server/services/log/file/file.go
  server/services/log/service.go
  server/store/datastore/log.go
  server/store/datastore/log_test.go
  server/store/mocks/store.go
  server/store/store.go
Labels: server, agent, enhancement, build_pr_images

#4124 Fix agent last work update throttling
  server/grpc/rpc.go
  server/grpc/rpc_test.go
Labels: bug

#4126 Fix agent last work update throttling (#4124)
  server/grpc/rpc.go
  server/grpc/rpc_test.go
Labels: regression

#4123 Docs: reference to built-in docker compose and remove deprecated version from compose examples
  docs/docs/30-administration/00-getting-started.md
  docs/docs/30-administration/05-deployment-methods/10-docker-compose.md
  docs/docs/30-administration/10-database.md
  docs/docs/30-administration/10-server-config.md
  docs/docs/30-administration/11-forges/30-gitea.md
  docs/docs/30-administration/11-forges/60-bitbucket_datacenter.md
  docs/docs/30-administration/40-advanced/10-proxy.md
  docs/docs/30-administration/40-advanced/20-ssl.md
  docs/docs/30-administration/40-advanced/30-autoscaler.md
Labels: documentation

#4114 Restart tasks on dead agents sooner
  agent/runner.go
  server/queue/fifo.go
  server/queue/fifo_test.go
  shared/constant/constant.go
Labels: server, enhancement

#4115 Run queue.process() in background
  server/queue/fifo.go
  server/queue/fifo_test.go
Labels: bug, server

#4134 build: web: test should wait for format-check
  .woodpecker/web.yaml
Labels: skip-changelog, build

#4128 Set repo user to repairing user when old user is missing
  server/api/repo.go
Labels: server, enhancement

#4130 Set `/woodpecker` as default workdir for the **woodpecker-cli** container
  docker/Dockerfile.cli.alpine.multiarch
  docker/Dockerfile.cli.multiarch
  docs/docs/91-migrations.md
Labels: breaking, cli

#4135 Fix repo add loading spinner
  web/src/views/RepoAdd.vue
Labels: bug, ui

#4136 Default git clone support sha256
  shared/constant/constant.go
Labels: feature, dependencies

#4138 static workflow: let lychee pretend to be curl
  .woodpecker/static.yaml
Labels: skip-changelog, build

#4129 cli exec: fix flag type and remove uneffective ones
  cli/exec/flags.go
  cli/exec/metadata.go
Labels: bug, documentation, refactor, cli

#4142 cli exec: rename "--pipeline-files" to "--pipeline-changed-files"
  cli/exec/flags.go
  cli/exec/metadata.go
Labels: skip-changelog, cli

#4132 Ensure cli exec has by default not the same prefix
  cli/exec/exec.go
  cli/exec/flags.go
Labels: bug, cli

#4103 Replay pipeline using `cli exec` by downloading metadata
  cli/exec/exec.go
  cli/exec/flags.go
  cli/exec/metadata.go
  cli/exec/metadata_test.go
  cmd/server/docs/docs.go
  server/api/pipeline.go
  server/api/pipeline_test.go
  server/pipeline/items.go
  server/pipeline/stepbuilder/metadata.go
  server/pipeline/stepbuilder/metadata_test.go
  server/pipeline/stepbuilder/stepBuilder.go
  server/pipeline/stepbuilder/stepBuilder_test.go
  server/router/api.go
  web/src/assets/locales/en.json
  web/src/lib/api/index.ts
  web/src/router.ts
  web/src/views/repo/pipeline/PipelineDebug.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
  woodpecker-go/woodpecker/interface.go
  woodpecker-go/woodpecker/mocks/client.go
  woodpecker-go/woodpecker/pipeline.go
Labels: server, ui, feature, cli

#4143 Update image filter error message
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/compiler_test.go
  web/src/assets/locales/en.json
Labels: documentation

#3174 Move docker resource limit settings from server to agent
  cmd/server/flags.go
  cmd/server/setup.go
  docs/docs/30-administration/10-server-config.md
  docs/docs/30-administration/22-backends/10-docker.md
  docs/docs/91-migrations.md
  pipeline/backend/docker/config.go
  pipeline/backend/docker/convert.go
  pipeline/backend/docker/convert_test.go
  pipeline/backend/docker/docker.go
  pipeline/backend/docker/flags.go
  pipeline/backend/types/step.go
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/compiler/option.go
  pipeline/frontend/yaml/compiler/option_test.go
  pipeline/frontend/yaml/linter/linter.go
  pipeline/frontend/yaml/linter/linter_test.go
  pipeline/frontend/yaml/types/container.go
  pipeline/frontend/yaml/types/container_test.go
  server/config.go
  server/model/resource_limit.go
  server/pipeline/stepbuilder/stepBuilder.go
Labels: enhancement, breaking

#4092 Implement registries for Kubernetes backend
  docs/docs/20-usage/41-registries.md
  docs/docs/30-administration/22-backends/40-kubernetes.md
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/kubernetes/pod_test.go
  pipeline/backend/kubernetes/secrets.go
  pipeline/backend/kubernetes/secrets_test.go
  pipeline/frontend/yaml/utils/image.go
Labels: enhancement, backend/kubernetes, build_pr_images

#3539 Implement org/user agents
  cmd/server/docs/docs.go
  server/api/agent.go
  server/grpc/auth_server.go
  server/grpc/rpc.go
  server/model/agent.go
  server/model/agent_test.go
  server/model/task.go
  server/model/task_test.go
  server/pipeline/queue.go
  server/queue/fifo.go
  server/queue/queue.go
  server/router/api.go
  server/store/datastore/agent.go
  server/store/datastore/agent_test.go
  server/store/datastore/migration/015_add_org_agents.go
  server/store/datastore/migration/migration.go
  server/store/mocks/store.go
  server/store/store.go
  web/src/assets/locales/en.json
  web/src/components/admin/settings/AdminAgentsTab.vue
  web/src/components/admin/settings/AdminQueueTab.vue
  web/src/components/agent/AgentForm.vue
  web/src/components/agent/AgentList.vue
  web/src/components/agent/AgentManager.vue
  web/src/components/org/settings/OrgAgentsTab.vue
  web/src/components/user/UserAgentsTab.vue
  web/src/lib/api/index.ts
  web/src/lib/api/types/agent.ts
  web/src/lib/api/types/queue.ts
  web/src/views/User.vue
  web/src/views/org/OrgSettings.vue
  woodpecker-go/woodpecker/types.go
Labels: server, feature, build_pr_images, highlight
