Repository woodpecker-ci/woodpecker, pull requests merged in 2024-05, with the labels that each got.

#3663 Cleanup api docs and ts api-client options
  cli/common/flags.go
  cmd/server/docs/docs.go
  go.sum
  server/api/agent.go
  server/api/badge.go
  server/api/cron.go
  server/api/global_secret.go
  server/api/hook.go
  server/api/org.go
  server/api/org_secret.go
  server/api/orgs.go
  server/api/pipeline.go
  server/api/registry.go
  server/api/repo.go
  server/api/repo_secret.go
  server/api/stream.go
  server/api/user.go
  server/api/users.go
  web/src/components/admin/settings/AdminAgentsTab.vue
  web/src/components/admin/settings/AdminOrgsTab.vue
  web/src/components/admin/settings/AdminReposTab.vue
  web/src/components/admin/settings/AdminSecretsTab.vue
  web/src/components/admin/settings/AdminUsersTab.vue
  web/src/components/layout/popups/ManualPipelinePopup.vue
  web/src/components/org/settings/OrgSecretsTab.vue
  web/src/components/repo/settings/BadgeTab.vue
  web/src/components/repo/settings/CronTab.vue
  web/src/components/repo/settings/RegistriesTab.vue
  web/src/components/repo/settings/SecretsTab.vue
  web/src/components/user/UserSecretsTab.vue
  web/src/lib/api/index.ts
  web/src/store/pipelines.ts
  web/src/views/repo/RepoBranches.vue
  web/src/views/repo/RepoPullRequests.vue
Labels: documentation, refactor

#3660 Add cli output handlers
  cli/common/flags.go
  cli/output/output.go
  cli/output/table.go
  cli/output/table_test.go
  cli/pipeline/create.go
  cli/pipeline/info.go
  cli/pipeline/last.go
  cli/pipeline/list.go
  cli/pipeline/list_test.go
  cli/pipeline/pipeline.go
  cli/pipeline/pipeline_test.go
  woodpecker-go/woodpecker/interface.go
  woodpecker-go/woodpecker/mocks/client.go
Labels: enhancement, cli

#3675 Add class to forge button be easey to select for css
  web/src/views/repo/RepoWrapper.vue
Labels: ui, skip-changelog

#3679 Clarify info on failing workflows/Steps
  docs/docs/20-usage/20-workflow-syntax.md
Labels: documentation

#3678 Add discord announcements
  .woodpecker/social.yaml
Labels: build

#3683 Fix parent pipeline env
  server/pipeline/restart.go
Labels: bug

#3688 Check for error in repo middleware
  server/router/middleware/session/repo.go
Labels: bug, server

#3692 Skip golangci in pre-commit.ci
  .pre-commit-config.yaml
Labels: build

#3696 Pin golang container to minor release
  .gitpod.yml
  .woodpecker/binaries.yaml
  .woodpecker/docker.yaml
  .woodpecker/docs.yaml
  .woodpecker/test.yaml
Labels: skip-changelog, build

#3700 use wayback machine to fix offline link
  docs/docs/92-awesome.md
Labels: documentation, skip-changelog

#3699 Make retry count of config fetching form forge configure
  cmd/server/flags.go
  docs/docs/30-administration/10-server-config.md
  server/services/config/combined_test.go
  server/services/config/forge.go
  server/services/config/forge_test.go
  server/services/manager.go
  server/services/setup.go
Labels: server, enhancement

#3687 Add documentation for setting Kubernetes labels and annotations
  docs/docs/30-administration/22-backends/40-kubernetes.md
Labels: documentation, backend/kubernetes

#3702 Add nix flake for dev shell
  .cspell.json
  flake.lock
  flake.nix
Labels: devx

#3704 flake: add flake-utils import and use eachDefaultSystem
  flake.lock
  flake.nix
Labels: devx

#3703 Lint file names and directories via cSpell too
  .cspell.json
  .woodpecker/static.yaml
  CHANGELOG.md
  Makefile
  docs/cookbook/2024-1-1-continuous-deployment/index.md
  pipeline/frontend/metadata/substitution.go
  pipeline/frontend/metadata/substitution_test.go
Labels: refactor

#3670 Cleanup server env settings
  .gitpod.yml
  cmd/server/flags.go
  cmd/server/server.go
  docs/docs/20-usage/15-terminology/index.md
  docs/docs/91-migrations.md
  server/forge/bitbucketdatacenter/bitbucketdatacenter.go
  server/forge/gitea/gitea.go
  server/forge/github/github.go
  server/forge/gitlab/gitlab.go
  server/forge/setup/setup.go
  server/model/forge.go
  server/services/setup.go
Labels: refactor

#3717 Remove discord as official community channel
  README.md
  docs/docusaurus.config.ts
Labels: documentation, governance

#3706 cspell lint go code
  .cspell.json
  .woodpecker/binaries.yaml
  .woodpecker/docker.yaml
  .woodpecker/securityscan.yaml
  .woodpecker/static.yaml
  .woodpecker/test.yaml
  .woodpecker/web.yaml
  agent/logger.go
  agent/runner.go
  agent/tracer.go
  cli/deploy/deploy.go
  cli/exec/exec.go
  cli/internal/util.go
  cli/lint/lint.go
  cli/output/table.go
  cli/pipeline/pipeline.go
  cli/registry/registry_add.go
  cli/registry/registry_set.go
  cli/update/tar.go
  cli/update/updater.go
  cmd/agent/core/agent.go
  cmd/agent/core/flags.go
  cmd/agent/core/health.go
  pipeline/backend/common/script.go
  pipeline/backend/docker/convert.go
  pipeline/backend/docker/docker.go
  pipeline/backend/kubernetes/flags.go
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/kubernetes/service.go
  pipeline/backend/kubernetes/utils.go
  pipeline/backend/kubernetes/volume.go
  pipeline/backend/local/command.go
  pipeline/frontend/yaml/compiler/option.go
  pipeline/frontend/yaml/constraint/constraint.go
  pipeline/frontend/yaml/linter/schema/schema.go
  pipeline/frontend/yaml/matrix/matrix.go
  pipeline/frontend/yaml/types/base/bool.go
  pipeline/frontend/yaml/types/volume.go
  pipeline/rpc/proto/woodpecker.proto
  pipeline/shared/replace_secrets.go
  server/router/router.go
  server/services/config/http.go
  server/services/manager.go
Labels: refactor

#3725 Remove discord announcements
  .woodpecker/social.yaml
Labels: governance, build

#3726 Fix oauth file envvars
  cmd/server/flags.go
  server/services/setup.go
Labels: bug, regression

#3695 Use IDs for tokens
  docs/docs/91-migrations.md
  server/api/hook.go
  server/api/login.go
  server/api/repo.go
  server/api/user.go
  server/router/middleware/session/user.go
  server/web/config.go
  shared/token/token.go
Labels: enhancement

#3734 Fix secret translations
  web/src/components/user/UserSecretsTab.vue
  web/src/views/User.vue
Labels: regression

#3711 Fix privileged steps in kubernetes
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/kubernetes/pod_test.go
  pipeline/frontend/yaml/compiler/compiler_test.go
  pipeline/frontend/yaml/linter/linter.go
Labels: bug, backend/kubernetes, build_pr_images

#3741 Fix spelling in README
  README.md
Labels: documentation
