Repository woodpecker-ci/woodpecker, pull requests merged in 2024-10, with the labels that each got.

#4154 Add `.lycheeignore`
  .lycheeignore
Labels: build

#4155 Print agent labels in debug mode
  cmd/agent/core/agent.go
Labels: agent, enhancement, backend

#4156 Print agent labels in debug mode (#4155)
  cmd/agent/core/agent.go
Labels: agent, enhancement

#4158 fix: Add wildcard to `.lycheeignore`
  .lycheeignore
Labels: skip-changelog

#4162 renovate: set `automergetype=pr`
  .cspell.json
  .github/renovate.json
Labels: build

#4187 chore(deps): update dependency vite to v5.4.6 [security] (#4163)
  web/pnpm-lock.yaml
Labels: ui, security, dependencies

#4190 Fix NFPM builds
  nfpm/agent.yaml
  nfpm/server.yaml
Labels: build, regression

#4189 Backport JS dependency updates
  docs/package.json
  docs/pnpm-lock.yaml
  web/eslint.config.js
  web/package.json
  web/pnpm-lock.yaml
  web/src/App.vue
  web/src/components/atomic/SyntaxHighlight.ts
  web/src/components/repo/pipeline/PipelineLog.vue
  web/src/compositions/useDate.ts
  web/src/compositions/useInjectProvide.ts
  web/src/compositions/usePaginate.test.ts
  web/src/compositions/usePipelineFeed.ts
  web/src/lib/api/client.ts
  web/src/lib/api/index.ts
  web/src/main.ts
  web/src/router.ts
  web/src/views/org/OrgWrapper.vue
  web/src/views/repo/RepoWrapper.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
  web/vite.config.ts
Labels: dependencies

#4197 Upgrade vue-i18n
  web/package.json
  web/pnpm-lock.yaml
Labels: ui, dependencies, regression

#4153 Highlight invalid entries in manual pipeline trigger
  web/src/components/form/KeyValueEditor.vue
  web/src/views/repo/RepoManualPipeline.vue
Labels: ui, enhancement, ux

#4203 Fix errant apostrophe in docker-compose documentation
  docs/docs/30-administration/05-deployment-methods/10-docker-compose.md
Labels: documentation

#4141 Report custom labels set by agent admins back
  agent/rpc/client_grpc.go
  cmd/agent/core/agent.go
  cmd/agent/core/flags.go
  cmd/server/docs/docs.go
  docs/docs/20-usage/20-workflow-syntax.md
  docs/docs/30-administration/15-agent-config.md
  docs/docs/91-migrations.md
  pipeline/rpc/mocks/peer.go
  pipeline/rpc/peer.go
  pipeline/rpc/proto/version.go
  pipeline/rpc/proto/woodpecker.pb.go
  pipeline/rpc/proto/woodpecker.proto
  server/grpc/rpc.go
  server/grpc/rpc_test.go
  server/grpc/server.go
  server/model/agent.go
  server/store/datastore/migration/016_add_custom_labels_to_agent.go
  server/store/datastore/migration/migration.go
  web/src/assets/locales/en.json
  web/src/components/agent/AgentForm.vue
  web/src/lib/api/types/agent.ts
  woodpecker-go/woodpecker/types.go
Labels: server, agent, enhancement

#4201 Assign workflows to agents with the best label matches
  server/grpc/filter.go
  server/grpc/filter_test.go
  server/queue/fifo.go
  server/queue/fifo_test.go
  server/queue/queue.go
Labels: server, enhancement

#4208 Use middleware to load org
  server/api/agent.go
  server/api/org.go
  server/api/org_registry.go
  server/api/org_secret.go
  server/router/api.go
  server/router/middleware/session/org.go
  server/router/middleware/session/user.go
Labels: server, refactor

#4211 Correctly init workflow metadata for cli exec
  cli/exec/exec.go
Labels: bug, cli, regression

#4213 Only allow docker-buildx plugin >= 5.0.0 to be priviledged by default
  shared/constant/constant.go
Labels: security, dependencies

#4219 WebUI: agent edit/detail view: change the **HELP** url based on the b…
  web/src/components/agent/AgentForm.vue
Labels: ui, enhancement

#4257 chore: fix `http-proxy-middleware` CVE
  docs/package.json
  docs/pnpm-lock.yaml
Labels: security, dependencies

#4255 fix: repo/owner parsing for gitlab
  server/forge/gitlab/convert.go
  server/forge/gitlab/gitlab_test.go
Labels: bug, forge/gitlab, build_pr_images

#4253 Update nix flake
  flake.lock
Labels: skip-changelog, dependencies, devx

#4256 Improve nix development environment
  flake.nix
Labels: devx

#4261 fix: repo/owner parsing for gitlab (#4255)
  server/forge/gitlab/convert.go
  server/forge/gitlab/gitlab_test.go
Labels: bug, forge/gitlab

#4262 Increase `WOODPECKER_FORGE_TIMEOUT` to fix config fetching for GitLab
  cmd/server/flags.go
  docs/docs/30-administration/10-server-config.md
  server/services/config/forge.go
Labels: bug, server, forge/gitlab, build_pr_images

#4259 Delete GitLab webhooks with partial URL match
  server/forge/gitlab/gitlab.go
Labels: bug, forge/gitlab, build_pr_images

#4272 Don't parse forge config files multiple times if no error occured
  server/services/config/forge.go
  server/services/config/forge_test.go
Labels: bug, server, backport

#4276 Fix renovate support for `xgo`
  .cspell.json
  .github/renovate.json
  Makefile
  docker/Dockerfile.make
Labels: build

#4277 Add instructions how to build images locally
  docs/docs/92-development/07-guides.md
Labels: documentation
