Repository woodpecker-ci/woodpecker, pull requests merged in 2025-10, with the labels that each got.

#5583 Document pipeline backend engine interface precisely
  pipeline/backend/docker/docker.go
  pipeline/backend/types/backend.go
Labels: documentation

#5586 make local backend tests less flaky
  pipeline/backend/local/local_test.go
Labels: tests, skip-changelog

#5587 Improve error message when agent fails to connect
  cmd/agent/core/agent.go
Labels: server, enhancement

#5578 Support matrix environ badges only with no key-values
  web/src/components/atomic/Badge.vue
Labels: bug, ui

#5593 Add disabled badge to agents
  web/src/assets/locales/en.json
  web/src/components/agent/AgentList.vue
Labels: ui, enhancement, ux

#5596 Fix Kubernetes install docs to use OCI artifacts instead of deprecated helm chart
  docs/versioned_docs/version-3.10/30-administration/05-installation/20-helm-chart.md
  docs/versioned_docs/version-3.8/30-administration/05-installation/20-helm-chart.md
  docs/versioned_docs/version-3.9/30-administration/05-installation/20-helm-chart.md
Labels: documentation

#5611 Enhance Bitbucket Datacenter build status reporting
  server/forge/bitbucketdatacenter/bitbucketdatacenter.go
  server/forge/bitbucketdatacenter/bitbucketdatacenter_test.go
  server/forge/bitbucketdatacenter/fixtures/expected/PostBuildStatus.json
  server/forge/bitbucketdatacenter/fixtures/handler.go
Labels: enhancement, forge/bitbucket
