Repository woodpecker-ci/woodpecker, pull requests merged in 2025-09, with the labels that each got.

#5494 fix: allow spaces in `WOODPECKER_PLUGINS_PRIVILEGED`
  cli/admin/secret/secret_add.go
  cli/admin/secret/secret_set.go
  cli/exec/flags.go
  cli/lint/lint.go
  cli/org/secret/secret_add.go
  cli/org/secret/secret_set.go
  cli/pipeline/create.go
  cli/pipeline/deploy/deploy.go
  cli/pipeline/start.go
  cli/repo/secret/secret_add.go
  cli/repo/secret/secret_set.go
  cmd/agent/core/flags.go
  cmd/server/flags.go
  pipeline/backend/kubernetes/flags.go
Labels: bug

#5497 Add Bitbucket key limit known issue
  docs/docs/30-administration/10-configuration/12-forges/50-bitbucket.md
Labels: documentation, forge/bitbucket

#5520 Docs: remove dead links from awesome page
  docs/src/pages/awesome.md
Labels: documentation, skip-changelog

#5522 Regenerate mocks after changing queue interface
  server/queue/mocks/queue.go
Labels: skip-changelog

#5518 Use correct error when config fetching fails
  server/pipeline/create.go
Labels: skip-changelog, regression

#5525 Fix forge oauth columns migration
  server/store/datastore/migration/027_fix_forge_columns.go
Labels: server, regression

#5526 Fix forge oauth columns migration (2)
  server/store/datastore/migration/027_fix_forge_columns.go
Labels: server, regression

#5533 Fix dir not found handling
  server/forge/forgejo/forgejo.go
  server/forge/gitea/gitea.go
Labels: bug, forge/gitea, forge/forgejo

#5549 Fix queue task processing
  server/api/hook.go
  web/src/views/admin/AdminQueue.vue
Labels: server, ui, regression

#5550 Add back-off retry for pod log streaming to kubernetes backend
  pipeline/backend/kubernetes/kubernetes.go
Labels: bug, backend/kubernetes

#5536 Support for pull requests opened events from forked repositories
  server/forge/bitbucketdatacenter/bitbucketdatacenter.go
  server/forge/bitbucketdatacenter/fixtures/HookPullRequestMerged.json
  server/forge/bitbucketdatacenter/fixtures/HookPullRequestOpened.json
  server/forge/bitbucketdatacenter/fixtures/HookPullRequestOpenedFromFork.json
  server/forge/bitbucketdatacenter/fixtures/HookPush.json
  server/forge/bitbucketdatacenter/fixtures/hooks.go
  server/forge/bitbucketdatacenter/parse.go
  server/forge/bitbucketdatacenter/parse_test.go
Labels: bug, forge/bitbucket

#5552 Enable completion support for cli
  cli/internal/config/config.go
  cmd/cli/app.go
Labels: enhancement, cli

#5559 Trace errors during SetupWorkflow, make service step setup errors visible to user
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/kubernetes/service.go
  pipeline/errors/types/errors.go
  pipeline/pipeline.go
Labels: agent, enhancement

#5565 Update release template
  .github/release_template.md
Labels: governance, skip-changelog

#5571 Disable CGO for swag fmt
  Makefile
Labels: bug, skip-changelog, devx

#3349 Allow to configure a config extension per repo
  .cspell.json
  cmd/server/flags.go
  cmd/server/openapi/docs.go
  docs/docs/20-usage/72-extensions/40-configuration-extension.md
  docs/docs/20-usage/72-extensions/_category_.yaml
  docs/docs/20-usage/72-extensions/index.md
  docs/docs/30-administration/10-configuration/10-server.md
  docs/src/pages/migrations.md
  server/api/repo.go
  server/model/pagination.go
  server/model/repo.go
  server/services/config/combined_test.go
  server/services/config/http.go
  server/services/manager.go
  server/services/setup.go
  server/services/utils/hostmatcher/hostmatcher.go
  server/services/utils/hostmatcher/hostmatcher_test.go
  server/services/utils/hostmatcher/http.go
  server/services/utils/http.go
  server/services/utils/http_test.go
  web/components.d.ts
  web/src/assets/locales/en.json
  web/src/lib/api/index.ts
  web/src/lib/api/types/repo.ts
  web/src/router.ts
  web/src/views/repo/settings/Extensions.vue
  web/src/views/repo/settings/RepoSettings.vue
Labels: ui, feature, addon

#5576 Don't split language if not required
  web/src/compositions/useI18n.ts
Labels: bug, ui

#5580 Announce only stable releases
  .woodpecker/social.yaml
Labels: build
