Repository woodpecker-ci/woodpecker, pull requests merged in 2025-03, with the labels that each got.

#4924 Add migration to fix zero forge_id in orgs table
  server/store/datastore/migration/018_fix_orgs_users_match.go
  server/store/datastore/migration/022_set_new_defaults_for_require_approval.go
  server/store/datastore/migration/024_unsanitize_org_and_user_names.go
  server/store/datastore/migration/025_fix_zero_forge_id_ref.go
  server/store/datastore/migration/migration.go
Labels: bug, server

#4961 Fix fs owner in scratch-based container images
  docker/Dockerfile.agent.multiarch
  docker/Dockerfile.server.multiarch.rootless
Labels: bug, server, agent

#4964 Add backoff retry for store setup
  cmd/server/flags.go
  cmd/server/server.go
  cmd/server/setup.go
Labels: server, enhancement

#4968 Remove woodpecker prefix from env var title in docs
  docs/docs/20-usage/20-workflow-syntax.md
  docs/docs/20-usage/41-registries.md
  docs/docs/30-administration/00-general.md
  docs/docs/30-administration/10-configuration/10-server.md
  docs/docs/30-administration/10-configuration/11-backends/10-docker.md
  docs/docs/30-administration/10-configuration/11-backends/20-kubernetes.md
  docs/docs/30-administration/10-configuration/11-backends/30-local.md
  docs/docs/30-administration/10-configuration/12-forges/20-github.md
  docs/docs/30-administration/10-configuration/12-forges/30-gitea.md
  docs/docs/30-administration/10-configuration/12-forges/35-forgejo.md
  docs/docs/30-administration/10-configuration/12-forges/40-gitlab.md
  docs/docs/30-administration/10-configuration/12-forges/50-bitbucket.md
  docs/docs/30-administration/10-configuration/12-forges/60-bitbucket_datacenter.md
  docs/docs/30-administration/10-configuration/30-agent.md
Labels: documentation, refactor

#4972 Add documentation for WOODPECKER_EXPERT env vars
  cmd/server/flags.go
  docs/docs/30-administration/10-configuration/10-server.md
Labels: documentation

#4796 Tag pipeline with source information
  CHANGELOG.md
  cmd/agent/core/agent.go
  cmd/agent/core/agent_test.go
  docs/docs/20-usage/20-workflow-syntax.md
  docs/src/pages/migrations.md
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/kubernetes/pod_test.go
  pipeline/backend/kubernetes/secrets.go
  pipeline/backend/kubernetes/secrets_test.go
  pipeline/backend/types/step.go
  pipeline/const.go
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/convert.go
  server/grpc/rpc.go
  server/model/agent.go
  server/model/agent_test.go
  server/model/task.go
  server/model/task_test.go
  server/pipeline/stepbuilder/stepBuilder.go
Labels: enhancement

#4991 Add missing links to 3.x docs
  docs/src/pages/versions.md
Labels: documentation

#4421 Add icons to all tabs
  web/src/assets/locales/en.json
  web/src/components/atomic/Icon.vue
  web/src/components/repo/pipeline/PipelineItem.vue
  web/src/components/repo/pipeline/PipelineStepList.vue
  web/src/views/admin/AdminSettingsWrapper.vue
  web/src/views/org/settings/OrgSettingsWrapper.vue
  web/src/views/repo/RepoWrapper.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
  web/src/views/repo/settings/RepoSettings.vue
  web/src/views/user/UserWrapper.vue
Labels: ui, enhancement

#5009 Dont center items in more menu
  web/src/components/layout/scaffold/Tabs.vue
Labels: ui, regression

#5008 Fix queue badge list
  web/src/components/atomic/Badge.vue
  web/src/views/admin/AdminQueue.vue
Labels: ui, regression

#5010 Use badge value instead of label for single values
  web/src/components/atomic/Badge.vue
  web/src/components/secrets/SecretList.vue
  web/src/views/RepoAdd.vue
  web/src/views/admin/AdminRepos.vue
  web/src/views/admin/AdminUsers.vue
  web/src/views/repo/RepoBranches.vue
Labels: ui, enhancement

#5013 Replace illegal characters in Kubernetes labels
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/kubernetes/secrets.go
Labels: server, backend/kubernetes

#5002 Use pointer cursor for icon buttons
  web/src/components/atomic/IconButton.vue
  web/src/components/layout/Panel.vue
  web/src/views/repo/pipeline/PipelineConfig.vue
Labels: bug, ui

#5018 Use xorm quoter for feed query
  server/store/datastore/feed.go
  server/store/datastore/helper.go
Labels: server, refactor

#5034 Bump golangci-lint to v2
  .golangci.yaml
  .woodpecker/test.yaml
  Makefile
  pipeline/backend/kubernetes/pod.go
  server/grpc/filter.go
  server/grpc/rpc.go
  server/router/middleware/session/org.go
  server/router/middleware/session/user.go
  server/services/config/forge.go
  server/services/encryption/constants.go
  server/services/encryption/encryption_builder.go
Labels: build

#5023 Use existing WorkingDir for clone steps
  .markdownlint.yaml
  docs/docs/20-usage/20-workflow-syntax.md
  docs/src/pages/migrations.md
  pipeline/frontend/yaml/compiler/compiler_test.go
  pipeline/frontend/yaml/compiler/convert.go
Labels: bug, breaking, backend/kubernetes
