Repository woodpecker-ci/woodpecker, pull requests merged in 2025-01, with the labels that each got.

#4653 Add same when filter for ptrettier step in web workflow so we dont get dependency issues
  .woodpecker/web.yaml
Labels: skip-changelog, build

#4650 Fix workflow volume and network config
  pipeline/backend/docker/docker.go
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/types/config.go
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/compiler_test.go
Labels: bug, agent

#4656 Revert volumes/network list
  cmd/server/openapi.go
  pipeline/backend/docker/docker.go
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/types/config.go
  pipeline/frontend/yaml/compiler/compiler.go
  pipeline/frontend/yaml/compiler/compiler_test.go
  pipeline/rpc/proto/version.go
  pipeline/rpc/proto/woodpecker.pb.go
  pipeline/rpc/proto/woodpecker_grpc.pb.go
Labels: skip-changelog

#4643 fix cli exec statement in debug tab
  web/src/assets/locales/en.json
  web/src/views/repo/pipeline/PipelineDebug.vue
Labels: bug

#4447 Improve code highlighting in web UI
  web/src/components/form/InputField.vue
  web/src/components/layout/Panel.vue
  web/src/components/repo/pipeline/PipelineLog.vue
  web/src/style.css
  web/windi.config.ts
Labels: ui, build_pr_images

#4644 Refactor `secrets` page in docs
  docs/docs/20-usage/40-secrets.md
Labels: documentation

#4669 Increase left padding for repo items
  web/src/components/repo/RepoItem.vue
Labels: ui, regression

#4673 Unify CLI bin name
  docs/src/pages/migrations.md
  nfpm/cli.yaml
Labels: breaking, build

#4663 feat(bitbucketdatacenter): Add support for fetching and converting projects to teams
  server/forge/bitbucketdatacenter/bitbucketdatacenter.go
  server/forge/bitbucketdatacenter/convert.go
  server/forge/bitbucketdatacenter/convert_test.go
Labels: enhancement, forge/bitbucket

#4676 Remove deprecated API field
  cmd/server/openapi/docs.go
  server/api/repo.go
  server/model/repo.go
Labels: breaking, skip-changelog

#4680 Don't force password change when creating user in alpine images
  docker/Dockerfile.agent.alpine.multiarch.rootless
  docker/Dockerfile.cli.alpine.multiarch.rootless
  docker/Dockerfile.server.alpine.multiarch.rootless
Labels: regression

#4683 Revert `rootful` agent images again
  .woodpecker/docker.yaml
  docker/Dockerfile.agent.alpine.multiarch
  docker/Dockerfile.agent.multiarch
  docs/docs/30-administration/04-image-variants.md
  docs/docs/92-development/07-guides.md
  docs/src/pages/migrations.md
Labels: regression, build_pr_images

#4641 Add priority menu to tabs
  web/src/components/atomic/Icon.vue
  web/src/components/layout/scaffold/Header.vue
  web/src/components/layout/scaffold/Tabs.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: ui, refactor

#4690 Reduce interactive WP icon size
  web/src/components/repo/pipeline/PipelineItem.vue
Labels: ui, regression

#4687 Don't fail user creation if org exists
  server/store/datastore/org.go
  server/store/datastore/user.go
  server/store/datastore/users_test.go
Labels: bug, server

#4689 Fix text overflow on login mask
  web/src/views/Login.vue
Labels: ui, regression

#4697 Add margins to moving WP svg logo
  web/src/assets/woodpecker.svg
Labels: bug, ui

#4707 Reduce version redundancy
  docs/docusaurus.config.ts
Labels: documentation, refactor

#4717 Fix mobile view of the popup
  web/src/components/layout/Popup.vue
Labels: bug, ui

#4716 Harmonize en texts
  web/src/assets/locales/en.json
  web/src/components/secrets/SecretEdit.vue
Labels: ui, refactor

#4719 Add docs-dependencies target to makefile
  .woodpecker/docs.yaml
  Makefile
  docs/docs/92-development/09-openapi.md
  docs/package.json
  docs/versioned_docs/version-1.0/92-development/08-swagger.md
  docs/versioned_docs/version-2.6/92-development/08-swagger.md
  docs/versioned_docs/version-2.7/92-development/09-swagger.md
  docs/versioned_docs/version-2.8/92-development/09-swagger.md
Labels: build

#4729 Use mirror.gcr.io as `trivy` registry
  .woodpecker/securityscan.yaml
Labels: build

#4737 Improve 3.0.0 migration notes
  docs/src/pages/migrations.md
Labels: documentation

#4646 v3.0 blog post
  docs/blog/2024-12-28-release-v3.0.0/approval-requirements.png
  docs/blog/2024-12-28-release-v3.0.0/debug-pipelines.png
  docs/blog/2024-12-28-release-v3.0.0/index.md
Labels: skip-changelog

#4741 Fix package configs
  nfpm/agent.yaml
  nfpm/server.yaml
Labels: bug, build

#4742 use v3 woodpecker libs
  .gitpod.yml
  .golangci.yaml
  docs/docs/30-administration/22-backends/50-custom-backends.md
  pipeline/rpc/proto/woodpecker.proto
Labels: lib

#4744 Add missing error message for org_access_denied
  web/src/assets/locales/en.json
  web/src/views/Login.vue
Labels: bug, ui

#4743 Fix cron migration note in v3 blog post
  docs/blog/2024-12-28-release-v3.0.0/index.md
Labels: documentation, skip-changelog

#4748 fix minor tag creation for server scratch image
  .woodpecker/docker.yaml
Labels: build

#4749 Fix log folder permissions
  server/services/log/file/file.go
Labels: bug, server

#4746 Fix sql identifier escaping in datastore feed
  server/store/datastore/feed.go
  server/store/datastore/feed_test.go
  server/store/datastore/helper.go
Labels: bug, server

#4772 Various docs improvements
  docs/blog/2024-12-28-release-v3.0.0/index.md
  docs/docusaurus.config.ts
  docs/src/css/custom.css
  docs/src/pages/migrations.md
Labels: documentation

#4768 Add allow list for approvals
  cmd/server/openapi/docs.go
  server/api/repo.go
  server/model/repo.go
  server/pipeline/gated.go
  server/pipeline/gated_test.go
  web/src/assets/locales/en.json
  web/src/lib/api/types/repo.ts
  web/src/views/repo/settings/General.vue
Labels: feature

#4794 Revert "Tag pipeline with source information (#4771)"
  docs/src/pages/migrations.md
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/kubernetes/pod_test.go
  pipeline/backend/kubernetes/secrets.go
  pipeline/backend/kubernetes/secrets_test.go
  server/pipeline/stepbuilder/stepBuilder.go
Labels: server, regression
