Repository woodpecker-ci/woodpecker, pull requests merged in 2025-06, with the labels that each got.

#5235 Ignore direnv config and folder
  .gitignore
Labels: devx

#5236 update docs-link for todo checker
  docs/plugins/woodpecker-plugins/plugins.json
Labels: plugin, documentation

#5196 kubernetes: prevent secrets from leaking to api-server logs
  pipeline/backend/kubernetes/kubernetes.go
  pipeline/backend/kubernetes/pod.go
  pipeline/backend/kubernetes/pod_test.go
  pipeline/backend/kubernetes/secrets.go
  pipeline/backend/types/step.go
  pipeline/frontend/yaml/compiler/compiler_test.go
  pipeline/frontend/yaml/compiler/convert.go
  pipeline/frontend/yaml/compiler/settings/params.go
  pipeline/frontend/yaml/compiler/settings/params_test.go
Labels: enhancement, security, backend/kubernetes

#5275 Use pipeline number in title
  web/src/views/repo/pipeline/Pipeline.vue
  web/src/views/repo/pipeline/PipelineChangedFiles.vue
  web/src/views/repo/pipeline/PipelineConfig.vue
  web/src/views/repo/pipeline/PipelineDebug.vue
  web/src/views/repo/pipeline/PipelineErrors.vue
Labels: bug, ui

#5227 Add pipeline author and avatar env vars
  cmd/server/openapi/docs.go
  docs/docs/20-usage/50-environment.md
  docs/src/pages/migrations.md
  pipeline/frontend/metadata/environment.go
  pipeline/frontend/metadata/types.go
  server/pipeline/stepbuilder/metadata.go
Labels: enhancement
