Repository woodpecker-ci/woodpecker, pull requests merged in 2025-04, with the labels that each got.

#5033 Style navbar login button as navbar-link
  web/src/components/layout/header/Navbar.vue
Labels: ui, refactor

#5042 Fix exclude path constraint behavior
  pipeline/frontend/yaml/constraint/constraint.go
  pipeline/frontend/yaml/constraint/constraint_test.go
Labels: bug, pipeline-config

#5047 Revert "Use existing WorkingDir for clone steps (#5023)"
  .markdownlint.yaml
  docs/docs/20-usage/20-workflow-syntax.md
  docs/src/pages/migrations.md
  pipeline/frontend/yaml/compiler/compiler_test.go
  pipeline/frontend/yaml/compiler/convert.go
Labels: skip-changelog

#5048 BitbucketDC: add event pull request opened
  server/forge/bitbucketdatacenter/bitbucketdatacenter.go
Labels: bug, forge/bitbucket

#5054 Add v3.5 docs to prev version list
  docs/src/pages/versions.md
Labels: skip-changelog

#5057 Fix cli format flag fallback
  cli/repo/repo.go
Labels: bug, cli

#5065 Revert web dependency updates
  web/package.json
  web/pnpm-lock.yaml
Labels: skip-changelog

#5069 Improve CLI info text and remove markdown
  web/src/assets/locales/en.json
Labels: bug, ui, translation

#5068 Add missing icon for changes files tab
  web/src/components/atomic/Icon.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
Labels: bug, ui

#5086 Move plugin-surge docs to codeberg
  docs/plugins/woodpecker-plugins/plugins.json
Labels: plugin, documentation

#5056 Document rootless container requirements for skip-clone
  docs/docs/20-usage/20-workflow-syntax.md
  docs/versioned_docs/version-3.5/20-usage/20-workflow-syntax.md
Labels: documentation

#5096 Mention `backend_options` in workflow syntax docs
  docs/docs/20-usage/20-workflow-syntax.md
  docs/versioned_docs/version-3.5/20-usage/20-workflow-syntax.md
Labels: documentation

#5098 Slugify plugin names used for urls
  docs/plugins/woodpecker-plugins/package.json
  docs/plugins/woodpecker-plugins/src/index.ts
  docs/pnpm-lock.yaml
Labels: documentation

#5099 Fix plugin slug in list view
  docs/plugins/woodpecker-plugins/src/index.ts
  docs/plugins/woodpecker-plugins/src/theme/WoodpeckerPluginList.tsx
  docs/plugins/woodpecker-plugins/src/types.ts
Labels: documentation, regression

#5103 Scroll to selected pipeline step
  web/src/components/repo/pipeline/PipelineStepList.vue
Labels: ui, enhancement

#5087 .deb and .rpm installation commands fixed
  docs/docs/30-administration/05-installation/30-packages.md
  docs/versioned_docs/version-3.5/30-administration/05-installation/30-packages.md
Labels: documentation

#5102 Fix example value for `WOODPECKER_GRPC_ADDR` in autoscaler docs
  docs/docs/30-administration/10-configuration/40-autoscaler.md
  docs/versioned_docs/version-3.5/30-administration/10-configuration/40-autoscaler.md
Labels: documentation

#5113 Use centrally typed inject provide in Vue
  web/src/components/layout/popups/DeployPipelinePopup.vue
  web/src/components/repo/pipeline/PipelineLog.vue
  web/src/components/repo/pipeline/PipelineStepList.vue
  web/src/compositions/useInjectProvide.ts
  web/src/compositions/useTabs.ts
  web/src/views/org/OrgRepos.vue
  web/src/views/org/OrgWrapper.vue
  web/src/views/org/settings/OrgAgents.vue
  web/src/views/org/settings/OrgRegistries.vue
  web/src/views/org/settings/OrgSecrets.vue
  web/src/views/org/settings/OrgSettingsWrapper.vue
  web/src/views/repo/RepoBranch.vue
  web/src/views/repo/RepoBranches.vue
  web/src/views/repo/RepoManualPipeline.vue
  web/src/views/repo/RepoPipelines.vue
  web/src/views/repo/RepoPullRequest.vue
  web/src/views/repo/RepoPullRequests.vue
  web/src/views/repo/RepoWrapper.vue
  web/src/views/repo/pipeline/Pipeline.vue
  web/src/views/repo/pipeline/PipelineChangedFiles.vue
  web/src/views/repo/pipeline/PipelineConfig.vue
  web/src/views/repo/pipeline/PipelineDebug.vue
  web/src/views/repo/pipeline/PipelineErrors.vue
  web/src/views/repo/pipeline/PipelineWrapper.vue
  web/src/views/repo/settings/Actions.vue
  web/src/views/repo/settings/Badge.vue
  web/src/views/repo/settings/Crons.vue
  web/src/views/repo/settings/General.vue
  web/src/views/repo/settings/Registries.vue
  web/src/views/repo/settings/RepoSettings.vue
  web/src/views/repo/settings/Secrets.vue
Labels: ui, refactor

#5116 Use slugified plugin urls in docs
  docs/blog/2024-01-01-continuous-deployment/index.md
  docs/docs/20-usage/51-plugins/20-creating-plugins.md
  docs/docs/20-usage/75-project-settings.md
  docs/docs/20-usage/90-advanced-usage.md
  docs/plugins/woodpecker-plugins/src/index.ts
  docs/versioned_docs/version-2.8/20-usage/51-plugins/20-creating-plugins.md
  docs/versioned_docs/version-2.8/20-usage/90-advanced-usage.md
  docs/versioned_docs/version-3.3/20-usage/51-plugins/20-creating-plugins.md
  docs/versioned_docs/version-3.3/20-usage/75-project-settings.md
  docs/versioned_docs/version-3.3/20-usage/90-advanced-usage.md
  docs/versioned_docs/version-3.4/20-usage/51-plugins/20-creating-plugins.md
  docs/versioned_docs/version-3.4/20-usage/75-project-settings.md
  docs/versioned_docs/version-3.4/20-usage/90-advanced-usage.md
  docs/versioned_docs/version-3.5/20-usage/51-plugins/20-creating-plugins.md
  docs/versioned_docs/version-3.5/20-usage/75-project-settings.md
  docs/versioned_docs/version-3.5/20-usage/90-advanced-usage.md
  pipeline/frontend/yaml/linter/schema/schema.json
Labels: documentation

#5118 Move `plugin-s3` to Codeberg
  docs/plugins/woodpecker-plugins/plugins.json
Labels: documentation

#5119 Fix link
  docs/docs/20-usage/20-workflow-syntax.md
Labels: documentation

#5104 Set dynamic page titles
  web/src/assets/locales/en.json
  web/src/compositions/useWPTitle.ts
  web/src/views/Login.vue
  web/src/views/RepoAdd.vue
  web/src/views/Repos.vue
  web/src/views/admin/AdminAgents.vue
  web/src/views/admin/AdminInfo.vue
  web/src/views/admin/AdminOrgs.vue
  web/src/views/admin/AdminQueue.vue
  web/src/views/admin/AdminRegistries.vue
  web/src/views/admin/AdminRepos.vue
  web/src/views/admin/AdminSecrets.vue
  web/src/views/admin/AdminSettingsWrapper.vue
  web/src/views/admin/AdminUsers.vue
  web/src/views/org/OrgRepos.vue
  web/src/views/org/settings/OrgAgents.vue
  web/src/views/org/settings/OrgRegistries.vue
  web/src/views/org/settings/OrgSecrets.vue
  web/src/views/repo/RepoBranch.vue
  web/src/views/repo/RepoBranches.vue
  web/src/views/repo/RepoManualPipeline.vue
  web/src/views/repo/RepoPipelines.vue
  web/src/views/repo/RepoPullRequest.vue
  web/src/views/repo/RepoPullRequests.vue
  web/src/views/repo/pipeline/Pipeline.vue
  web/src/views/repo/pipeline/PipelineChangedFiles.vue
  web/src/views/repo/pipeline/PipelineConfig.vue
  web/src/views/repo/pipeline/PipelineDebug.vue
  web/src/views/repo/pipeline/PipelineErrors.vue
  web/src/views/repo/settings/Actions.vue
  web/src/views/repo/settings/Badge.vue
  web/src/views/repo/settings/Crons.vue
  web/src/views/repo/settings/General.vue
  web/src/views/repo/settings/Registries.vue
  web/src/views/repo/settings/Secrets.vue
  web/src/views/user/UserAgents.vue
  web/src/views/user/UserCLIAndAPI.vue
  web/src/views/user/UserGeneral.vue
  web/src/views/user/UserRegistries.vue
  web/src/views/user/UserSecrets.vue
Labels: ui, enhancement

#5130 Mention named volumes
  docs/docs/20-usage/70-volumes.md
  docs/versioned_docs/version-3.5/20-usage/70-volumes.md
Labels: documentation

#5129 Explain tasks
  docs/docs/20-usage/15-terminology/index.md
  docs/versioned_docs/version-3.5/20-usage/15-terminology/index.md
Labels: documentation

#5134 Use docker go client directly
  go.mod
  go.sum
  pipeline/backend/docker/docker.go
Labels: feature, dependencies
