Repository woodpecker-ci/woodpecker, pull requests merged in 2025-07, with the labels that each got.

#5349 Update and improve nix flake
  flake.lock
  flake.nix
Labels: devx

#5354 🧑‍💻 Add support for proxying to existing woodpecker server
  web/package.json
  web/pnpm-lock.yaml
  web/vite.config.ts
Labels: ui, devx

#5355 Add ASCII JUnit Test Report plugin
  docs/plugins/woodpecker-plugins/plugins.json
Labels: plugin, documentation

#5376 Show oauth host and favicon on login
  web/src/assets/locales/en.json
  web/src/views/Login.vue
Labels: ui, enhancement

#5381 Prevent body jump when scrollbar appears
  web/src/App.vue
Labels: ui, enhancement

#5379 Show changed files as file-tree
  web/src/components/FileTree.vue
  web/src/components/atomic/Icon.vue
  web/src/views/repo/pipeline/PipelineChangedFiles.vue
Labels: ui, enhancement
